= Staging devstudio Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

= Pre-Staging Steps

See link:Pre-Staging.adoc[Pre-Staging]


= Staging steps

[IMPORTANT]
====

Before running any of the jobs or scripts below, make sure to set the correct versions to the values for the release you're staging or releasing.

* look for versionWithRespin, update to version you're staging
* look for PREV and NEXT variables; set to previous / next milestone (AMx, AMy, AMz, Final/GA)
* look for NEXT, set to next milestone
* check target platform versions are current w/ latest versions
* check parent pom version, version_parent, is current

====

== Clone jbosstools-build-ci repo

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ ! -d jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout jbosstools-4.4.x
chmod +x -R */*.sh */*/*.sh

----

== Update Discovery Sites and URLs

See link:JBT_Staging.adoc[JBoss Tools Staging]

== Verify correct version set in com.jboss.devstudio.central.core

See link:JBT_Staging.adoc[JBoss Tools Staging]

== Disable jobs

See link:JBT_Staging.adoc[JBoss Tools Staging]

== Stage to devstudio.redhat.com and internal qa server

=== Copy & rename builds & update sites from "snapshots" to "staging"

Here is a job that performs the copy (& rename) from /snapshots/ to /staging/:

https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites/

Here's a job that verifies everything is published:

https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-03-verify-builds-update-sites/


TIP: Once the staging build folder exists, start fetching the devstudio installer (we'll need it later to do a smoke test)

[source,bash]
----

cd ~/tmp
versionWithRespin_ds=10.4.0.AM3
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}

----

You'll use this downloaded installer later, but since it takes a while to download, it's more efficient to start it now.


=== Cleanup OLD builds

Optional step.

Run this job to move any old builds into an OLD/ folder for later cleanup, or delete them immediately.

https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites/


=== Update /staging/updates/ sites and merge in Integration Stack content

See link:JBT_Staging.adoc[JBoss Tools Staging]


== Release the latest staging site to ide-config.properties

See link:JBT_Staging.adoc[JBoss Tools Staging]


== Smoke test the release (manually)

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Bring Your Own Eclipse category from

https://devstudio.redhat.com/10.0/staging/updates/

3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----
versionWithRespin_ds=10.4.0.AM3
cd ~/tmp
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html

# should have already downloaded this above
if [[ ! -f ${installerJar} ]]; then wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}; fi

java -jar ~/tmp/${installerJar}

----

0. After downloading and installing devstudio from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See link:JBT_Staging.adoc[JBoss Tools Staging]


== Notify the team (send 1 email)

See link:JBT_Staging.adoc[JBoss Tools Staging]


== Trigger QE Smoke tests (automated)

Trigger the QE smoke tests in https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=10.4.0.AM3
cd ~/tmp
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
rm -f index.html

version_ds_INST=${installerJar#devstudio-}
version_ds_INST=${version_ds_INST%-installer*}
echo "Devstudio installer version: ${version_ds_INST}"

# run the one buildflow job
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in devstudio.buildflow.it.smoke; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="DEVSTUDIO_VERSION=${version_ds_INST}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s
done

----


== Sign RPM

0. This section only applies to GA builds. No need to sign AMx milestones!

1. give URL link to Chris via RCM ticket, eg., https://projects.engineering.redhat.com/browse/RCM-12825

[source,bash]
----


# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=10.3.0.GA
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-05-sign-rpm-email-request; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

2. Chris signs it, and gives back a URL,eg., http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/JBDS-10.3.0/rpms/signed/

3. Fetch rpms, regen metadata

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=10.3.0.GA
# NOTE: do not use http://download-node-02.eng.bos.redhat.com as it may not resolve from within Jenkins
signedURL=http://download.devel.redhat.com/devel/candidates/jboss/devstudio/devstudio-10.3.0.GA/rpms/signed
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-06-sign-rpm-fetch; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&signedURL=${signedURL}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  Eclipse
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

Next, update your /etc/yum.repos.d/rh-eclipse46-devstudio.repo file like this:

NOTE: Run the following commands as root user:

[source,bash]
----

cat <<EOF > /etc/yum.repos.d/rh-eclipse46-devstudio.repo

[rh-eclipse46-devstudio-staging-10.3]
name=rh-eclipse46-devstudio-staging-10.3
baseurl=https://devstudio.redhat.com/10.0/staging/builds/devstudio-10.3.0.GA-build-rpm/latest/x86_64/
enabled=1
gpgcheck=1
upgrade_requirements_on_install=1
metadata_expire=2m

[rh-eclipse46-devstudio-snapshots-10.3]
name=rh-eclipse46-devstudio-snapshots-10.3
baseurl=https://devstudio.redhat.com/10.0/snapshots/rpms/10.3.0/x86_64/
enabled=0
gpgcheck=0
upgrade_requirements_on_install=1
metadata_expire=120m

EOF

# If you already have rh-eclipse46-devstudio installed:
yum update rh-eclipse46-devstudio -y --best

# Or, if not already installed
yum install rh-eclipse46-devstudio -y --best

----

[WARNING]
====
Installation should complete without any problems. Should NOT see an error like this:
[source,bash]
----
Error: Package rh-eclipse46-devstudio-10.3-0.20170218.1756.el7.x86_64.rpm is not signed
----
====


