= Release JBoss Developer Studio Development Milestone

This document describe how to publish a valid JBoss Developer Studio build to production after being verified by QE.

= Prerelease Steps

These steps can be done before the actual release (eg., on the Thurs or Fri before the Monday release, as long as QE has more-or-less signed off). Check with QE before proceeding.

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA.

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten.

Send an email to jbosstools-dev@ and jboss-devstudio-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
google-chrome && google-chrome https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions

----

== Rename artifacts to remove timestamp and buildID

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`devstudio-10.3.0.AM1-v20151002-2235-B124-installer-eap.jar` must be renamed to `devstudio-10.3.0.AM1-installer-eap.jar`.

Connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then:

[source,bash]
----
versionExe=1.3.0-GA # note the dash, not period after x.y.z
versionWithRespin_ds=10.3.0.GA # a, b, c...
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
pushd /qa/services/http/binaries/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
for f in $(ls *latest*); do echo "rm $f"; rm -f $f; done
for f in $(ls devstudio-${version_ds}-* | grep -v latest); do g=$(echo $f | sed s#-v[[:digit:]]*-[[:digit:]]*-B[[:digit:]]*##); echo "mv $f $g"; mv $f $g; done
for f in $(ls development-suite-${versionExe}-* | grep -v latest); do g=$(echo $f | sed s#-[[:digit:]]*-[[:digit:]]*##); echo "mv $f $g"; mv $f $g; done
touch *
chmod +x *.jar *.exe
ls -l
popd
----

Now, move & symlink the ${versionWithRespin_ds} folder:

[source,bash]
----
versionWithRespin_ds=10.3.0.GA # a, b, c...
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
buildType=stable # use /stable/ or /development/ as appropriate
pushd /qa/services/http/binaries/RHDS/10.0/staging/builds/
mkdir -p ../../${buildType}/builds/
mv devstudio-${versionWithRespin_ds}-build-product ../../${buildType}/builds/devstudio-${version_ds}-build-product
ln -s ../../${buildType}/builds/devstudio-${version_ds}-build-product devstudio-${versionWithRespin_ds}-build-product
popd

----

== Verify install instructions are correct

Look at the .txt and .html files in /qa/services/http/binaries/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/

Verify that they contain correct install/usage instructions & versions.

If anything is wrong, fix it by hand, then also commit your changes to the templates.

https://github.com/jbdevstudio/jbdevstudio-product/commit/3827045dca85e73c5ae339cc13f514591e3c1835
https://github.com/jbdevstudio/jbdevstudio-product/commit/e6c2954207d1db7451f7adfd2d89c7ceccd6adbe

== File bug to update http://developers.redhat.com/products/devstudio/

Goal is to update the following pages to include links to guides and to set the correct latest GA release version:

* http://developers.redhat.com/products/devstudio/download/
* http://developers.redhat.com/products/devstudio/hello-world/
* http://developers.redhat.com/products/devstudio/docs-and-apis/

Past example:

* https://issues.jboss.org/browse/DEVELOPER-3908

Later, the necessary changes should be made in Drupal, where this website is managed, by someone who has the necessary permissions.

Once you have the JIRA, you can link to it when sending the note to release-engineering@ below.

NOTE: If we ever decide to drop the EAP-bundled installer, or there's a newer version of EAP than is bundled, we could add the EAP 7 zip / installer to list of devstudio artifacts on both developers.redhat.com and www.jboss.org. Explicit listing of files used to be done like this:
* https://github.com/redhat-developer/developers.redhat.com/blob/25640af93a8d7d219c189d37c528534acda17483/products/devstudio/_common/product.yml and
* https://github.com/redhat-developer/developers.redhat.com/blob/25640af93a8d7d219c189d37c528534acda17483/products/eap/_common/product.yml

== Clone jbosstools-build-ci repo

See details in JBT_Staging_For_QE.adoc

== Announce internally for push to CSP staging site

Submit an RCM ticket to release-engineering@redhat.com to requet that the binaries be uploaded to the CSP (Red Hat Customer Portal) and Download Manager.

IMPORTANT: As this takes some time and requires coordination with other teams, this step should be initiated a few days before release to allow processing time.

Previous ticket:

* https://projects.engineering.redhat.com/browse/RCM-12959

Communicate with Chris O'Brien (internal IRC: siege) to coordinate the release. All the above can happen in parallel / before the updates below.

Here is a job that creates the RCM ticket:

WARNING: TODO: make sure this works (untested - was done by hand last time).

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-dev-stable-00-releng-request-email/configure

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=10.3.0.GA
GOLIVEDATE="Foo, Feb 30, 2017"
TOrecipients="release-engineering@redhat.com"
CCrecipients="cobrien@redhat.com, mhusnain@redhat.com, nboldt@redhat.com, jmaury@redhat.com, timoran@redhat.com"
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-dev-stable-00-releng-request-email; do
  prevJob=$(prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable" -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&\
GOLIVEDATE=${GOLIVEDATE}&TOrecipients=${TOrecipients}&CCrecipients=${CCrecipients}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" != "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----


= Release steps

Once QE has signed off, and bits are staged to CSP, you can proceed w/ the rest of the release.

=== Copy content to release directory

See JBT_Release.adoc

=== Copy RPM content to release directory

If and only if we are releasing at the same the RPM version of Devstudio that is designed to work on RHSCL, then this job should also be run:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jbosstools-releng/job/jbosstools-releng-push-to-dev-stable-02-copy-builds-and-rpms/

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_jbt=4.4.3.Final
versionWithRespin_ds=10.3.0.GA
version_jbt=$(echo ${versionWithRespin_jbt} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
if [[ ${version_jbt} == *".Final" ]]; then
  stream_jbt=4.4.neon
  stream_ds=10.0.neon
else
  stream_jbt=master
  stream_ds=master
fi

ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-dev-stable-02-copy-builds-and-rpms; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="stream_jbt=${stream_jbt}&stream_ds=${stream_ds}&\
versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----


=== Update /development/updates/ sites (and /stable/updates if Final)

See JBT_Release.adoc


== Update Target Platforms

See JBT_Release.adoc


== Release the latest milestone to ide-config.properties

See JBT_Release.adoc


== Update Marketplace entry

WARNING: Only applies to Beta and better versions.

[source,bash]
----

google-chrome && google-chrome http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio/edit

----


=== If node doesn't exist yet

For the first Beta, create a new node on Marketplace, using single feature, com.jboss.devstudio.core.feature

=== If node already exists

Access it via +http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio/edit+ and update the following things:

* Solution version number to match new version
* Description to match new version & dependencies
* Notes / warnings (if applicable, eg., JDK issues)

=== Validate Marketplace install

1. Get a compatible Eclipse
2. Install from Marketplace
3. Install everything from Central + Earlyaccess
4. Test a project example


== Release JIRA

See JBT_Release.adoc


== Submit PR to update tools.jboss.org

Provide a PR to add the latest JBDS milestones to this listing:

https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml

For non-Final/GA releases, only JBT should be added. Examples:

* https://github.com/jbosstools/jbosstools-website/pull/622 (JBT 4.4.1 / JBDS 10.1)
* https://github.com/jbosstools/jbosstools-website/pull/651 (JBT 4.4.2.AM3)

=== SHA256 values

To get the SHA256 values for easy pasting into the product.yml file, first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then run this:

[source,bash]
----
versionWithRespin_ds=10.3.0.GA
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # **

cd ~/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ # ~
for f in *.jar *.zip; do
  size=$(du -h $f); size=${size%*M*};
  sha=$(cat ${f}.sha256); sh=${sha:0:2};
  echo "            url: http://www.jboss.org/download-manager/content/origin/files/sha256/${sh}/${sha}/${f}" >> /tmp/yml.txt
  echo "            file_size: ${size}MB" >> /tmp/yml.txt
done
cd /tmp
f=devstudio-${version_ds}-target-platform.zip
size=$(wget https://devstudio.redhat.com/10.0/development/updates/core/ --no-check-certificate -q -O - | egrep devstudio-${version_ds}-target-platform.zip | egrep -v sha256 | sed "s#.\+>\([0-9]\+M\)</td.\+#\1#")
# sha=$(wget https://devstudio.redhat.com/10.0/development/updates/core/${f}.sha256 --no-check-certificate -q -O -); sh=${sha:0:2}
echo "            url: https://devstudio.redhat.com/10.0/development/updates/core/${f}" >> /tmp/yml.txt
echo "            file_size: ${size}B" >> /tmp/yml.txt
cat /tmp/yml.txt; rm -f /tmp/yml.txt

----

[IMPORTANT]
====
You will need hub installed to generate a PR via commandline script below. You can get it here:

https://hub.github.com/
====

Then, back on your own machine...

[source,bash]
----
version_jbt=4.4.3.AM1
version_ds=10.3.0.AM1

topic=release-${version_jbt}
branch=master
gituser=${GITUSER} # your github username

# where you have https://github.com/jbosstools/jbosstools-website checked out
cd ${HOME}/tru
pushd jbosstools-website/

  git stash
  git checkout ${branch}
  git pull origin ${branch}
  git pull origin
  git checkout origin/${branch} -b ${topic}
  git checkout ${topic}
  git stash pop

  # using your text editor of choice, vim, sublime, etc.
  vim _config/products.yml
  st _config/products.yml

  # make changes, using the generated content above, then...

  if [[ ${version_jbt} == *"Final" ]]; then
    git commit -m "add ${version_jbt} and ${version_ds} to tools.jboss.org" .
  else
    git commit -m "add ${version_jbt} to tools.jboss.org" .
  fi

  numCommits=$(git status | egrep "by [0-9]+ commit" | sed "s/.\+by \([0-9]\+\) commit.*/\1/")
  if [[ $numCommits -gt 1 ]]; then
    #squash commits ##
    echo ""
    echo "Squash commits:"
    echo "  git rebase -i HEAD~$numCommits" # ~
    echo ""
    git rebase -i HEAD~$numCommits # ~
    if [[ "$?" != "0" ]]; then break 2; fi
  fi
  git pull --rebase origin ${branch}
  git push ${gituser} ${topic}
  parentProject=$(git remote -v | grep origin | grep push | sed "s/.\+github.com\(:\|\/\)\(.\+\)\/.\+/\2/")
  thisProject=$(git remote -v | grep origin | grep push | sed "s/.\+github.com\(:\|\/\)\(.\+\)\/\(.\+\)\.git.\+/\3/")
  # to do a 'hub pull-request' you must install hub first: https://github.com/defunkt/hub#readme
  # alternatively, you can do a pull request in your browser from https://github.com/${gituser}/devstudio-<component>
  lastCommitComment="$(git log -1 --pretty=%B)"
  if [[ ${lastCommitComment:45} ]]; then
    msgTitle=${lastCommitComment:0:45} # first 45 chars
    msgTitle=${msgTitle% *} # no partial words
    hub pull-request -o -f -m "${msgTitle}...

${lastCommitComment}" -b ${parentProject}:${branch} -h ${gituser}:${topic}
  else
    hub pull-request -o -f -m "${lastCommitComment}

${lastCommitComment}" -b ${parentProject}:${branch} -h ${gituser}:${topic}
  fi
  echo ""
  echo "  >> Pull Request: https://github.com/${parentProject}/${thisProject}/pulls/${gituser}"
  echo "  >> Topic Branch: https://github.com/${gituser}/${thisProject}/commits/${topic}"
  echo "  >> Origin Branch: https://github.com/${parentProject}/${thisProject}/commits/${branch}"
  echo "  >> JIRA / Topic: https://issues.jboss.org/browse/${topic}"
  echo ""

popd


----

Commit changes and submit PR, eg., https://github.com/jbosstools/jbosstools-website/pull/651 or https://github.com/jbosstools/jbosstools-website/pull/664


== Tagging Developer Studio

See Branching_and_Tagging.adoc


== Smoke test the release

Before notifying team of release, must check for obvious problems. Any failure there should be fixed with highest priority. In general, it could be wrong URLs in a composite site.

=== Validate update site install (BYOE)

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install BYOE category from https://devstudio.redhat.com/10.0/development/updates/ and/or https://devstudio.redhat.com/10.0/stable/updates/
3. Restart. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

=== Validate installer install

1. Download JBDS installer from https://devstudio.redhat.com/10.0/development/builds/ or https://devstudio.redhat.com/10.0/stable/builds/
2. Install via UI or headlessly with
    java -jar devstudio-*.jar -console -options /dev/null
3. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----

version_ds=10.3.0.GA
qual="development"; if [[ ${version##*GA} == "" ]]; then qual="stable"; fi # **##
cd ~/tmp # ~
wget https://devstudio.redhat.com/static/10.0/${qual}/builds/devstudio-${version_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/static/10.0/${qual}/builds/devstudio-${version_ds}-build-product/latest/all/${installerJar}

java -jar ~/tmp/${installerJar} # ~

----


== Notify Team Lead(s)

Here's a job that notifies Jeff that the website is ready to be updated with a new blog post:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-dev-stable-07-notification-emails/configure

Using the script below, you can trigger the job remotely.

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

blogURL=/blog/10.3.0.ga-for-neon.2.html
pullrequestNum=682
eclipseVersionSuffix=".2" # for Eclipse 4.6.2 Neon.2

versionWithRespin_jbt=4.4.3.Final
versionWithRespin_ds=10.3.0.GA
version_jbt=$(echo ${versionWithRespin_jbt} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # \) # ***
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***

ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-dev-stable-07-notification-emails; do
  prevJob=$(prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable" -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="version_jbt=${version_jbt}&version_ds=${version_ds}&\
blogURL=${blogURL}&pullrequestNum=${pullrequestNum}&eclipseVersionSuffix=${eclipseVersionSuffix}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----


== Commit updates to release guide (including this document):

[source,bash]
----

version_jbt=4.4.3.Final
version_ds=10.3.0.GA
cd jbdevstudio-devdoc/release_guide/
git commit -m "update release guide for ${version_jbt} and ${version_ds}" .
git push origin HEAD:master

----

