= Publishing devstudio Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

TODO: use consistent instructions for fetching sources from git & pushing changes
TODO: use sshfs to do copies in a single step, instead of rsync-pull/rsync-push (2 steps)

== Update Discovery Sites and URLs

See details in JBT_Staging_For_QE.adoc

== Verify correct version set in com.jboss.devstudio.central.core

See details in JBT_Staging_For_QE.adoc

== Disable jobs

See details in JBT_Staging_For_QE.adoc

== Stage to devstudio.redhat.com and internal qa server

=== Copy & rename builds & update sites from "snapshots" to "staging"

Here is a job that performs the copy (& rename) from /snapshots/ to /staging/:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_master/

Here's a job that verifies everything is published:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-03-verify-builds-update-sites_master/


[source,bash]
----

# TODO once the staging build folder exists, start fetching the devstudio installer (we'll need it later to do a smoke test)

cd ~/tmp
rm -f index.html
versionWithRespin_ds=10.2.0.AM3 # a, b, c...
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}

----

You'll use this downloaded installer later, but since it takes a while to download, it's more efficient to start it now.


=== Cleanup OLD builds

Optional step.

Run this job to move any old builds into an OLD/ folder for later cleanup, or delete them immediately.

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites_master

----

=== Update https://devstudio.jboss.com/10.0/staging/updates/

This should point to the latest staging bits. Just copy what's in discovery.central/composite*.xml into this folder.

[source,bash]
----

cd ~/truu
RSYNC="rsync -aPrz --rsh=ssh --protocol=28"

versionWithRespin_ds_PREV=10.2.0.AM2 # a, b, c...
versionWithRespin_ds=10.2.0.AM3 # a, b, c...
# use filemgmt.jboss.org IP instead of 10.5.105.197 because it's 3x faster!
DESTINATION=devstudio@10.5.105.197:/www_htdocs/devstudio
PROJECT_PATH=jbdevstudio-website/content
DEST_URL="https://devstudio.redhat.com"
updatePath=10.0/staging/updates

pushd ${PROJECT_PATH}/${updatePath}
git fetch origin master
git checkout FETCH_HEAD

for d in discovery.central discovery.earlyaccess; do
  mkdir -p ${d}/${versionWithRespin_ds}/
  pushd ${d}/${versionWithRespin_ds}/
    ${RSYNC} ${DESTINATION}/${updatePath}/${d}/${versionWithRespin_ds}/composite*xml ./
	# should not have and devstudio .Final stuff (except target platform versions)
	for c in composite*.xml; do sed -i "s/${versionWithRespin_ds_PREV}/${versionWithRespin_ds}/g" $c; done
    cat compositeContent.xml | egrep "${versionWithRespin_ds}|targetplatforms|REPO|updates|timestamp"
  popd
done
rsync discovery.central/${versionWithRespin_ds}/composite*.xml ./

# update index.html
if [[ -f index.html ]]; then
  sed -i "s#${versionWithRespin_ds_PREV}#${versionWithRespin_ds}#" index.html
  cat index.html | egrep "${versionWithRespin_ds_PREV}|${versionWithRespin_ds}"
fi

# push changes to server
${RSYNC} discovery.central/${versionWithRespin_ds}/composite*xml ${DESTINATION}/${updatePath}/discovery.central/${versionWithRespin_ds}/
${RSYNC} discovery.earlyaccess/${versionWithRespin_ds}/composite*xml ${DESTINATION}/${updatePath}/discovery.earlyaccess/${versionWithRespin_ds}/
${RSYNC} ./composite*xml *.html ${DESTINATION}/${updatePath}/

# verify changes
echo "Check 4 URLs:"
google-chrome && google-chrome \
${DEST_URL}/${updatePath}/discovery.central/${versionWithRespin_ds}/compositeContent.xml \
${DEST_URL}/${updatePath}/discovery.earlyaccess/${versionWithRespin_ds}/compositeContent.xml \
${DEST_URL}/${updatePath}/compositeContent.xml \
${DEST_URL}/${updatePath}/

rm -fr discovery.central/${versionWithRespin_ds}/composite*.xml discovery.earlyaccess/${versionWithRespin_ds}/composite*.xml

# commit the change and push to master
git commit -m "release ${versionWithRespin_ds} to QE" .
git push origin HEAD:master
popd

----

=== Merge in Integration Stack content

See details in Merge_IS_Discovery.adoc

== Release the latest staging site to ide-config.properties

See details in JBT_Staging_For_QE.adoc


== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install BYOE category from

https://devstudio.redhat.com/10.0/staging/updates/

3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----
versionWithRespin_ds=10.2.0.AM3 # a, b, c...
cd ~/tmp
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html

# should have already downloaded this above
if [[ ! -f ${installerJar} ]]; then wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}; fi

java -jar ~/tmp/${installerJar}

----

0. After downloading and installing devstudio from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See details in JBT_Staging_For_QE.adoc

TODO: Important: if you switched the _master jobs to run from origin/jbosstools-4.4.x or some other branch, make sure that the jobs are once again building from the correct branch.


== Notify the team (send 1 email)

See details in JBT_Staging_For_QE.adoc

