= Publishing devstudio Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

TODO: use consistent instructions for fetching sources from git & pushing changes
TODO: use sshfs to do copies in a single step, instead of rsync-pull/rsync-push (2 steps)

== Update Discovery Sites and URLs

See details in JBT_Staging_For_QE.adoc

== Verify correct version set in com.jboss.devstudio.central.core

See details in JBT_Staging_For_QE.adoc

== Disable jobs

See details in JBT_Staging_For_QE.adoc

== Stage to devstudio.redhat.com and internal qa server

=== Copy & rename builds & update sites from "snapshots" to "staging"

Here is a job that performs the copy (& rename) from /snapshots/ to /staging/:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-staging-02-copy-builds-and-update-sites_master/

Here's a job that verifies everything is published:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-staging-03-verify-builds-update-sites_master/


[source,bash]
----

# TODO once the staging build folder exists, start fetching the devstudio installer (we'll need it later to do a smoke test)

cd ~/tmp
rm -f index.html
versionWithRespin_ds=10.1.0.AM3 # a, b, c...
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}

----

You'll use this downloaded installer later, but since it takes a while to download, it's more efficient to start it now.


=== Cleanup OLD builds

Optional step.

First, use sshfs to mount filemgmt file paths.

[source,bash]
----

JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
sshfs $JBDS $HOME/JBDS-ssh

----

Then move old builds into an OLD/ folder to they're less visible and ready for deletion later.

[source,bash]
----
version_PREV=10.0.0.Alpha0 # a, b, c...
for d in updates/core updates/central updates/earlyaccess updates/discovery.central updates/discovery.earlyaccess builds; do
  if [[ -d $HOME/JBDS-ssh/10.0/staging/${d}/ ]]; then
    echo "${d}/*${version_PREV}* ..."
    mkdir -p $HOME/JBDS-ssh/10.0/staging/${d}/OLD/
    mv $HOME/JBDS-ssh/10.0/staging/${d}/*${version_PREV}* $HOME/JBDS-ssh/10.0/staging/${d}/OLD/
  fi
done

----

=== Update https://devstudio.jboss.com/10.0/staging/updates/

This should point to the latest staging bits. Just copy what's in discovery.central/composite*.xml into this folder.

[source,bash]
----

cd ~/truu
RSYNC="rsync -aPrz --rsh=ssh --protocol=28"

versionWithRespin_ds_PREV=10.0.1.AM2 # a, b, c...
versionWithRespin_ds=10.1.0.AM3 # a, b, c...
DESTINATION=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
PROJECT_PATH=jbdevstudio-website/content
DEST_URL="https://devstudio.redhat.com"
updatePath=10.0/staging/updates

pushd ${PROJECT_PATH}/${updatePath}
git fetch origin master
git checkout FETCH_HEAD

for d in discovery.central discovery.earlyaccess; do
  mkdir -p ${d}/${versionWithRespin_ds}/
  pushd ${d}/${versionWithRespin_ds}/
    ${RSYNC} ${DESTINATION}/${updatePath}/${d}/${versionWithRespin_ds}/composite*xml ./
	# should not have and devstudio .Final stuff (except target platform versions)
	for c in composite*.xml; do sed -i "s/${versionWithRespin_ds_PREV}/${versionWithRespin_ds}/g" $c; done
    cat compositeContent.xml | egrep "${versionWithRespin_ds}|targetplatforms|REPO|updates|timestamp"
  popd
done
rsync discovery.central/${versionWithRespin_ds}/composite*.xml ./

# update index.html
if [[ -f index.html ]]; then
  sed -i "s#${versionWithRespin_ds_PREV}#${versionWithRespin_ds}#" index.html
  cat index.html | egrep "${versionWithRespin_ds_PREV}|${versionWithRespin_ds}"
fi

# push changes to server
${RSYNC} discovery.central/${versionWithRespin_ds}/composite*xml ${DESTINATION}/${updatePath}/discovery.central/${versionWithRespin_ds}/
${RSYNC} discovery.earlyaccess/${versionWithRespin_ds}/composite*xml ${DESTINATION}/${updatePath}/discovery.earlyaccess/${versionWithRespin_ds}/
${RSYNC} ./composite*xml *.html ${DESTINATION}/${updatePath}/

# verify changes
echo "Check 4 URLs:"
google-chrome && google-chrome \
${DEST_URL}/${updatePath}/discovery.central/${versionWithRespin_ds}/compositeContent.xml \
${DEST_URL}/${updatePath}/discovery.earlyaccess/${versionWithRespin_ds}/compositeContent.xml \
${DEST_URL}/${updatePath}/compositeContent.xml \
${DEST_URL}/${updatePath}/

rm -fr discovery.central/${versionWithRespin_ds}/composite*.xml discovery.earlyaccess/${versionWithRespin_ds}/composite*.xml

# commit the change and push to master
git commit -m "release ${versionWithRespin_ds} to QE" .
git push origin HEAD:master
popd

----

=== Merge in Integration Stack content

See details in Merge_IS_Discovery.adoc

== Release the latest staging site to ide-config.properties

See details in JBT_Staging_For_QE.adoc


== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install BYOE category from https://devstudio.redhat.com/10.0/staging/updates/
3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----
versionWithRespin_ds=10.1.0.AM3 # a, b, c...
cd ~/tmp
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html

# should have already downloaded this above
if [[ ! -f ${installerJar} ]]; then wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}; fi

java -jar ~/tmp/${installerJar}

----

0. After downloading and installing devstudio from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See details in JBT_Staging_For_QE.adoc

TODO: Important: if you switched the _master jobs to run from origin/jbosstools-4.4.x or some other branch, make sure that the jobs are once again building from the correct branch.


== Notify the team (send 1 email)

See details in JBT_Staging_For_QE.adoc


== Kick downstream Dev Platform Installer

Now that devstudio installer is staged, you can submit a PR against the dev platform installer and have that built.

See: https://github.com/redhat-developer-tooling/developer-platform-install/blob/master/requirements.json#L24

Build: http://machydra.brq.redhat.com:8080/job/developer-platform-installer-build/

When done, start signing process. See https://mojo.redhat.com/docs/DOC-1075518


== Copy Dev Platform Installer exe to Wonka

Denis (or Nick) will publish the latest installer to Wonka.

On wonka.mw.lab.eng.bos.redhat.com (10.16.89.81), the signed installer will be in this folder:

you@wonka.mw.lab.eng.bos.redhat.com:/home/windup/apache2/www/html/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all


== Copy Dev Platform Installer & description/instruction files to www.qa

To prepare for staging in CSP, copy these files into the build folder and rename them so they match the filename of the .exe installer:

https://raw.githubusercontent.com/jbdevstudio/jbdevstudio-product/jbosstools-4.4.0.x/results/customer-portal/devsuite.detailed-description.html
https://raw.githubusercontent.com/jbdevstudio/jbdevstudio-product/jbosstools-4.4.0.x/results/customer-portal/devsuite.manual-instructions.txt

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then:

[source,bash]
----

versionWithRespin_ds=10.1.0.AM3 # a, b, c...
installerExe=development-suite-1.0.1-foo-fix-this-bundle-installer.exe
installerDir=RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all
wonkaDir=nboldt@wonka.mw.lab.eng.bos.redhat.com:/home/windup/apache2/www/html/

# grab a copy of the installer.exe from Wonka
scpr ${wonkaDir}/${installerDir}/${installerExe} $HOME/${installerDir}/
# generate new sha256sum (takes about 3 minutes!)
y=$HOME/${installerDir}/${installerExe}; for m in $(sha256sum ${y}); do if [[ $m != ${y} ]]; then echo $m > ${y}.sha256; fi; done
cat ${y}.sha256

----

Review content here:

http://www.qa.jboss.com/binaries/devstudio/10.0/staging/builds/devstudio-10.1.0.AM3-build-product/latest/all/

== Notify the team (send 1 email)

Run this on dev01 so that we can use /bin/mail. Email should be generated automatically rather than requiring copy & paste into your mail client.

[source,bash]
----
version_ds=10.1.0.AM3
version_devsuite=1.0.0-GA
versionWithRespin_ds=10.1.0.AM3 # a, b, c...
installerExe=development-suite-1.0.1-foo-fix-this-bundle-installer.exe
installerDir=RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all
respin="respin-"
recipients=jboss-devstudio-list@redhat.com
sender="Nick Boldt <nboldt@redhat.com>"
subject="Red Hat Development Suite ${version_devsuite} (including devstudio ${versionWithRespin_ds}) available for QE testing"
echo "
These are not FINAL bits, but preliminary results for QE & community testing. Not for redistribution to customers or end users.

Windows Installer:

http://www.qa.jboss.com/binaries/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerExe}

New + Noteworthy (subject to change):
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule / Upcoming Releases: https://issues.jboss.org/projects/JBDS?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page
" > /tmp/mailbody.ds.txt
if [[ $respin != "respin-" ]]; then
echo "
--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${version_ds}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${version_JBT}%22%29%29%29

To compare the upcoming version of Central (${versionWithRespin_ds}) against an older version, add lines similar to these your eclipse.ini file after the -vmargs line for the appropriate version & URLs:
 -Djboss.discovery.directory.url=https://devstudio.redhat.com/10.0/staging/updates/discovery.central/${versionWithRespin_ds}/devstudio-directory.xml
 -Djboss.discovery.site.url=https://devstudio.redhat.com/10.0/staging/updates/
 -Djboss.discovery.earlyaccess.site.url=https://devstudio.redhat.com/10.0/staging/updates/discovery.earlyaccess/${versionWithRespin_ds}/
 -Djboss.discovery.earlyaccess.list.url=https://devstudio.redhat.com/10.0/staging/updates/discovery.earlyaccess/${versionWithRespin_ds}/devstudio-earlyaccess.properties

" >> /tmp/mailbody.ds.txt
fi

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" $recipients -- -f"$sender" < /tmp/mailbody.ds.txt
rm -f /tmp/mailbody.ds.txt

----
____

