= Release JBoss Developer Studio Development Milestone

This document describe how to publish a valid JBoss Developer Studio build to production after being verified by QE.

= Prerelease Steps

These steps can be done before the actual release (eg., on the Thurs or Fri before the Monday release, as long as QE has more-or-less signed off). Check with QE before proceeding.

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA.

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten.

Send an email to jbosstools-dev@ and jboss-devstudio-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
google-chrome && google-chrome https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions

----

== Rename artifacts to remove timestamp and buildID

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`devstudio-10.3.0.AM1-v20151002-2235-B124-installer-eap.jar` must be renamed to `devstudio-10.3.0.AM1-installer-eap.jar`.

Connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then:

[source,bash]
----
versionExe=1.2.0-GA # note the dash, not period after x.y.z
versionWithRespin_ds=10.3.0.AM1 # a, b, c...
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
pushd /qa/services/http/binaries/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
for f in $(ls *latest*); do echo "rm $f"; rm -f $f; done
for f in $(ls devstudio-${version_ds}-* | grep -v latest); do g=$(echo $f | sed s#-v[[:digit:]]*-[[:digit:]]*-B[[:digit:]]*##); echo "mv $f $g"; mv $f $g; done
for f in $(ls development-suite-${versionExe}-* | grep -v latest); do g=$(echo $f | sed s#-[[:digit:]]*-[[:digit:]]*##); echo "mv $f $g"; mv $f $g; done
touch *
chmod +x *.jar *.exe
ls -l
popd
----

Now, move & symlink the ${versionWithRespin_ds} folder:

[source,bash]
----
versionWithRespin_ds=10.3.0.AM1 # a, b, c...
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
buildType=stable # use /stable/ or /development/ as appropriate
pushd /qa/services/http/binaries/RHDS/10.0/staging/builds/
mkdir -p ../../${buildType}/builds/
mv devstudio-${versionWithRespin_ds}-build-product ../../${buildType}/builds/devstudio-${version_ds}-build-product
ln -s ../../${buildType}/builds/devstudio-${version_ds}-build-product devstudio-${versionWithRespin_ds}-build-product
popd

----

== Verify install instructions are correct

Look at the .txt and .html files in /qa/services/http/binaries/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/

Verify that they contain correct install/usage instructions & versions.

If anything is wrong, fix it by hand, then also commit your changes to the templates.

https://github.com/jbdevstudio/jbdevstudio-product/commit/3827045dca85e73c5ae339cc13f514591e3c1835
https://github.com/jbdevstudio/jbdevstudio-product/commit/e6c2954207d1db7451f7adfd2d89c7ceccd6adbe

== Submit PRs to update https://www.jboss.org/products/devstudio/ and http://developers.redhat.com/products/devstudio/

Goal is to update the following pages to include links to guides and to set the correct latest GA release version:

* https://www.jboss.org/products/devstudio/download/
* https://www.jboss.org/products/devstudio/overview/
* http://developers.redhat.com/products/devstudio/overview/
* http://developers.redhat.com/products/devstudio/download/

by updating these lines:

* https://github.com/jboss-developer/www.jboss.org/blob/master/products/devstudio/_common/product.yml#L3
* https://github.com/redhat-developer/developers.redhat.com/blob/master/products/devstudio/_common/product.yml#L4

Past example:

* https://issues.jboss.org/browse/DEVELOPER-2900
* https://github.com/jboss-developer/www.jboss.org/pull/1032
* https://github.com/redhat-developer/developers.redhat.com/pull/1021

Once you have the JIRA, you can link to it when sending the note to release-engineering@ below.

TODO: add EAP 7 zip / installer to list of devstudio artifacts on both developers.redhat.com and www.jboss.org. Explicit listing of files used to be done like this:
* https://github.com/redhat-developer/developers.redhat.com/blob/25640af93a8d7d219c189d37c528534acda17483/products/devstudio/_common/product.yml and
* https://github.com/redhat-developer/developers.redhat.com/blob/25640af93a8d7d219c189d37c528534acda17483/products/eap/_common/product.yml


== Announce internally for push to CSP staging site

First thing is to ask for availability of the binaries to CSP (Red Hat Customer Portal) and Golden Gate (JBoss products portal).

NOTE: As this takes some time and can be easily cancelled, this step can be anticipated a few days before release.

Previous tickets:

* https://projects.engineering.redhat.com/browse/RCM-6841
* https://projects.engineering.redhat.com/browse/RCM-10069

*To* release-engineering@redhat.com +
and +
*Cc* cobrien@redhat.com, ldimaggi@redhat.com, mhusnain@redhat.com, timoran@redhat.com, nboldt@redhat.com, mistria@redhat.com, alkazako@redhat.com, jmaury@redhat.com, bsutter@redhat.com, pmuir@redhat.com, paul.robinson@redhat.com, dcoughli@redhat.com +

[source,bash]
----
versionWithRespin_ds=10.3.0.AM1 # a, b, c...
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
buildType=stable # use /stable/ or /development/ as appropriate
GOLIVEDATE="Wed, Dec 07, 2016"

if [[ ${version_ds} != ${versionWithRespin_ds} ]]; then
  versionFriendlyName="${version_ds} (to be renamed from ${versionWithRespin_ds})"
else
  versionFriendlyName="${version_ds}"
fi

TOrecipients="release-engineering@redhat.com"
CCrecipients="cobrien@redhat.com, ldimaggi@redhat.com, mhusnain@redhat.com, nboldt@redhat.com, alkazako@redhat.com, jmaury@redhat.com, lmohanty@redhat.com"
sender="Nick Boldt <nboldt@redhat.com>"
subject="Red Hat JBoss Developer Studio ${versionFriendlyName} available for push to CSP, CDN, & Download Manager staging servers"

echo "
JBoss Developer Studio ${versionFriendlyName} is available to push to CSP, CDN, & Download Manager staging servers, for subsequent smoke test & review by QE.

We hope to promote the staged (or hidden) artifacts to production by the end of the day, Eastern Standard Time, on ${GOLIVEDATE}. If required, the end of the next day is also acceptable.

Files to publish are available from here [0]:

[0] http://www.qa.jboss.com/binaries/devstudio/10.0/${buildType}/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/

There are 4 files for push to CSP:

* devstudio-${version_ds}-installer-standalone.jar
* devstudio-${version_ds}-installer-eap.jar
* devstudio-${version_ds}-updatesite-core.zip
* devstudio-${version_ds}-updatesite-central.zip

Please include the pre-generated the HTML and text content in the above folder when creating new CSP pages.

There are 4 files for for push to CDN / download manager:

* devstudio-${version_ds}-installer-standalone.jar
* devstudio-${version_ds}-installer-eap.jar
* devstudio-${version_ds}-updatesite-core.zip
* devstudio-${version_ds}-updatesite-central.zip

Note that the sources zip has been removed.

If feasible, you could still publish the .txt and .html instructions, which will direct people to fetch sources from github and explain some gotchas when building.

--

When pushed, please reply so that QE can review the CSP pages & CDN files for push to production.

Note that in addition to the new CSP page, eg., [1] or [2], the CSP landing page [3] should also be updated to point to the latest release.

[1] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=${version_ds}
[2] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=10.3.0
[3] https://access.redhat.com/downloads/

Only ONE of the artifacts above [4] requires sign-in from CDN/Download Manager. The rest are No T&C.

[4] devstudio-*-installer-eap.jar (contains EAP)

" > /tmp/mailbody.jbds.txt

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" "$TOrecipients" -c "$CCrecipients" -- -f"$sender" < /tmp/mailbody.jbds.txt
rm -f /tmp/mailbody.jbds.txt

----

Communicate with Paul Robinson / Daniel Coughlin, Chris O'Brien, etc. to coordinate the release. All the above can happen in parallel / before the updates below.


= Release steps

Once QE has signed off, and bits are staged to CSP, you can proceed w/ the rest of the release.

== Copy from /staging/ into /development/ (and /stable/)

Here is a job that performs the copy from /staging/ to /development/:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-dev-stable-02-copy-builds-and-update-sites

You can also push just the RPMs with this job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-dev-stable-02-copy-builds-and-rpms

When the job is done, verify everything has been published:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-dev-stable-03-verify-builds-update-sites

=== Update /development/updates/ sites (and /stable/updates if Final)

See JBT_Release.adoc


== Update Target Platforms

See JBT_Release.adoc


== Release the latest milestone to ide-config.properties

See JBT_Release.adoc


== Update Marketplace entry

WARNING: Only applies to Beta and better versions.

[source,bash]
----

google-chrome && google-chrome http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio/edit

----


=== If node doesn't exist yet

For the first Beta, create a new node on Marketplace, using single feature, com.jboss.devstudio.core.feature

=== If node already exists

Access it via +http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Notes / warnings (if applicable, eg., JDK issues)

=== Validate Marketplace install

1. Get a compatible Eclipse
2. Install from Marketplace
3. Install everything from Central + Earlyaccess
4. Test a project example


== Release JIRA

See JBT_Release.adoc


== Submit PR to update tools.jboss.org

Provide a PR to add the latest JBDS milestones to this listing:

https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml_

Examples:

* https://github.com/jbosstools/jbosstools-website/pull/622 (JBT 4.4.1 / JBDS 10.1)
* https://github.com/jbosstools/jbosstools-website/pull/651 (JBT 4.4.2.AM3)

=== SHA256 values

To get the SHA256 values for easy pasting into the product.yml file, first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then run this:

[source,bash]
----
versionWithRespin_ds=10.3.0.AM1 # a, b, c...
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # **

cd ~/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ # ~
for f in *.jar *.zip; do
  size=$(du -h $f); size=${size%*M*};
  sha=$(cat ${f}.sha256); sh=${sha:0:2};
  echo "            url: http://www.jboss.org/download-manager/content/origin/files/sha256/${sh}/${sha}/${f}" >> /tmp/yml.txt
  echo "            file_size: ${size}MB" >> /tmp/yml.txt
done
cd /tmp
f=devstudio-${version_ds}-target-platform.zip
size=$(wget https://devstudio.redhat.com/10.0/development/updates/core/ --no-check-certificate -q -O - | egrep devstudio-${version_ds}-target-platform.zip | egrep -v sha256 | sed "s#.\+>\([0-9]\+M\)</td.\+#\1#")
# sha=$(wget https://devstudio.redhat.com/10.0/development/updates/core/${f}.sha256 --no-check-certificate -q -O -); sh=${sha:0:2}
echo "            url: https://devstudio.redhat.com/10.0/development/updates/core/${f}" >> /tmp/yml.txt
echo "            file_size: ${size}B" >> /tmp/yml.txt
done
cat /tmp/yml.txt; rm -f /tmp/yml.txt

----

Then, back on your own machine...

[source,bash]
----
version_jbt=4.4.3.AM1
version_ds=10.3.0.AM1

cd ~/tru # where you have jbosstools-website checked out ~

pushd jbosstools-website/
  t=release-${version_jbt}
  gw1m
  st _config/products.yml

  # make changes, using the generated content above, then...

  if [[ ${version_jbt} == *"Final" ]]; then
    git commit -m "add ${version_jbt} and ${version_ds} to tools.jboss.org" .
  else
    git commit -m "add ${version_jbt} to tools.jboss.org" .
  fi
  gw2
popd


----

Commit changes and submit PR, eg., https://github.com/jbosstools/jbosstools-website/pull/651 or https://github.com/jbosstools/jbosstools-website/pull/664


== Tag Git

Once cloned to disk, this script will create the tags if run from the location with your git clones. If tags exist, no new tag will be created.

[source,bash]
----

# if not already cloned, the do this:
git clone https://github.com/jbdevstudio/jbdevstudio-product
git clone https://github.com/jbdevstudio/jbdevstudio-ci
git clone https://github.com/jbdevstudio/jbdevstudio-website
git clone https://github.com/jbdevstudio/jbdevstudio-artwork
git clone https://github.com/jbdevstudio/jbdevstudio-devdoc

version_ds=10.3.0.AM1
if [[ ${version_ds} == *".GA" ]]; then
  jbt_branch=jbosstools-4.4.3.x
else
  jbt_branch=master
fi
cd ~/truu # ~
for d in product ci website artwork devdoc; do
  echo "====================================================================="
  echo "Tagging jbdevstudio-${d} from branch ${jbt_branch} as tag ${version_ds}..."
  pushd jbdevstudio-${d}
  git fetch origin ${jbt_branch}
  git tag jbdevstudio-${version_ds} FETCH_HEAD
  git push origin jbdevstudio-${version_ds}
  echo ">>> https://github.com/jbdevstudio/jbdevstudio-${d}/tree/jbdevstudio-${version_ds}"
  popd >/dev/null
  echo "====================================================================="
  echo ""
done

----

== Smoke test the release

Before notifying team of release, must check for obvious problems. Any failure there should be fixed with highest priority. In general, it could be wrong URLs in a composite site.

=== Validate update site install (BYOE)

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install BYOE category from https://devstudio.redhat.com/10.0/development/updates/ and/or https://devstudio.redhat.com/10.0/stable/updates/
3. Restart. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

=== Validate installer install

1. Download JBDS installer from https://devstudio.redhat.com/10.0/development/builds/ or https://devstudio.redhat.com/10.0/stable/builds/
2. Install via UI or headlessly with
    java -jar devstudio-*.jar -console -options /dev/null
3. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----

version_ds=10.3.0.AM1
qual="development"; if [[ ${version##*GA} == "" ]]; then qual="stable"; fi # **##
cd ~/tmp # ~
wget https://devstudio.redhat.com/static/10.0/${qual}/builds/devstudio-${version_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/static/10.0/${qual}/builds/devstudio-${version_ds}-build-product/latest/all/${installerJar}

java -jar ~/tmp/${installerJar} # ~

----


== Notify Team Lead(s)

Here's a job that notifies Jeff that the website is ready to be updated with a new blog post:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/jbosstools-releng/job/jbosstools-releng-push-to-dev-stable-07-notification-emails/configure

Using the script below, you can trigger the job remotely.

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

blogURL=/blog/am1-for-neon.2.html
pullrequestNum=664
eclipseVersionSuffix=".2" # for Eclipse 4.6.2 Neon.2

versionWithRespin_jbt=4.4.3.AM1
versionWithRespin_ds=10.3.0.AM1
version_jbt=$(echo ${versionWithRespin_jbt} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # \) # ***
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***

JP=/home/nboldt/tru/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-dev-stable-07-notification-emails; do
  ${JP} -j ${j} -t enable
  sleep 3s
  ${JP} -j ${j} -t buildWithParameters -d "version_jbt=${version_jbt}&version_ds=${version_ds}&\
blogURL=${blogURL}&pullrequestNum=${pullrequestNum}&eclipseVersionSuffix=${eclipseVersionSuffix}"
  sleep 15s
  ${JP} -j ${j} -t disable
  ${JP} -j ${j} -t lastBuild/toggleLogKeep
done

----


== Commit updates to release guide (including this document):

[source,bash]
----

version_jbt=4.4.3.AM1
version_ds=10.3.0.AM1
cd ~/truu # ~
cd jbdevstudio-devdoc/release_guide/
git commit -m "update release guide for ${version_jbt} and ${version_ds}" .
git push origin HEAD:master

----

