= Release JBoss Developer Studio Development Milestone

This document describe how to publish a valid JBoss Developer Studio build to production after being verified by QE.

= Prerelease Steps

These steps can be done before the actual release (eg., on the Thurs or Fri before the Monday release, as long as QE has more-or-less signed off). Check with QE before proceeding.

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA.

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten.

Send an email to jbosstools-dev@ and jboss-devstudio-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
google-chrome && google-chrome https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions

----

== Rename artifacts to remove timestamp and buildID

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`devstudio-10.1.0.GA-v20151002-2235-B124-installer-eap.jar` must be renamed to `devstudio-10.1.0.GA-installer-eap.jar`.

Connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then:

[source,bash]
----
version_ds=10.1.0.GA
versionExe=1.1.0-GA # note the dash, not period after x.y.z
versionWithRespin_ds=10.1.0.GA # a, b, c...
pushd /qa/services/http/binaries/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
for f in $(ls *latest*); do echo "rm $f"; rm -f $f; done
for f in $(ls devstudio-${version_ds}-* | grep -v latest); do g=$(echo $f | sed s#-v[[:digit:]]*-[[:digit:]]*-B[[:digit:]]*##); echo "mv $f $g"; mv $f $g; done
for f in $(ls development-suite-${versionExe}-* | grep -v latest); do g=$(echo $f | sed s#-[[:digit:]]*-[[:digit:]]*##); echo "mv $f $g"; mv $f $g; done
touch *
chmod +x *.jar *.exe
ls -l
popd
----

Now, move & symlink the ${versionWithRespin_ds} folder:

[source,bash]
----
version_ds=10.1.0.GA
versionWithRespin_ds=10.1.0.GA # a, b, c...
buildType=stable # use /stable/ or /development/ as appropriate
pushd /qa/services/http/binaries/RHDS/10.0/staging/builds/
mkdir -p ../../${buildType}/builds/
mv devstudio-${versionWithRespin_ds}-build-product ../../${buildType}/builds/devstudio-${version_ds}-build-product
ln -s ../../${buildType}/builds/devstudio-${version_ds}-build-product devstudio-${versionWithRespin_ds}-build-product
popd

----

== Verify install instructions are correct

Look at the .txt and .html files in /qa/services/http/binaries/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/

Verify that they contain correct install/usage instructions & versions.

If anything is wrong, fix it by hand, then also commit your changes to the templates.

https://github.com/jbdevstudio/jbdevstudio-product/commit/3827045dca85e73c5ae339cc13f514591e3c1835
https://github.com/jbdevstudio/jbdevstudio-product/commit/e6c2954207d1db7451f7adfd2d89c7ceccd6adbe

== Submit PRs to update https://www.jboss.org/products/devstudio/ and http://developers.redhat.com/products/devstudio/

Goal is to update the following pages to include links to guides and to set the correct latest GA release version:

* https://www.jboss.org/products/devstudio/download/
* https://www.jboss.org/products/devstudio/overview/
* http://developers.redhat.com/products/devstudio/overview/
* http://developers.redhat.com/products/devstudio/download/

by updating these lines:

* https://github.com/jboss-developer/www.jboss.org/blob/master/products/devstudio/_common/product.yml#L3
* https://github.com/redhat-developer/developers.redhat.com/blob/master/products/devstudio/_common/product.yml#L4

Past example:

* https://issues.jboss.org/browse/DEVELOPER-2900
* https://github.com/jboss-developer/www.jboss.org/pull/1032
* https://github.com/redhat-developer/developers.redhat.com/pull/1021

Once you have the JIRA, you can link to it when sending the note to release-engineering@ below.

TODO: add EAP 7 zip / installer to list of devstudio artifacts on both developers.redhat.com and www.jboss.org. Explicit listing of files used to be done like this:
* https://github.com/redhat-developer/developers.redhat.com/blob/25640af93a8d7d219c189d37c528534acda17483/products/devstudio/_common/product.yml and
* https://github.com/redhat-developer/developers.redhat.com/blob/25640af93a8d7d219c189d37c528534acda17483/products/eap/_common/product.yml


== Announce internally for push to CSP staging site

First thing is to ask for availability of the binaries to CSP (Red Hat Customer Portal) and Golden Gate (JBoss products portal).

NOTE: As this takes some time and can be easily cancelled, this step can be anticipated a few days before release.

*To* release-engineering@redhat.com +
and +
*Cc* cobrien@redhat.com, ldimaggi@redhat.com, mhusnain@redhat.com, jpallich@redhat.com, nboldt@redhat.com, mistria@redhat.com, alkazako@redhat.com, jmaury@redhat.com, bsutter@redhat.com, pmuir@redhat.com, paul.robinson@redhat.com, dcoughli@redhat.com +

[source,bash]
----
version_ds=10.1.0.GA
versionWithRespin_ds=10.1.0.GA # a, b, c...
versionExe=1.1.0-GA # note the dash, not period after x.y.z
buildType=stable # use /stable/ or /development/ as appropriate
GOLIVEDATE="Tuesday, June 22, 2016"
JIRA="https://issues.jboss.org/browse/DEVELOPER-3207"

if [[ ${version_ds} != ${versionWithRespin_ds} ]]; then
  versionFriendlyName="${version_ds} (to be renamed from ${versionWithRespin_ds})"
else
  versionFriendlyName="${version_ds}"
fi

TOrecipients="release-engineering@redhat.com"
CCrecipients="cobrien@redhat.com, ldimaggi@redhat.com, mhusnain@redhat.com, nboldt@redhat.com, alkazako@redhat.com, jmaury@redhat.com, paul.robinson@redhat.com, dcoughli@redhat.com, dbhole@redhat.com, lmohanty@redhat.com"
sender="Nick Boldt <nboldt@redhat.com>"
subject="Red Hat JBoss Developer Studio ${versionFriendlyName} & Red Hat Development Suite ${versionExe} available for push to CSP staging server & CDN / Download Manager"

echo "
JBoss Developer Studio ${versionFriendlyName} & Red Hat Development Suite ${versionExe} are available to push to CSP staging server and to the CDN / Download Manager, for subsequent smoke test & review by QE.

We hope to go live by ${GOLIVEDATE}.

Here's a JIRA to update http://developers.redhat.com/products/devstudio/ and https://www.jboss.org/products/devstudio/

${JIRA}

Files to publish are available from here [0]:

[0] http://www.qa.jboss.com/binaries/devstudio/10.0/${buildType}/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/

There are 4 files for push to CSP:

* devstudio-${version_ds}-installer-standalone.jar
* devstudio-${version_ds}-installer-eap.jar
* devstudio-${version_ds}-updatesite-core.zip
* devstudio-${version_ds}-updatesite-central.zip
* (exclude development-suite-*-installer.exe)
* (exclude *-src.zip

Please include the pre-generated the HTML and text content in the above folder when creating new CSP pages.

There are 5 files for for push to CDN:

* devstudio-${version_ds}-installer-standalone.jar
* devstudio-${version_ds}-installer-eap.jar
* devstudio-${version_ds}-updatesite-core.zip
* devstudio-${version_ds}-updatesite-central.zip
* development-suite-${versionExe}-bundle-installer.exe
* (exclude *-src.zip)

When pushed, please reply so that QE can review the CSP pages & CDN files for push to production.

Note that in addition to the new CSP page, eg., [1] or [2], the CSP landing page [3] should also be updated to point to the latest release.

[1] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version_ds=${version_ds}
[2] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version_ds=10.0.0
[3] https://access.redhat.com/downloads/

Only TWO of the artifacts above [4],[5] require sign in from CDN/Download Manager. The rest are No T&C.

[4] devstudio-*-installer-eap.jar (contains EAP)
[5] development-suite-*-installer.jar (contains RHEL)

" > /tmp/mailbody.jbds.txt

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" "$TOrecipients" -c "$CCrecipients" -- -f"$sender" < /tmp/mailbody.jbds.txt
rm -f /tmp/mailbody.jbds.txt

----

Communicate with Paul Robinson / Daniel Coughlin, Chris O'Brien, etc. to coordinate the release. All the above can happen in parallel / before the updates below.


= Release steps

Once QE has signed off, and bits are staged to CSP, you can proceed w/ the rest of the release.

== Copy from /staging/ into /development/

Here is a job that performs the copy from /staging/ to /development/:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-dev-stable-02-copy-builds-and-update-sites_4.4.neon/configure

Or, if that fails:

[source,bash]
----
# globals
eclipseReleaseName=neon
devstudioReleaseVersion=10.0
quiet="-q" # "" for loud, or "-q" for quiet log
STAGE=${WORKSPACE}/jbosstools-build-ci/publish/stage.sh

if [[ ! -x ${STAGE} ]]; then
  cd /tmp
  if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
  wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.4.x/publish/stage.sh --no-check-certificate
  chmod +x stage.sh
  STAGE=/tmp/stage.sh
fi

norm="\033[0;39m"
green="\033[1;32m"
red="\033[1;31m"

####################################################

version_ds=10.1.0.GA
versionWithRespin_ds=10.1.0.GA

JBDS="devstudio@filemgmt.jboss.org:/www_htdocs/devstudio"
mkdir -p ${HOME}/JBDS-ssh; sshfs $JBDS ${HOME}/JBDS-ssh

# 1. installers, update sites, central/earlyaccess, discovery (5 builds)
quals="development"; if [[ ${version_ds##*GA} == "" ]]; then quals="development stable"; fi # **##
for qual in $quals; do
  for site in product central earlyaccess discovery.central discovery.earlyaccess; do
    time ${STAGE} -sites $site -stream "${versionWithRespin_ds}" -vr ${version_ds} -sd ${devstudioReleaseVersion} \
      -dd static/${devstudioReleaseVersion} -st staging -dt ${qual} \
      -JOB_NAME devstudio-${versionWithRespin_ds}-build-\${site} -DESTINATION ${JBDS} -DEST_URL https://devstudio.redhat.com ${quiet} &
    sleep 5
  done
done

# 2. copy 1 site: devstudio installers & update site [INTERNAL - includes EAP installer]
quals="development"; if [[ ${version_ds##*GA} == "" ]]; then quals="development stable"; fi # **##
for qual in $quals; do
  for site in product; do
    time ${STAGE} -sites $site -stream "${versionWithRespin_ds}" -vr ${version_ds} -sd ${devstudioReleaseVersion} \
      -dd static/${devstudioReleaseVersion} -st staging -dt ${qual} \
      -JOB_NAME devstudio-${versionWithRespin_ds}-build-\${site} \
      -DESTINATION /qa/services/http/binaries/RHDS -DEST_URL http://www.qa.jboss.com/binaries/devstudio ${quiet} &
    sleep 5
  done
done

# copy 6 zips & SHAs
# devstudio-10.1.0.GA-target-platform-central.zip           devstudio-10.1.0.GA-target-platform.zip          devstudio-10.1.0.GA-updatesite-core.zip
# devstudio-10.1.0.GA-target-platform-earlyaccess.zip       devstudio-10.1.0.GA-updatesite-central.zip       devstudio-10.1.0.GA-updatesite-earlyaccess.zip
tmpdir=~/temp-stage/release_ds_${version_ds}_zips # ~
quals="development"; if [[ ${version_ds##*GA} == "" ]]; then quals="development stable"; fi # **##
for site in core; do
  mkdir -p ${tmpdir}/${devstudioReleaseVersion}/development/updates/${site}
  # get zips
  time rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/${devstudioReleaseVersion}/staging/updates/${site}/devstudio-${versionWithRespin_ds}*.zip* \
    ${tmpdir}/${devstudioReleaseVersion}/development/updates/${site}/
  for qual in $quals; do
    echo "mkdir ${site}" | sftp ${JBDS}/${devstudioReleaseVersion}/${qual}/updates/
    # rename from staging/*/versionWithRespin_ds/ to ${qual}/*/version/
    for zip in ${tmpdir}/${devstudioReleaseVersion}/development/updates/${site}/devstudio-${versionWithRespin_ds}*.zip*; do
      zipNew=${zip/${versionWithRespin_ds}/${version_ds}}
      zipNew=${zipNew##*/}; # **##
      {
        destprefix=https://devstudio.redhat.com/static/${devstudioReleaseVersion}/${qual}/updates/${site}/ && \
        time rsync -aPrz --rsh=ssh --protocol=28 ${zip} ${JBDS}/static/${devstudioReleaseVersion}/${qual}/updates/${site}/${zipNew} && \
        echo -e "
[INFO] [zips] ${green}${destprefix}/${norm}
[INFO] [zips] ${green}${destprefix}/${zipNew}/${norm}
[INFO] [zips] ${green}DONE${norm}: copy ${qual} devstudio zips & SHAs" &
      }
    done
  done
done
rm -fr $tmpdir

####################################################

# wait until all background tasks (jbt: 8, ds: 11) are done
wait

----

When the job is done, verify everything has been published:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-dev-stable-03-verify-builds-update-sites_4.4.neon/build

Or, if that fails:

[source,bash]
----

# globals
eclipseReleaseName=neon
devstudioReleaseVersion=10.0
quiet="-q" # "" for loud, or "-q" for quiet log
CHECK=${WORKSPACE}/jbosstools-build-ci/publish/checkStagingURLs.sh

if [[ ! -x ${CHECK} ]]; then
  cd /tmp
  if [[ -f /tmp/checkStagingURLs.sh ]]; then rm -f /tmp/checkStagingURLs.sh; fi
  wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.4.x/publish/checkStagingURLs.sh --no-check-certificate
  chmod +x checkStagingURLs.sh
  CHECK=/tmp/checkStagingURLs.sh
fi

version_ds=10.1.0.GA
quals="development"
if [[ ${version_ds##*GA} == "" ]]; then quals="development stable"; fi # ** ##
for qual in $quals; do time ${CHECK} -vrds ${version_ds} -dsrv ${devstudioReleaseVersion} -qual $qual ${quiet}; echo ""; done

----


== Update https://devstudio.redhat.com/10.0/development/updates/

To update the content in https://devstudio.redhat.com/10.0/development/updates/ ...

[source,bash]
----

cd ~/truu # ~
pushd jbdevstudio-website/content/10.0/
git fetch origin master
git checkout FETCH_HEAD

# mount an sshfs drive for $JBDS
JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
sshfs $JBDS $HOME/JBDS-ssh

version_ds=10.1.0.GA
versionWithRespin_ds=10.1.0.GA # a, b, c...
quals="development"; if [[ ${version##*GA} == "" ]]; then quals="development stable"; fi # **##
echo "
- integration-stack/*
- */OLD/
- */binary/
+ core/${versionWithRespin_ds}/
+ core/composite*.xml
- core/*
+ central/${versionWithRespin_ds}/
+ central/composite*.xml
- central/*
+ earlyaccess/${versionWithRespin_ds}/
+ earlyaccess/composite*.xml
- earlyaccess/*
+ discovery.central/${versionWithRespin_ds}/
+ discovery.central/composite*.xml
- discovery.central/*
+ discovery.earlyaccess/${versionWithRespin_ds}/
+ discovery.earlyaccess/${versionWithRespin_ds}/plugins/
+ discovery.earlyaccess/${versionWithRespin_ds}/plugins/*.jar
+ discovery.earlyaccess/composite*.xml
- discovery.earlyaccess/*
- site.css
- *.gz
- *.jar
- *.zip
" > /tmp/filter-devstudio
scpr $JBDS/10.0/staging/updates/* staging/updates/ --include-from=/tmp/filter-devstudio

for qual in $quals; do
  echo ":: $qual"
  scpr staging/updates/* ${qual}/updates/ --include-from=/tmp/filter-devstudio -q

  pushd ${qual}/updates/
  if [[ ${versionWithRespin_ds} != ${version_ds} ]]; then
    # rename the staging folders to their final names (CR1c -> Final)
    for d in core central earlyaccess discovery.central discovery.earlyaccess; do
      rm -fr ${d}/${version_ds}
      mv ${d}/${versionWithRespin_ds} ${d}/${version_ds}
    done
  fi

  # fix composite sites to use the correct paths (not /staging, but /static)
  now=`date +%s000`
  for c in index.html compositeContent.xml compositeArtifacts.xml */compositeContent.xml */compositeArtifacts.xml */${version_ds}/compositeContent.xml */${version_ds}/compositeArtifacts.xml; do
    if [[ $c == ${c/integration-stack/} ]]; then
      echo "$c ..."
      sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
      sed -i -e "s#10.0/staging/updates/#static/10.0/${qual}/updates/#" $c
      sed -i -e "s#${versionWithRespin_ds}#${version_ds}#" $c
    fi
  done
  popd
done
rm -f /tmp/filter-devstudio

# copy versioned composite site into parent folder
for qual in $quals; do
  echo ":: $qual"
  pushd ${qual}/updates/ >/dev/null
    for d in core central earlyaccess discovery.central discovery.earlyaccess; do
      if [[ -f ${d}/${version_ds}/compositeContent.xml ]]; then
        scpr ${d}/${version_ds}/composite*.xml ${d}/
      fi
      ga -f ${d}/${version_ds}/* ${d}/*.*ml
    done
  popd >/dev/null
done

# push updated files to server
for qual in $quals; do
  pushd ${qual}/updates/ >/dev/null
    JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
    scpr *.*ml ${JBDS}/10.0/${qual}/updates/
    for d in discovery.central discovery.earlyaccess; do
      echo ${d}/
      scpr ${d}/*.*ml ${JBDS}/10.0/${qual}/updates/${d}/
      scpr ${d}/*.*ml ${JBDS}/static/10.0/${qual}/updates/${d}/
    done
    for d in discovery.central discovery.earlyaccess; do
      echo ${d}/
      scpr ${d}/${version_ds}/* ${JBDS}/10.0/${qual}/updates/${d}/${version_ds}/
      scpr ${d}/${version_ds}/* ${JBDS}/static/10.0/${qual}/updates/${d}/${version_ds}/
    done
  popd >/dev/null
done

# commit the change and push to master
for qual in $quals; do git add ${qual}/updates; done
git commit -m "release JBT ${versionWithRespin_ds} to public" .
git push origin HEAD:master

popd

# verify site contents are shown
quals="development"; if [[ ${version##*GA} == "" ]]; then quals="development stable"; fi # **##
for qual in $quals; do
  google-chrome && google-chrome \
  https://devstudio.redhat.com/10.0/${qual}/updates \
  https://devstudio.redhat.com/10.0/${qual}/updates/compositeContent.xml \
  https://devstudio.redhat.com/10.0/${qual}/updates/discovery.earlyaccess/ \
  https://devstudio.redhat.com/10.0/${qual}/updates/discovery.earlyaccess/compositeContent.xml \
  https://devstudio.redhat.com/10.0/${qual}/updates/earlyaccess/ \

done

----

Open p2-browser and verify these sites load correctly:

https://devstudio.redhat.com/10.0/development/updates/
https://devstudio.redhat.com/10.0/development/updates/discovery.earlyaccess/
https://devstudio.redhat.com/10.0/development/updates/discovery.earlyaccess/10.1.0.GA/

https://devstudio.redhat.com/10.0/stable/updates/
https://devstudio.redhat.com/10.0/stable/updates/discovery.earlyaccess/
https://devstudio.redhat.com/10.0/stable/updates/discovery.earlyaccess/10.1.0.GA/

----

Ensure content exists (this is already done automatically above, but that's before making the above updates).

[source,bash]
----
version_ds=10.1.0.GA
# review changes
quals="development"; if [[ ${version##*GA} == "" ]]; then quals="development stable"; fi # **##
for qual in $quals; do
  google-chrome && google-chrome \
  https://devstudio.redhat.com/10.0/${qual}/updates/discovery.earlyaccess/${version_ds}/devstudio-directory.xml \
  https://devstudio.redhat.com/10.0/${qual}/updates/discovery.earlyaccess/${version_ds}/devstudio-earlyaccess.properties \
  https://devstudio.redhat.com/10.0/${qual}/updates/discovery.earlyaccess/${version_ds}/plugins/ \

done

----

== Update Target Platforms

If this new release includes a new Target Platform, you need to release the latest target platform. If not, there's nothing to do here.

[source,bash]
----

cd ~/truu # or where you have jbdevstudio-website checked out ~

TARGET_PLATFORM_VERSION_MAX=4.60.1.Final
now=`date +%s000`
JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio

# for Final TPs only!
pushd jbdevstudio-website/content/targetplatforms/
  git fetch origin master
  git checkout FETCH_HEAD

  for f in jbdevstudio; do
    tppath=${f}target/${TARGET_PLATFORM_VERSION_MAX}
    # move actual TP to /static/ folder
    echo "rename targetplatforms/${tppath} static/targetplatforms/${tppath}" | sftp ${JBDS}/
    # get contents from remote
    rsync -Pzrlt --rsh=ssh --protocol=28 $JBDS/static/targetplatforms/${tppath}/composite*.xml ${tppath}/
    # change pointer to include /static/
    for d in ${tppath}/composite*.xml; do
      sed -i -e "s#[\'\"]REPO/[\'\"]#'https://devstudio.redhat.com/static/targetplatforms/${tppath}/REPO/'#g" $d ##
    done
    echo "version = 1
metadata.repository.factory.order = compositeContent.xml,\!
artifact.repository.factory.order = compositeArtifacts.xml,\!" > ${tppath}/p2.index
    rsync -Przlt ${tppath}/composite*.xml ${tppath}/p2.index ${tppath}/REPO/
    # create composite pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${tppath}/* $JBDS/targetplatforms/${tppath}/
  done
  # commit changes to github
  git add ${f}target
  git commit -m "move target platforms into /static/ and update composite pointers to latest => ${TARGET_PLATFORM_VERSION_MAX}" .
  git push origin HEAD:master
popd

# for Final TPs only!
google-chrome && google-chrome \
https://devstudio.redhat.com/static/targetplatforms/${tppath}/REPO/
https://devstudio.redhat.com/static/targetplatforms/${tppath}/compositeContent.xml \

# verify files are correct
google-chrome && google-chrome \
https://devstudio.redhat.com/targetplatforms/${tppath}/REPO/compositeContent.xml \
https://devstudio.redhat.com/targetplatforms/${tppath}/REPO/p2.index \
https://devstudio.redhat.com/targetplatforms/${tppath}/compositeContent.xml \
https://devstudio.redhat.com/targetplatforms/${tppath}/p2.index

----


== Release the latest milestone to ide-config.properties

See JBT_Release.adoc


== Update Marketplace entry

WARNING: Only applies to Beta and better versions.

=== If node doesn't exist yet

For the first Beta, create a new node on Marketplace, using single feature, com.jboss.devstudio.core.feature

=== If node already exists

Access it via +http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Notes / warnings (if applicable, eg., JDK issues)

=== Validate Marketplace install

1. Get a compatible Eclipse
2. Install from Marketplace
3. Install everything from Central + Earlyaccess
4. Test a project example


== Release JIRA

See JBT_Release.adoc


== Submit PR to update tools.jboss.org

Provide a PR to add the latest JBDS milestones to this listing:

https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml_

Examples:

* https://github.com/jbosstools/jbosstools-website/pull/622 (JBT 4.4.1 / JBDS 10.1)

=== SHA256 values

To get the SHA256 values for easy pasting into the product.yml file, first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then run this:

[source,bash]
----
version_ds=10.1.0.GA
versionWithRespin_ds=10.1.0.GA # a, b, c...

cd ~/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ # ~
for f in *.jar *.zip; do
  size=$(du -h $f); size=${size%*M*};
  sha=$(cat ${f}.sha256); sh=${sha:0:2};
  echo "            url: http://www.jboss.org/download-manager/content/origin/files/sha256/${sh}/${sha}/${f}" >> /tmp/yml.txt
  echo "            file_size: ${size}MB" >> /tmp/yml.txt
done
cd /tmp
f=devstudio-${version_ds}-target-platform.zip
size=$(wget https://devstudio.redhat.com/10.0/development/updates/core/ --no-check-certificate -q -O - | egrep devstudio-${version_ds}-target-platform.zip | egrep -v sha256 | sed "s#.\+>\([0-9]\+M\)</td.\+#\1#")
# sha=$(wget https://devstudio.redhat.com/10.0/development/updates/core/${f}.sha256 --no-check-certificate -q -O -); sh=${sha:0:2}
echo "            url: https://devstudio.redhat.com/10.0/development/updates/core/${f}" >> /tmp/yml.txt
echo "            file_size: ${size}B" >> /tmp/yml.txt
done
cat /tmp/yml.txt; rm -f /tmp/yml.txt

----

Then, back on your own machine...

[source,bash]
----
version_jbt=4.4.2.AM1
version_ds=10.2.0.AM1

cd ~/tru # where you have jbosstools-website checked out

pushd jbosstools-website/
  t=release-4.4.2.AM1-10.2.0.AM1
  gw1m
  st _config/products.yml

  # make changes, using the generated content above, then...

  git commit -m "add ${version_ds} and ${version_jbt} to tools.jboss.org" .
  gw2
popd


----

Commit changes and submit PR, eg., https://github.com/jbosstools/jbosstools-website/pull/622


== Tag Git

Once cloned to disk, this script will create the tags if run from the location with your git clones. If tags exist, no new tag will be created.

[source,bash]
----

# if not already cloned, the do this:
git clone https://github.com/jbdevstudio/jbdevstudio-product
git clone https://github.com/jbdevstudio/jbdevstudio-ci
git clone https://github.com/jbdevstudio/jbdevstudio-website
git clone https://github.com/jbdevstudio/jbdevstudio-artwork
git clone https://github.com/jbdevstudio/jbdevstudio-devdoc

jbt_branch=master # or jbosstools-4.4.2.x
version_ds=10.2.0.AM1
cd ~/truu # ~
for d in product ci website artwork devdoc; do
  echo "====================================================================="
  echo "Tagging jbdevstudio-${d} from branch ${jbt_branch} as tag ${version_ds}..."
  pushd jbdevstudio-${d}
  git fetch origin ${jbt_branch}
  git tag jbdevstudio-${version_ds} FETCH_HEAD
  git push origin jbdevstudio-${version_ds}
  echo ">>> https://github.com/jbdevstudio/jbdevstudio-${d}/tree/jbdevstudio-${version_ds}"
  popd >/dev/null
  echo "====================================================================="
  echo ""
done

----

== Smoke test the release

Before notifying team of release, must check for obvious problems. Any failure there should be fixed with highest priority. In general, it could be wrong URLs in a composite site.

=== Validate update site install (BYOE)

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install BYOE category from https://devstudio.redhat.com/10.0/development/updates/ and/or https://devstudio.redhat.com/10.0/stable/updates/
3. Restart. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

=== Validate installer install

1. Download JBDS installer from https://devstudio.redhat.com/10.0/development/builds/ or https://devstudio.redhat.com/10.0/stable/builds/
2. Install via UI or headlessly with
    java -jar devstudio-*.jar -console -options /dev/null
3. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----

version_ds=10.1.0.GA
qual="development"; if [[ ${version##*GA} == "" ]]; then qual="stable"; fi # **##
cd ~/tmp # ~
wget https://devstudio.redhat.com/static/10.0/${qual}/builds/devstudio-${version_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/static/10.0/${qual}/builds/devstudio-${version_ds}-build-product/latest/all/${installerJar}

java -jar ~/tmp/${installerJar} # ~

----


== Notify Team Lead(s)

Notifify Alexy & Jeff that the website is ready to be updated with a new blog post.

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-push-to-dev-stable-07-notification-emails_4.4.neon/configure


== Commit updates to release guide (including this document):

[source,bash]
----

version_jbt=4.4.1.Final
version_ds=10.1.0.GA
cd ~/truu # ~
cd jbdevstudio-devdoc/release_guide/
git commit -m "update release guide for ${version_jbt} and ${version_ds}" .
git push origin HEAD:master

----

