= Publishing devstudio Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

[IMPORTANT]
====

Before running any of the jobs or scripts below, make sure to set the correct versions to the values for the release you're staging or releasing.

* look for versionWithRespin, update to version you're staging
* look for PREV and NEXT variables; set to previous / next milestone (AM1, AM2, AM3, Final/GA)
* look for NEXT, set to next milestone
* check target platform versions are current w/ latest versions
* check parent pom version, version_parent, is current

====

== Clone jbosstools-build-ci repo

== Clone jbosstools-build-ci repo

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ ! -d jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout jbosstools-4.4.x
chmod +x -R */*.sh */*/*.sh

----

== Update Discovery Sites and URLs

See details in JBT_Staging_For_QE.adoc

== Verify correct version set in com.jboss.devstudio.central.core

See details in JBT_Staging_For_QE.adoc

== Disable jobs

See details in JBT_Staging_For_QE.adoc

== Stage to devstudio.redhat.com and internal qa server

=== Copy & rename builds & update sites from "snapshots" to "staging"

Here is a job that performs the copy (& rename) from /snapshots/ to /staging/:

https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites/

Here's a job that verifies everything is published:

https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-03-verify-builds-update-sites/


TIP: Once the staging build folder exists, start fetching the devstudio installer (we'll need it later to do a smoke test)

[source,bash]
----

cd ~/tmp
rm -f index.html
versionWithRespin_ds=10.3.0.GA # a, b, c...
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}

----

You'll use this downloaded installer later, but since it takes a while to download, it's more efficient to start it now.


=== Cleanup OLD builds

Optional step.

Run this job to move any old builds into an OLD/ folder for later cleanup, or delete them immediately.

https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites/


=== Update /staging/updates/ sites and merge in Integration Stack content

See details in JBT_Staging_For_QE.adoc


== Release the latest staging site to ide-config.properties

See details in JBT_Staging_For_QE.adoc


== Smoke test the release (manually)

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Bring Your Own Eclipse category from

https://devstudio.redhat.com/10.0/staging/updates/

3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----
versionWithRespin_ds=10.3.0.GA # a, b, c...
cd ~/tmp
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html

# should have already downloaded this above
if [[ ! -f ${installerJar} ]]; then wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}; fi

java -jar ~/tmp/${installerJar}

----

0. After downloading and installing devstudio from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See details in JBT_Staging_For_QE.adoc


== Notify the team (send 1 email)

See details in JBT_Staging_For_QE.adoc


== Trigger QE Smoke tests (automated)

Trigger the QE smoke tests in https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/

WARNING: TODO: make sure this works - could also wrap this inside a Jenkins job so it's easier to trigger? See https://issues.jboss.org/browse/JBIDE-23733

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=10.3.0.GA # a, b, c...
cd ~/tmp
wget https://devstudio.redhat.com/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
rm -f index.html

version_ds_INST=${installerJar#devstudio-}
version_ds_INST=${version_ds_INST%-installer*}
echo "Devstudio installer version: ${version_ds_INST}"

# run the one buildflow job
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in devstudio.buildflow.it.smoke; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="DEVSTUDIO_VERSION=${version_ds_INST}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s
done

----


== Sign RPM

0. This section only applies to GA builds. No need to sign AMx milestones!

1. give URL link to Chris via RCM ticket, eg., https://projects.engineering.redhat.com/browse/RCM-10070, https://projects.engineering.redhat.com/browse/RCM-10215

WARNING: TODO: make sure this works (untested - was done by hand last time).

[source,bash]
----


# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=10.3.0.GA
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-05-sign-rpm-email-request; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

2. Chris signs it, and gives back a URL,eg., http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/JBDS-10.3.0/rpms/signed/

3. Fetch rpms, regen metadata

WARNING: TODO: make sure this works (untested - was done by hand last time).

[source,bash]
----

# Jenkins login for the Wonka server
export userpass=WONKAUSER:PASSWORD

versionWithRespin_ds=10.3.0.GA
signedURL=http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/JBDS-10.3.0/rpms/signed/
wonkajenkins=http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-06-sign-rpm-fetch; do
  prevJob=$(${JP} -s ${wonkajenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${wonkajenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&signedURL=${signedURL}"
  nextJob=$(${JP} -s ${wonkajenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${wonkajenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${wonkajenkins}/${j}"
  else
    ${JP} -s ${wonkajenkins} -j ${j} -t disable
    ${JP} -s ${wonkajenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

