= Publishing JBT update sites for QE

This document describe how to provide a valid JBoss Tools build to QE so they can test us.

TODO: use consistent instructions for fetching sources from git & pushing changes
TODO: use sshfs to do copies in a single step, instead of rsync-pull/rsync-push (2 steps)

[NOTE]
====
Note that +sftp://tools@filemgmt.jboss.org/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+ +

If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools .
A Jenkins job can then be triggered to sync changes to download.jboss.org: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-download.jboss.org-rsync-from-svn/
====

== Enable staging jobs

You will need to enable the jobs:

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD
stream_jbt=4.4.neon # or 4.4.neon
for j in jbosstools-push-to-staging-07-notification-emails_${stream_jbt} \
jbosstools-push-to-staging-03-verify-builds-update-sites_${stream_jbt} \
jbosstools-push-to-staging-02-copy-builds-and-update-sites_${stream_jbt} \
jbosstools-push-to-staging-01-check-versions-branches-root-poms_${stream_jbt} \
jbosstools-push-to-staging-00-buildflow_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
done

----

== Verify correct versions, branches exist, and root poms are correct

Run this job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-staging-01-check-versions-branches-root-poms_master

If any branches have not yet been created, you can either:
* Ask Denis, Fred, or Max to get them created
* Create them yourself like this:

[source,bash]
----
git checkout master; git pull origin jmaster; git checkout -b jbosstools-4.4.1.x; git push origin jbosstools-4.4.1.x
# or, for jbosstools-build-ci
git checkout jbosstools-4.4.x; git pull origin jbosstools-4.4.x; git checkout -b jbosstools-4.4.1.x; git push origin jbosstools-4.4.1.x

----

Once the above conditions have been met, you can proceed to the next steps.

== Disable jobs

To prevent accidentally rebuilding something while you're copying it away, make sure that all the stable branch jobs (4.4.neon, 10.0.neon) are disabled. These include all product, composite and aggregate jobs:

[source,bash]
----
# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD
stream_jbt=4.4.neon # or 4.4.neon
stream_ds=10.0.neon # or 10.0.neon
for j in jbosstools-build.parent_${stream_jbt} jbosstoolstargetplatforms-matrix jbosstools-buildflow_${stream_jbt} jbosstools-composite-install_${stream_jbt} jbosstools-browsersim-standalone_${stream_jbt} jbosstools-build-sites.aggregate.site_${stream_jbt} jbosstools-build-sites.aggregate.coretests-site_${stream_jbt} jbosstools-centraltarget_${stream_jbt} jbosstools-build-sites.aggregate.child-sites_${stream_jbt} devstudio.product_${stream_ds} devstudio.versionwatch_${stream_ds} jbosstools-install-p2director.install-tests.matrix_${stream_jbt} jbosstools-install-grinder.install-tests.matrix_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable && echo -n ".D"
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/lastBuild/toggleLogKeep && echo -n ".K"
done
echo ""

----

== Update Discovery Sites and URLs

[[update-discovery-urls]]
Update the *stable branch* (or master) discovery job ( https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-discovery_4.4.neon/configure (or jbosstools-discovery_master)) to use the correct source URLs and versions +


Then respin the job:

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

versionWithRespin_jbt=4.4.1.Final # a, b, c... (not SNAPSHOT!)
stream_jbt=4.4.neon # or 4.4.neon
stream_ds=10.0.neon # or 10.0.neon
TARGET_PLATFORM_VERSION_MAX=4.60.1.Final
TARGET_PLATFORM_CENTRAL_MAX=4.60.1.Final-SNAPSHOT
for j in jbosstools-discovery_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
  curl -k -u ${userpass} --data "VERSION=${versionWithRespin_jbt##*.}&TARGET_PLATFORM_VERSION_MAXIMUM=${TARGET_PLATFORM_VERSION_MAX}&JBTCENTRALTARGET_VERSION=${TARGET_PLATFORM_CENTRAL_MAX}" https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/buildWithParameters && echo -n ".B"
  sleep 15s
  # then disable the job
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable && echo -n ".D"
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/lastBuild/toggleLogKeep && echo -n ".K"
done

----


== Download the latest Eclipse

You'll need this later for smoke testing. Start fetching it now to save time later.

[source,bash]
----

cd ~/tmp; wget https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/neon/R/eclipse-jee-neon-R-linux-gtk-x86_64.tar.gz &
# or
cd ~/tmp; wget https://hudson.eclipse.org/packaging/job/neon.epp-tycho-build/388/artifact/org.eclipse.epp.packages/archive/20160613-1800_eclipse-jee-neon-R-linux.gtk.x86_64.tar.gz &

----

== Stage to download.jboss.org

=== Copy & rename builds & update sites from "snapshots" to "staging"

Here is a job that performs the copy (& rename) from /snapshots/ to /staging/:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-staging-02-copy-builds-and-update-sites_master/

Here's a job that verifies everything is published:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-staging-03-verify-builds-update-sites_master/


=== Cleanup OLD builds

Optional step.

First, use sshfs to mount filemgmt file paths.

[source,bash]
----

TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
sshfs $TOOLS /media/TOOLS-ssh

----

Then move old builds into an OLD/ folder to they're less visible and ready for deletion later.

[source,bash]
----
version_PREV=4.4.0.Alpha0 # a, b, c...
for d in updates/core updates/central updates/earlyaccess updates/discovery.central updates/discovery.earlyaccess builds; do
  if [[ -d /media/TOOLS-ssh/neon/staging/${d}/ ]]; then
    echo "${d}/*${version_PREV}* ..."
    mkdir -p /media/TOOLS-ssh/neon/staging/${d}/OLD/
    mv /media/TOOLS-ssh/neon/staging/${d}/*${version_PREV}* /media/TOOLS-ssh/neon/staging/${d}/OLD/
  fi
done

----

=== Update http://download.jboss.org/jbosstools/neon/staging/updates/ site

This should point to the latest staging bits. Just copy what's in discovery.central/composite*.xml into this folder.

[source,bash]
----

cd ~/tru
RSYNC="rsync -aPrz --rsh=ssh --protocol=28"

versionWithRespin_jbt_PREV=4.4.1.AM3 # a, b, c...
versionWithRespin_jbt=4.4.1.Final # a, b, c...
DESTINATION=tools@filemgmt.jboss.org:/downloads_htdocs/tools
PROJECT_PATH=jbosstools-download.jboss.org/jbosstools
DEST_URL="http://download.jboss.org/jbosstools"
updatePath=neon/staging/updates

pushd ${PROJECT_PATH}/${updatePath}
git fetch origin master
git checkout FETCH_HEAD

for d in discovery.central discovery.earlyaccess; do
  mkdir -p ${d}/${versionWithRespin_jbt}/
  pushd ${d}/${versionWithRespin_jbt}/
    ${RSYNC} ${DESTINATION}/${updatePath}/${d}/${versionWithRespin_jbt}/composite*xml ./
    cat compositeContent.xml | egrep "${versionWithRespin_jbt}|targetplatforms|REPO|updates|timestamp"
  popd
done
rsync discovery.central/${versionWithRespin_jbt}/composite*.xml ./

# update index.html
if [[ -f index.html ]]; then
  sed -i "s#${versionWithRespin_jbt_PREV}#${versionWithRespin_jbt}#" index.html
  cat index.html | egrep "${versionWithRespin_jbt_PREV}|${versionWithRespin_jbt}"
fi

## wait here until all copies from snapshots -> staging is done

# push changes to server
${RSYNC} discovery.central/${versionWithRespin_jbt}/composite*xml ${DESTINATION}/${updatePath}/discovery.central/${versionWithRespin_jbt}/
${RSYNC} discovery.earlyaccess/${versionWithRespin_jbt}/composite*xml ${DESTINATION}/${updatePath}/discovery.earlyaccess/${versionWithRespin_jbt}/
${RSYNC} ./composite*xml *.html ${DESTINATION}/${updatePath}/

# verify changes
echo "Check 4 URLs:"
google-chrome && google-chrome \
${DEST_URL}/${updatePath}/discovery.central/${versionWithRespin_jbt}/compositeContent.xml \
${DEST_URL}/${updatePath}/discovery.earlyaccess/${versionWithRespin_jbt}/compositeContent.xml \
${DEST_URL}/${updatePath}/compositeContent.xml \
${DEST_URL}/${updatePath}/

rm -fr discovery.central/${versionWithRespin_jbt}/composite*.xml discovery.earlyaccess/${versionWithRespin_jbt}/composite*.xml

# commit the change and push to master
git commit -m "release ${versionWithRespin_jbt} to QE" .
git push origin HEAD:master
popd

----

=== Merge in Integration Stack content

If staging devstudio too, wait until you get to this step and merge in both at the same time.

See details in Merge_IS_Discovery.adoc

== Release the latest staging site to ide-config.properties

Check out http://download.jboss.org/jbosstools/configuration/ide-config.properties

Update it so that the links for the latest milestone point to valid URLs. Comment out staging links as required.

[source,bash]
----

# adjust these steps to fit your own path location & git workflow
cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=4.4.1.Final
versionWithRespin_jbt=4.4.1.Final # a, b, c...
version_ds=10.1.0.GA # no respin suffix here
versionWithRespin_ds=10.1.0.GA # a, b, c...

git fetch origin master
git checkout FETCH_HEAD

# then edit ide-config.properties
# vim ide-config.properties
st ide-config.properties
# TODO something like this?
# sed -i "s/CR1b/CR1c/g" ide-config.properties

# verify these 6 URLs exist
URLs="$(egrep -v "#" ide-config.properties | egrep "${version}|${versionWithRespin_jbt}|${version_ds}|${versionWithRespin_ds}" | sed -e "s#.\+|\([0-9.a-zA-Z]\+\)=\(.\+\)#\2#")"
google-chrome && google-chrome $URLs
for u in $URLs; do echo "$u"; done

# commit the change and push to master
ci "release JBT ${version} (${versionWithRespin_jbt}) to staging: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
RSYNC="rsync -aPrz --rsh=ssh --protocol=28"
${RSYNC} ide-config.properties $TOOLS/configuration/ide-config.properties

popd

----

== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Abridged category from http://download.jboss.org/jbosstools/neon/staging/updates/
3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again


== Enable jobs

You will need to re-enable the jobs once the bits are staged, so that CI builds can continue.

If the next build WILL be a respin, you need to simply:

* re-enable 15 jobs that were disabled above. If you committed a change to jbdevstudio-ci, you can simply revert that commit to re-enable the jobs!

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD
stream_jbt=4.4.neon # or 4.4.neon
stream_ds=10.0.neon # or 10.0.neon
for j in jbosstools-build.parent_${stream_jbt} jbosstoolstargetplatforms-matrix jbosstools-buildflow_${stream_jbt} jbosstools-composite-install_${stream_jbt} jbosstools-browsersim-standalone_${stream_jbt} jbosstools-build-sites.aggregate.site_${stream_jbt} jbosstools-build-sites.aggregate.coretests-site_${stream_jbt} jbosstools-centraltarget_${stream_jbt} jbosstools-build-sites.aggregate.child-sites_${stream_jbt} devstudio.product_${stream_ds} devstudio.versionwatch_${stream_ds} jbosstools-install-p2director.install-tests.matrix_${stream_jbt} jbosstools-install-grinder.install-tests.matrix_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
done
echo ""
for j in jbosstools-discovery_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
done

----

TODO: Important: if you switched the _master jobs to run from origin/jbosstools-4.4.x or some other branch, make sure that the jobs are once again building from the correct branch.

If the next build will NOT be a respin, you will also need to ALSO make these changes to jobs, and upversion/release artifacts such as releng scripts or target platforms if you haven't done so already:

* set correct github branch, eg., switch from 4.4.1.Finalx to 4.4.x
* upversion dependencies, eg., releng scripts move from version CR1 to CR1 (if that's been released)
* upversion target platforms / Central version (if those have been released)


== Notify the team (send 1 email)

Run this build:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-push-to-staging-07-notification-emails_master

== Disable staging jobs

You will need to disable the jobs once the bits are staged, so that they won't run accidentally.

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD
stream_jbt=4.4.neon # or 4.4.neon
for j in jbosstools-push-to-staging-07-notification-emails_${stream_jbt} \
jbosstools-push-to-staging-03-verify-builds-update-sites_${stream_jbt} \
jbosstools-push-to-staging-02-copy-builds-and-update-sites_${stream_jbt} \
jbosstools-push-to-staging-01-check-versions-branches-root-poms_${stream_jbt} \
jbosstools-push-to-staging-00-buildflow_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable && echo -n ".D"
done

----
