= Release JBoss Tools Development Milestone

This document describe how to publish a valid JBoss Tools build to production after being verified by QE.

With distractions (email, IRC), this process took 90 mins for the Beta release.

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA.

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten.

Send an email to jbosstools-dev@ and jboss-devstudio-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

Should NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete. But in practice, this happens every time.

[source,bash]
----
google-chrome && google-chrome https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Summary

Here are some generalities site promotion/release process. It's not an exhaustive list so you need to read the full document to do a release, but it gives an overview of the various steps.

. CI build output is published the 'builds/staging' folder, while aggregated update-sites goes to 'updates/nightly' folder
. After branching, component repository are rebuilt from branch (instead of 'master') and new aggregated updatesites are created as well.  A site is promoted from nightly to staging for QE, and moves from 'updates/nightly' to 'updates/staging', including a respin suffix if required.
.. If QE finds a blocker issue, a respin is requested
... On Jira, add a 'respin-a' or 'respin-b' or 'respin-x' label to bugs that needs for be fixed for the respin
... Edit CI jobs to the next respin label (eg CR2b)
... Re-run necessary jobs
... Go To 1
.. If QE approves, release is accepted and promoted
... JIRA is checked to ensure all JIRAs for this milestone are resolved
... Site moves from 'updates/staging' with respin label to 'static/releases' without respin label
... Links to 'updates/neon' are replaced to link to new version
... JBoss Tools website is updated
... Git repositories are tagged
... Eclipse Marketplace entries are created or updated
... JIRA version can be released
... Interested parties are notified


== Copy sites

These steps happens on filemgmt.jboss.org, in the jbosstools download area.

=== Copy content to release directory

TODO: is this warning still relevant?
PLEASE NOTE! If you're pushing a new /development/ site and the last release was to /stable/, make sure you disconnect the symlinks first or you'll end up putting a milestone into /stable/ instead of /development/.

See section "Copy from development to stable & create symlinks from /stable/ into /development/" for details.


We simply copy the content of the latest respin to the release directory (under _jbosstools/static_ which is using Akamai)

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Here is a script that performs the copy from /staging/ to /development/.

[source,bash]
----

cd /tmp
if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.4.x/publish/stage.sh --no-check-certificate
chmod +x stage.sh

eclipseReleaseName=neon
quiet="-q" # "" for loud, or "-q" for quiet log
version_jbt=4.4.1.AM3 # release version: no a, b, c suffix
versionWithRespin_jbt=4.4.1.AM3 # a, b, c...
STAGE=./stage.sh

norm="\033[0;39m"
green="\033[1;32m"
red="\033[1;31m"

#################

TOOLS="tools@filemgmt.jboss.org:/downloads_htdocs/tools"

quals="development"; # TODO enable stable?
# if [[ ${version_jbt##*Final} == "" ]]; then quals="development stable"; fi # **##
for qual in $quals; do
  for site in core coretests central earlyaccess discovery.central discovery.earlyaccess browsersim-standalone; do
    time ${STAGE} -sites $site -stream "${versionWithRespin_jbt}" -vr ${version_jbt} \
      -sd ${eclipseReleaseName} -dd static/${eclipseReleaseName} -st staging -dt ${qual} \
      -JOB_NAME jbosstools-${versionWithRespin_jbt}-build-\${site} ${quiet} &
  done
done

# JBT zips into http://download.jboss.org/jbosstools/static/${eclipseReleaseName}/development/updates/core/
quals="development"; # TODO enable stable?
# if [[ ${version_jbt##*Final} == "" ]]; then quals="development stable"; fi
tmpdir=~/temp-stage/jbosstools-static-${qual}-updates-core_${versionWithRespin_jbt}_zips; mkdir -p ${tmpdir}
# get src.zip & browsersim-standalone.zip
srcprefix=${TOOLS}/${eclipseReleaseName}/staging/builds/jbosstools-${versionWithRespin_jbt}-build
{
  time rsync -aPrz --rsh=ssh ${quiet} --protocol=28 \
  ${srcprefix}-core/latest/all/jbosstools-${version_jbt}-src.zip* \
  ${srcprefix}-browsersim-standalone/latest/jbosstools-*-browsersim-standalone.zip* \
  ${tmpdir}/ && \
  for qual in $quals; do
    echo "mkdir core" | sftp ${TOOLS}/static/${eclipseReleaseName}/${qual}/updates/ && \
    destprefix=http://download.jboss.org/jbosstools/static/${eclipseReleaseName}/${qual}/updates/core && \
    time rsync -aPrz --rsh=ssh ${quiet} --protocol=28 ${tmpdir}/*.zip* ${TOOLS}/static/${eclipseReleaseName}/${qual}/updates/core/
  done && \
  rm -fr $tmpdir && echo -e "
[INFO] [zips] ${green}${destprefix}/${norm}
[INFO] [zips] ${green}${destprefix}/jbosstools-${version_jbt}-src.zip${norm}
[INFO] [zips] ${green}${destprefix}/jbosstools-${version_jbt}-browsersim-standalone.zip${norm}
[INFO] [zips] ${green}DONE${norm}: ${green}jbosstools-*-src.zip + ${green}jbosstools-*-browsersim-standalone.zip${norm}" &
}

# wait until all 8+? background tasks (jbt: 8, ds: ?) are done
wait

# TODO wait until the above 7+1 (or 2x(7+1)) pushes are done (should be nothing if you run this:
ps ax | grep stage.sh | grep -v grep | egrep -- "-sites|-sd"


# TODO run on local, not dev01
# verify we have all the files we expect to see
#TODO migrate this to staging script and into a Jenkins job too!
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
sshfs $TOOLS $HOME/TOOLS-ssh
version_jbt=4.4.1.AM3
versionWithRespin_jbt=4.4.1.AM3 # a, b, c...
expectedCount=0
quals="development"; if [[ ${version_jbt##*Final} == "" ]]; then quals="development stable"; fi # **##
rm -f /tmp/${version_jbt}.found.txt
for qual in $quals; do
  (( expectedCount += 18 )); # now 18
  find $HOME/TOOLS-ssh/static/neon/${qual}/updates/* -maxdepth 1 -name "*${version_jbt}*" -o -name "*${versionWithRespin_jbt}*" | sort >> /tmp/${version_jbt}.found.txt
done
theCount=$(cat /tmp/${version_jbt}.found.txt | wc -l)
if [[ ${theCount} == ${expectedCount} ]]; then
  echo "[INFO] Found all expected ${expectedCount} files/folders" | egrep "${expectedCount}|${theCount}|INFO|ERROR"
else
  echo "[ERROR] expected ${expectedCount} files/folders, found ${theCount}:" | egrep "${expectedCount}|${theCount}|INFO|ERROR"
  cat /tmp/${version_jbt}.found.txt | sort | egrep "${version_jbt}|${versionWithRespin_jbt}"
fi
echo "Download all these zips to verify they work:"
cat /tmp/${version_jbt}.found.txt | sed "s#$HOME/TOOLS-ssh/#http://download.jboss.org/jbosstools/#" | egrep "\.zip"
echo "Review these pages to verify the work:"
google-chrome && google-chrome $(cat /tmp/${version_jbt}.found.txt | sed "s#$HOME/TOOLS-ssh/#http://download.jboss.org/jbosstools/#" | egrep -v "\.zip")
rm -f /tmp/${version_jbt}.found.txt

----


=== Update composite site metadata for update

Update files __http://download.jboss.org/jbosstools/neon/development/updates/composite*.xml__ , with SFTP/SCP via command-line or your
favourite SFTP GUI client (such as Eclipse RSE).

This site needs to contain:
* The latest JBoss Tools core site
* The latest matching target platform site
* The latest matching JBoss Tools Central site

[source,bash]
----

cd ~/tru # or where you have jbosstools-download.jboss.org checked out

pushd jbosstools-download.jboss.org/jbosstools/neon

git fetch origin master
git checkout FETCH_HEAD

version_jbt=4.4.1.AM3
versionWithRespin_jbt=4.4.1.AM3 # a, b, c...
quals="development"; if [[ ${version_jbt##*Final} == "" ]]; then quals="development stable"; fi # **##
echo "
- integration-stack/*
- webtools/*
- */OLD/
- */reddeer/*
+ core/${versionWithRespin_jbt}/
+ core/composite*.xml
- core/*
+ coretests/${versionWithRespin_jbt}/
+ coretests/composite*.xml
- coretests/*
+ central/${versionWithRespin_jbt}/
+ central/composite*.xml
- central/*
+ earlyaccess/${versionWithRespin_jbt}/
+ earlyaccess/composite*.xml
- earlyaccess/*
+ discovery.central/${versionWithRespin_jbt}/
+ discovery.central/composite*.xml
- discovery.central/*
+ discovery.earlyaccess/${versionWithRespin_jbt}/
+ discovery.earlyaccess/${versionWithRespin_jbt}/plugins/
+ discovery.earlyaccess/${versionWithRespin_jbt}/plugins/*.jar
+ discovery.earlyaccess/composite*.xml
- discovery.earlyaccess/*
- site.css
- *.gz
- *.jar
- *.zip
" > /tmp/filter-jbosstools
scpr $TOOLS/neon/staging/updates/* staging/updates/ --include-from=/tmp/filter-jbosstools -q

for qual in $quals; do
  echo ":: $qual"
  scpr staging/updates/* ${qual}/updates/ --include-from=/tmp/filter-jbosstools

  pushd ${qual}/updates/
  if [[ ${versionWithRespin_jbt} != ${version_jbt} ]]; then
    # rename the staging folders to their final names (CR1c -> Final)
    for d in core coretests central earlyaccess discovery.central discovery.earlyaccess; do
      rm -fr ${d}/${version_jbt}
      mv ${d}/${versionWithRespin_jbt} ${d}/${version_jbt}
    done
  fi

  # fix composite sites to use the correct paths (not /staging, but /static)
  now=`date +%s000`
  for c in compositeContent.xml compositeArtifacts.xml */compositeContent.xml */compositeArtifacts.xml */${version_jbt}/compositeContent.xml */${version_jbt}/compositeArtifacts.xml; do
    if [[ $c == ${c/integration-stack/} ]]; then
      echo "$c ..."
      sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
      sed -i -e "s#jbosstools/neon/staging/updates/#jbosstools/static/neon/${qual}/updates/#" $c
      sed -i -e "s#${versionWithRespin_jbt}#${version_jbt}#" $c
    fi
  done
  popd
done
rm -f /tmp/filter-jbosstools

# copy versioned composite site into parent folder
for qual in $quals; do
  echo ":: $qual"
  pushd ${qual}/updates/ >/dev/null
    for d in core coretests central earlyaccess discovery.central discovery.earlyaccess; do
      if [[ -f ${d}/${version_jbt}/compositeContent.xml ]]; then
        scpr ${d}/${version_jbt}/composite*.xml ${d}/
      fi
      ga -f ${d}/${version_jbt}/* ${d}/*.*ml
    done
  popd >/dev/null
done

# push updated files to server
for qual in $quals; do
  pushd ${qual}/updates/ >/dev/null
    TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
    scpr *.*ml ${TOOLS}/neon/${qual}/updates/
    for d in core coretests discovery.central discovery.earlyaccess; do
      echo ${d}/
      scpr ${d}/*.*ml ${TOOLS}/neon/${qual}/updates/${d}/
      scpr ${d}/*.*ml ${TOOLS}/static/neon/${qual}/updates/${d}/
    done
    for d in discovery.central discovery.earlyaccess; do
      echo ${d}/
      scpr ${d}/${version_jbt}/* ${TOOLS}/neon/${qual}/updates/${d}/${version_jbt}/
      scpr ${d}/${version_jbt}/* ${TOOLS}/static/neon/${qual}/updates/${d}/${version_jbt}/
    done
  popd >/dev/null
done

# commit the change and push to master
for qual in $quals; do git add ${qual}/updates; done
git commit -m "release JBT ${versionWithRespin_jbt} to public" .
git push origin HEAD:master

popd

# verify site contents are shown
quals="development"; if [[ ${version_jbt##*Final} == "" ]]; then quals="development stable"; fi # **##
for qual in $quals; do
  google-chrome && google-chrome \
  http://download.jboss.org/jbosstools/neon/${qual}/updates \
  http://download.jboss.org/jbosstools/neon/${qual}/updates/compositeContent.xml \
  http://download.jboss.org/jbosstools/neon/${qual}/updates/core \
  http://download.jboss.org/jbosstools/neon/${qual}/updates/core/compositeContent.xml \
  http://download.jboss.org/jbosstools/static/neon/${qual}/updates/core \
  http://download.jboss.org/jbosstools/static/neon/${qual}/updates/coretests \
  http://download.jboss.org/jbosstools/neon/${qual}/updates/discovery.earlyaccess/ \
  http://download.jboss.org/jbosstools/neon/${qual}/updates/discovery.earlyaccess/compositeContent.xml \
  http://download.jboss.org/jbosstools/static/neon/${qual}/updates/central/ \
  http://download.jboss.org/jbosstools/static/neon/${qual}/updates/earlyaccess/ \

done

----

Open p2-browser and verify these sites load correctly:

http://download.jboss.org/jbosstools/neon/development/updates/
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/4.4.1.AM3/
http://download.jboss.org/jbosstools/static/neon/development/updates/coretests/4.4.1.AM3/

(and, if this is a Final)

http://download.jboss.org/jbosstools/neon/stable/updates/
http://download.jboss.org/jbosstools/neon/stable/updates/discovery.earlyaccess/
http://download.jboss.org/jbosstools/neon/stable/updates/discovery.earlyaccess/4.4.1.AM3/
http://download.jboss.org/jbosstools/static/neon/stable/updates/coretests/4.4.1.AM3/


=== WebTools

==== Publish Site

Webtools site is expected to be found in +http://download.jboss.org/tools/updates/webtools/neon+. So, with a sftp client, on filemgmt.jboss.org,
create a symlink from +/updates/webtools/neon+ to http://download.jboss.org/jbosstools/neon/stable/updates/ (or /development/updates/ if we're
before first Final release).

# verify site contents are shown
google-chrome && google-chrome http://download.jboss.org/jbosstools/updates/webtools/neon http://download.jboss.org/jbosstools/updates/webtools/

----

==== Notify webtools project

If this is the first milestone release (ie if you had to create the 'updates/webtools/neon' directory (next year will be "neon"), ensure that upstream project Web Tools (WTP) knows to include this new URL in their server adapter wizard. New bugzilla required!

* https://issues.jboss.org/browse/JBIDE-18921
* https://bugs.eclipse.org/454810

== Update Target Platforms

If this new release includes a new Target Platform, you need to release the latest target platform. If not, there's nothing to do here.

=== Final/GA releases

For Final or GA releases, the target platform folders should be moved to /static/ and composited back.

Thus for example,

http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/4.*.*.Final/
http://download.jboss.org/jbosstools/targetplatforms/jbdevstudiotarget/4.*.*.Final/

should be moved to:

http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/4.*.*.Final/
http://download.jboss.org/jbosstools/static/targetplatforms/jbdevstudiotarget/4.*.*.Final/

Then you can create composites in the old locations pointing to the new one, like this:

https://github.com/jbosstools/jbosstools-download.jboss.org/commit/d5306ce9408144ef681627ad8f5bd1e6c491bcf4

[source,bash]
----

cd ~/tru # or where you have jbosstools-download.jboss.org checked out ~

TARGET_PLATFORM_VERSION_MAX_PREV=4.60.1.AM1-SNAPSHOT
TARGET_PLATFORM_VERSION_MAX=4.60.1.AM3-SNAPSHOT
now=`date +%s000`
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools

# for Final TPs only!
pushd jbosstools-download.jboss.org/jbosstools/targetplatforms/
  git fetch origin master
  git checkout FETCH_HEAD

  for f in jbosstools; do
    git add ${f}target
    # move actual TP to /static/ folder
    echo "rename targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX} static/targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX}" | sftp ${TOOLS}/
    # change pointer to include /static/
    for d in ${f}target/${TARGET_PLATFORM_VERSION_MAX}/composite*.xml ${f}target/${TARGET_PLATFORM_VERSION_MAX}/REPO/composite*.xml; do
      sed -i -e "s#jbosstools/targetplatforms#jbosstools/static/targetplatforms#g" $d
    done
    # create composite pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${f}target/${TARGET_PLATFORM_VERSION_MAX}/* $TOOLS/targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX}/
  done
  # commit changes to github
  git commit -m "move target platforms into /static/ and update composite pointers to latest neon => ${TARGET_PLATFORM_VERSION_MAX}" .
  git push origin HEAD:master
popd

# for Final TPs only!
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/REPO/ \
http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/compositeContent.xml \

# verify files are correct
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/REPO/compositeContent.xml \
http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/compositeContent.xml

----


== Release the latest milestone to ide-config.properties

Check out http://download.jboss.org/jbosstools/configuration/ide-config.properties

Update it so that the links for the latest milestone point to valid URLs. Comment out staging links as required.

[source,bash]
----

# adjust these steps to fit your own path location & git workflow
cd ~/tru # ~
pushd jbosstools-download.jboss.org/jbosstools/configuration
version_jbt=4.4.1.AM3
versionWithRespin_jbt=4.4.1.AM3 # a, b, c...
version_ds=10.1.0.AM3 # no respin suffix here
versionWithRespin_ds=10.1.0.AM3 # a, b, c...

git fetch origin master
git checkout FETCH_HEAD

# you'll want to use URLs like these
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/neon/development/updates/discovery.central/${version_jbt}/jbosstools-directory.xml \
http://download.jboss.org/jbosstools/neon/development/updates/ \
http://download.jboss.org/jbosstools/neon/development/updates/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/development/updates/earlyaccess/ \
http://download.jboss.org/jbosstools/neon/development/updates/earlyaccess/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/${version_jbt}/jbosstools-earlyaccess.properties \

# verify
google-chrome && google-chrome \
https://devstudio.redhat.com/10.0/development/updates/discovery.central/${version_jbt}/devstudio-directory.xml \
https://devstudio.redhat.com/10.0/development/updates/ \
https://devstudio.redhat.com/10.0/development/updates/compositeContent.xml \
https://devstudio.redhat.com/10.0/development/updates/earlyaccess/ \
https://devstudio.redhat.com/10.0/development/updates/earlyaccess/compositeContent.xml \
https://devstudio.redhat.com/10.0/development/updates/discovery.earlyaccess/${version_jbt}/devstudio-earlyaccess.properties

# then edit ide-config.properties
# vim ide-config.properties
st ide-config.properties

# verify these 4 to 6 URLs exist
URLs="$(egrep -v "#" ide-config.properties | egrep "${version_jbt}|${versionWithRespin_jbt}|${version_ds}|${versionWithRespin_ds}" | sed -e "s#.\+|\([0-9.a-zA-Z]\+\)=\(.\+\)#\2#")"
google-chrome && google-chrome $URLs
for u in $URLs; do echo "$u"; done

# commit the change and push to master
ci "release JBT ${version_jbt} (${versionWithRespin_jbt}) to public: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
rsync -Pzrlt --rsh=ssh --protocol=28 ide-config.properties $TOOLS/configuration/ide-config.properties
popd

----


== Update Eclipse Marketplace (add/remove features)

WARNING: Only applies to Beta and better versions.

=== If node does not yet exist

For the first Beta, create a new node on Marketplace, using content from http://download.jboss.org/jbosstools/static/neon/stable/updates/core/4.4.1.AM3/site.properties

=== If node already exists

Access it via +https://marketplace.eclipse.org/content/jboss-tools/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Update list of features, using content of http://download.jboss.org/jbosstools/static/neon/stable/updates/core/4.4.1.AM3/site.properties

To diff if any new features have been added/removed:

[source,bash]
----
version_jbt_PREV=4.4.1.AM2
version_jbt=4.4.1.AM3

cd /tmp
wget -O ${version_jbt_PREV}.properties http://download.jboss.org/jbosstools/static/neon/development/updates/core/${version_jbt_PREV}/site.properties
wget -O ${version_jbt}.properties http://download.jboss.org/jbosstools/static/neon/development/updates/core/${version_jbt}/site.properties
diff -u ${version_jbt_PREV}.properties ${version_jbt}.properties

# then verify the the new feature(s) were added to the CoreTools category
google-chrome && google-chrome https://marketplace.eclipse.org/content/jboss-tools/edit

rm -f /tmp/${version_jbt_PREV}.properties /tmp/${version_jbt}.properties

----

=== Validate Marketplace install

(If this is an development milestone towards a .0.Final, or a stable .x.Final build...)

1. Get a compatible Eclipse
2. Install from Marketplace
3. Install everything from Central + Earlyaccess
4. Test a project example


== Release JIRA

If there are no unresolved issues, release the milestone version in JIRA.

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA.

[source,bash]
----

google-chrome && google-chrome https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions

----


== Submit PR to update tools.jboss.org

See JBDS_Release.adoc


== Tag Git

=== Create tags for build-related repositories

Once cloned to disk, this script will create the tags if run from the location with your git clones. If tags exist, no new tag will be created.

[source,bash]
----

# if not already cloned, the do this:
git clone https://github.com/jbosstools/jbosstools-build
git clone https://github.com/jbosstools/jbosstools-build-ci
git clone https://github.com/jbosstools/jbosstools-build-sites
git clone https://github.com/jbosstools/jbosstools-devdoc
git clone https://github.com/jbosstools/jbosstools-discovery
git clone https://github.com/jbosstools/jbosstools-download.jboss.org
git clone https://github.com/jbosstools/jbosstools-maven-plugins
git clone https://github.com/jbosstools/jbosstools-versionwatch

# maven-plugins does not get released/branched the same as other projects, but tag it anyway
# download.jboss.org tag might not be valid as tweaks to ide-config.properties happen frequently

jbt_branch=master # jbosstools-4.4.0.x
version_jbt=4.4.1.AM3
cd ~/tru # ~
for d in build build-ci build-sites devdoc discovery download.jboss.org maven-plugins versionwatch; do
  echo "====================================================================="
  echo "Tagging jbosstools-${d} from branch ${jbt_branch} as tag ${version_jbt}..."
  pushd jbosstools-${d}
  git fetch origin ${jbt_branch}
  git tag jbosstools-${version_jbt} FETCH_HEAD
  git push origin jbosstools-${version_jbt}
  echo ">>> https://github.com/jbosstools/jbosstools-${d}/tree/jbosstools-${version_jbt}"
  popd >/dev/null
  echo "====================================================================="
  echo ""
done

----

=== Request bulk tag creation

@since 4.3: bulk-tagging via script; email generated

*To:* alkazako@redhat.com, jmaury@redhat.com +

[source,bash]
----
version_jbt=4.4.1.AM3
recipients="alkazako@redhat.com, jmaury@redhat.com"
sender="nboldt@redhat.com"
subject="Ready for JBT ${version_jbt} tag creation"
qual="development"; if [[ ${version_jbt##*Final} == "" ]]; then qual="stable"; fi # **##
echo "

cd ~/tru # to your clone of jbosstools-build-ci # ~
pushd jbosstools-build-ci/util >/dev/null

# get CSV file & tag repos
curl http://download.jboss.org/jbosstools/static/neon/${qual}/updates/core/${version_jbt}/buildinfo.json | python buildinfo2tags.py \
-n jbosstools-${version_jbt} | python tagrepos.py GITHUBUSER GITHUBPWD
" > /tmp/mailbody.jbt.txt
fi

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" $recipients -c $sender -- -f"$sender" < /tmp/mailbody.jbt.txt
rm -f /tmp/mailbody.jbt.txt

----


== Smoke test the release

Before notifying team of release, must check for obvious problems. Any failure there should be fixed with highest priority. In general, it could be wrong URLs in a composite site.

=== Validate update site install

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Abridged category from http://download.jboss.org/jbosstools/neon/development/updates/ and/or http://download.jboss.org/jbosstools/neon/stable/updates/
3. Restart. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again


== Notify Alexey & Jeff

Notifify Alexy & Jeff that the website is ready to be updated & blog ready to be posted.

If co-releasing JBT and JBDS, make sure that JBDS is released too!

DO NOT send email notification until the above update to the website is done, and the new blog announcement is live, with image inclusion, spelling, & grammar checks done.

____

[source,bash]
----

version_jbt=4.4.1.AM3
eclipseVersion="Eclipse 4.6.0 Neon.0"
qual="development"; if [[ ${version_jbt##*Final} == "" ]]; then qual="stable"; fi # **##
pullrequestURL=https://github.com/jbosstools/jbosstools-website/pull/615
blogURL=/blog/am3-for-neon.html

TOrecipients="alkazako@redhat.com, jmaury@redhat.com"
CCrecipients="nboldt@redhat.com"
sender="Nick Boldt <nboldt@redhat.com>"
subject="Ready for JBT ${version_jbt} blog & announcement"
echo "
Here's a PR for adding ${version_jbt} to the JBoss Tools download page:

${pullrequestURL}

Suggested blog filename: ${blogURL}

The complete list of projects in JBoss Tools, and the SHAs used to build those projects, can be seen here:

http://download.jboss.org/jbosstools/static/neon/${qual}/updates/core/${version_jbt}/buildinfo.json

From that list you can create all the jbosstools-${version_jbt} tags in Github, should you so desire.

Below is a sample email you could send to the jbosstools-dev mailing list when the blog is live.

--

Subject:

JBoss Tools ${version_jbt} is now available

Body:

This is a ${qual} release aimed at ${eclipseVersion} users.

Announcement Blog: http://tools.jboss.org/blog/

Eclipse Marketplace: https://marketplace.eclipse.org/content/jboss-tools

Update Site: http://download.jboss.org/jbosstools/neon/${qual}/updates/

Zips: http://tools.jboss.org/downloads/jbosstools/neon/${version_jbt}.html#zips

Installation instructions: http://tools.jboss.org/downloads/installation.html

New + Noteworthy (subject to change): http://tools.jboss.org/documentation/whatsnew/jbosstools/${version_jbt}.html

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBIDE?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel
" > /tmp/mailbody.jbt.txt

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" "$TOrecipients" -c "$CCrecipients" -- -f"$sender" < /tmp/mailbody.jbt.txt
rm -f /tmp/mailbody.jbt.txt

----
____

