= Release JBoss Tools Development Milestone

This document describe how to publish a valid JBoss Tools build to production after being verified by QE.

With distractions (email, IRC), this process took 90 mins for the Beta release.

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA.

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten.

Send an email to jbosstools-dev@ and jboss-devstudio-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
google-chrome && google-chrome https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Summary

Here are some generalities site promotion/release process. It's not an exhaustive list so you need to read the full document to do a release, but it gives an overview of the various steps.

. CI build output is published the 'builds/staging' folder, while aggregated update-sites goes to 'updates/nightly' folder
. After branching, component repository are rebuilt from branch (instead of 'master') and new aggregated updatesites are created as well.  A site is promoted from nightly to staging for QE, and moves from 'updates/nightly' to 'updates/staging', including a respin suffix if required.
.. If QE finds a blocker issue, a respin is requested
... On Jira, add a 'respin-a' or 'respin-b' or 'respin-x' label to bugs that needs for be fixed for the respin
... Edit CI jobs to the next respin label (eg CR2b)
... Re-run necessary jobs
... Go To 1
.. If QE approves, release is accepted and promoted
... JIRA is checked to ensure all JIRAs for this milestone are resolved
... Site moves from 'updates/staging' with respin label to 'static/releases' without respin label
... Links to 'updates/neon' are replaced to link to new version
... JBoss Tools website is updated
... Git repositories are tagged
... Eclipse Marketplace entries are created or updated
... JIRA version can be released
... Interested parties are notified


== Copy sites

These steps happens on filemgmt.jboss.org, in the jbosstools download area.

=== Copy content to release directory

TODO: is this warning still relevant?
PLEASE NOTE! If you're pushing a new /development/ site and the last release was to /stable/, make sure you disconnect the symlinks first or you'll end up putting a milestone into /stable/ instead of /development/.

See section "Copy from development to stable & create symlinks from /stable/ into /development/" for details.


We simply copy the content of the latest respin to the release directory (under _jbosstools/static_ which is using Akamai)

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Here is a script that performs the copy from /staging/ to /development/.

[source,bash]
----

cd /tmp
if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.4.x/publish/stage.sh --no-check-certificate
chmod +x stage.sh

stream=4.4.0.Alpha2 # staged version # a, b, c...
version=4.4.0.Alpha2 # release version: no a, b, c suffix
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
for qual in $quals; do
  for site in core coretests central earlyaccess discovery.central discovery.earlyaccess browsersim-standalone; do
    ./stage.sh -sites $site -stream ${stream} -vr ${version} -sd neon -dd static/neon -st staging -dt $qual -JOB_NAME jbosstools-\${stream}-build-\${site} -q &
  done
done

# TODO wait until the above 7 (or 2x7) pushes are done (should be nothing if you run this:
ps ax | grep stage.sh | grep "sites"

# TODO merge this into stage.sh?
# JBT zips into http://download.jboss.org/jbosstools/static/neon/development/updates/core/
version=4.4.0.Alpha1
versionWithRespin=4.4.0.Alpha2 # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
for site in core; do
  tmpdir=~/temp-stage/jbosstools-static-${qual}-updates-${site}_${versionWithRespin}_zips; mkdir -p ${tmpdir}
  # get src.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/neon/staging/builds/jbosstools-${versionWithRespin}-build-core/latest/all/jbosstools-${version}-src.zip* ${tmpdir}/
  # get browsersim-standalone.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/neon/staging/builds/jbosstools-${versionWithRespin}-build-browsersim-standalone/latest/jbosstools-*-browsersim-standalone.zip* ${tmpdir}/
  for qual in $quals; do
    echo "mkdir ${site}" | sftp ${TOOLS}/static/neon/${qual}/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/*.zip* ${TOOLS}/static/neon/${qual}/updates/${site}/
  done
  rm -fr $tmpdir
done
echo "DONE: JBT zips" | grep "JBT zips"

# verify we have all the files we expect to see (run locally, not on dev01)
#TODO make sure you've mounted ~/TOOLS-ssh first!
version=4.4.0.Alpha1
versionWithRespin=4.4.0.Alpha2 # a, b, c...
expectedCount=0
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
rm -f /tmp/${version}.found.txt
for qual in $quals; do
  (( expectedCount += 18 ));
  find $HOME/TOOLS-ssh/static/neon/${qual}/updates/* -maxdepth 1 -name "*${version}*" -o -name "*${versionWithRespin}*" | sort >> /tmp/${version}.found.txt
done
theCount=$(cat /tmp/${version}.found.txt | wc -l)
if [[ ${theCount} == ${expectedCount} ]]; then
  echo "[INFO] Found all expected ${expectedCount} files/folders" | egrep "${expectedCount}|${theCount}|INFO|ERROR"
else
  echo "[ERROR] expected ${expectedCount} files/folders, found ${theCount}:" | egrep "${expectedCount}|${theCount}|INFO|ERROR"
  cat /tmp/${version}.found.txt | sort | egrep "${version}|${versionWithRespin}"
fi
echo "Download all these zips to verify they work:"
cat /tmp/${version}.found.txt | sed "s#$HOME/TOOLS-ssh/#http://download.jboss.org/jbosstools/#" | egrep "\.zip"
echo "Review these pages to verify the work:"
google-chrome && google-chrome $(cat /tmp/${version}.found.txt | sed "s#$HOME/TOOLS-ssh/#http://download.jboss.org/jbosstools/#" | egrep -v "\.zip")
rm -f /tmp/${version}.found.txt

----


=== Update composite site metadata for update

Update files __http://download.jboss.org/jbosstools/neon/development/updates/composite*.xml__ , with SFTP/SCP via command-line or your
favourite SFTP GUI client (such as Eclipse RSE).

This site needs to contain:
* The latest JBoss Tools core site
* The latest matching target platform site
* The latest matching JBoss Tools Central site

[source,bash]
----

#TODO JBIDE-20904 make this process smarter... copy from staging site, then replace "staging/" with "development/" (or "stable/") and ${versionWithRespin} with ${version}


cd ~/tru # or where you have jbosstools-download.jboss.org checked out

pushd jbosstools-download.jboss.org/jbosstools/neon

git fetch origin master
git checkout FETCH_HEAD

version=4.4.0.Alpha2
versionWithRespin=4.4.0.Alpha2 # a, b, c...
echo "
- integration-stack/*
- webtools/*
- */OLD/
- */reddeer/*
+ core/${versionWithRespin}/
+ core/composite*.xml
- core/*
+ coretests/${versionWithRespin}/
+ coretests/composite*.xml
- coretests/*
+ central/${versionWithRespin}/
+ central/composite*.xml
- central/*
+ earlyaccess/${versionWithRespin}/
+ earlyaccess/composite*.xml
- earlyaccess/*
+ discovery.central/${versionWithRespin}/
+ discovery.central/composite*.xml
- discovery.central/*
+ discovery.earlyaccess/${versionWithRespin}/
+ discovery.earlyaccess/${versionWithRespin}/plugins/
+ discovery.earlyaccess/${versionWithRespin}/plugins/*.jar
+ discovery.earlyaccess/composite*.xml
- discovery.earlyaccess/*
- site.css
- *.gz
- *.jar
- *.zip
" > /tmp/filter
scpr $TOOLS/neon/staging/updates/* staging/updates/ --include-from=/tmp/filter
scpr staging/updates/* development/updates/ --include-from=/tmp/filter
rm -f /tmp/filter

pushd development/updates/
if [[ ${versionWithRespin} != ${version} ]]; then
  # rename the staging folders to their final names (CR1c -> Final)
  for d in core coretests central earlyaccess discovery.central discovery.earlyaccess; do
    rm -fr ${d}/${version}
    mv ${d}/${versionWithRespin} ${d}/${version}
  done
fi

# replace static/releases with neon/staging/updates, then replace all the versions
now=`date +%s000`
for c in compositeContent.xml compositeArtifacts.xml */compositeContent.xml */compositeArtifacts.xml */${version}/compositeContent.xml */${version}/compositeArtifacts.xml; do
  if [[ $c == ${c/integration-stack/} ]]; then
    echo "$c ..."
    sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
    sed -i -e "s#jbosstools/neon/staging/updates/#jbosstools/static/neon/development/updates/#" $c
    sed -i -e "s#${versionWithRespin}#${version}#" $c
  fi
done

for d in core coretests central earlyaccess discovery.central discovery.earlyaccess; do
  ga -f ${d}/${version}/* ${d}/*.*ml
done

# commit the change and push to master
git commit -m "release JBT ${versionWithRespin} to public" .
git push origin HEAD:master

# push updated files to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
scpr *.*ml ${TOOLS}/neon/development/updates/
for d in core coretests discovery.central discovery.earlyaccess; do
  scpr ${d}/*.*ml ${TOOLS}/neon/development/updates/${d}/
done
for d in discovery.central discovery.earlyaccess; do
  scpr ${d}/${version}/* ${TOOLS}/neon/development/updates/${d}/${version}/
done

popd
popd

# verify site contents are shown
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/neon/development/updates/ \
http://download.jboss.org/jbosstools/neon/development/updates/core/ \
http://download.jboss.org/jbosstools/neon/development/updates/coretests/ \
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/ \
http://download.jboss.org/jbosstools/neon/development/updates/earlyaccess/ \
http://download.jboss.org/jbosstools/neon/development/updates/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/development/updates/core/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/development/updates/earlyaccess/compositeContent.xml \

----

If this is a /stable/ release, carefully merge changes from /development into /stable, then commit your changes & push to the server. Verify:

[source,bash]
----

# verify site contents are shown
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/neon/stable/updates/ \
http://download.jboss.org/jbosstools/neon/stable/updates/core/ \
http://download.jboss.org/jbosstools/neon/stable/updates/coretests/ \
http://download.jboss.org/jbosstools/neon/stable/updates/discovery.earlyaccess/ \
http://download.jboss.org/jbosstools/neon/stable/updates/earlyaccess/ \
http://download.jboss.org/jbosstools/neon/stable/updates/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/stable/updates/core/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/stable/updates/discovery.earlyaccess/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/stable/updates/earlyaccess/compositeContent.xml \

----

Open p2-browser and verify these sites load correctly:

http://download.jboss.org/jbosstools/neon/development/updates/coretests/
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/4.4.0.Alpha2/

http://download.jboss.org/jbosstools/neon/stable/updates/coretests/
http://download.jboss.org/jbosstools/neon/stable/updates/discovery.earlyaccess/
http://download.jboss.org/jbosstools/neon/stable/updates/discovery.earlyaccess/4.4.0.Alpha2/


=== WebTools

==== Publish Site

Webtools site is expected to be found in +http://download.jboss.org/tools/updates/webtools/neon+. So, with a sftp client, on filemgmt.jboss.org,
create a symlink from +/updates/webtools/neon+ to http://download.jboss.org/jbosstools/neon/stable/updates/ (or /development/updates/ if we're
before first Final release).

# verify site contents are shown
google-chrome && google-chrome http://download.jboss.org/jbosstools/updates/webtools/neon http://download.jboss.org/jbosstools/updates/webtools/

----

==== Notify webtools project

If this is the first milestone release (ie if you had to create the 'updates/webtools/neon' directory (next year will be "neon"), ensure that upstream project Web Tools (WTP) knows to include this new URL in their server adapter wizard. New bugzilla required!

* https://issues.jboss.org/browse/JBIDE-18921
* https://bugs.eclipse.org/454810

== Update Target Platforms

If this new release includes a new Target Platform, you need to release the latest target platform. If not, there's nothing to do here.

=== Final/GA releases

For Final or GA releases, the target platform folders should be moved to /static/ and composited back.

Thus for example,

http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/4.*.*.Final/
http://download.jboss.org/jbosstools/targetplatforms/jbdevstudiotarget/4.*.*.Final/

should be moved to:

http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/4.*.*.Final/
http://download.jboss.org/jbosstools/static/targetplatforms/jbdevstudiotarget/4.*.*.Final/

Then you can create composites in the old locations pointing to the new one, like this:

https://github.com/jbosstools/jbosstools-download.jboss.org/commit/d5306ce9408144ef681627ad8f5bd1e6c491bcf4

[source,bash]
----

cd ~/tru # or where you have jbosstools-download.jboss.org checked out ~

TARGET_PLATFORM_VERSION_MAX_PREV=4.60.0.Alpha1-SNAPSHOT
TARGET_PLATFORM_VERSION_MAX=4.60.0.Alpha1-SNAPSHOT
now=`date +%s000`
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools

# for Final TPs only!
pushd jbosstools-download.jboss.org/jbosstools/targetplatforms/
  git fetch origin master
  git checkout FETCH_HEAD

  for f in jbosstools; do
    git add ${f}target
    # move actual TP to /static/ folder
    echo "rename targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX} static/targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX}" | sftp ${TOOLS}/
    # change pointer to include /static/
    for d in ${f}target/${TARGET_PLATFORM_VERSION_MAX}/composite*.xml ${f}target/${TARGET_PLATFORM_VERSION_MAX}/REPO/composite*.xml; do
      sed -i -e "s#jbosstools/targetplatforms#jbosstools/static/targetplatforms#g" $d
    done
    # create composite pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${f}target/${TARGET_PLATFORM_VERSION_MAX}/* $TOOLS/targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX}/
  done
  # commit changes to github
  git commit -m "move target platforms into /static/ and update composite pointers to latest neon => ${TARGET_PLATFORM_VERSION_MAX}" .
  git push origin HEAD:master
popd

# for Final TPs only!
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/REPO/ \
http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/compositeContent.xml \

# verify files are correct
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/REPO/compositeContent.xml \
http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/compositeContent.xml

----

=== JBoss Central, Early Access, and Discovery

There's nothing more to do here (it was done above). Just review these URLs:

[source,bash]
----

# verify site are correct:
version=4.4.0.Alpha2
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/static/neon/development/updates/central/${version} \
http://download.jboss.org/jbosstools/static/neon/development/updates/earlyaccess/${version} \
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/${version} \
http://download.jboss.org/jbosstools/neon/development/updates/discovery.central/${version}

----

If this is a .Final release make sure that content in development is copied over to stable too:

[source,bash]
----
version=4.4.0.Alpha2
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
cd ~/tru # ~
for d in central earlyaccess; do
  pushd jbosstools-download.jboss.org/jbosstools/neon/stable/updates/discovery.${d}
    scpr $TOOLS/neon/development/updates/discovery.${d}/${version} ./
    scpr ${version} $TOOLS/neon/stable/updates/discovery.${d}/
  popd
done
for d in central earlyaccess; do
  pushd jbosstools-download.jboss.org/jbosstools/static/neon/stable/updates/core/${d}
    scpr $TOOLS/static/neon/development/updates/core/${d}/${version} ./
    scpr ${version} $TOOLS/static/neon/stable/updates/core/${d}/
  popd
done

# verify site are correct:
version=4.4.0.Alpha2
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/static/neon/stable/updates/central/${version} \
http://download.jboss.org/jbosstools/static/neon/stable/updates/earlyaccess/${version} \
http://download.jboss.org/jbosstools/neon/stable/updates/discovery.earlyaccess/${version} \
http://download.jboss.org/jbosstools/neon/stable/updates/discovery.central/${version}

----


== Copy from development to stable & create symlinks from /stable/ into /development/

If this is a .Final release:

First, mount an sshfs drive for $TOOLS, tools@filemgmt.jboss.org:/downloads_htdocs/tools, eg., into $HOME/TOOLS-ssh/

Then, ensure that the destination dirs exist. Move the contents of /development/ into /stable/, then symlink back from the old place:

[source,bash]
----

# TODO SKIPPED for 4.4.0.Alpha2 because we just published bits to both paths using stage.sh so no need to move/symlink

TOOLSmnt=$HOME/TOOLS-ssh
version=4.4.0.Alpha2
mkdir -p ${TOOLSmnt}/static/neon/{development,stable}/updates/{central,core,coretests,earlyaccess}
for d in central core coretests earlyaccess; do
  if [[ ! -d ${TOOLSmnt}/static/neon/stable/updates/${d}/${version} ]]; then mv ${TOOLSmnt}/static/neon/{development,stable}/updates/${d}/${version}; fi
  pushd ${TOOLSmnt}/static/neon/development/updates/${d}/; rm -f $version; ln -s ../../../../../static/neon/stable/updates/${d}/${version}/; popd
  ls -la ${TOOLSmnt}/static/neon/{development,stable}/updates/${d}
  google-chrome && google-chrome http://download.jboss.org/jbosstools/static/neon/development/updates/${d}/ http://download.jboss.org/jbosstools/static/neon/development/updates/${d}/${version}
done

# verify discovery content is where it should be:
for d in ${TOOLSmnt}/neon/{development,stable}/updates/{discovery.,}{central,earlyaccess}; do
  echo $d;
  if [[ -L "${d}" ]]; then #symlinks ##
    ls -la ${d}/.. | egrep "$(basename ${d})" | grep -- "->"
  else # normal dirs
    ls -la ${d}
  fi
  echo ""
done

# verify discovery content is where it should be:
for d in ${TOOLSmnt}/static/neon/{development,stable}/updates/{central,earlyaccess}; do
  echo $d;
  if [[ -L "${d}" ]]; then #symlinks ##
    ls -la ${d}/.. | egrep "$(basename ${d})" | grep -- "->"
  else # normal dirs
    ls -la ${d}
  fi
  echo ""
done

----

Also, make sure that links in composite*.xml files point at the /stable/ URLs, not the /development/ ones.


== Merge in Integration Stack content

See details in Merge_IS_Discovery.adoc

[source,bash]
----

pushd /tmp
  wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.4.x/publish/mergeISdiscovery.sh && chmod +x mergeISdiscovery.sh
  ./mergeISdiscovery.sh -q development -q -stable -version 4.4.0.Alpha2 -versionWithRespin 4.4.0.Alpha2 -is http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/discovery/4.3.0.Final/earlyaccess/
  rm -f /tmp/mergeISdiscovery.sh
popd

----


== Release the latest milestone to ide-config.properties

Check out http://download.jboss.org/jbosstools/configuration/ide-config.properties

Update it so that the links for the latest milestone point to valid URLs. Comment out staging links as required.

[source,bash]
----

# adjust these steps to fit your own path location & git workflow
cd ~/tru # ~
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=4.4.0.Alpha2
versionWithRespin=4.4.0.Alpha2 # a, b, c...

git fetch origin master
git checkout FETCH_HEAD

# you'll want to use URLs like these
google-chrome && google-chrome \
http://download.jboss.org/jbosstools/neon/development/updates/discovery.central/${version}/jbosstools-directory.xml \
http://download.jboss.org/jbosstools/neon/development/updates/ \
http://download.jboss.org/jbosstools/neon/development/updates/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/development/updates/earlyaccess/ \
http://download.jboss.org/jbosstools/neon/development/updates/earlyaccess/compositeContent.xml \
http://download.jboss.org/jbosstools/neon/development/updates/discovery.earlyaccess/${version}/jbosstools-earlyaccess.properties \

# then edit ide-config.properties
# vim ide-config.properties
st ide-config.properties

# commit the change and push to master
ci "release JBT ${version} (${versionWithRespin}) to public: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
rsync -Pzrlt --rsh=ssh --protocol=28 ide-config.properties $TOOLS/configuration/ide-config.properties
popd

----

== Update Eclipse Marketplace (add/remove features)

WARNING: Only for Beta, CR and GA! We do not release Alphas to Eclipse Marketplace.
NOTE: for 4.3.1.*, we will skip this step until Final (no Betas)!

=== If node does not yet exist

This is usually the case of first Beta version.

Create a new node on Marketplace, use content of http://download.jboss.org/jbosstools/static/neon/stable/updates/core/4.4.0.Alpha2/site.properties

=== If node already exists

Access it via +https://marketplace.eclipse.org/content/jboss-tools/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Update list of features, using content of http://download.jboss.org/jbosstools/static/neon/stable/updates/core/4.4.0.Alpha2/site.properties

To diff if any new features have been added/removed:

[source,bash]
----
versionWithRespin_PREV=4.3.1.Final
version=4.4.0.Alpha2

cd /tmp
wget -O ${versionWithRespin_PREV}.properties http://download.jboss.org/jbosstools/static/neon/development/updates/core/${versionWithRespin_PREV}/site.properties
wget -O ${version}.properties http://download.jboss.org/jbosstools/static/neon/development/updates/core/${version}/site.properties
diff -u ${versionWithRespin_PREV}.properties ${version}.properties

# then verify the the new feature(s) were added to the CoreTools category
google-chrome && google-chrome https://marketplace.eclipse.org/content/jboss-tools/edit

rm -f /tmp/${versionWithRespin_PREV}.properties /tmp/${version}.properties

----


== Smoke test the release

Before notifying team of release, must check for obvious problems. Any failure there should be fixed with highest priority. In general, it could be wrong URLs in a composite site.

=== Validate update site install

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Abridged category from http://download.jboss.org/jbosstools/neon/development/updates/ and/or http://download.jboss.org/jbosstools/neon/stable/updates/
3. Restart. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

=== Validate Marketplace install

1. Get a compatible Eclipse
2. Install from Marketplace
3. Install everything from Central + Earlyaccess
4. Test a project example


== Git tags

=== Create tags for build-related repositories

Once cloned to disk, this script will create the tags if run from the location with your git clones. If tags exist, no new tag will be created.

[source,bash]
----

# if not already cloned, the do this:
git clone https://github.com/jbosstools/jbosstools-build
git clone https://github.com/jbosstools/jbosstools-build-ci
git clone https://github.com/jbosstools/jbosstools-build-sites
git clone https://github.com/jbosstools/jbosstools-devdoc
git clone https://github.com/jbosstools/jbosstools-discovery
git clone https://github.com/jbosstools/jbosstools-download.jboss.org
git clone https://github.com/jbosstools/jbosstools-maven-plugins
git clone https://github.com/jbosstools/jbosstools-versionwatch

# maven-plugins does not get released/branched the same as other projects, but tag it anyway
# download.jboss.org tag might not be valid as tweaks to ide-config.properties happen frequently

jbt_branch=master
version=4.4.0.Alpha2
cd ~/tru # ~
for d in build build-ci build-sites devdoc discovery download.jboss.org maven-plugins versionwatch; do
  echo "====================================================================="
  echo "Tagging jbosstools-${d} from branch ${jbt_branch} as tag ${version}..."
  pushd jbosstools-${d}
  git fetch origin ${jbt_branch}
  git tag jbosstools-${version} FETCH_HEAD
  git push origin jbosstools-${version}
  echo ">>> https://github.com/jbosstools/jbosstools-${d}/tree/jbosstools-${version}"
  popd >/dev/null
  echo "====================================================================="
  echo ""
done

----

=== Request bulk tag creation

@since 4.3: bulk-tagging via script; email generated

*To:* alkazako@redhat.com +

[source,bash]
----
version=4.4.0.Alpha2
recipients=alkazako@redhat.com
sender="nboldt@redhat.com"
subject="Ready for JBT ${version} tag creation"
echo "

cd ~/tru # to your clone of jbosstools-build-ci # ~
pushd jbosstools-build-ci/util >/dev/null

# get CSV file & tag repos
curl http://download.jboss.org/jbosstools/static/neon/development/updates/core/${version}/buildinfo.json | python buildinfo2tags.py \
-n jbosstools-${version} | python tagrepos.py GITHUBUSER GITHUBPWD
" > /tmp/mailbody.jbt.txt
fi

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" $recipients -c $sender -- -f"$sender" < /tmp/mailbody.jbt.txt
rm -f /tmp/mailbody.jbt.txt

----


== Release JIRA

If there are no unresolved issues, release the milestone version in JIRA.

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA.

[source,bash]
----

google-chrome && google-chrome https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions

----


== Update jbosstools-website

Provide a PR to add the latest JBT milestones to this listing: https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml_

Example:

* https://github.com/jbosstools/jbosstools-website/pull/193 (note that the JBDS part is better done after & seprarately, while releasing JBDS)
* https://github.com/jbosstools/jbosstools-website/pull/211 (only JBT part of the change)
* https://github.com/jbosstools/jbosstools-website/pull/343 (ony JBT)
* https://github.com/jbosstools/jbosstools-website/pull/388 (only JBT)
* https://github.com/jbosstools/jbosstools-website/pull/418 (JBT / JBDS Final)
* https://github.com/jbosstools/jbosstools-website/pull/449 (JBT Final)
* https://github.com/jbosstools/jbosstools-website/pull/488 (JBT CR2)
* https://github.com/jbosstools/jbosstools-website/pull/513 (JBDS GA)
* https://github.com/jbosstools/jbosstools-website/pull/568 (JBT 4.4.0.Alpha2)


== Enable jobs

NOTE: This should have been done after staging, but just in case it was not, here's a reminder.

As you have just released something, the next build will be a CI snapshot for the following milestone.

Thus, you need to:

* re-enable jobs that were disabled during staging
* set correct github branch, eg., switch from 4.4.0.Alpha2x to 4.4.x
* upversion dependencies, eg., releng scripts move from version Final to CR1 (if that's been released)
* upversion target platforms / Central version (if those have been released)


== Notify Alexey & Max

Notifify Alexy & Max that the website is ready to be updated & blog ready to be posted.

If co-releasing JBT and JBDS, make sure that JBDS is released too!

DO NOT send email notification until the above update to the website is done, and the new blog announcement is live, with image inclusion, spelling, & grammar checks done.

____

[source,bash]
----

version=4.4.0.Alpha2
eclipseVersion="Eclipse 4.6.0.M7 neon.0.M7"
qual="development"; if [[ ${version##*GA} == "" ]]; then qual="stable"; fi # **##
pullrequestURL=https://github.com/jbosstools/jbosstools-website/pull/583
blogURL=/blog/alpha-for-neon.html

TOrecipients="alkazako@redhat.com"
CCrecipients="max.andersen@redhat.com, nboldt@redhat.com"
sender="Nick Boldt <nboldt@redhat.com>"
subject="Ready for JBT ${version} blog & announcement"
echo "
Here's a PR for adding ${version} to the JBoss Tools download page:

${pullrequestURL}

Suggested blog filename: ${blogURL}

The complete list of projects in JBoss Tools, and the SHAs used to build those projects, can be seen here:

http://download.jboss.org/jbosstools/static/neon/${qual}/updates/core/${version}/buildinfo.json

From that list you can create all the jbosstools-${version} tags in Github, should you so desire.

Below is a sample email you could send to the jbosstools-dev mailing list when the blog is live.

--

Subject:

JBoss Tools ${version} is now available

Body:

This is a ${qual} release aimed at ${eclipseVersion} users.

Announcement Blog: http://tools.jboss.org/blog/

Eclipse Marketplace: https://marketplace.eclipse.org/content/jboss-tools

Update Site: http://download.jboss.org/jbosstools/neon/${qual}/updates/

Zips: http://tools.jboss.org/downloads/jbosstools/neon/${version}.html#zips

Installation instructions: http://tools.jboss.org/downloads/installation.html

New + Noteworthy (subject to change): http://tools.jboss.org/documentation/whatsnew/jbosstools/${version}.html

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBIDE?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel
" > /tmp/mailbody.jbt.txt

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" "$TOrecipients" -c "$CCrecipients" -- -f"$sender" < /tmp/mailbody.jbt.txt
rm -f /tmp/mailbody.jbt.txt

----
____

