= Publishing JBT update sites for QE

This document describe how to provide a valid JBoss Tools build to QE so they can test us.

TODO: use consistent instructions for fetching sources from git & pushing changes
TODO: use sshfs to do copies in a single step, instead of rsync-pull/rsync-push (2 steps)

[NOTE]
====
Note that +sftp://tools@10.5.105.197/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+ +

(Use filemgmt.jboss.org IP instead of 10.5.105.197 because it's 3x faster!)

If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools .
A Jenkins job can then be triggered to sync changes to download.jboss.org: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-download.jboss.org-rsync-from-svn/
====

== Enable staging jobs

You will need to enable the jobs:

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

stream_jbt=master # or 4.4.neon
for j in jbosstools-releng-push-to-staging-07-notification-emails_${stream_jbt} \
jbosstools-releng-push-to-staging-03-verify-builds-update-sites_${stream_jbt} \
jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_${stream_jbt} \
jbosstools-releng-push-to-staging-01-check-versions-branches-root-poms_${stream_jbt} \
jbosstools-releng-push-to-staging-buildflow_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
done

----

== Verify correct versions, branches exist, and root poms are correct

Configure, then run this job:

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

stream_jbt=master # or 4.4.neon
stream_ds=master # or 10.0.neon
github_branch=master # or jbosstools-4.4.1.x or jbosstools-4.4.x
version_parent=4.4.2.AM1-SNAPSHOT
version_jbt=4.4.2.AM3
version_ds=10.2.0.AM3

# TODO migrate this to use jbosstools-build-ci/util/jenkinsPost.sh wrapper
for j in jbosstools-releng-push-to-staging-01-check-versions-branches-root-poms_master; do
  curl -k -u ${userpass} --data "stream_jbt=${stream_jbt}&github_branch=${github_branch}&version_parent=${version_parent}&version_jbt=${version_jbt}&version_ds=${version_ds}" \
    https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/buildWithParameters && echo -n ".B"
  sleep 10s
  google-chrome http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/lastBuild/console &
done

----


If any branches have not yet been created, you can either:
* Ask Denis, Fred, or Max to get them created
* Create them yourself like this:

[source,bash]
----
git checkout master; git pull origin master; git checkout -b jbosstools-4.4.1.x; git push origin jbosstools-4.4.1.x
# or, for jbosstools-build-ci
git checkout jbosstools-4.4.x; git pull origin jbosstools-4.4.x; git checkout -b jbosstools-4.4.1.x; git push origin jbosstools-4.4.1.x

----

Once the above conditions have been met, you can proceed to the next steps.

== Disable jobs

To prevent accidentally rebuilding something while you're copying it away, make sure that all the stable branch jobs (4.4.neon, 10.0.neon) are disabled. These include all product, composite and aggregate jobs:

[source,bash]
----
# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

stream_jbt=master # or 4.4.neon
stream_ds=master # or 10.0.neon
for j in jbosstools-build.parent_${stream_jbt} jbosstoolstargetplatforms-matrix jbosstools-buildflow_${stream_jbt} jbosstools-composite-install_${stream_jbt} jbosstools-browsersim-standalone_${stream_jbt} jbosstools-build-sites.aggregate.site_${stream_jbt} jbosstools-build-sites.aggregate.coretests-site_${stream_jbt} jbosstools-centraltarget_${stream_jbt} jbosstools-build-sites.aggregate.child-sites_${stream_jbt} devstudio.product_${stream_ds} devstudio.versionwatch_${stream_ds} jbosstools-install-p2director.install-tests.matrix_${stream_jbt} jbosstools-install-grinder.install-tests.matrix_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable && echo -n ".D"
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/lastBuild/toggleLogKeep && echo -n ".K"
done
echo ""

----

== Update Discovery Sites and URLs

[[update-discovery-urls]]
Update the *stable branch* (or master) discovery job ( https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-discovery_4.4.neon/configure (or jbosstools-discovery_master)) to use the correct source URLs and versions +


Then respin the job:

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

versionWithRespin_jbt=4.4.2.AM3 # a, b, c... (not SNAPSHOT!)
versionWithRespin_ds=10.2.0.AM3
stream_jbt=master # or 4.4.neon
stream_ds=master # or 10.0.neon
TARGET_PLATFORM_VERSION_MAX=4.61.0.AM2-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.61.0.AM1-SNAPSHOT
for j in jbosstools-discovery_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
  curl -k -u ${userpass} --data "buildType=staging&versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}&\
TARGET_PLATFORM_VERSION_MAX=${TARGET_PLATFORM_VERSION_MAX}&TARGET_PLATFORM_CENTRAL_MAX=${TARGET_PLATFORM_CENTRAL_MAX}" \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/buildWithParameters && echo -n ".B"
  sleep 15s
  # then disable the job
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable && echo -n ".D"
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/lastBuild/toggleLogKeep && echo -n ".K"
done

----


== Download the latest Eclipse

You'll need this later for smoke testing. Start fetching it now to save time later.

[source,bash]
----

cd ~/tmp; wget http://download.eclipse.org/technology/epp/downloads/release/neon/1a/eclipse-jee-neon-1a-linux-gtk-x86_64.tar.gz &
# or
cd ~/tmp; wget https://hudson.eclipse.org/packaging/job/neon.epp-tycho-build/437/artifact/org.eclipse.epp.packages/archive/20160913-0900_eclipse-jee-neon-1-linux.gtk.x86_64.tar.gz &

----

== Stage to download.jboss.org

=== Copy & rename builds & update sites from "snapshots" to "staging"

Here is a job that performs the copy (& rename) from /snapshots/ to /staging/:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_master

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

stream_jbt=master # or 4.4.neon
stream_ds=master # or 10.0.neon
versionWithRespin_jbt=4.4.2.AM3
versionWithRespin_ds=10.2.0.AM3
TARGET_PLATFORM_VERSION_MAX=4.61.0.AM2-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.61.0.AM1-SNAPSHOT

# TODO migrate this to use jbosstools-build-ci/util/jenkinsPost.sh wrapper
for j in jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_master; do
  curl -k -u ${userpass} --data "stream_jbt=${stream_jbt}&stream_ds=${stream_ds}&\
versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}&\
TARGET_PLATFORM_VERSION_MAX=${TARGET_PLATFORM_VERSION_MAX}&TARGET_PLATFORM_CENTRAL_MAX=${TARGET_PLATFORM_CENTRAL_MAX}" \
    https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/buildWithParameters && echo -n ".B"
  sleep 10s
  google-chrome http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/lastBuild/console &
done

----

If you can't get the job to run because dev01 slave is backlogged with a long queue, look in the job configuration and run the script manually on dev01 itself.

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_master/configure-readonly/

=== Verify builds and update sites correctly pushed

Here's a job that verifies everything is published:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-03-verify-builds-update-sites_master

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

versionWithRespin_jbt=4.4.2.AM3
versionWithRespin_ds=10.2.0.AM3

# TODO migrate this to use jbosstools-build-ci/util/jenkinsPost.sh wrapper
for j in jbosstools-releng-push-to-staging-03-verify-builds-update-sites_master; do
  curl -k -u ${userpass} --data "versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}" \
    https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/buildWithParameters && echo -n ".B"
  sleep 10s
  google-chrome http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/lastBuild/console &
done

----

If you can't get the job to run because dev01 slave is backlogged with a long queue, look in the job configuration and run the script manually on dev01 itself.

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_master/configure-readonly/

=== Cleanup OLD builds

Optional step.

Run this job to move any old builds into an OLD/ folder for later cleanup, or delete them immediately.

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites_master

----

=== Update /staging/updates/ sites and merge in Integration Stack content

Here's a job that verifies everything is updated & merged:

http://wonka.mw.lab.eng.bos.redhat.com/jenkins/view/devstudio/job/jbosstools-releng-push-to-staging-04-update-merge-composites-html_master/

Using the script below, you can trigger the job remotely.

But if you need a login for Jenkins, please contact nboldt@redhat.com or jsightle@redhat.com.

[source,bash]
----

versionWithRespin_jbt=4.4.2.AM3
versionWithRespin_ds=10.2.0.AM3
versionWithRespin_ds_PREV=10.2.0.AM2
earlyaccess_IS=earlyaccess/
version_jbt_IS=4.4.0.Alpha1
version_ds_IS=10.0.0.Alpha1
for j in jbosstools-releng-push-to-staging-04-update-merge-composites-html_master; do
  curl -k --data "token=RELENG&versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}&versionWithRespin_ds_PREV=${versionWithRespin_ds_PREV}\
&earlyaccess_IS=${earlyaccess_IS}&version_jbt_IS=${version_jbt_IS}&version_ds_IS=${version_ds_IS}" \
    http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/${j}/buildWithParameters && echo -n ".B"
  sleep 10s
  google-chrome http://wonka.mw.lab.eng.bos.redhat.com/jenkins/job/${j}/lastBuild/console &
done

----


== Release the latest staging site to ide-config.properties

Check out http://download.jboss.org/jbosstools/configuration/ide-config.properties

Update it so that the links for the latest milestone point to valid URLs. Comment out staging links as required.

[source,bash]
----

# adjust these steps to fit your own path location & git workflow
cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=4.4.2.AM3
versionWithRespin_jbt=4.4.2.AM3 # a, b, c...
versionWithRespin_ds=10.2.0.AM3 # a, b, c...
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # **

git fetch origin master
git checkout FETCH_HEAD

# then edit ide-config.properties
# vim ide-config.properties
st ide-config.properties
# TODO something like this?
# 1. swap  ^(jb.+(4.4.2|10.2.0).AM)(1)= for \12=
# 2. swap ^#(jb.+(4.4.2|10.2.0).AM1=) for \1

# verify these 6 URLs exist
URLs="$(egrep -v "#" ide-config.properties | egrep "${version}|${versionWithRespin_jbt}|${version_ds}|${versionWithRespin_ds}" | sed -e "s#.\+|\([0-9.a-zA-Z]\+\)=\(.\+\)#\2#")"
google-chrome && google-chrome $URLs
for u in $URLs; do echo "$u"; done

# commit the change and push to master
ci "release JBT ${version} (${versionWithRespin_jbt}) to staging: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
# use filemgmt.jboss.org IP instead of 10.5.105.197 because it's 3x faster!
TOOLS=tools@10.5.105.197:/downloads_htdocs/tools
RSYNC="rsync -aPrz --rsh=ssh --protocol=28"
${RSYNC} ide-config.properties $TOOLS/configuration/ide-config.properties

popd

----

== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Abridged category from

http://download.jboss.org/jbosstools/neon/staging/updates/

3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again


== Enable jobs

You will need to re-enable the jobs once the bits are staged, so that CI builds can continue.

If the next build WILL be a respin, you need to simply:

* re-enable 15 jobs that were disabled above. If you committed a change to jbdevstudio-ci, you can simply revert that commit to re-enable the jobs!

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

stream_jbt=master # or 4.4.neon
stream_ds=master # or 10.0.neon
for j in jbosstools-build.parent_${stream_jbt} jbosstoolstargetplatforms-matrix jbosstools-buildflow_${stream_jbt} jbosstools-composite-install_${stream_jbt} jbosstools-browsersim-standalone_${stream_jbt} jbosstools-build-sites.aggregate.site_${stream_jbt} jbosstools-build-sites.aggregate.coretests-site_${stream_jbt} jbosstools-centraltarget_${stream_jbt} jbosstools-build-sites.aggregate.child-sites_${stream_jbt} devstudio.product_${stream_ds} devstudio.versionwatch_${stream_ds} jbosstools-install-p2director.install-tests.matrix_${stream_jbt} jbosstools-install-grinder.install-tests.matrix_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
done
echo ""
for j in jbosstools-discovery_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
done

----

TODO: Important: if you switched the _master jobs to run from origin/jbosstools-4.4.x or some other branch, make sure that the jobs are once again building from the correct branch.

If the next build will NOT be a respin, you will also need to ALSO make these changes to jobs, and upversion/release artifacts such as releng scripts or target platforms if you haven't done so already:

* set correct github branch, eg., switch from 4.4.2.AM3x to 4.4.x
* upversion dependencies, eg., releng scripts move from version CR1 to CR1 (if that's been released)
* upversion target platforms / Central version (if those have been released)


== Notify the team (send 1 email)

Run this build:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-releng-push-to-staging-07-notification-emails_master

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

versionWithRespin_jbt=4.4.2.AM3
versionWithRespin_ds=10.2.0.AM3
TARGET_PLATFORM_VERSION_MIN=4.60.2.AM2-SNAPSHOT
TARGET_PLATFORM_VERSION_MAX=4.61.0.AM2-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.61.0.AM1-SNAPSHOT
respinSuffix=""

for j in jbosstools-releng-push-to-staging-07-notification-emails_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n ".E"
  curl -k -u ${userpass} --data "versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}&\
TARGET_PLATFORM_VERSION_MIN=${TARGET_PLATFORM_VERSION_MIN}&\
TARGET_PLATFORM_VERSION_MAX=${TARGET_PLATFORM_VERSION_MAX}&\
TARGET_PLATFORM_CENTRAL_MAX=${TARGET_PLATFORM_CENTRAL_MAX}" \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/buildWithParameters && echo -n ".B"
  sleep 15s
  # then disable the job
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable && echo -n ".D"
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/lastBuild/toggleLogKeep && echo -n ".K"
done

----

== Disable staging jobs

You will need to disable the jobs once the bits are staged, so that they won't run accidentally.

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

stream_jbt=master # or 4.4.neon
for j in jbosstools-releng-push-to-staging-07-notification-emails_${stream_jbt} \
jbosstools-releng-push-to-staging-03-verify-builds-update-sites_${stream_jbt} \
jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_${stream_jbt} \
jbosstools-releng-push-to-staging-01-check-versions-branches-root-poms_${stream_jbt} \
jbosstools-releng-push-to-staging-buildflow_${stream_jbt}; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable && echo -n ".D"
done

----
