= Pre-Staging steps

Before beginning a stage at the end of a sprint, a number of things need to be done:

* Send reminder note to jbosstools-dev@lists.jboss.org of upcoming target platform freeze
* Send reminder note to jbosstools-dev@lists.jboss.org of upcoming code freeze (last Wed of sprint)
* Confirm latest Integration Stack (IS) release & URLs
* Clone jbosstools-build-ci repo
* Create New & Noteworthy JIRAs (last Wed of sprint)


== Send reminder note to jbosstools-dev@lists.jboss.org of upcoming target platform freeze & code freeze

1. If there have been significant changes to target platforms this sprint, on the Monday prior to the last Wednesday of the sprint, send a note to jbosstools-dev@lists.jboss.org reminding people of these changes and calling for any last minute updates that might be needed to be done to the TARGET PLATFORMS before code freeze. Changes must be committed, built, and live by EOD Tuesday, one day before code freeze.

This will also serve as a reminder of the upcoming CODE FREEZE on the last Wednesday of the sprint.

2. For GA releases, the target plaform must also be link:Nexus_Release.adoc[released to Nexus].


== Confirm latest Integration Stack (IS) release & URLs

Contact Paul Leacu (pleacu@redhat.com) to ask what the latest IS releases are (4.4.x, 10.x) and the URLs to use when link:Merge_IS_Discovery.adoc[merging this content] into the Central Discovery sites.


== Clone jbosstools-build-ci repo

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ ! -d jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout jbosstools-4.4.x
chmod +x -R */*.sh */*/*.sh

----


== Creating New & Noteworthy JIRAs

Configure, then run this job: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jbosstools-releng/job/jbosstools-releng-push-to-staging-00-new-and-noteworthy-jiras/

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_jbt=4.4.4.AM7
versionWithRespin_ds=10.4.0.AM7

ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-00-new-and-noteworthy-jiras; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----
Or, you can run this script:

[source,bash]
----

python /tmp/jbt.github/jbosstools-build-ci/util/createnewandnoteworthy.py -u usernameJIRA -p passwordJIRA -s https://issues.stage.jboss.org \
  -i ${versionWithRespin_jbt} -d ${versionWithRespin_ds}

----

