= Pre-Staging steps

Before beginning a stage at the end of a sprint, a number of things need to be done:

* Send reminder note to jbosstools-dev@lists.jboss.org of upcoming target platform freeze

* Send reminder note to jbosstools-dev@lists.jboss.org of upcoming code freeze (last Wed of sprint)

* Confirm latest Integration Stack (IS) release & URLs

* Clone jbosstools-build-ci repo


== Send reminder note to jbosstools-dev@lists.jboss.org of upcoming target platform freeze & code freeze

1. If there have been significant changes to target platforms this sprint, on the Monday prior to the last Wednesday of the sprint, send a note to jbosstools-dev@lists.jboss.org reminding people of these changes and calling for any last minute updates that might be needed to be done to the TARGET PLATFORMS before code freeze. Changes must be committed, built, and live by EOD Tuesday, one day before code freeze.

This will also serve as a reminder of the upcoming CODE FREEZE on the last Wednesday of the sprint.

2. For GA releases, the target plaform must also be link:Nexus_Release.adoc[released to Nexus].


== Confirm latest Integration Stack (IS) release & URLs

Contact Paul Leacu (pleacu@redhat.com) to ask what the latest IS releases are (4.4.x, 10.x) and the URLs to use when link:Merge_IS_Discovery.adoc[merging this content] into the Central Discovery sites.


== Clone jbosstools-build-ci repo

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ ! -d jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout jbosstools-4.4.x
chmod +x -R */*.sh */*/*.sh

----
