
= JBoss Tools Integration Stack Release Process

== Introduction

This document describes the task of updating, building and publishing the community and production versions of the JBoss Tools Integration Stack.

The Integration Stack is an aggregation of Eclipse features and plugins comprised of JBoss tooling in support of Data Virtualization, BRMS/BPMS, Fuse ServiceWorks, Fuse ActiveMQ and legacy SOA 5.x development.  It is formed by a Maven project which produces an Eclipse p2 update site, a Mylyn discovery update mechanism augmenting JBoss Central and an aggregation of associated component target dependencies and JBoss Core tooling target dependencies.  The target dependencies take the form of generated .target files (tycho mojo) and a target p2 update repository.

Click https://mojo.redhat.com/docs/DOC-946223 for a quick overview/ presentation of the Integration Stack.

[NOTE]
----
Note:  Many steps require privileged access to JBoss servers, Developer Studio servers or nexus.
----

== Update Process

The Integration Stack project is open source (naturally) and can be found here: https://github.com/jbosstools/jbosstools-integration-stack

Typical updates most frequently occur to the aggregate site composite files.  These would change if a new version of Teiid Designer needed to be included for example.

https://github.com/jbosstools/jbosstools-integration-stack/blob/master/jbosstools/site/compositeArtifacts.xml
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/jbosstools/site/compositeContent.xml

These files define the IS component update sites.  Note that with rare exceptions these component update sites must be in .Final form for a .Final/.GA IS build.

The second most frequent update occurs in the tycho mojo target platform definition files:

https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/integration-stack-base.target
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/core-base.target
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/community.target

[NOTE]
----
Note: The Github source branch jbosstools-4.1.x should be used for JBTIS 4.1.x (Kepler) builds.
----

== Build/ Publish Process

The build/ publish process is a sequential set of tasks that must be executed in order.  The order is as follows:

    JBTIS target platform
    JBTIS aggregate/ discovery
    JBTIS Publish
    JBDSIS target platform
    JBDSIS aggregate discovery
    JBDSIS Publish.

Other fun facts:

* Not all tasks must be executed for a release.  For example, if there's no change to the target platform the aggregate build may use the existing one.
* It's possible to release JBTIS independently however JBDSIS must release from an existing JBTIS.
* The component POMs may or may not pick up the latest JBTIS TP.  We recommend that they do but it is not required.

There exists Jenkins build jobs for each Eclipse-based revision of JBDS (Kepler, Luna, etc).  Examples will be referenced explicitly in the build procedure instructions.

=== Community JBTIS Build

There is a community version of the target platform, p2 aggregate update site and discovery update mechanism.  The target platform and p2 site are required for the production build.

==== JBTIS Target Platform Build/ Release Process

The JBoss Tools Integration Stack Target Platform project creates two target files:

* An aggregate of the JBoss Tools Core target dependencies + Integration Stack base target dependencies (base).

e.g.  http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.1.8.Final/aggregate-base.target

* An aggregate of the JBoss Tools Core target dependencies + Integration Stack base target dependencies + any other community dependencies (full).

e.g.  http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.1.8.Final/aggregate-full.target

The JBoss Tools Integration Stack Target Platform project also creates one repository:

e.g.  http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.0.Alpha4/REPO/

The integration-stack base target dependencies are deployed to the JBoss nexus releases repository for use by the integration stack component projects.

e.g.  https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/4.1.8.Final/

Target artifacts local to the IS:

* integration-stack-base.target - integration stack component required dependencies
* core.base.target - JBoss tools core required dependencies
* community.target - dependencies specific to the community (not required for JBDS)

Target artifacts drawn from org.jboss.tools.targetplatforms:

* jbosstools-unified....target

Ultimately the target platform dependencies are merged like this:

[source,bash]
-------------------
 integration-stack specific target dependencies: integration-stack-base.target
 JBoss Tools core target dependencies:           + core-base.target
 JBoss Tools unified core target dependencies:   + jbosstools-unified....target 
                                                   --------------------
                                                   aggregate-base.target
 community-specific target dependencies:         + community.target             
                                                   --------------------
                                                   aggregate-full.target
-------------------

If an IS component causes a new target dependency, this JBTIS TP build procedure must be executed.  The result is a new JBTIS TP in nexus.  That must then be used by the requesting component POM which will produce a new component update site.  That update site must then be referenced by the JBTIS Aggregate/Discovery procedure.  For example, if Teiid has a new target platform dependency it would be necessary to first build JBTIS TP, then rebuild Teiid, then build JBTIS - modifying the aggregate composites to reference the new Teiid update site.

Git ref: https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform

==== JBTIS Target Platform Dependency Update:

As an example, the JBDS core target dependencies need to be updated from 4.2.0.Beta2b to 4.2.0.Beta2c.  Perform the following steps:

[source,bash]
----
# Clone the jbosstools-integration-stack locally.  
# Modify jbosstools-integration-stack/target-platform/core-base.target  
# Clone or otherwise retrieve the verifyTarget.sh bash scriipt from  
https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/verifyTarget.sh  
  
./verifyTarget.sh -x -b ~/git-clone/jbosstools-integration-stack/target-platform -p target-platform  
     -z ~/install/eclipse-jee-luna-M7-linux-gtk-x86_64.tar.gz
----

Git diff the core-base.target file.  Commit and issue a PR.

==== Jenkins JBTIS Target Platform Build:

As an example, lets build JBTIS target platform 4.1.8.Final for Kepler using the 4.1.x specific Jenkins job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-target-platform-4.1.x/

* Tag a label onto the GIT target platform sources associated with any target platform build committed to nexus.
* Label the Jenkins build and set 'keep forever".

The staging checkbox simply controls whether the generated artifacts are published to the staging area.

==== Publish the Community IS Target Platform Components

Given a successful build from the previous step, make the JBTIS TP public.  This example uses a 4.2.0 Alpha-based target platform for Luna.

[source,bash]
----
# Copy the TP locally from staging  
cd ~/temp; mkdir -p tp; cd tp  
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-target-platform/4.2.0.Alpha4 .  
 
# Now copy the TP files onto jbosstools   
scp -r 4.2.0.Alpha4 tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/ 
----

Update the jbosstools target platform composites.  Remember to update the timestamps (vim :call ReplaceTimestamp()):
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/targetplatforms/jbtistarget/luna/compositeArtifacts.xml
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/targetplatforms/jbtistarget/luna/compositeContents.xml
Once the PR has been issued and merged to https://github.com/jbosstools/jbosstools-download.jboss.org, push the changes to the download.jboss.org server. (Applying the PR is only the first half of getting these live.)

[source,bash]
----
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/targetplatforms/jbtistarget/luna  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/luna  
put compositeArtifacts.xml  
put compositeContent.xml  
bye 
----

Verify:

http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.0.Alpha4/
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/luna/

==== Promote the Published JBTIS Target Platform Components to Nexus 

The JBTIS target platform is now built and published but we're still not done.  It must finally be promoted to nexus.  Be cautious here - once created there's no easy way to remove it.

[source,bash]
----
# First build and deploy to staging  
git clone -o origin https://github.com/jbosstools/jbosstools-integration-stack.git ./jbosstools-integration-stack  
cd ./jbosstools-integration-stack/target-platform  
 
# Edit pom.xml - change n.n.n-SNAPSHOT to n.n.n.Final  
# Clear out your local maven repository and build/ deploy  
rm -rf ~/.m2/repository  
mvn -U -s ~/.m2/settings-staging.xml -DuseReleaseProfile=true -Pjboss-release clean deploy  
 
# if you get an Error 401 - check your ~/.m2/settings-staging.xml  Make sure your server passwords are encrypted correctly.  
 
# Now promote from staging to release nexus (log into sonatype nexus with your favourite browser)  
 https://repository.jboss.org/nexus/index.html#stagingRepositories  
 
# Look for jboss_releases_staging_profile-nnnn - the Maven deploy from the previous step 
# should have populated it.  
# Check the box to the left  
# Select the 'Close' button to finalize for release or select the 'Drop' button to delete the repo  
# Once the close has completed - click 'Refresh'
----

*This completes the JBTIS Target Platform build/ release process.*

=== JBTIS Aggregate/ Discovery Build/ Release Process
This section describes the process of building and releasing the actual JBTIS aggregate p2 update site and the JBoss Central update site.  The project architecture is as follows:

[source,bash]
----
 jbosstools
 JBTIS - Community side.  Mylyn discovery and Equinox P2 update site generation.

     discovery
     JBTIS JBoss Tools Central Integration Stack discovery update generation.

        generation
        Create the Mylyn directory XML.

        org.jboss.tools.central.discovery.integration-stack
        Create the JBoss Tools central discovery update plugin.  Specifies connector 
        descriptors, installation units, etc.

     site
     JBTIS composite artifacts, content and P2 update categories.
----

Git ref: https://github.com/jbosstools/jbosstools-integration-stack/tree/master/jbosstools

==== Jenkins JBTIS Aggregate Discovery Build

As an example, lets build JBTIS 4.1.5.CR1 for Kepler using the 4.1.x specific Jenkins job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-disc-4.1.x/

The build type is selectable.  Use "integration" for builds that are better than continuous integration/ nightly but not quite milestone, "development" for milestones (i.e. beta and CR builds) and "stable" for final release builds.  Also note the upstream jbosstools site references.

Fun Facts:

I started this build 6 hours ago - what's going on?

Lets see with the Jenkins stats view:  https://jenkins.mw.lab.eng.bos.redhat.com/hudson/

* Tag a label onto the GIT sources associated with any build committed to a milestone or release.  It is a required parameter to the configuration.  (i.e. JBTIS-4.1.5.Final)

* Label the Jenkins build and set 'keep forever".

==== Publish the Community IS Components

There exists a separate Jenkins job to move the build artifacts out of the JBoss tools staging area into a JBoss tools update area.

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish-4.1.x/

Match the build type to the aggregate build type from the previous section.  Match the target folder to the aggregate build version string.

Verify - note that the offline zip version is also created:

http://download.jboss.org/jbosstools/updates/development/kepler/integration-stack/aggregate/4.1.5.CR1/
http://download.jboss.org/jbosstools/updates/development/kepler/integration-stack/aggregate/jbosstools-integration-stack-aggregate-4.1.5.CR1.zip

==== Publish and Push the JBTIS Aggregate p2 Update Site

In this example we'll use the development 4.1.5.CR1 build from the previous step.  Clone jbosstools-download.jboss.org and update the composites in both the integration-stack directory and integration-stack/aggregate to reflect the new version and then update the timestamps.

[source,bash]
----
# Clone https://github.com/jbosstools/jbosstools-download.jboss.org  
# Edit composite*.xml - update version and also change timestamp.  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/kepler/integration-stack/  
vi compositeArtifacts.xml   
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
      
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/kepler/integration-stack/aggregate  
vi compositeArtifacts.xml   
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
----

Commit and issue a PR.  Once the PR is merged, push the changes to the JBoss tools server:

[source,bash]
----
# Push the development changes to the server  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/kepler/integration-stack/  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/kepler/integration-stack/  
put compositeArtifacts.xml  
put compositeContent.xml  
bye  
  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/kepler/integration-stack/aggregate  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/kepler/integration-stack/aggregate  
put compositeArtifacts.xml  
put compositeContent.xml  
bye 
----

[NOTE]
----
Note: If you updated a stable version, update the development version with the same bits along with the development composites.  That way development is never behind stable.  e.g.
----

[source,bash]
----
cd ~/temp; mkdir -p updt; cd updt  
      
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/kepler/integration-stack/aggregate/4.1.5.Final .  
scp -r 4.1.5.Final  tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/kepler/integration-stack/aggregate/  
----

Verify (development):

http://download.jboss.org/jbosstools/updates/development/kepler/integration-stack/
http://download.jboss.org/jbosstools/updates/development/kepler/integration-stack/aggregate


Verify (stable):

http://download.jboss.org/jbosstools/updates/stable/kepler/integration-stack/
http://download.jboss.org/jbosstools/updates/stable/kepler/integration-stack/aggregate

==== Publish the Community IS Sources

This is the JBTIS community project sources only.  Individual components manage their own source availability.  In this example we're publishing the 4.1.5.Final JBTIS project sources (zip and MD5).

[source,bash]
----
mkdir -p ~/temp/release;  cd ~/temp/release  
  
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc/all/JBTIS-aggregate-disc-Sources-SNAPSHOT.zip .  

rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc/all/JBTIS-aggregate-disc-Sources-SNAPSHOT.zip.MD5 .  

mv JBTIS-aggregate-disc-Sources-SNAPSHOT.zip jbosstools-integration-stack-sources-4.1.5.Final.zip  

mv JBTIS-aggregate-disc-Sources-SNAPSHOT.zip.MD5 jbosstools-integration-stack-sources-4.1.5.Final.zip.MD5  

rsync -arzq --protocol=28 jbosstools-integration-stack-sources-4.1.5.Final.zip tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/kepler/integration-stack/aggregate  

rsync -arzq --protocol=28 jbosstools-integration-stack-sources-4.1.5.Final.zip.MD5 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/kepler/integration-stack/aggregate 
----

==== Test Eclipse p2 Update

Install JBossTools from Eclipse Marketplace (i.e. JBossTools 4.1.2).

[source,bash]
----
# Start jbdevstudio or eclipse-with-jbosstools, then:  
Help > Install New Software...  
Add...  
 - use this for 'Location:'  
http://download.jboss.org/jbosstools/updates/development/kepler/integration-stack/aggregate/4.1.5.CR1/
----

==== Test JBTIS JBoss Central Discovery Update

[source,bash]
----
# Using JBDS 7.1.1.GA  
./jbdevstudio -vmargs -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.1.5.CR1/jbosstools-integration-stack-directory.xml \  
   -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.1.5.CR1  
     
# Using Eclipse Kepler, install 'JBoss Tools 4.1.2.Final' from Marketplace:  
./eclipse -vmargs -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.1.5.CR1/jbosstools-integration-stack-directory.xml \  
   -Djboss.discovery.site.url=p://download.jboss.org/jbosstools/discovery/development/integration-stack/4.1.5.CR1  
----

==== Publish and Push the JBTIS JBoss Central Discovery Jar

The JBoss Central discovery jar is actually committed to the discovery download site.  Update the directory XML as well.

[source,bash]
----
mkdir -p ~/temp/disc;  cd ~/temp/disc  
wget http://download.jboss.org/jbosstools/discovery/stable/integration-stack/4.1.5.Final/org.jboss.tools.central.discovery.integration-stack_4.1.5.Final-v20140409-0146-B11.jar  
 
# clone jbosstools-download.jboss.org  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/stable/kepler/plugins  
cp ~/temp/disc/org.jboss.tools.central.discovery.integration-stack_4.1.5.Final-v20140409-0146-B11.jar .  
 
# edit ../jbosstools-directory.xml: update org.jboss.tools.central.discovery.integration-stack_4.1.5.Final-v20140409-0146-B11.jar 
----

[NOTE]
----
Note: If committing a stable discovery jar/ directory XML - repeat the steps into the development directory (e.g.):

    /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/kepler/plugins

Commit and issue a PR to http://download.jboss.org/jbosstools.  Once the PR has been merged, manually push the updated jar and jbosstools-directory.xml onto the JBoss server.
----

[source,bash]
----
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/stable/kepler  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/kepler  
put jbosstools-directory.xml  
bye  

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/stable/kepler/plugins  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/kepler/plugins  
put org.jboss.tools.central.discovery.integration-stack_4.1.5.Final-v20140409-0146-B11.jar  
bye 
----

==== Generate Release Notes

Start by generating a release notes report from JBTIS JIRA:

[source,bash]
----
https://issues.jboss.org/browse/JBTIS  
select Summary  
select Release Notes Report  
ctrl-select versions, Issue type: All  
select Next 
----

Edit the resulting report, merging in the release notes fragments from the updated components.   Use the existing release note format (JBDS not JBT).

=== JBTIS Aggregate/ Discovery Website Update

Clone and modify any jbosstools website component features ascii doc files.  Also modify 'whatsnew' and download links.

Ref Git: https://github.com/jbosstools/jbosstools-website

Ref: http://tools.jboss.org/features/

Ref: http://tools.jboss.org/whatsnew/jbosstools/4.1.2.Final.html

Ref: http://tools.jboss.org/downloads/jbosstools_is/kepler

Build and verify the website before committing and issuing a PR.

Ref: https://github.com/jbosstools/jbosstools-website/blob/master/readme.adoc

Update products.yml:

[source,bash]
----
# Clone jbosstools-website  
# edit /home/pleacu/git-clone/jbosstools-website/_config/products.yml  
# Update supported_devstudio_is_version, devstudio_is, supported_jbt_is_version and jbt_is.  
----

Update JBoss Tools blog:

[source,bash]
----
# Clone jbosstools-website  
cd /home/pleacu/git-clone/jbosstools-website/blog  
cp 2014-04-14-JBTIS-4.1.5.Final.adoc 2014-??-??-JBTIS-4.?.?.Final.adoc 
----

*This completes the JBTIS aggregate/ discovery build/ release process.*

== Production JBDSIS Build

The production JBDSIS build draws its content from the JBTIS build.  Consequently, the content of the production build is always less than or equal to the community build.  JBDSIS does not have its own composite files for p2 update site artifacts.

=== JBDSIS Target Platform

The JBTIS target platform defines the target platform dependencies for both the community and production IS.  A production target platform is created from a copy of the community target platform.

In this example the 7.0.1.GA target platform (Kepler) repository is created.  First update the common update release area.

[source,bash]
----
ssh wallace  
cd /mnt/devstudio/updates/7.0.0  
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/4.1.8.Final .  
# Inspect  
mv 4.1.8.Final 7.0.1.GA.jbds-is-target-platform 
----

URL:
https://devstudio.jboss.com/updates/7.0.0/7.0.1.GA.jbds-is-target-platform

Update the QE test staging area:

[source,bash]
----
ssh dev01.mw.lab.eng.bos.redhat.com  
sudo su - hudson  
cd /qa/services/http/binaries/RHDS/targetplatforms/jbdsistarget/  
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/4.1.8.Final .  
# Inspect  
mv 4.1.8.Final 7.0.1.GA  
----

Verify:

http://www.qa.jboss.com/binaries/RHDS/targetplatforms/jbdsistarget/7.0.1.GA/

*** This completes the JBDSIS TP build/ release process.

=== JBDSIS Aggregate/ Discovery Build/ Release Process

This section describes the process of building and releasing the actual JBDSIS aggregate p2 update site and the JBoss Central update site.  The project architecture is as follows:
 
[source,bash]
----
 devstudio
 JBDSIS - Production side.  Mylyn discovery and Equinox P2 update site generation.

    discovery
    JBDSIS JBoss Tools Central Integration Stack discovery update generation.

	com.jboss.jbds.central.discovery.integration-stack
	Create the JBoss Tools central discovery update plugin.  Specifies connector descriptors, 
        installation units, etc.

	generation
	Create the Mylyn directory XML.

    site
    JBDSIS P2 update categories.  Composite content drawn from JBTIS.
----

Git ref: https://github.com/jbosstools/jbosstools-integration-stack/tree/master/devstudio
 
==== Jenkins JBDSIS Aggregate Discovery Build:

As an example, lets build JBDSIS 7.0.2.CR1 for Kepler using the 4.1.x specific Jenkins job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBDSIS-aggregate-disc-7.0.x

Note the community JBTIS aggregate composite site from which this build draws its content.  As with the JBTIS build, the build type is selectable - make sure you select the correct parameter there as it affects the site index.html and the discovery site.

* Tag a label onto the GIT sources associated with any build committed to a milestone or release.  It is a required parameter to the configuration.  (i.e. JBDSIS-7.0.2.GA)
* Label the Jenkins build and set 'keep forever".

==== Publish the Production IS Components

There exists a separate Jenkins job to move the build artifacts out of the JBoss tools staging area into a JBoss tools update area.  In this example the JBDSIS 7.0.2.CR2 development release is published.

Match the build type to the aggregate build type from the previous section.  Match the target folder to the aggregate build version string.

Verify:

http://www.qa.jboss.com/binaries/RHDS/updates/development/kepler/integration-stack/aggregate/7.0.2.CR2/
 
==== Publish and Push the JBTIS Aggregate p2 Update Site

In this example we'll use the development 7.0.2.CR2 build from the previous step.    Update the production aggregate Eclipse p2 repository as well as the offline .zip file

[source,bash]
----
ssh wallace.redhat.com  
rsync -aPrz --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/kepler/integration-stack/aggregate/7.0.2.CR2/*   
     /mnt/devstudio/updates/7.0.0/7.0.2.CR2.jbds-is/  
     
# Copy the p2 update site zip (devstudio-integration-stack-aggregate-7.0.2.CR2-SNAPSHOT.zip) to the devstudio update area:  
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/kepler/integration-stack/aggregate/devstudio-integration-stack-aggregate-7.0.2.CR2.zip   

/mnt/devstudio/updates/7.0.0/jbdevstudio-integration-stack-updatesite-7.0.2.CR2.zip
----

Note that  a stable build will be retrieved from a corresponding stable path.  If you update stable make sure to update development as well.

Clone jbdevstudio-website and update the composites in both the integration-stack directory and integration-stack/aggregate to reflect the new version and then update the timestamps.

Git ref: https://github.com/jbdevstudio/jbdevstudio-website

[NOTE]
----
Note: Don't forget to update index.html!
----

[source,bash]
----
# Update https://devstudio.jboss.com/updates/7.0-development/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/7.0-development/integration-stack  
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!
----

Commit and issue a PR.  Once the PR is merged, push the changes to the devstudio tools server:

[source,bash]
----
cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/updates/7.0-development/integration-stack  
sftp wallace.redhat.com:/mnt/devstudio/updates/7.0-development/integration-stack  
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye
----

Update the QE test staging area:

[source,bash]
----
ssh dev01.mw.lab.eng.bos.redhat.com  
sudo su - hudson  
cp -r /qa/services/http/binaries/RHDS/updates/development/kepler/integration-stack/aggregate/7.0.2.CR2  
     /qa/services/http/binaries/RHDS/builds/staging/jbdsis-7.0.2-updatesite/ 
----

[NOTE]
----
Note: If you updated a stable version, update the development version with the same bits.  That way development is never behind stable.
----

==== Test Eclipse p2 Update

[source,bash]
----
Start jbdevstudio or eclipse-with-jbds, then:  
    Help > Install New Software...  
    Add...  
    - use this for 'Location:'  
    https://devstudio.jboss.com/updates/7.0-development/integration-stack/  
----

==== Test JBDSIS JBoss Central Discovery Update

[source,bash]
----
./jbdevstudio -vmargs -Djboss.discovery.directory.url=http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/7.0.2.CR2/devstudio-integration-stack-directory.xml  
      -Djboss.discovery.site.url=http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/7.0.2.CR2
----

==== Test JBDSIS Offline Install

To install JBDSIS in a completely offline way, you need three zips or jars to act as update sites:

* JBDS target platform zip
* JBDS installer or update site zip
* JBDS IS update site zip

Retrieve the offline JBDS zips:

https://devstudio.jboss.com/updates/7.0/#offline

If you dont' already have installFromTarget.sh, see this:

https://gist.github.com/nickboldt/e899f4e22a0654af667e

Install JBDS into ~/offline, then:

[source,bash]
----
~/bin/installFromTarget.sh -ECLIPSE ~/offline/studio/ -INSTALL_PLAN  
'jar:file:///home/pleacu/install/jbdevstudio-integration-stack-updatesite-7.0.2.CR1.zip!/,jar:file:///home/pleacu/install/jbdevstudio-updatesite-7.1.1.GA-v20140314-2145-B688.zip!/,jar:file:///home/pleacu/install/jbdevstudiotarget-4.32.0.Final.zip!/'  
----

==== Publish and Push the JBDSIS JBoss Central Discovery Jar

 
[NOTE]
----
Note: Only perform this task with a .GA JBDSIS
----

[source,bash]
----
# Copy the JBDSIS central jar into position  
 cd ~/temp/disc  
 wget http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/7.0.1.GA/com.jboss.jbds.central.discovery.integration-stack_7.0.1.GA-v20140409-1834-B7.jar  
 sftp wallace.redhat.com:/mnt/devstudio/updates/7.0/discovery  
 put com.jboss.jbds.central.discovery.integration-stack_7.0.1.GA-v20140409-1834-B7.jar  
 bye 
----

Clone jbdevstudio-website and update the JBDSIS JBoss Central JAR file and devstudio-directory discovery XML file.  Update the composites and index.html in the 7.0/integration-stack, 7.0/central/integration-stack and 7.0 discovery directory then push the files to the devstudio server.

Git ref: https://github.com/jbdevstudio/jbdevstudio-website

[source,bash]
----
# Go live!  
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/7.0/discovery  
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack_7.0.2.GA-v20140409-1834-B7.jar .  
cd ..  

# edit devstudio-directory.xml - add:  
<entry url="discovery/com.jboss.jbds.central.discovery.integration-stack_7.0.1.GA-v20140409-1834-B7.jar" permitCategories="true"/>  
      
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/7.0/integration-stack  

# update compositeArtifacts.xml, compositeContent.xml, index.html - versions and timestamps  
cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/updates/7.0/integration-stack  
sftp wallace.redhat.com:/mnt/devstudio/updates/7.0/integration-stack  
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml  
   sftp> put index.html  
      
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/7.0/central/integration-stack  
sftp wallace.redhat.com:/mnt/devstudio/updates/7.0/central/integration-stack/  
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml  
   sftp> put index.html  
      
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/7.0/discovery  
sftp wallace.redhat.com:/mnt/devstudio/updates/7.0/discovery  
   sftp> put com.jboss.jbds.central.discovery.integration-stack_7.0.1.GA-v20140409-1834-B7.jar  
      
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/7.0  
sftp wallace.redhat.com:/mnt/devstudio/updates/7.0  
   sftp> put devstudio-directory.xml
----

==== Update the Customer Support Portal

Generate a ticket with engineering services.  Ref: https://engineering.redhat.com/rt/Ticket/Display.html?id=296645

Update the JBDS site - e.g:

https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=7.1.1

*This completes the JBDSIS aggregate/ discovery build/ release process.*
____
