
= JBoss Tools Integration Stack Release Process

== Introduction
[.lead]

This document describes the task of updating, building and publishing the community and production versions of the *JBoss Tools Integration Stack*.

The _Integration Stack_ (IS) is an aggregation of Eclipse features and plugins comprised of JBoss Tooling. These tools are in support of Data Virtualization, BRMS/BPMS, Fuse Tooling and legacy SOA 5.x development. 
In terms of build artifacts, the _Integration Stack_ is:

* an aggregation of several projects which produce released (or Early Access) update site & zip, 
* a discovery site which exposes that content from within JBoss Central, and 
* some target platform dependencies, also available as an update site & zip. The target platforms are also available as +.target files+, published to JBoss Nexus.

Click https://mojo.redhat.com/docs/DOC-946223 for a quick overview/ presentation of the Integration Stack.

[NOTE]
----
Note:  Many steps in this release process require privileged access to JBoss servers, Developer Studio servers and the JBoss Nexus servers.
----

== Update Process
[.lead]

The Integration Stack project is open source (naturally) and can be found here: 

https://github.com/jbosstools/jbosstools-integration-stack

Typical updates most frequently occur to the aggregate site composite files.  These would change if a new version of Teiid Designer needed to be included for example.

https://github.com/jbosstools/jbosstools-integration-stack/blob/master/jbosstools/site-final/compositeArtifacts.xml
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/jbosstools/site-final/compositeContent.xml

These files define the IS component update sites.  Note that with rare exceptions these component update sites must be in .Final form for a .Final/.GA IS build.

The second most frequent update occurs in the tycho mojo target platform definition files:

https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/integration-stack-base.target
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/integration-stack-base-ea.target
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/core-base.target
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/community.target

[NOTE]
----
Note: Github source branch master should be used for JBTIS 4.3.x (Mars) builds.
      Github source branch jbosstools-4.2.x should be used for JBTIS 4.2.x (Luna) builds.
      Github source branch jbosstools-4.1.x should be used for JBTIS 4.1.x (Kepler) builds.
      
----

== Build/ Publish Process
[.lead]

The build/ publish process is a sequential set of tasks that must be executed in order.  The order is as follows:

* JBTIS target platform       http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-target-platform/
* JBTIS aggregate/ discovery  http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-discovery/ (or -disc)
* JBTIS Publish               http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish/
* JBDSIS target platform
* JBDSIS aggregate discovery  http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBDSIS-aggregate-discovery/ (or -disc)
* JBDSIS Publish              http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBDSIS-aggregate-publish/

Note:

* For previous years' jobs, job name will have a suffix such as -4.1.x or -4.2.x. 
* For 4.2.x and earlier, the discovery job name contains suffix of *disc*, not *discovery*, eg., JBTIS-aggregate-disc-4.2.x.

* If the target platform has not changed since the previous build, aggregation can use the most recent target platform without needing to rebuild it.

* JBTIS can be released while JBDSIS is still kept internal; however, every JBDSIS release should have a matching concurrent JBTIS release). This is the same rule in JBT and JBDS releases.

* It is strongly recommended that ALL integration stack components' POMs build with the latest JBTIS TP. This should be enforced as a requirement for participation in the JBTIS/JBDSIS aggregate to ensure all components use the same compatible dependencies and don't introduce incompatible install-time or run-time requirements.

There exists Jenkins build jobs for each Eclipse-based revision of JBDS (Kepler, Luna, Mars, Neon, etc).  Examples will be referenced explicitly in the build procedure instructions.

=== Community JBTIS Build
[.lead]

There are community versions of the JBTIS target platform, aggregate update sites and discovery update mechanism.  The target platforms and aggregate sites are required for the production build.

==== JBTIS Target Platform Build/ Release Process
[.lead]

The *JBoss Tools Integration Stack Target Platform* project creates four target files:

* An aggregate of the JBoss Tools Core target dependencies and JBoss Tools multiple dependencies + released Integration Stack base target dependencies (base).

[source,bash]
----
   1. released integration-stack specific target dependencies:   integration-stack-base.target
   2. the JBoss Tools core target dependencies:                + core-base.target
   3. the JBoss Tools unified core target dependencies:        + jbosstools-multiple.target
                                                                 -----------------------------
      to generate an aggregate base target dependencies file:    aggregate-base.target
----
e.g.  http://download.jboss.org/jbosstools/builds/staging/JBTIS-target-platform/4.2.8.Final/aggregate-base.target

* An aggregate of the JBoss Tools Core target dependencies and JBoss Tools multiple dependencies + early access Integration Stack base target dependencies (base-ea).

[source,bash]
----
   1. released integration-stack specific target dependencies:   integration-stack-base-ea.target
   2. the JBoss Tools core target dependencies:                + core-base.target
   3. the JBoss Tools unified core target dependencies:        + jbosstools-multiple.target
                                                                 --------------------------------
      to generate an aggregate base target dependencies file:    aggregate-base-ea.target
----
e.g.  http://download.jboss.org/jbosstools/builds/staging/JBTIS-target-platform/4.2.8.Final/aggregate-base-ea.target

* An aggregate of the JBoss Tools Core target dependencies + Integration Stack base target dependencies + any other community dependencies (full).

[source,bash]
----
   1. the previously generated aggregate base EA target file:    aggregate-base.target
   2. the community-specific target dependencies:              + community.target
                                                                 ---------------------
      to generate the full community target dependencies file:   aggregate-full.target
----
e.g.  http://download.jboss.org/jbosstools/builds/staging/JBTIS-target-platform/4.2.8.Final/aggregate-full.target

* An aggregate of the JBoss Tools Core target dependencies + early access Integration Stack base target dependencies + any other community dependencies (full-ea).

[source,bash]
----
   1. the previously generated aggregate base EA target file:    aggregate-base-ea.target
   2. the community-specific target dependencies:              + community.target
                                                                 ------------------------
      to generate the full community target dependencies file:   aggregate-full-ea.target
----
e.g.  http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/aggregate-full-ea.target

The JBoss Tools Integration Stack Target Platform project also creates four repositories:

* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/jbtis/REPO/

* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/jbtis/earlyaccess/REPO/

* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/jbdsis/REPO/

* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/jbdsis/earlyaccess/REPO/

The jbdsis repositories are built separately so as to avoid pulling in any community bits.

_The integration-stack tycho target dependency_ +(.target)+ _files are deployed to the JBoss nexus releases repository for use by the integration stack component projects_.  If you are an integration stack component developer or potentially a QE test developer, your maven POM target-platform-configuration should reference one of these as your target-platform artifact.

* https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/4.3.0.Final/

target-platform-4.3.0.Final-base-ea.target  - classifier base-ea
target-platform-4.3.0.Final-base.target	    - classifier base
target-platform-4.3.0.Final-full-ea.target  - classifier full-ea
target-platform-4.3.0.Final-full.target	    - classifier full

Target artifacts drawn from +org.jboss.tools.targetplatforms+:

* *jbosstools-multiple.target*

If an IS component causes a new target dependency, this JBTIS TP build procedure must be executed.  The result is a new JBTIS TP in nexus and new target platform repositories.  That must then be used by the requesting component POM which will produce a new component update site.  That update site must then be referenced by the JBTIS Aggregate/Discovery procedure as well as the component POM.

For example, if Teiid Designer has a new target platform dependency it would be necessary to first build JBTIS TP, then rebuild Teiid Designer, then build JBTIS - modifying the aggregate composites to reference the new Teiid update site.  JBDSIS would need to be built after that...

The following JBoss Tools target platform update process should be followed when updating the JBTIS target platform:

link:https://github.com/jbosstools/jbosstools-devdoc/blob/master/building/target_platforms/target_platforms_updates.adoc[JBoss target platform updates]

Git ref: 

* https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform
* https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/
* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/

==== JBTIS Target Platform Dependency Update:

As an example, the JBDS core target dependencies need to be updated from 4.3.0.Beta2 to 4.3.0.Beta3.  Many if not all of the IUs need to be updated in the core-base.target file.  This update can be performed automatically be performing the following steps:

* Clone the jbosstools-integration-stack locally.
* Modify repository URLs in jbosstools-integration-stack/target-platform/*.target  
* Clone or otherwise retrieve the verifyTarget.sh bash script from  

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/verifyTarget.sh 

* Update component versions based on new repository URLs.
[source,bash]
----
~/bin/verifyTarget.sh -x -b ~/git-clone/jbosstools-integration-stack/target-platform -p target-platform -z ~/install/eclipse-jee-mars-RC2-linux-gtk-x86_64.tar.gz -V 0.23.1
----

* p2 diff the generated Integration Stack released target platforms - i.e.:

[source,bash]
----
p2diff \
 file:///home/pleacu/git-clone/jbosstools-integration-stack.orig/target-platform/target/target-platform.target.repo \
 file:///home/pleacu/git-clone/jbosstools-integration-stack/target-platform/target/target-platform.target.repo

p2diff \
 file:///home/pleacu/git-clone/jbosstools-integration-stack.orig/target-platform/target/target-platform-ea.target.repo \
 file:///home/pleacu/git-clone/jbosstools-integration-stack/target-platform/target/target-platform-ea.target.repo
----

Git diff the core-base.target file.  Commit and issue a PR.

A PR should be sent out for public review.  e.g.

[source,bash]
----
  Greetings -
      A proposal to change the JBTIS target platform is described here:

   https://issues.jboss.org/browse/JBTIS-xxx

   PR:  https://github.com/jbosstools/jbosstools-integration-stack/pull/yyy

   Synopsis:

   1. Pick up the org.eclipse.birt.feature.group for use in Teiid
   2. Update to Luna SR1
      http://download.jboss.org/jbosstools/updates/requirements/luna/201409180900-SR1
   3. Update JBoss Tools core target dependencies to CR1
      http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.CR1-updatesite-core/
      http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.CR1-updatesite-coretests/
   4. Update orbit requirements to 2014
      http://download.jboss.org/jbosstools/updates/requirements/orbit/R20140525021250

   Please respond by COB on Thursday, Sept 25 to the specified Jira if there are any issues.

   Thanks,
         --paull
----

[NOTE]
----
Note:  A non-API-change dependant update (micro-release update) may be done without a full review proposal.
----

==== Jenkins JBTIS Target Platform Build:

As an example, let's build JBTIS target platform 4.3.0.Final for Mars using the specific Jenkins job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-target-platform/

* Tag a label onto the GIT target platform sources associated with any target platform build committed to nexus.
* Label the Jenkins build and set 'keep forever".

The staging checkbox simply controls whether the generated artifacts are published to the staging area.  The POM action can be used to deploy a SNAPSHOT release.

==== Publish the Community IS Target Platform Components

Given a successful build from the previous step, make the JBTIS TP public.  This example uses a 4.3.0.Final based target platform for Mars.

[source,bash]
----
# Copy the TP locally from staging  
cd ~/temp; mkdir -p tp; cd tp  
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-target-platform/4.3.0.Final .  
 
# Now copy the TP files onto jbosstools   
scp -r 4.3.0.Final tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/ 
----

Update the jbosstools target platform composites.
----
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/targetplatforms/jbtistarget/mars/compositeArtifacts.xml
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/targetplatforms/jbtistarget/mars/compositeContents.xml
----
Remember to update the timestamps (+vim :call ReplaceTimestamp()+):
* Clone https://github.com/jbosstools/jbosstools-download.jboss.org  
* Edit composite*.xml - update version and also change timestamp.  
[source,bash]
----
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/targetplatforms/jbtistarget/luna
vi compositeArtifacts.xml (compositeContent.xml)
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
----
Once the PR has been issued and merged to https://github.com/jbosstools/jbosstools-download.jboss.org, push the changes to the +download.jboss.org server+. (_Applying the PR is only the first half of getting these live._)

[source,bash]
----
# Push committed changes to the JBoss tools server.
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/luna  
put compositeArtifacts.xml  
put compositeContent.xml  
bye 
----

Verify:

*Mars*

http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/jbtis/REPO
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/jbtis/earlyaccess/REPO
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/jbdsis/REPO
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.3.0.Final/jbdsis/earlyaccess/REPO
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/mars/

==== Promote the Published JBTIS Target Platform Components to Nexus 

The JBTIS target platform is now built and published but we're still not done.  It must finally be promoted to nexus (which is where most components will pull it from).  *Be cautious here - once created there's no easy way to remove it.*  Note that this task will be done infrequently as the SNAPSHOT release will typically be used by developers until late in the release cycle.

* Clone jbosstools-integration-stack from jbosstools:

[source,bash]
----
# First build and deploy to staging  
git clone -o origin https://github.com/jbosstools/jbosstools-integration-stack.git ./jbosstools-integration-stack  
cd ./jbosstools-integration-stack/target-platform  

# Set the correct production branch (_if necessary_)
git checkout jbosstools-4.2.x
----

* Clear out your local maven repository and build/ deploy enabling the jboss-release profile:

[source,bash]
----
rm -rf ~/.m2/repository  
mvn -U -s ~/.m2/settings-staging.xml -DuseReleaseProfile=true -Pjboss-release clean deploy  
----
 
*If you get an Error 401 - check your +~/.m2/settings-staging.xml+ - make sure your server passwords are encrypted correctly.*
 
* Now promote from staging to the release nexus (log into sonatype nexus with your favorite browser)  
----
 https://repository.jboss.org/nexus/index.html#stagingRepositories  
---- 
Look for 'jboss_releases_staging_profile-nnnn' - the Maven deploy from the previous step will have populated it. 
 
* Check the box to the left  
* Select the 'Close' button to finalize for release or select the 'Drop' button to delete the repository 
* Once the close has completed - click 'Refresh'
* Select the 'Release' button

Verify - https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/4.3.0.Final/

[NOTE]
----
Note:  A simple listing of the above URL will not cause the deployed directory to become visible.  An artifact must be requested by name from a POM to update the cache.  To be sure - check the origin URL to see that the nexus deployment completed successfully.  e.g.
----
http://origin-repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/ 

Send out a notification to jbds-is-pm and QE indicating that a new JBTIS target platform is available.  e.g.

[source,bash]
----
   Greetings -
      An updated JBTIS TP is available:

   https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/4.2.0.Beta2a/

   See Jira for details:

   https://issues.jboss.org/browse/JBTIS-328

   1. Pick up the org.eclipse.birt.feature.group for use in Teiid
   2. Update to Luna SR1
      http://download.jboss.org/jbosstools/updates/requirements/luna/201409180900-SR1
   3. Update JBoss Tools core target dependencies to CR1
      http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.CR1-updatesite-core/
      http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.CR1-updatesite-coretests/
   4. Update orbit requirements to 2014
      http://download.jboss.org/jbosstools/updates/requirements/orbit/R20140525021250

            --paull
----

[big]*See JBDSIS Target Platform later in the document.  This completes the JBTIS Target Platform build/ release process.*

<<<

=== SAP Tooling Build/ Release Process
[.lead]

This section describes the process of building and releasing the SAP tooling update site for both community and devstudio.

Git ref: https://github.com/jbosstools/jbosstools-fuse-extras/tree/master/jboss-fuse-sap-tool-suite

==== Jenkins SAP Build

As an example, lets build SAP 7.3.0.Beta4 for Luna using the Jenkins job:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-fuse-sap-tooling-7.3.x/

The build parameters are self-explanatory.  Use care in deciding which Fuse tooling URL to use as there are class dependencies.

i.e.
fuse-tooling-url: http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/fuse-tooling/7.3.0.Beta5/all/repo/

Upon successful completion, this build will invoke the SAP tooling publish Jenkins job:

Git ref: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-fuse-sap-tooling-publish-7.3.x/

For a development build, our example yields the following:

http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/7.3.0.Beta4/

This effectively publishes the community SAP tooling bits.  The production devstudio bits require that the tooling update site is rsync'd to the devstudio.redhat.com server.  See the
*jboss.discovery.site.integration-stack-sap.url* in ide-config.properties .

[NOTE]
----
Note: We do *NOT* want an aggregate composite - only the most recent update site folder should appear in the composites.  Edit if necessary...
----

==== Publish the Community SAP Update Site (devstudio)

*Mars:*
[source,bash]
----
mkdir -p ~/temp/release;  cd ~/temp/release  
  
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/compositeArtifacts.xml .
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/compositeContent.xml .
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/7.3.0.Beta2a .

rsync -arzq --protocol=28 compositeArtifacts.xml devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/jboss-fuse-sap-tool-suite/
rsync -arzq --protocol=28 compositeContent.xml devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/jboss-fuse-sap-tool-suite/
rsync -arzq --protocol=28 7.3.0.Beta2a devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/jboss-fuse-sap-tool-suite/
----
Verify

http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/7.3.0.Beta2a/
https://devstudio.redhat.com/updates/8.0/integration-stack/jboss-fuse-sap-tool-suite/7.3.0.Beta2a/

=== JBTIS Aggregate/ Discovery Build/ Release Process
This section describes the process of building and releasing the JBTIS aggregate update site and the JBoss Central discovery site.  The project architecture is as follows:

[source,bash]
----
 jbosstools
 JBTIS - Community side. Mylyn discovery and update site generation.

     discovery
     JBTIS JBoss Tools Central Integration Stack discovery update generation.

        generation
        Create the Released Mylyn directory XML.

        generation-ea
        Create the Early Access Mylyn directory XML.

        org.jboss.tools.central.discovery.integration-stack
        Create the JBoss Tools central discovery update plugin.  Specifies released connector 
        descriptors, installation units, etc.

        org.jboss.tools.central.discovery.integration-stack.earlyaccess
        Create the JBoss Tools central discovery update plugin.  Specifies early access connector 
        descriptors, installation units, etc.

     site-final
     JBTIS .Final only composite artifacts, content and p2 update categories mirror.

     site-ea
     JBTIS early access (EA) only composite artifacts, content and p2 update categories mirror.
----

Git ref: https://github.com/jbosstools/jbosstools-integration-stack/tree/master/jbosstools

==== Jenkins JBTIS Aggregate Discovery Build
[.lead]

As an example, let's build JBTIS 4.3.0.Alpha2 for Mars using the Jenkins job:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-discovery/

The build type is selectable.  Use "integration" for builds that are better than continuous integration/ nightly but not quite milestone, "development" for milestones (i.e. beta and CR builds) and "stable" for final release builds.  Also note the upstream jbosstools site references.  The default options will get you the following:



To see what's happening with a given build, or why it's stuck, you can look at URLs such as these:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-discovery/

* Tag a label onto the GIT sources associated with any build committed to a milestone or release.  It is a required parameter to the configuration.  (i.e. JBTIS-4.1.6.Final)

* Label the Jenkins build and set 'keep forever".

==== Publish the JBoss Tools (Community) Integration Stack Components

There exists a separate Jenkins job to move the build artifacts out of the JBoss tools staging area into a JBoss tools update area.  For use when creating released sites: development/ stable.

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish/	       # mars
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish-4.2.x/    # luna
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish-4.1.x/    # kepler

Verify - note that the offline zip files and MD5s are also created (e.g.):

*Mars:*

http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/jbosstools-integration-stack-4.3.0.Alpha2.zip (MD5) +
http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/jbosstools-integration-stack-4.3.0.Alpha2-earlyaccess.zip (MD5) +

*Luna:*

http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/aggregate/jbosstools-integration-stack-aggregate-4.2.3.CR2.zip (MD5) +
http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/aggregate/jbosstools-integration-stack-aggregate-4.2.3.CR2-earlyaccess.zip (MD5) +

==== Publish and Push the JBTIS Aggregate Update Site

Clone jbosstools-download.jboss.org and update the composites in both the integration-stack directory to reflect the new version and then update the timestamps.  Remember to update both the released composites as well as the early access composites.

* Clone https://github.com/jbosstools/jbosstools-download.jboss.org 

* Edit composite*.xml - update version and also change timestamp.

*Mars:*

[source,bash]
----  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/mars/development/updates/integration-stack/
vi compositeArtifacts.xml (compositeContent.xml)
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
      
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/mars/development/updates/integration-stack/earlyaccess
...
----

*Luna:*

[source,bash]
----  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/integration-stack/  
vi compositeArtifacts.xml (compositeContent.xml)
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
      
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/integration-stack/aggregate  
...

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/integration-stack/earlyaccess
...
----

Commit and issue a PR.  Once the PR is merged, push the changes to the JBoss tools server:

*Mars:*

[source,bash]
----
# Push the development changes to the server  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/mars/development/updates/integration-stack/  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/development/updates/integration-stack/  
put compositeArtifacts.xml  
put compositeContent.xml  
bye  
  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/mars/development/updates/integration-stack/earlyaccess
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/umars/development/updates/integration-stack/earlyaccess
put compositeArtifacts.xml  
put compositeContent.xml  
bye 
----

*Luna:*

[source,bash]
----
# Push the development changes to the server  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/integration-stack/  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/  
put compositeArtifacts.xml  
put compositeContent.xml  
bye  
  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/integration-stack/aggregate  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/aggregate  
put compositeArtifacts.xml  
put compositeContent.xml  
bye

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/integration-stack/earlyaccess
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/earlyaccess
put compositeArtifacts.xml  
put compositeContent.xml  
bye 
----

[big]
*Note: If you updated a stable version, update the development version with the same bits along with the development composites.  That way development is never behind stable.*

Verify (development):

http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/
http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/earlyaccess
http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/
http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/earlyaccess/

Verify (stable):

http://download.jboss.org/jbosstools/mars/stable/updates/integration-stack/
http://download.jboss.org/jbosstools/mars/stable/updates/integration-stack/earlyaccess
http://download.jboss.org/jbosstools/updates/stable/luna/integration-stack/
http://download.jboss.org/jbosstools/updates/stable/luna/integration-stack/earlyaccess/

==== Publish and Push the JBTIS JBoss Central Discovery Jar

The JBoss Central discovery jars are rsync'd to the discovery download site depending on how you build.  Minimally you will find them here:

* http://download.jboss.org/jbosstools/mars/integration/updates/integration-stack/discovery/<version>
* http://download.jboss.org/jbosstools/mars/snapshots/updates/integration-stack/discovery/master/

If staged also find them here:

* http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/discovery/<version>

Update the directory XML as well.

* clone jbosstools-download.jboss.org 

*Mars:*

The jbosstools-directory.xml is auto-gtenerated - see:

http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/discovery/4.3.0.Alpha2/jbosstools-directory.xml

If building for a QE handoff, test like this:
[source,bash]
----
./eclipse -vmargs \
   -Djboss.discovery.directory.url=\
   http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/discovery/4.3.0.Alpha2/jbosstools-directory.xml \
   -Djboss.discovery.site.integration-stack.url=\
   http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/discovery/4.3.0.Alpha2/
----

If going live, merge the IS composites into core.  This optimizes the number of URLs users see when installing the IS.

*DEVELOPMENT (e.g):*

Update core composites:

* http://download.jboss.org/jbosstools/mars/development/updates/
* http://download.jboss.org/jbosstools/mars/development/updates/earlyaccess/

Merge core discovery - JBoss Central

Merge +
http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/discovery/composite* +
into +
http://download.jboss.org/jbosstools/mars/development/updates/discovery.central/4.3.0.Final/composite*

Merge +
http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/discovery/earlyaccess/composite* +
into +
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/4.3.0.Final/composite*

Copy the IS discovery plugins +

http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/discovery/4.3.0.Alpha2/plugins/ +
http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/discovery/4.3.0.Alpha2/earlyaccess/plugins/

to: +

http://download.jboss.org/jbosstools/mars/development/updates/discovery.central/4.3.0.Final/plugins/ +
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/4.3.0.Final/plugins/

*STABLE (e.g):*

Update core composites:

* http://download.jboss.org/jbosstools/mars/stable/updates/
* http://download.jboss.org/jbosstools/mars/stable/updates/earlyaccess/

Merge core discovery - JBoss Central

Merge +
http://download.jboss.org/jbosstools/mars/stable/updates/integration-stack/discovery/composite* +
into +
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.central/4.3.0.Final/composite*

Merge +
http://download.jboss.org/jbosstools/mars/stable/updates/integration-stack/discovery/earlyaccess/composite* +
into +
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.earlyaccess/4.3.0.Final/composite*

Copy the IS discovery plugins +

http://download.jboss.org/jbosstools/mars/stable/updates/integration-stack/discovery/4.3.0.Alpha2/plugins/ +
http://download.jboss.org/jbosstools/mars/stable/updates/integration-stack/discovery/4.3.0.Alpha2/earlyaccess/plugins/

to: +

http://download.jboss.org/jbosstools/mars/stable/updates/discovery.central/4.3.0.Final/plugins/ +
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.earlyaccess/4.3.0.Final/plugins/

Next edit *jbosstools-earlyaccess.properties*.  Add/ update any IUs that are early access.  The master version of *jbosstools-earlyaccess.properties* should be edited here, so the discovery job can fetch it: +

http://download.jboss.org/jbosstools/mars/snapshots/updates/earlyaccess.properties/master/jbosstools-earlyaccess.properties +

The 4.3.mars version of jbosstools-earlyaccess.properties should be edited here, so the discovery job can fetch it: +

http://download.jboss.org/jbosstools/mars/snapshots/updates/earlyaccess.properties/4.3.mars/jbosstools-earlyaccess.properties +
 
*Luna:*

[source,bash]
----
mkdir -p ~/temp/disc-jbtis;  cd ~/temp/disc-jbtis
wget http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.2.2.CR1/org.jboss.tools.central.discovery.integration-stack_4.2.2.CR1-v20150326-2110-B348.jar
wget http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.2.2.CR1/org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.2.2.CR1-v20150326-2110-B348.jar

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/plugins  
cp ~/temp/disc-jbtis/org.jboss.tools.central.discovery.integration-stack_4.2.2.CR1-v20150326-2110-B348.jar .
cp ~/temp/disc-jbtis/org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.2.2.CR1-v20150326-2110-B348.jar .
cd .. 
----

[NOTE]
----
Note: If committing a stable discovery jar/ directory XML - repeat the steps into the development directory.  Commit and issue a PR to http://download.jboss.org/jbosstools.  Once the PR has been merged, manually push the updated jar and jbosstools-directory.xml onto the JBoss server.
----

*Mars:*
[source,bash]
----
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/mars/stable/updates/discovery.central/4.3.0.Final/
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/stable/updates/discovery.central/4.3.0.Final/
put jbosstools-directory.xml
put jbosstools-earlyaccess.properties
bye  

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/mars/stable/updates/discovery.central/4.3.0.Final/plugins
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/stable/updates/discovery.central/4.3.0.Final/plugins
put org.jboss.tools.central.discovery.integration-stack_4.3.0.Beta1-v20150720-1209-B396.jar
put org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.3.0.Beta1-v20150720-1209-B396.jar
bye 
----

*Luna:*

[source,bash]
----
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna
put jbosstools-directory.xml
put jbosstools-earlyaccess.properties
bye  

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/plugins  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/plugins  
put org.jboss.tools.central.discovery.integration-stack_4.2.2.CR1-v20150326-2110-B348.jar
put org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.2.2.CR1-v20150326-2110-B348.jar
bye 
----

==== Git Status

Your git status should appear something like this:

[source,bash]
----
# On branch JBTIS-442
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   jbosstools/targetplatforms/jbtistarget/luna/compositeArtifacts.xml
#	modified:   jbosstools/targetplatforms/jbtistarget/luna/compositeContent.xml
#	modified:   jbosstools/targetplatforms/jbtistarget/mars/compositeArtifacts.xml
#	modified:   jbosstools/targetplatforms/jbtistarget/mars/compositeContent.xml
#	modified:   jbosstools/updates/development/luna/integration-stack/aggregate/compositeArtifacts.xml
#	modified:   jbosstools/updates/development/luna/integration-stack/aggregate/compositeContent.xml
#	modified:   jbosstools/updates/development/luna/integration-stack/compositeArtifacts.xml
#	modified:   jbosstools/updates/development/luna/integration-stack/compositeContent.xml
#	modified:   jbosstools/updates/development/luna/integration-stack/earlyaccess/compositeArtifacts.xml
#	modified:   jbosstools/updates/development/luna/integration-stack/earlyaccess/compositeContent.xml
#	modified:   jbosstools/updates/development/luna/jbosstools-directory.xml
#	modified:   jbosstools/updates/development/luna/jbosstools-earlyaccess.properties
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	jbosstools/updates/development/luna/plugins/org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.2.2.CR2-v20150603-0919-B15.jar
#	jbosstools/updates/development/luna/plugins/org.jboss.tools.central.discovery.integration-stack_4.2.2.CR2-v20150603-0919-B15.jar
----

Verify:

http://download.jboss.org/jbosstools/mars/stable/updates/discovery.central/4.3.0.Final/jbosstools-directory.xml
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.central/4.3.0.Final/plugins
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.earlyaccess/4.3.0.Final/jbosstools-earlyaccess.properties

http://download.jboss.org/jbosstools/updates/development/luna/jbosstools-directory.xml
http://download.jboss.org/jbosstools/updates/development/luna/jbosstools-earlyaccess.properties
http://download.jboss.org/jbosstools/updates/development/luna/plugins/

==== Publish the Community IS Sources

This is the JBTIS community project sources only.  Individual component's source bundles are carried in the aggregate.  In this example we're publishing the 4.2.0.Final JBTIS project sources (Luna zip and MD5).

[source,bash]
----
mkdir -p ~/temp/release;  cd ~/temp/release  
  
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc-4.2.x/all/JBTIS-aggregate-disc-4.2.x-SNAPSHOT-src.zip .  
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc-4.2.x/all/JBTIS-aggregate-disc-4.2.x-SNAPSHOT-src.zip.MD5 .  
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc-ea-4.2.x/all/JBTIS-aggregate-disc-ea-4.2.x-SNAPSHOT-src.zip .  
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc-ea-4.2.x/all/JBTIS-aggregate-disc-ea-4.2.x-SNAPSHOT-src.zip.MD5 .  

mv JBTIS-aggregate-disc-4.2.x-SNAPSHOT-src.zip jbosstools-integration-stack-sources-4.2.0.Final.zip  
mv JBTIS-aggregate-disc-4.2.x-SNAPSHOT-src.zip.MD5 jbosstools-integration-stack-sources-4.2.0.Final.zip.MD5  
mv JBTIS-aggregate-disc-ea-4.2.x-SNAPSHOT-src.zip jbosstools-integration-stack-sources-ea-4.2.0.Final.zip  
mv JBTIS-aggregate-disc-ea-4.2.x-SNAPSHOT-src.zip.MD5 jbosstools-integration-stack-sources-ea-4.2.0.Final.zip.MD5  

rsync -arzq --protocol=28 jbosstools-integration-stack-sources-4.2.0.Final.zip tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/luna/integration-stack/aggregate  
rsync -arzq --protocol=28 jbosstools-integration-stack-sources-4.2.0.Final.zip.MD5 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/luna/integration-stack/aggregate 
rsync -arzq --protocol=28 jbosstools-integration-stack-sources-ea-4.2.0.Final.zip tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/luna/integration-stack/aggregate  
rsync -arzq --protocol=28 jbosstools-integration-stack-sources-ea-4.2.0.Final.zip.MD5 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/luna/integration-stack/aggregate 
----

==== Test Eclipse Update

Install JBossTools from Eclipse Marketplace (i.e. JBossTools 4.2.3.Final).

[source,bash]
----
# Mars
# Start jbdevstudio or eclipse-with-jbosstools, then:  
Help > Install New Software...  
Add...  
 - use this for 'Location:' 
 http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/
 http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/earlyaccess

# Luna
# Start jbdevstudio or eclipse-with-jbosstools, then:  
Help > Install New Software...  
Add...  
 - use this for 'Location:' 
 http://download.jboss.org/jbosstools/builds/staging/development/luna/integration-stack/
 http://download.jboss.org/jbosstools/builds/staging/development/luna/integration-stack/earlyaccess

----

==== Test JBTIS JBoss Central Discovery Update

[source,bash]
----

./eclipse -vmargs \
  -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/discovery/4.3.0.Alpha2/jbosstools-directory.xml
  -Djboss.discovery.site.integration-stack.url=http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/discovery/4.3.0.Alpha2 \
  -Djboss.discovery.earlyaccess.site.integration-stack.url=http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/discovery/4.3.0.Alpha2/earlyaccess \

./eclipse -vmargs \
  -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/stable/integration-stack/4.2.3.Final/jbosstools-integration-stack-directory.xml \
  -Djboss.discovery.site.integration-stack.url=http://download.jboss.org/jbosstools/discovery/stable/integration-stack/4.2.3.Final \
  -Djboss.discovery.earlyaccess.site.integration-stack.url=http://download.jboss.org/jbosstools/discovery/stable/integration-stack/earlyaccess/4.2.3.Final/
----

=== JBTIS Aggregate/ Discovery Website Update

Clone and modify any jbosstools website component features ascii doc files.  Also modify 'whatsnew' and download links.

Ref Git: https://github.com/jbosstools/jbosstools-website +
Ref: http://tools.jboss.org/features/ +
Ref: http://tools.jboss.org/downloads/jbosstools_is/mars +

Build and verify the website before committing and issuing a PR.

*Update products.yml:*

* Clone jbosstools-website  https://github.com/jbosstools/jbosstools-website
* Edit /home/pleacu/git-clone/jbosstools-website/_config/products.yml  
* Update devstudio_is and jbt_is.  

*Update JBoss Tools blog:*

[source,bash]
----
# Clone jbosstools-website  
cd /home/pleacu/git-clone/jbosstools-website/blog 

# Use an older one as a template - note only one dot in file name 
cp integration-stack-4.2.2.Final-for-luna.adoc integration-stack-4.3.0.Alpha2-for-mars.adoc
----

*Test JBoss Tools web site:*

Ref: https://github.com/jbosstools/jbosstools-website/blob/master/readme.adoc

[source,bash]
----
# In a bash shell...
bash --login
rvm use 1.9.3
rvm gemset create jbosstools-website
cd ~/git-clone/jbosstools-website/
rake setup
gem install bundler
bundle install
rake clean preview

# In a web browser...
http://localhost:4242/blog/2015-03-18-JBTIS-417-Final.html
http://localhost:4242/downloads/jbosstools_is/kepler/4.1.6.Final.html
----

See xcoulon to push the PR.

Verify:

http://tools.jboss.org/blog/

[big]*This completes the JBTIS aggregate/ discovery build/ release process.*

== Production JBDSIS Build

The production JBDSIS build draws its content from the community JBTIS build.  Consequently, the content of the production build is always less than or equal to the community build.  JBDSIS does not have its own composite files for update site artifacts.

=== JBDSIS Target Platform
[.lead]
*The JBDSIS target platform is pulled from the JBTIS target platform and is a result of different merge targets.*  The JBDSIS target platform does not merge in the +community.target+ file.  It is created under the common JBTIS target platform build.

In this example the 9.0.0.Beta1 target platform (Mars) repository is created.  First update the common and static update release areas.

* Copy the community JBTIS target platform locally and remote-sync it to the devstudio update area.

*Mars:*
 
[source,bash]
----
cd ~/temp; mkdir -p tp; cd tp
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/4.3.0.Final .

rsync -arzq --protocol=28 4.3.0.Final/jbdsis devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/targetplatforms/jbdsistarget/9.0.0.Beta1.jbds-is-target-platform
----

*Luna:*

[source,bash]
----
cd ~/temp; mkdir -p tp; cd tp
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/4.2.4.Final .

rsync -arzq --protocol=28 4.2.4.Final/jbdsis devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/8.0.4.GA.jbds-is-target-platform
rsync -arzq --protocol=28 4.2.4.Final/jbdsis devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/8.0.4.GA.jbds-is-target-platform
----

URL:

https://devstudio.redhat.com/targetplatforms/jbdsistarget/9.0.0.Beta1.jbds-is-target-platform/jbdsis/REPO/
https://devstudio.redhat.com/targetplatforms/jbdsistarget/9.0.0.Beta1.jbds-is-target-platform/jbdsis/earlyaccess/REPO/

https://devstudio.redhat.com/updates/8.0.0/8.0.4.GA.jbds-is-target-platform/jbdsis/REPO
https://devstudio.redhat.com/updates/8.0.0/8.0.4.GA.jbds-is-target-platform/jbdsis/earlyaccess/REPO

Verify:

https://devstudio.redhat.com/updates/8.0.0/8.0.4.GA.jbds-is-target-platform/jbdsis/REPO
https://devstudio.redhat.com/updates/8.0.0/8.0.4.GA.jbds-is-target-platform/jbdsis/earlyaccess/REPO
https://devstudio.redhat.com/static/updates/8.0.0/8.0.4.GA.jbds-is-target-platform/jbdsis/REPO
https://devstudio.redhat.com/static/updates/8.0.0/8.0.4.GA.jbds-is-target-platform/jbdsis/earlyaccess/REPO

https://devstudio.redhat.com/targetplatforms/jbdsistarget/9.0.0.Beta1.jbds-is-target-platform/...

*** This completes the JBDSIS TP build/ release process.

=== JBDSIS Aggregate/ Discovery Build/ Release Process
[.lead]
This section describes the process of building and releasing the actual JBDSIS aggregate update site and the JBoss Central discovery site.  The project architecture is as follows:
 
[source,bash]
----
 devstudio
 JBDSIS - Production side.  Mylyn discovery and Eclipse p2 update site generation.

    discovery
    JBDSIS JBoss Tools Central Integration Stack discovery update generation.

	com.jboss.jbds.central.discovery.integration-stack
	Create the JBoss Tools central discovery update plugin.  Specifies connector descriptors, 
        installation units, etc.

	com.jboss.jbds.central.discovery.integration-stack.earlyaccess
	Create the JBoss Tools central discovery update plugin.  Specifies early access connector descriptors, 
        installation units, etc.

	generation
	Create the Mylyn directory XML.

        generation-ea
        Create the Early Access Mylyn directory XML.

    site-ga
    JBDSIS P2 release (GA) update categories.  Composite content drawn from JBTIS.

    site-ea
    JBDSIS P2 early access update categories.  Composite content drawn from JBTIS.
----

Git ref: https://github.com/jbosstools/jbosstools-integration-stack/tree/master/devstudio
 
==== Jenkins JBDSIS Aggregate Discovery Build:

As an example, lets build JBDSIS using the specific Jenkins job:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBDSIS-aggregate-discovery

Note the community JBTIS aggregate composite site from which this build draws its content.  As with the JBTIS build, the build type is selectable - make sure you select the correct parameter as it affects the discovery site and site index.html.

Upon successful completion of this build, the JBDSIS-aggregate-discovery build will be invoked to build the release (.Final) components.

*Mars:*

*SNAPSHOTS -*

* https://devstudio.redhat.com/9.0/snapshots/updates/integration-stack/
* https://devstudio.redhat.com/9.0/snapshots/updates/integration-stack/master/
* https://devstudio.redhat.com/9.0/snapshots/updates/integration-stack/master/earlyaccess/
* https://devstudio.redhat.com/9.0/snapshots/updates/integration-stack/discovery/master/

*DEVSTUDIO STAGING (if enabled) -*

* https://devstudio.redhat.com/9.0/staging/updates/integration-stack/
* https://devstudio.redhat.com/9.0/staging/updates/integration-stack/${VERSION}
* https://devstudio.redhat.com/9.0/staging/updates/integration-stack/discovery/${VERSION}

* Tag a label onto the GIT sources associated with any build committed to a milestone or release.  It is a required parameter to the configuration.  (i.e. JBDSIS-9.0.0.Alpha2)
* Label the Jenkins build and set 'keep forever".

==== Publish the Production Integration Stack Components

There exists a separate Jenkins job to move the build artifacts out of the JBoss tools staging area into a JBoss tools update area.  Match the build type to the aggregate build type from the previous section.  Match the target folder to the aggregate build version string.

*For Mars builds, after QE has approved the release rerun the JBDSIS-aggregate-publish job enabling the RELEASE parameter.*

Verify:

https://devstudio.redhat.com/9.0/staging/updates/integration-stack/
http://www.qa.jboss.com/binaries/RHDS/updates/development/luna/integration-stack/aggregate/8.0.0.CR2/
http://www.qa.jboss.com/binaries/RHDS/updates/development/kepler/integration-stack/aggregate/8.0.3.CR2/
 
==== Publish and Push the JBDSIS Aggregate Update Site

Update the production aggregate Eclipse p2 repository as well as the offline .zip file.  If this is an earlyaccess jar - update the earlyaccess (devstudio/earlyaccess) composites.

*Mars:*

*Select the RELEASE check box in the JBDSIS-aggregate-publish Jenkins job*

Note that a stable build will be retrieved from a corresponding stable path.  If you update stable make sure to update development as well.

Clone +jbdevstudio-website+ and update the composites in both the integration-stack directory and integration-stack/aggregate to reflect the new version and then update the timestamps.

*Luna:*

[source,bash]
----
cd ~/temp; mkdir -p jbds-update; cd jbds-update

# Copy the update site to the devstudio update areas:  
rsync -aPrzq --protocol=28  pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/8.0.3.CR2 .

rsync -arzq --protocol=28 8.0.3.CR2/ devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/8.0.3.CR2.jbds-is
rsync -arzq --protocol=28 8.0.3.CR2/ devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/8.0.3.CR2.jbds-is
     
# Copy the update site zip to the devstudio update areas:  
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/devstudio-integration-stack-aggregate-8.0.3.CR2.zip devstudio-integration-stack-aggregate-8.0.3.CR2.zip
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/devstudio-integration-stack-aggregate-8.0.3.CR2-earlyaccess.zip devstudio-integration-stack-aggregate-8.0.3.CR2-earlyaccess.zip

rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.3.CR2.zip devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.3.CR2.zip
rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.3.CR2.zip devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.3.CR2.zip

rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.3.CR2-earlyaccess.zip devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.3.CR2-earlyaccess.zip
rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.3.CR2-earlyaccess.zip devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.3.CR2-earlyaccess.zip

# Copy the update site MD5 to the devstudio update areas:  
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/devstudio-integration-stack-aggregate-8.0.3.CR2.zip.MD5 devstudio-integration-stack-aggregate-8.0.3.CR2.zip.MD5
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/devstudio-integration-stack-aggregate-8.0.3.CR2-earlyaccess.zip.MD5 devstudio-integration-stack-aggregate-8.0.3.CR2-earlyaccess.zip.MD5

rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.3.CR2.zip.MD5 devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.3.CR2.zip.MD5
rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.3.CR2.zip.MD5 devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.3.CR2.zip.MD5

rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.3.CR2-earlyaccess.zip.MD5 devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.3.CR2-earlyaccess.zip.MD5
rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.3.CR2-earlyaccess.zip.MD5 devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.3.CR2-earlyaccess.zip.MD5
----

Git ref: https://github.com/jbdevstudio/jbdevstudio-website

===== Update the developer/stable/staging studio composite update sites.

*Mars:*

[source,bash]
----
# Update https://devstudio.redhat.com/9.0/development/updates/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
# Update https://devstudio.redhat.com/9.0/stable/updates/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
# Update https://devstudio.redhat.com/9.0/staging/updates/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  

 e.g.
 cd /home/pleacu/git-clone/jbdevstudio-website/content/9.0/development/updates/integration-stack
 # update compositeArtifacts.xml,  compositeContent.xml, index.html  
 # edit composite*.xml - also change timestamp!  
 vi compositeArtifacts.xml  
 <esc> :call ReplaceTimestamp()  
 <esc> :wq!

# Update https://devstudio.redhat.com/9.0/development/updates/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html   
# Update https://devstudio.redhat.com/9.0/stable/updates/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html  
# Update https://devstudio.redhat.com/9.0/staging/updates/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html  

 e.g.
 cd /home/pleacu/git-clone/jbdevstudio-website/content/9.0/development/updates/integration-stack/earlyaccess
 # update compositeArtifacts.xml,  compositeContent.xml, index.html  
 # edit composite*.xml - also change timestamp!  
 vi compositeArtifacts.xml  
 <esc> :call ReplaceTimestamp()  
 <esc> :wq!

# Update https://devstudio.redhat.com/9.0/development/updates/integration-stack/discovery/compositeContent.xml, compositeArtifacts.xml, index.html  
# Update https://devstudio.redhat.com/9.0/stable/updates/integration-stack/discovery/compositeContent.xml, compositeArtifacts.xml, index.html  
# Update https://devstudio.redhat.com/9.0/staging/updates/integration-stack/discovery/compositeContent.xml, compositeArtifacts.xml, index.html  

 e.g.
 cd /home/pleacu/git-clone/jbdevstudio-website/content/9.0/development/updates/integration-stack/discovery
 # update compositeArtifacts.xml,  compositeContent.xml, index.html  
 # edit composite*.xml - also change timestamp!  
 vi compositeArtifacts.xml  
 <esc> :call ReplaceTimestamp()  
 <esc> :wq!

# Update core composites (development/ stable)

# https://devstudio.redhat.com/9.0/development/updates/ 
# https://devstudio.redhat.com/9.0/development/updates/earlyaccess/

# Merge core discovery - JBoss Central (development/ stable)

# https://devstudio.redhat.com/9.0/development/updates/discovery.central/9.0.0.GA/devstudio-directory.xml
# https://devstudio.redhat.com/9.0/development/updates/discovery.central/9.0.0.GA/plugins/com.jboss.jbds.central.discovery.integration-stack_...jar
#                                                                                         com.jboss.jbds.central.discovery.integration-stack.earlyaccess_...jar 
# https://devstudio.redhat.com/9.0/development/updates/discovery.earlyaccess/9.0.0.GA/devstudio-directory.xml
# https://devstudio.redhat.com/9.0/stable/updates/discovery.earlyaccess/9.0.0.GA/devstudio-earlyaccess.properties
# https://devstudio.redhat.com/9.0/development/updates/discovery.earlyaccess/9.0.0.GA/plugins
 
----

*Luna:*

[source,bash]
----
# Update https://devstudio.redhat.com/updates/8.0-development/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/integration-stack  
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0-development/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/integration-stack/earlyaccess
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0-staging/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-staging/integration-stack  
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0-staging/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-staging/integration-stack/earlyaccess
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/integration-stack  
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/integration-stack/earlyaccess
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0/integration-stack/aggregate/compositeContent.xml, compositeArtifacts.xml
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/integration-stack/aggregate
# update compositeArtifacts.xml,  compositeContent.xml
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/central/integration-stack  
# edit index.html

----

If this is an earlyaccess jar - update the earlyaccess (devstudio/earlyaccess) composites.

[source,bash]
----
# Update https://devstudio.redhat.com/updates/8.0-development/compositeContent.xml, compositeArtifacts.xml
 cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0-development 
# update compositeArtifacts.xml,  compositeContent.xml
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0-staging/compositeContent.xml, compositeArtifacts.xml
 cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0-staging
# update compositeArtifacts.xml,  compositeContent.xml
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0/compositeContent.xml, compositeArtifacts.xml  # Go Live
 cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0
# update compositeArtifacts.xml,  compositeContent.xml
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!
----

Commit and issue a PR.  Once the PR is merged, push the changes to the devstudio tools server:

[source,bash]
----
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/integration-stack  
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-development/integration-stack  
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/integration-stack/earlyaccess
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-development/integration-stack/earlyaccess  
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-staging/integration-stack  
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-staging/integration-stack  
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-staging/integration-stack/earlyaccess
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-staging/integration-stack/earlyaccess
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye

cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0-development
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/earlyaccess/8.0-development
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> bye

cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0-staging
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/earlyaccess/8.0-staging
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> bye
----

Verify:  https://devstudio.redhat.com/updates/8.0-development/integration-stack

==== Publish and Push the JBDSIS JBoss Central Discovery Jar (Luna)

The JBoss Central discovery jar is actually committed to the discovery download site.  Update the directory XML as well.

*Luna:*

[source,bash]
----
mkdir -p ~/temp/disc;  cd ~/temp/disc
wget http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.3.CR2/com.jboss.jbds.central.discovery.integration-stack_8.0.1.GA-v20150408-1203-B104.jar
wget http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.3.CR2/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.1.GA-v20150408-1203-B104.jar 

# clone jbdevstudio-website

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/discovery
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack_8.0.1.GA-v20150408-1203-B104.jar .
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.1.GA-v20150408-1203-B104.jar .

cd ..
----
* edit devstudio-directory.xml: update jar file names
* edit devstudio-earlyaccess.properties: add any IUs that are early access

[source,bash]
----
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-staging/discovery
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack_8.0.1.GA-v20150408-1203-B104.jar .
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.1.GA-v20150408-1203-B104.jar .

cd ..
----
* edit devstudio-directory.xml, devstudio-earlyaccess.properties

The master version of devstudio-earlyaccess.properties should be edited here, so the discovery job can fetch it: 

https://devstudio.redhat.com/9.0/snapshots/updates/earlyaccess.properties/master/devstudio-earlyaccess.properties

The 4.3.mars version of devstudio-earlyaccess.properties should be edited here, so the discovery job can fetch it: 

https://devstudio.redhat.com/9.0/snapshots/updates/earlyaccess.properties/4.3.mars/devstudio-earlyaccess.properties

[NOTE]
----
Commit and issue a PR to https://github.com/jbdevstudio/jbdevstudio-website.  Once the PR has been merged, manually push the updated jar and devstudio-directory.xml onto the JBoss server.

https://github.com/jbdevstudio/jbdevstudio-website/blob/master/content/9.0/snapshots/updates/earlyaccess.properties/master/devstudio-earlyaccess.properties may need to be manually pushed to https://devstudio.redhat.com/9.0/snapshots/updates/earlyaccess.properties/master/devstudio-earlyaccess.properties
----

[source,bash]
----
# Copy the JBDSIS central jar and metadata files into position  
 cd ~/temp/disc  
 wget http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.3.CR2/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.3.CR2-v20141023-1623-B69.jar  

 sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-development/discovery  
 - or -
 sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-staging/discovery  

 put com.jboss.jbds.central.discovery.integration-stack_8.0.3.CR2-v20140409-1834-B7.jar
 put com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.3.CR2-v20150522-0954-B10.jar
 bye

 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/  (or 8.0-staging)
 sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-development/
 put devstudio-directory.xml
 put devstudio-earlyaccess.properties
 bye 
----

Clone jbdevstudio-website and update the JBDSIS JBoss Central JAR file and devstudio-directory discovery XML file.  Update the composites and index.html in the 8.0/integration-stack, 8.0/central/integration-stack and 8.0 discovery directory then push the files to the devstudio server.

Git ref: https://github.com/jbdevstudio/jbdevstudio-website

Verify: https://devstudio.redhat.com/updates/8.0-development/devstudio-directory.xml

==== Go live Luna!
[source,bash]
----
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/discovery  
cp ~/temp/disc/com* .

# Push the discovery jars
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/discovery 
   sftp> put com.jboss.jbds.central.discovery.integration-stack_8.0.3.CR2-v20150408-1203-B104.jar
   sftp> put com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.3.CR2-v20150408-1203-B104.jar
   sftp> bye

cd ..

# edit devstudio-directory.xml, devstudio-earlyaccess.properties
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0  
   sftp> put devstudio-directory.xml
   sftp> put devstudio-earlyaccess.properties
      
# update compositeArtifacts.xml, compositeContent.xml, index.html - versions and timestamps  

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/integration-stack  
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack  
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml     
   sftp> put index.html  
   sftp> bye

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/integration-stack/aggregate
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/aggregate
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml     
   sftp> put index.html  
   sftp> bye

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/integration-stack/earlyaccess
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/earlyaccess
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml     
   sftp> put index.html  
   sftp> bye

#cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/central/integration-stack  
#sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/central/integration-stack/  
#   sftp> put compositeArtifacts.xml  
#   sftp> put compositeContent.xml  
#   sftp> put index.html  
      
cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/earlyaccess/8.0
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml     
   sftp> bye
----

[NOTE]
----
Note: If you updated a stable version, update the development version with the same bits.  That way development is never behind stable.
----

==== Git Status

Your git status (Luna) should appear something like this:

[source,bash]
----
# On branch JBTIS-480
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   earlyaccess/8.0-development/compositeArtifacts.xml
#	modified:   earlyaccess/8.0-development/compositeContent.xml
#	modified:   earlyaccess/8.0-staging/compositeArtifacts.xml
#	modified:   earlyaccess/8.0-staging/compositeContent.xml
#	modified:   earlyaccess/8.0/compositeArtifacts.xml
#	modified:   earlyaccess/8.0/compositeContent.xml
#	modified:   updates/8.0-development/devstudio-directory.xml
#	modified:   updates/8.0-development/integration-stack/compositeArtifacts.xml
#	modified:   updates/8.0-development/integration-stack/compositeContent.xml
#	modified:   updates/8.0-development/integration-stack/earlyaccess/compositeArtifacts.xml
#	modified:   updates/8.0-development/integration-stack/earlyaccess/compositeContent.xml
#	modified:   updates/8.0-development/integration-stack/earlyaccess/index.html
#	modified:   updates/8.0-development/integration-stack/index.html
#	modified:   updates/8.0-staging/devstudio-directory.xml
#	modified:   updates/8.0-staging/integration-stack/compositeArtifacts.xml
#	modified:   updates/8.0-staging/integration-stack/compositeContent.xml
#	modified:   updates/8.0-staging/integration-stack/earlyaccess/compositeArtifacts.xml
#	modified:   updates/8.0-staging/integration-stack/earlyaccess/compositeContent.xml
#	modified:   updates/8.0-staging/integration-stack/earlyaccess/index.html
#	modified:   updates/8.0-staging/integration-stack/index.html
#	modified:   updates/8.0/devstudio-directory.xml
#	modified:   updates/8.0/devstudio-earlyaccess.properties
#	modified:   updates/8.0/integration-stack/aggregate/compositeArtifacts.xml
#	modified:   updates/8.0/integration-stack/aggregate/compositeContent.xml
#	modified:   updates/8.0/integration-stack/compositeArtifacts.xml
#	modified:   updates/8.0/integration-stack/compositeContent.xml
#	modified:   updates/8.0/integration-stack/earlyaccess/compositeArtifacts.xml
#	modified:   updates/8.0/integration-stack/earlyaccess/compositeContent.xml
#	modified:   updates/8.0/integration-stack/earlyaccess/index.html
#	modified:   updates/8.0/integration-stack/index.html
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	updates/8.0-development/discovery/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.3.GA-v20150825-1155-B20.jar
#	updates/8.0-development/discovery/com.jboss.jbds.central.discovery.integration-stack_8.0.3.GA-v20150825-1155-B20.jar
#	updates/8.0-staging/discovery/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.3.GA-v20150825-1155-B20.jar
#	updates/8.0-staging/discovery/com.jboss.jbds.central.discovery.integration-stack_8.0.3.GA-v20150825-1155-B20.jar
#	updates/8.0/discovery/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.3.GA-v20150825-1155-B20.jar
#	updates/8.0/discovery/com.jboss.jbds.central.discovery.integration-stack_8.0.3.GA-v20150825-1155-B20.jar
----

==== Test Install from Update Site

[source,bash]
----
Start jbdevstudio or eclipse-with-jbds, then:  
    Help > Install New Software...  
    Add...  
    - use this for 'Location:'  
    https://devstudio.redhat.com/updates/7.0-development/integration-stack/  

# TODO: document what steps to perform, other than simply starting JBDS and looking at the above URL

----

==== Test JBDSIS JBoss Central Discovery Site

*Luna:*

[source,bash]
----
./jbdevstudio -vmargs -Djboss.discovery.directory.url=http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.3.CR2/devstudio-integration-stack-directory.xml  
      -Djboss.discovery.site.url=http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.3.CR2

# TODO: document what steps to perform, other than simply starting JBDS and looking at Central. Install everything? Install all Early Access stuff?

----

==== Test JBDSIS Offline Install

To install JBDSIS in a completely offline way, you need three zips or jars to act as update sites:

* JBDS target platform zip
* JBDS installer or update site zip
* JBDS IS update site zip

Ref: http://docbuilder.usersys.redhat.com/23023/#Install_JBoss_Developer_Studio_Integration_Stack_in_Eclipse_when_Offline

Retrieve the offline JBDS zips:

https://devstudio.redhat.com/updates/8.0/#offline

If you don't already have installFromTarget.sh, see this:

https://gist.github.com/nickboldt/e899f4e22a0654af667e

Install JBDS into ~/offline, then:

[source,bash]
----
~/bin/installFromTarget.sh -ECLIPSE ~/offline/studio/ -INSTALL_PLAN  
'jar:file:///home/pleacu/install/jbdevstudio-integration-stack-updatesite-8.0.3.CR2.zip!/,jar:file:///home/pleacu/install/jboss-devstudio-8.1.0.GA-updatesite-core.zip!/,jar:file:///home/pleacu/install/jbdevstudiotarget-4.32.0.Final.zip!/'  
----

==== Update the Red Hat Customer Support Portal

Generate a ticket with engineering services. 
[source,bash]
---- 
Ref: https://engineering.redhat.com/rt/Ticket/Display.html?id=296645
Ref: https://engineering.redhat.com/rt/Ticket/Display.html?id=341933
----
Verify:

https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=8.0.0

==== Update Eclipse Marketplace

Log into Eclipse Marketplace - go to the Integration Stack content page:

https://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-integration-stack-luna/edit 

If it's a new page it must be submitted for inclusion the the Eclipse website master.  If it's an existing page you may edit it.

Start a plain Eclipse session (no JBT or JBDS) and search for an included keyword (i.e. Fuse).  It will install both the IS and required core features.

*Update get-started.adoc:*

* Clone www.jboss.org  https://github.com/jboss-developer/www.jboss.org
* Edit /home/pleacu/git-clone/www.jboss.org/products/devstudio/get-started.adoc

*Test www.jboss.org site:*

[source,bash]
----
# In a bash shell...
bash --login
rvm use 1.9.3
rvm gemset create www.jboss.org
cd ~/git-clone/www.jboss.org/products/devstudio
rake setup
gem install bundler
bundle install
rake clean preview

# In a web browser...
http://localhost:4242/products/devstudio
----

See ???? to push the PR.

Verify:

http://www.jboss.org/products/devstudio/get-started

[big]*This completes the JBDSIS aggregate/ discovery build/ release process.*
