
= JBoss Tools Integration Stack Release Process

== Introduction

This document describes the task of updating, building and publishing the community and production versions of the JBoss Tools Integration Stack.

The Integration Stack is an aggregation of Eclipse features and plugins comprised of JBoss tooling in support of Data Virtualization, BRMS/BPMS, Fuse Tooling and legacy SOA 5.x development.  It is formed by a Maven project which produces an Eclipse p2 update site, a Mylyn discovery update mechanism augmenting JBoss Central and an aggregation of associated component target dependencies and JBoss Core tooling target dependencies.  The target dependencies take the form of generated .target files (tycho mojo) and a target p2 update repository.

Click https://mojo.redhat.com/docs/DOC-946223 for a quick overview/ presentation of the Integration Stack.

[NOTE]
----
Note:  Many steps require privileged access to JBoss servers, Developer Studio servers or nexus.
----

== Update Process

The Integration Stack project is open source (naturally) and can be found here: 

https://github.com/jbosstools/jbosstools-integration-stack

Typical updates most frequently occur to the aggregate site composite files.  These would change if a new version of Teiid Designer needed to be included for example.

https://github.com/jbosstools/jbosstools-integration-stack/blob/master/jbosstools/site/compositeArtifacts.xml
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/jbosstools/site/compositeContent.xml

These files define the IS component update sites.  Note that with rare exceptions these component update sites must be in .Final form for a .Final/.GA IS build.

The second most frequent update occurs in the tycho mojo target platform definition files:

https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/integration-stack-base.target
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/integration-stack-base-ea.target
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/core-base.target
https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform/community.target

[NOTE]
----
Note: Github source branch jbosstools-4.1.x should be used for JBTIS 4.1.x (Kepler) builds.
      Github source branch jbosstools-4.2.x should be used for JBTIS 4.2.x (Luna) builds.
      Github source branch master should be used for JBTIS 4.3.x (Mars) builds.
----

== Build/ Publish Process

The build/ publish process is a sequential set of tasks that must be executed in order.  The order is as follows:

    JBTIS target platform
    JBTIS aggregate/ discovery
    JBTIS Publish
    JBDSIS target platform
    JBDSIS aggregate discovery
    JBDSIS Publish.

Other fun facts:

* Not all tasks must be executed for a release.  For example, if there's no change to the target platform the aggregate build may use the existing one.
* It's possible to release JBTIS independently however JBDSIS must release from an existing JBTIS.
* The integration stack component's POMs may or may not pick up the latest JBTIS TP.  We recommend that they do but it is not required.

There exists Jenkins build jobs for each Eclipse-based revision of JBDS (Kepler, Luna, etc).  Examples will be referenced explicitly in the build procedure instructions.

=== Community JBTIS Build

There is a community version of the JBTIS target platform, p2 aggregate update site and discovery update mechanism.  The target platform and p2 site are required for the production build.

==== JBTIS Target Platform Build/ Release Process

The JBoss Tools Integration Stack Target Platform project creates four target files:

* An aggregate of the JBoss Tools Core target dependencies and JBoss Tools multiple dependencies + released Integration Stack base target dependencies (base).

[source,bash]
----
   1. released integration-stack specific target dependencies:   integration-stack-base.target
   2. the JBoss Tools core target dependencies:                + core-base.target
   3. the JBoss Tools unified core target dependencies:        + jbosstools-multiple.target
                                                                 -----------------------------
      to generate an aggregate base target dependencies file:    aggregate-base.target
----
e.g.  http://download.jboss.org/jbosstools/builds/staging/JBTIS-target-platform/4.2.3.Final/aggregate-base.target

* An aggregate of the JBoss Tools Core target dependencies and JBoss Tools multiple dependencies + early access Integration Stack base target dependencies (base-ea).

[source,bash]
----
   1. released integration-stack specific target dependencies:   integration-stack-base-ea.target
   2. the JBoss Tools core target dependencies:                + core-base.target
   3. the JBoss Tools unified core target dependencies:        + jbosstools-multiple.target
                                                                 --------------------------------
      to generate an aggregate base target dependencies file:    aggregate-base-ea.target
----
e.g.  http://download.jboss.org/jbosstools/builds/staging/JBTIS-target-platform/4.2.3.Final/aggregate-base-ea.target

* An aggregate of the JBoss Tools Core target dependencies + Integration Stack base target dependencies + any other community dependencies (full).

[source,bash]
----
   1. the previously generated aggregate base EA target file:    aggregate-base.target
   2. the community-specific target dependencies:              + community.target
                                                                 ---------------------
      to generate the full community target dependencies file:   aggregate-full.target
----
e.g.  http://download.jboss.org/jbosstools/builds/staging/JBTIS-target-platform/4.2.3.Final/aggregate-full.target

* An aggregate of the JBoss Tools Core target dependencies + early access Integration Stack base target dependencies + any other community dependencies (full-ea).

[source,bash]
----
   1. the previously generated aggregate base EA target file:    aggregate-base-ea.target
   2. the community-specific target dependencies:              + community.target
                                                                 ------------------------
      to generate the full community target dependencies file:   aggregate-full-ea.target
----
e.g.  http://download.jboss.org/jbosstools/builds/staging/JBTIS-target-platform/4.2.3.Final/aggregate-full-ea.target

The JBoss Tools Integration Stack Target Platform project also creates four repositories:

* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/jbtis/REPO/

* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/jbtis/earlyaccess/REPO/

* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/jbdsis/REPO/

* http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/jbdsis/earlyaccess/REPO/

The jbdsis repositories are built separately so as to avoid pulling in any community bits.

The integration-stack tycho target dependency (.target) files are deployed to the JBoss nexus releases repository for use by the integration stack component projects.  If you are an integration stack component developer or potentially a QE test developer, your maven POM target-platform-configuration should reference one of these as your target-platform artifact.

* https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/4.2.3.Final/

Target artifacts local to the IS:

* integration-stack-base.target - integration stack component required dependencies
* integration-stack-base-ea.target - integration stack early access component required dependencies
* core.base.target - JBoss tools core required dependencies
* community.target - dependencies specific to the community (not required for JBDS)

Target artifacts drawn from org.jboss.tools.targetplatforms:

* jbosstools-multiple.target

If an IS component causes a new target dependency, this JBTIS TP build procedure must be executed.  The result is a new JBTIS TP in nexus.  That must then be used by the requesting component POM which will produce a new component update site.  That update site must then be referenced by the JBTIS Aggregate/Discovery procedure.  For example, if Teiid has a new target platform dependency it would be necessary to first build JBTIS TP, then rebuild Teiid, then build JBTIS - modifying the aggregate composites to reference the new Teiid update site.

The following JBoss Tools target platform update process should be followed for updating the JBTIS target platform:

link:https://github.com/jbosstools/jbosstools-devdoc/blob/master/building/target_platforms/target_platforms_updates.adoc[JBoss target platform updates]

Git ref: https://github.com/jbosstools/jbosstools-integration-stack/blob/master/target-platform

==== JBTIS Target Platform Dependency Update:

As an example, the JBDS core target dependencies need to be updated from 4.2.0.Beta2b to 4.2.0.Beta2c.  Many if not all of the IUs need to be updated in the core-base.target file.  This update can be performed automatically be performing the following steps:

[source,bash]
----
# Clone the jbosstools-integration-stack locally.  
# Modify repository URLs in jbosstools-integration-stack/target-platform/*.target  
# Clone or otherwise retrieve the verifyTarget.sh bash script from  
https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/verifyTarget.sh  

# Update component versions based on new repository URLs.
cd ~/bin
./verifyTarget.sh -x -b ~/git-clone/jbosstools-integration-stack/target-platform -p target-platform -z ~/install/eclipse-jee-luna-SR2-linux-gtk-x86_64.tar.gz

# p2 diff the generated Integration Stack released target platform - i.e.:
p2diff \
 file:///home/pleacu/git-clone/jbosstools-integration-stack.orig/target-platform/target/target-platform.target.repo \
 file:///home/pleacu/git-clone/jbosstools-integration-stack/target-platform/target/target-platform.target.repo

# p2 diff the generated Integration Stack early access target platform - i.e.:
p2diff \
 file:///home/pleacu/git-clone/jbosstools-integration-stack.orig/target-platform/target/target-platform-ea.target.repo \
 file:///home/pleacu/git-clone/jbosstools-integration-stack/target-platform/target/target-platform-ea.target.repo
----

Git diff the core-base.target file.  Commit and issue a PR.

A PR should be sent out for public review.  e.g.

[source,bash]
----
  Greetings -
      A proposal to change the JBTIS target platform is described here:

   https://issues.jboss.org/browse/JBTIS-328

   PR:  https://github.com/jbosstools/jbosstools-integration-stack/pull/236

   Synopsis:

   1. Pick up the org.eclipse.birt.feature.group for use in Teiid
   2. Update to Luna SR1
      http://download.jboss.org/jbosstools/updates/requirements/luna/201409180900-SR1
   3. Update JBoss Tools core target dependencies to CR1
      http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.CR1-updatesite-core/
      http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.CR1-updatesite-coretests/
   4. Update orbit requirements to 2014
      http://download.jboss.org/jbosstools/updates/requirements/orbit/R20140525021250

   Please respond by COB on Thursday, Sept 25 to the specified Jira if there are any issues.

   Thanks,
         --paull
----

[NOTE]
----
Note:  A non-API-change dependant update (micro-release update) may be done without a full review proposal.
----

==== Jenkins JBTIS Target Platform Build:

As an example, lets build JBTIS target platform 4.2.3.Final for Luna using the specific Jenkins job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-target-platform-4.2.x/

* Tag a label onto the GIT target platform sources associated with any target platform build committed to nexus.
* Label the Jenkins build and set 'keep forever".

The staging checkbox simply controls whether the generated artifacts are published to the staging area.

==== Publish the Community IS Target Platform Components

Given a successful build from the previous step, make the JBTIS TP public.  This example uses a 4.2.3.Final-based target platform for Luna.

[source,bash]
----
# Copy the TP locally from staging  
cd ~/temp; mkdir -p tp; cd tp  
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-target-platform/4.2.3.Final .  
 
# Now copy the TP files onto jbosstools   
scp -r 4.2.3.Final tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/ 
----

Update the jbosstools target platform composites.
----
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/targetplatforms/jbtistarget/luna/compositeArtifacts.xml
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/targetplatforms/jbtistarget/luna/compositeContents.xml
----
Remember to update the timestamps (vim :call ReplaceTimestamp()):
[source,bash]
----
# Clone https://github.com/jbosstools/jbosstools-download.jboss.org  
# Edit composite*.xml - update version and also change timestamp.  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/targetplatforms/jbtistarget/luna
vi compositeArtifacts.xml (compositeContent.xml)
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
----
Once the PR has been issued and merged to https://github.com/jbosstools/jbosstools-download.jboss.org, push the changes to the download.jboss.org server. (Applying the PR is only the first half of getting these live.)

[source,bash]
----
# Push committed changes to the JBoss tools server.
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/luna  
put compositeArtifacts.xml  
put compositeContent.xml  
bye 
----

Verify:
----
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/jbtis/REPO
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/jbtis/earlyaccess/REPO
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/jbdsis/REPO
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/4.2.3.Final/jbdsis/earlyaccess/REPO
http://download.jboss.org/jbosstools/targetplatforms/jbtistarget/luna/
----

==== Promote the Published JBTIS Target Platform Components to Nexus 

The JBTIS target platform is now built and published but we're still not done.  It must finally be promoted to nexus (which is where most components will pull it from).  *Be cautious here - once created there's no easy way to remove it.*

* Clone jbosstools-integration-stack from jbosstools:

[source,bash]
----
# First build and deploy to staging  
git clone -o origin https://github.com/jbosstools/jbosstools-integration-stack.git ./jbosstools-integration-stack  
cd ./jbosstools-integration-stack/target-platform  

# Set the correct production branch (if necessary)
git checkout jbosstools-4.2.x
----

* Clear out your local maven repository and build/ deploy enabling the jboss-release profile:

[source,bash]
----
rm -rf ~/.m2/repository  
mvn -U -s ~/.m2/settings-staging.xml -DuseReleaseProfile=true -Pjboss-release clean deploy  
----
 
*If you get an Error 401 - check your ~/.m2/settings-staging.xml - make sure your server passwords are encrypted correctly.*
 
* Now promote from staging to the release nexus (log into sonatype nexus with your favorite browser)  
----
 https://repository.jboss.org/nexus/index.html#stagingRepositories  
---- 
Look for 'jboss_releases_staging_profile-nnnn' - the Maven deploy from the previous step will have populated it. 
 
* Check the box to the left  
* Select the 'Close' button to finalize for release or select the 'Drop' button to delete the repository 
* Once the close has completed - click 'Refresh'
* Select the 'Release' button

Verify - https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/4.2.3.Final/

[NOTE]
----
Note:  A simple listing of the above URL will not cause the deployed directory to become visible.  An artifact must be requested by name to update the cache.  To be sure - check the origin URL to see that the nexus deployment completed successfully.  e.g.
----
http://origin-repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/ 

Send out a notification to jbds-is-pm and QE indicating that a new JBTIS target platform is available.  e.g.

[source,bash]
----
   Greetings -
      An updated JBTIS TP is available:

   https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/tools/integration-stack/target-platform/4.2.0.Beta2a/

   See Jira for details:

   https://issues.jboss.org/browse/JBTIS-328

   1. Pick up the org.eclipse.birt.feature.group for use in Teiid
   2. Update to Luna SR1
      http://download.jboss.org/jbosstools/updates/requirements/luna/201409180900-SR1
   3. Update JBoss Tools core target dependencies to CR1
      http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.CR1-updatesite-core/
      http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.CR1-updatesite-coretests/
   4. Update orbit requirements to 2014
      http://download.jboss.org/jbosstools/updates/requirements/orbit/R20140525021250

            --paull
----

*This completes the JBTIS Target Platform build/ release process.*

=== SAP Tooling Build/ Release Process
This section describes the process of building and releasing the SAP tooling p2 update site for both community and devstudio.

Git ref: https://github.com/jbosstools/jbosstools-fuse-extras/tree/master/jboss-fuse-sap-tool-suite

==== Jenkins SAP Build

As an example, lets build SAP 7.3.0.Beta2 for Luna using the Jenkins job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-fuse-sap-tooling-7.3.x/

The build parameters are self-explanatory.  Use care in deciding which Fuse tooling URL to use as there are class dependencies.

i.e.
fuse-tooling-url: http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/fuse-tooling/7.3.0.Beta5/all/repo/

Upon successful completion, this build will invoke the SAP tooling publish Jenkins job:

Git ref: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-fuse-sap-tooling-publish-7.3.x/

For a development build, our example yields the following:

http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/7.3.0.Beta2/all/

This effectively publishes the community SAP tooling bits.  The production devstudio bits require that the tooling update site is rsync'd to the devstudio.redhat.com server.

==== Publish the Community SAP Update Site

[source,bash]
----
mkdir -p ~/temp/release;  cd ~/temp/release  
  
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/compositeArtifacts.xml .
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/compositeContent.xml .
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/7.3.0.Beta2a .

rsync -arzq --protocol=28 compositeArtifacts.xml devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/jboss-fuse-sap-tool-suite/
rsync -arzq --protocol=28 compositeContent.xml devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/jboss-fuse-sap-tool-suite/
rsync -arzq --protocol=28 7.3.0.Beta2a devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/jboss-fuse-sap-tool-suite/
----
Verify

http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/jboss-fuse-sap-tool-suite/7.3.0.Beta2a/
https://devstudio.redhat.com/updates/8.0/integration-stack/jboss-fuse-sap-tool-suite/7.3.0.Beta2a/

=== JBTIS Aggregate/ Discovery Build/ Release Process
This section describes the process of building and releasing the JBTIS aggregate p2 update site and the JBoss Central update site.  The project architecture is as follows:

[source,bash]
----
 jbosstools
 JBTIS - Community side.  Mylyn discovery and Equinox P2 update site generation.

     discovery
     JBTIS JBoss Tools Central Integration Stack discovery update generation.

        generation
        Create the Mylyn directory XML.

        org.jboss.tools.central.discovery.integration-stack
        Create the JBoss Tools central discovery update plugin.  Specifies connector 
        descriptors, installation units, etc.

     site
     JBTIS composite artifacts, content and p2 update categories build.

     site-final
     JBTIS .Final only composite artifacts, content and p2 update categories mirror.

     site-ea
     JBTIS early access (EA) only composite artifacts, content and p2 update categories mirror.
----

Git ref: https://github.com/jbosstools/jbosstools-integration-stack/tree/master/jbosstools

==== Jenkins JBTIS Aggregate Discovery Build

As an example, lets build JBTIS 4.3.0.Alpha2 for Mars using the Jenkins job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-disc/

The build type is selectable.  Use "integration" for builds that are better than continuous integration/ nightly but not quite milestone, "development" for milestones (i.e. beta and CR builds) and "stable" for final release builds.  Also note the upstream jbosstools site references.

Upon successful completion, this build will invoke the early access aggregate build:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-disc-mars-ea

Fun Facts:

I started this build 6 hours ago - what's going on?

Lets see with the Jenkins stats view:  https://jenkins.mw.lab.eng.bos.redhat.com/hudson/

* Tag a label onto the GIT sources associated with any build committed to a milestone or release.  It is a required parameter to the configuration.  (i.e. JBTIS-4.1.6.Final)

* Label the Jenkins build and set 'keep forever".

==== Publish the Community Integration Stack Components

There exists a separate Jenkins job to move the build artifacts out of the JBoss tools staging area (where the JBTIS aggregate build put them) into a JBoss tools update area.

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish-4.1.x/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish-4.2.x/

Match the build type to the aggregate build type from the previous section and match the target folder to the aggregate build version string.  Upon successful completion, the JBTIS-aggregate-publish project will invoke the early access aggregate publish job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBTIS-aggregate-publish/JBTIS-aggregate-publish-ea

[NOTE]
----
Verify - note that the offline zip version is also created:

http://download.jboss.org/jbosstools/updates/development/kepler/integration-stack/aggregate/4.1.5.CR1/
http://download.jboss.org/jbosstools/updates/development/kepler/integration-stack/aggregate/jbosstools-integration-stack-aggregate-4.1.5.CR1.zip

http://download.jboss.org/jbosstools/updates/development/mars/integration-stack/aggregate/4.3.0.Alpha2/
http://download.jboss.org/jbosstools/updates/development/mars/integration-stack/aggregate/4.3.0.Alpha2/earlyaccess/
http://download.jboss.org/jbosstools/updates/development/mars/integration-stack/aggregate/jbosstools-integration-stack-aggregate-4.3.0.Alpha2.zip
http://download.jboss.org/jbosstools/updates/development/mars/integration-stack/aggregate/jbosstools-integration-stack-aggregate-4.3.0.Alpha2-earlyaccess.zip
----

==== Publish and Push the JBTIS Aggregate p2 Update Site

In this example we'll use the development 4.3.0.Alpha2 build.  Clone jbosstools-download.jboss.org and update the composites in both the integration-stack directory and integration-stack/aggregate to reflect the new version and then update the timestamps.  Remember to update both the released composites as well as the early access composites.

[source,bash]
----
# Clone https://github.com/jbosstools/jbosstools-download.jboss.org  
# Edit composite*.xml - update version and also change timestamp.  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/mars/integration-stack/  
vi compositeArtifacts.xml (compositeContent.xml)
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
      
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/mars/integration-stack/aggregate  
vi compositeArtifacts.xml  (compositeContent.xml) 
<esc> :call ReplaceTimestamp()  
<esc> :wq!  

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/mars/integration-stack/earlyaccess
vi compositeArtifacts.xml  (compositeContent.xml) 
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
      
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/mars/integration-stack/earlyaccess
vi compositeArtifacts.xml  (compositeContent.xml)
<esc> :call ReplaceTimestamp()  
<esc> :wq!  
----

Commit and issue a PR.  Once the PR is merged, push the changes to the JBoss tools server:

[source,bash]
----
# Push the development changes to the server  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/mars/integration-stack/  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/  
put compositeArtifacts.xml  
put compositeContent.xml  
bye  
  
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/mars/integration-stack/aggregate  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/aggregate  
put compositeArtifacts.xml  
put compositeContent.xml  

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/mars/integration-stack/earlyaccess
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/earlyaccess
put compositeArtifacts.xml  
put compositeContent.xml  
bye 
----

[NOTE]
----
Note: If you updated a stable version, update the development version with the same bits along with the development composites.  That way development is never behind stable.  e.g.
----

[source,bash]
----
cd ~/temp; mkdir -p updt; cd updt  
      
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/kepler/integration-stack/aggregate/4.1.6.Final .  
scp -r 4.1.6.Final  tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/kepler/integration-stack/aggregate/  

- or -

scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/luna/integration-stack/aggregate/4.2.2.Final .  
scp -r 4.2.2.Final  tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/aggregate/  

- or -

scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/mars/integration-stack/aggregate/4.3.0.Alpha2 .  
scp -r 4.3.0.Alpha2  tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/mars/integration-stack/aggregate/  
----

Verify (development):

http://download.jboss.org/jbosstools/updates/development/kepler/integration-stack/

http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/

http://download.jboss.org/jbosstools/updates/development/mars/integration-stack/

Verify (stable):

http://download.jboss.org/jbosstools/updates/stable/luna/integration-stack/
http://download.jboss.org/jbosstools/updates/stable/luna/integration-stack/aggregate
http://download.jboss.org/jbosstools/updates/stable/luna/integration-stack/earlyaccess

==== Publish and Push the JBTIS JBoss Central Discovery Jar

The JBoss Central discovery jar is actually committed to the discovery download site.  Update the directory XML as well.  Also note that if the discovery jar is for early access the jar name should be modified to use 'earlyaccess'.

[source,bash]
----
mkdir -p ~/temp/disc-jbtis;  cd ~/temp/disc-jbtis
wget http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.2.2.CR1/org.jboss.tools.central.discovery.integration-stack_4.2.2.CR1-v20150326-2110-B348.jar
wget http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.2.2.CR1/org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.2.2.CR1-v20150326-2110-B348.jar
 
# clone jbosstools-download.jboss.org 

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/plugins  
cp ~/temp/disc-jbtis/org.jboss.tools.central.discovery.integration-stack_4.2.2.CR1-v20150326-2110-B348.jar .
cp ~/temp/disc-jbtis/org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.2.2.CR1-v20150326-2110-B348.jar .

cd .. 
# edit jbosstools-directory.xml: 
# update org.jboss.tools.central.discovery.integration-stack_4.2.2.CR1-v20150326-2110-B348.jar 
# update org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.2.2.CR1-v20150326-2110-B348.jar

# edit jbosstools-earlyaccess.properties: 
# add/ update any IUs that are early access
----
[NOTE]
----
Note: If committing a stable discovery jar/ directory XML - repeat the steps into the development directory (e.g.):

    /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/plugins

Commit and issue a PR to http://download.jboss.org/jbosstools.  Once the PR has been merged, manually push the updated jar and jbosstools-directory.xml onto the JBoss server.
----
[source,bash]
----
cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna
put jbosstools-directory.xml
put jbosstools-earlyaccess.properties
bye  

cd /home/pleacu/git-clone/jbosstools-download.jboss.org/jbosstools/updates/development/luna/plugins  
sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/plugins  
put org.jboss.tools.central.discovery.integration-stack_4.2.2.CR1-v20150326-2110-B348.jar
put org.jboss.tools.central.discovery.integration-stack.earlyaccess_4.2.2.CR1-v20150326-2110-B348.jar
bye 
----
Verify:

http://download.jboss.org/jbosstools/updates/development/luna/jbosstools-directory.xml
http://download.jboss.org/jbosstools/updates/development/luna/jbosstools-earlyaccess.properties
http://download.jboss.org/jbosstools/updates/development/luna/plugins/

==== Publish the Community IS Sources

This is the JBTIS community project sources only.  Individual component's source bundles are carried in the aggregate.  In this example we're publishing the 4.1.6.Final JBTIS project sources (zip and MD5).

[source,bash]
----
mkdir -p ~/temp/release;  cd ~/temp/release  
  
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc-4.1.x/all/JBTIS-aggregate-disc-4.1.x-SNAPSHOT-src.zip .  

rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc-4.1.x/all/JBTIS-aggregate-disc-4.1.x-SNAPSHOT-src.zip.MD5 .  

mv JBTIS-aggregate-disc-4.1.x-SNAPSHOT-src.zip jbosstools-integration-stack-sources-4.1.6.Final.zip  

mv JBTIS-aggregate-disc-4.1.x-SNAPSHOT-src.zip.MD5 jbosstools-integration-stack-sources-4.1.6.Final.zip.MD5  

rsync -arzq --protocol=28 jbosstools-integration-stack-sources-4.1.6.Final.zip tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/kepler/integration-stack/aggregate  

rsync -arzq --protocol=28 jbosstools-integration-stack-sources-4.1.6.Final.zip.MD5 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/stable/kepler/integration-stack/aggregate 

-or-

rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc/all/JBTIS-aggregate-disc-SNAPSHOT-src.zip .
rsync -arzq --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/staging/JBTIS-aggregate-disc/all/JBTIS-aggregate-disc-SNAPSHOT-src.zip.MD5 .
 
# rename

rsync -arzq --protocol=28 JBTIS-aggregate-disc-4.2.0.Final-src.zip tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/aggregate
rsync -arzq --protocol=28 JBTIS-aggregate-disc-4.2.0.Final-src.zip.MD5 tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/development/luna/integration-stack/aggregate

----

==== Test Eclipse p2 Update

Install JBossTools from Eclipse Marketplace (i.e. JBossTools 4.1.2).

[source,bash]
----
# Start jbdevstudio or eclipse-with-jbosstools, then:  
Help > Install New Software...  
Add...  
 - use this for 'Location:' 
 http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/
 - or -
 http://download.jboss.org/jbosstools/updates/development/luna/integration-stack/earlyaccess
----

==== Test JBTIS JBoss Central Discovery Update

[source,bash]
----
# Using Eclipse Kepler, install 'JBoss Tools 4.1.2.Final' from Marketplace:  
./eclipse -vmargs -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.1.5.CR1/jbosstools-integration-stack-directory.xml \  
   -Djboss.discovery.site.url=p://download.jboss.org/jbosstools/discovery/development/integration-stack/4.1.5.CR1  

# Using Eclipse Luna, install 'JBoss Tools 4.2.0.Final' from Marketplace:  
./eclipse -vmargs -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.3.0.Alpha2/jbosstools-integration-stack-directory.xml
   -Djboss.discovery.site.integration-stack.url=http://download.jboss.org/jbosstools/discovery/development/integration-stack/4.3.0.Alpha2
----

==== Generate Release Notes

Start by generating a release notes report from JBTIS JIRA:

[source,bash]
----
https://issues.jboss.org/browse/JBTIS  
select Summary  
select Release Notes Report  
ctrl-select versions, Issue type: All  
select Next 
----

Edit the resulting report, use the existing release note format (JBDS not JBT).  Give to technical documentation along with closed Jira/BZs from each updated component.

==== Publish Release Notes

When you get the consolidated JBDSIS_Release_Notes.html from documentation:

[source,bash]
----
mv JBDSIS_Release_Notes.html Release_Notes_7.0.3.html
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/7.0/integration-stack/release-notes/
put Release_Notes_7.0.3.html
----

=== JBTIS Aggregate/ Discovery Website Update

Clone and modify any jbosstools website component features ascii doc files.  Also modify 'whatsnew' and download links.

Ref Git: https://github.com/jbosstools/jbosstools-website

Ref: http://tools.jboss.org/features/

Ref: http://tools.jboss.org/whatsnew/jbosstools/4.1.2.Final.html

Ref: http://tools.jboss.org/downloads/jbosstools_is/kepler

Build and verify the website before committing and issuing a PR.

Update products.yml:

[source,bash]
----
# Clone jbosstools-website  
# edit /home/pleacu/git-clone/jbosstools-website/_config/products.yml  
# Update supported_devstudio_is_version, devstudio_is, supported_jbt_is_version and jbt_is.  
----

Update JBoss Tools blog:

[source,bash]
----
# Clone jbosstools-website  
cd /home/pleacu/git-clone/jbosstools-website/blog 

# Use an older one as a template - note only one dot in file name 
cp 2015-03-11-JBTIS-420-Final.adoc 2015-03-18-JBTIS-421-Final.adoc
----

Test JBoss Tools web site:

Ref: https://github.com/jbosstools/jbosstools-website/blob/master/readme.adoc

[source,bash]
----
# In a bash shell...
bash --login
rvm use 1.9.3
rvm gemset create jbosstools-website
cd ~/git-clone/jbosstools-website/
rake setup
gem install bundler
bundle install
rake clean preview

# In a web browser...
http://localhost:4242/blog/2015-03-18-JBTIS-417-Final.html
http://localhost:4242/downloads/jbosstools_is/kepler/4.1.6.Final.html
----

See xcoulon to push the PR.

Verify:

http://tools.jboss.org/blog/

*This completes the JBTIS aggregate/ discovery build/ release process.*

== Production JBDSIS Build

The production JBDSIS build draws its content from the JBTIS build.  Consequently, the content of the production build is always less than or equal to the community build.  JBDSIS does not have its own composite files and category definitions for p2 update site artifacts.

=== JBDSIS Target Platform

*The JBDSIS target platform is built separately from the JBTIS target platform and is a result of different merge targets.*  The JBDSIS target platform does not merge in the community.target file.  It is created under the common JBTIS target platform build.

In this example the 8.0.2.GA target platform (Luna) repository is created.  First update the common and static update release areas.

[source,bash]
----
# Copy the TP locally from jbosstools (community)
cd ~/temp; mkdir -p tp; cd tp
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/4.2.3.Final .

rsync -arzq --protocol=28 4.2.3.Final/jbdsis devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/8.0.2.GA.jbds-is-target-platform
rsync -arzq --protocol=28 4.2.3.Final/jbdsis devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/8.0.2.GA.jbds-is-target-platform
----

URL:
https://devstudio.redhat.com/updates/8.0.0/8.0.2.CR1.jbds-is-target-platform/jbdsis/REPO
https://devstudio.redhat.com/updates/8.0.0/8.0.2.CR1.jbds-is-target-platform/jbdsis/earlyaccess/REPO

Next update the QE test staging area:

[source,bash]
----
ssh dev01.mw.lab.eng.bos.redhat.com  
sudo su - hudson  
cd /qa/services/http/binaries/RHDS/targetplatforms/jbdsistarget/  
scp -r tools@filemgmt.jboss.org:/downloads_htdocs/tools/targetplatforms/jbtistarget/4.2.3.Final .  

# Edit composites - change jbtis to jbdsis; Inspect  
mv 4.2.3.Final 8.0.2.GA
----

Verify:

http://www.qa.jboss.com/binaries/RHDS/targetplatforms/jbdsistarget/8.0.2.GA/
https://devstudio.redhat.com/updates/8.0.0/8.0.2.CR1.jbds-is-target-platform/jbdsis/REPO
https://devstudio.redhat.com/updates/8.0.0/8.0.2.CR1.jbds-is-target-platform/jbdsis/earlyaccess/REPO
https://devstudio.redhat.com/static/updates/8.0.0/8.0.2.CR1.jbds-is-target-platform/jbdsis/REPO
https://devstudio.redhat.com/static/updates/8.0.0/8.0.2.CR1.jbds-is-target-platform/jbdsis/earlyaccess/REPO

*** This completes the JBDSIS TP build/ release process.

=== JBDSIS Aggregate/ Discovery Build/ Release Process

This section describes the process of building and releasing the actual JBDSIS aggregate p2 update site and the JBoss Central update site.  The project architecture is as follows:
 
[source,bash]
----
 devstudio
 JBDSIS - Production side.  Mylyn discovery and Equinox P2 update site generation.

    discovery
    JBDSIS JBoss Tools Central Integration Stack discovery update generation.

	com.jboss.jbds.central.discovery.integration-stack
	Create the JBoss Tools central discovery update plugin.  Specifies connector descriptors, 
        installation units, etc.

	generation
	Create the Mylyn directory XML.

    site
    JBDSIS P2 update categories.  Composite content drawn from JBTIS.  Used for discovery XML generation.

    site-ga
    JBDSIS P2 release (GA) update categories.  Composite content drawn from JBTIS.

    site-ea
    JBDSIS P2 early access update categories.  Composite content drawn from JBTIS.
----

Git ref: https://github.com/jbosstools/jbosstools-integration-stack/tree/master/devstudio
 
==== Jenkins JBDSIS Aggregate Discovery Build:

As an example, lets build JBDSIS 8.0.0.CR2 for Luna using the specific Jenkins job:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/JBDSIS-aggregate-disc

Note the community JBTIS aggregate composite site from which this build draws its content.  As with the JBTIS build, the build type is selectable - make sure you select the correct parameter there as it affects the site index.html and the discovery site.

Upon successful completion of this build, the JBDSIS-aggregate-disc-luna-ga build will be invoked to build the release (.Final) components.  After that the JBDSIS-aggregate-disc-luna-ea build will be invoked to build the early access update site.

* Tag a label onto the GIT sources associated with any build committed to a milestone or release.  It is a required parameter to the configuration.  (i.e. JBDSIS-8.0.0.CR2)
* Label the Jenkins build and set 'keep forever".

==== Publish the Production Integration Stack Components

There exists a separate Jenkins job to move the build artifacts out of the JBoss tools staging area into a JBoss tools update area.  In this example the JBDSIS 8.0.2.CR2 development release is published.

Match the build type to the aggregate build type from the previous section.  Match the target folder to the aggregate build version string.

Verify:

http://www.qa.jboss.com/binaries/RHDS/updates/development/kepler/integration-stack/aggregate/8.0.2.CR2/
http://www.qa.jboss.com/binaries/RHDS/updates/development/luna/integration-stack/aggregate/8.0.0.CR2/
 
==== Publish and Push the JBDSIS Aggregate p2 Update Site

In this example we'll use the development 8.0.0.Beta2 build.    Update the production aggregate Eclipse p2 repository as well as the offline .zip file.  If this is an earlyaccess jar - update the earlyaccess (devstudio/earlyaccess) composites.

[source,bash]
----
cd ~/temp; mkdir -p jbds-update; cd jbds-update

# Copy the p2 update site to the devstudio update areas:  
rsync -aPrzq --protocol=28  pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/8.0.0.CR2 .

rsync -arzq --protocol=28 8.0.0.CR2/ devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/8.0.0.CR2.jbds-is
rsync -arzq --protocol=28 8.0.0.CR2/ devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/8.0.0.CR2.jbds-is
     
# Copy the p2 update site zip to the devstudio update areas:  
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/devstudio-integration-stack-aggregate-8.0.0.Beta2.zip devstudio-integration-stack-aggregate-8.0.0.Beta2.zip
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/devstudio-integration-stack-aggregate-8.0.2.GA-earlyaccess.zip devstudio-integration-stack-aggregate-8.0.2.GA-earlyaccess.zip

rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.0.Beta2.zip devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.0.Beta2.zip
rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.0.Beta2.zip devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.0.Beta2.zip

rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.2.GA-earlyaccess.zip devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.2.GA-earlyaccess.zip
rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.2.GA-earlyaccess.zip devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.2.GA-earlyaccess.zip

# Copy the p2 update site MD5 to the devstudio update areas:  
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/devstudio-integration-stack-aggregate-8.0.0.Beta2a.zip.MD5 devstudio-integration-stack-aggregate-8.0.0.Beta2a.zip.MD5
rsync --rsh=ssh pleacu@dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/devstudio-integration-stack-aggregate-8.0.2.GA-earlyaccess.zip.MD5 devstudio-integration-stack-aggregate-8.0.2.GA-earlyaccess.zip.MD5

rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.0.Beta2a.zip.MD5 devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.0.Beta2a.zip.MD5
rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.0.Beta2a.zip.MD5 devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.0.Beta2a.zip.MD5

rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.2.GA-earlyaccess.zip.MD5 devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.2.GA-earlyaccess.zip.MD5
rsync -arzq --protocol=28 devstudio-integration-stack-aggregate-8.0.2.GA-earlyaccess.zip.MD5 devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/static/updates/8.0.0/jbdevstudio-integration-stack-updatesite-8.0.2.GA-earlyaccess.zip.MD5
----

Note that a stable build will be retrieved from a corresponding stable path.  If you update stable make sure to update development as well.

Clone jbdevstudio-website and update the composites in both the integration-stack directory and integration-stack/aggregate to reflect the new version and then update the timestamps.

Git ref: https://github.com/jbdevstudio/jbdevstudio-website

===== Update the developer studio composite update sites.

[NOTE]
----
Note: Don't forget to update index.html!
----

[source,bash]
----
# Update https://devstudio.redhat.com/updates/8.0-development/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/integration-stack  
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0-development/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/integration-stack/earlyaccess
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0-staging/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-staging/integration-stack  
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0-staging/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-staging/integration-stack/earlyaccess
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0/integration-stack/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/integration-stack  
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0/integration-stack/earlyaccess/compositeContent.xml, compositeArtifacts.xml, index.html  
 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/integration-stack/earlyaccess
# update compositeArtifacts.xml,  compositeContent.xml, index.html  
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/central/integration-stack  
# edit index.html

----

If this is an earlyaccess jar - update the earlyaccess (devstudio/earlyaccess) composites.

[source,bash]
----
# Update https://devstudio.redhat.com/updates/8.0-development/compositeContent.xml, compositeArtifacts.xml
 cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0-development 
# update compositeArtifacts.xml,  compositeContent.xml
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

# Update https://devstudio.redhat.com/updates/8.0-staging/compositeContent.xml, compositeArtifacts.xml
 cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0-staging
# update compositeArtifacts.xml,  compositeContent.xml
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!
----

Commit and issue a PR.  Once the PR is merged, push the changes to the devstudio tools server:

[source,bash]
----
cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/updates/8.0-development/integration-stack  
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-development/integration-stack  
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye

cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/updates/8.0-development/integration-stack/earlyaccess
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-development/integration-stack/earlyaccess  
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye

cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/updates/8.0-staging/integration-stack  
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-staging/integration-stack  
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye

cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/updates/8.0-staging/integration-stack/earlyaccess
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-staging/integration-stack/earlyaccess
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> put index.html  
sftp> bye

cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/earlyaccess/8.0-development
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/earlyaccess/8.0-development
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> bye

cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/earlyaccess/8.0-staging
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/earlyaccess/8.0-staging
sftp> put compositeArtifacts.xml  
sftp> put compositeContent.xml     
sftp> bye
----

Update the QE test staging area:

[source,bash]
----
ssh dev01.mw.lab.eng.bos.redhat.com  
sudo su - hudson  
cp -r /qa/services/http/binaries/RHDS/updates/development/kepler/integration-stack/aggregate/8.0.2.CR2 /qa/services/http/binaries/RHDS/builds/staging/jbdsis-8.0.2-updatesite/ 
- or - 
cp -r /qa/services/http/binaries/RHDS/updates/development/luna/integration-stack/aggregate/8.0.0.Beta2a /qa/services/http/binaries/RHDS/builds/staging/jbdsis-8.0.0.beta2a-updatesite/
----

==== Publish and Push the JBDSIS JBoss Central Discovery Jar

The JBoss Central discovery jar is actually committed to the discovery download site.  Update the directory XML as well.

[source,bash]
----
mkdir -p ~/temp/disc;  cd ~/temp/disc
wget http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.1.GA/com.jboss.jbds.central.discovery.integration-stack_8.0.1.GA-v20150408-1203-B104.jar
wget http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.1.GA/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.1.GA-v20150408-1203-B104.jar 

# clone jbdevstudio-website

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/discovery
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack_8.0.1.GA-v20150408-1203-B104.jar .
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.1.GA-v20150408-1203-B104.jar .

cd ..
# edit devstudio-directory.xml: update com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.0.Beta2-v20141001-1500-B67.jar
# edit devstudio-earlyaccess.properties: add any IUs that are early access

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-staging/discovery
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack_8.0.1.GA-v20150408-1203-B104.jar .
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.1.GA-v20150408-1203-B104.jar .

cd ..
# edit devstudio-directory.xml, devstudio-earlyaccess.properties

----

[NOTE]
----
Commit and issue a PR to https://github.com/jbdevstudio/jbdevstudio-website.  Once the PR has been merged, manually push the updated jar and devstudio-directory.xml onto the JBoss server.
----

[source,bash]
----
# Copy the JBDSIS central jar and metadata files into position  
 cd ~/temp/disc  
 wget http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.0.Beta2/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.0.Beta2-v20141023-1623-B69.jar  

 sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-development/discovery  
 - or -
 sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-staging/discovery  

 put com.jboss.jbds.central.discovery.integration-stack_8.0.0.Beta2-v20140409-1834-B7.jar
 bye

 cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0-development/
 sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0-development/
 put devstudio-directory.xml
 put devstudio-earlyaccess.properties
 bye 
----

Clone jbdevstudio-website and update the JBDSIS JBoss Central JAR file and devstudio-directory discovery XML file.  Update the composites and index.html in the 8.0/integration-stack, 8.0/central/integration-stack and 8.0 discovery directory then push the files to the devstudio server.

Git ref: https://github.com/jbdevstudio/jbdevstudio-website

Verify: https://devstudio.redhat.com/updates/8.0-development/devstudio-directory.xml

==== Go live!
[source,bash]
----
cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/discovery  
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack_8.0.2.GA-v20150408-1203-B104.jar .
cp ~/temp/disc/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.2.GA-v20150408-1203-B104.jar .
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/discovery 
   sftp> put com.jboss.jbds.central.discovery.integration-stack_8.0.2.GA-v20150408-1203-B104.jar
   sftp> put com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.2.GA-v20150408-1203-B104.jar
   sftp> bye

cd ..
# edit devstudio-directory.xml, devstudio-earlyaccess.properties
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0  
   sftp> put devstudio-directory.xml
   sftp> put devstudio-earlyaccess.properties
      
# update compositeArtifacts.xml, compositeContent.xml, index.html - versions and timestamps  
cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/updates/8.0/integration-stack  
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack  
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml     
   sftp> put index.html  
   sftp> bye

cd /home/pleacu/git-clone/PR/jbdevstudio-website/content/updates/8.0/integration-stack/earlyaccess
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/integration-stack/earlyaccess
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml     
   sftp> put index.html  
   sftp> bye

cd /home/pleacu/git-clone/jbdevstudio-website/content/updates/8.0/central/integration-stack  
sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/central/integration-stack/  
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml  
   sftp> put index.html  
      
# Update https://devstudio.redhat.com/updates/8.0/compositeContent.xml, compositeArtifacts.xml
cd /home/pleacu/git-clone/jbdevstudio-website/content/earlyaccess/8.0
# update compositeArtifacts.xml,  compositeContent.xml
# edit composite*.xml - also change timestamp!  
vi compositeArtifacts.xml  
<esc> :call ReplaceTimestamp()  
<esc> :wq!

sftp devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/earlyaccess/8.0
   sftp> put compositeArtifacts.xml  
   sftp> put compositeContent.xml     
   sftp> bye
----

[NOTE]
----
Note: If you updated a stable version, update the development version with the same bits.  That way development is never behind stable.
----

==== Git Status

Your git status should appear something like this:

[source,bash]
----
# On branch JBTIS-406
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   earlyaccess/8.0-development/compositeArtifacts.xml
#	modified:   earlyaccess/8.0-development/compositeContent.xml
#	modified:   earlyaccess/8.0-staging/compositeArtifacts.xml
#	modified:   earlyaccess/8.0-staging/compositeContent.xml
#	modified:   earlyaccess/8.0/compositeArtifacts.xml
#	modified:   earlyaccess/8.0/compositeContent.xml
#	modified:   updates/8.0-development/devstudio-directory.xml
#	modified:   updates/8.0-development/devstudio-earlyaccess.properties
#	modified:   updates/8.0-development/integration-stack/compositeArtifacts.xml
#	modified:   updates/8.0-development/integration-stack/compositeContent.xml
#	modified:   updates/8.0-development/integration-stack/index.html
#	modified:   updates/8.0-staging/devstudio-directory.xml
#	modified:   updates/8.0-staging/devstudio-earlyaccess.properties
#	modified:   updates/8.0-staging/integration-stack/compositeArtifacts.xml
#	modified:   updates/8.0-staging/integration-stack/compositeContent.xml
#	modified:   updates/8.0-staging/integration-stack/index.html
#	modified:   updates/8.0/devstudio-directory.xml
#	modified:   updates/8.0/devstudio-earlyaccess.properties
#	modified:   updates/8.0/integration-stack/compositeArtifacts.xml
#	modified:   updates/8.0/integration-stack/compositeContent.xml
#	modified:   updates/8.0/integration-stack/index.html
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	updates/8.0-development/discovery/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.2.GA-v20150220-1139-B91.jar
#	updates/8.0-development/integration-stack/earlyaccess/
#	updates/8.0-staging/discovery/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.2.GA-v20150220-1139-B91.jar
#	updates/8.0-staging/integration-stack/earlyaccess/
#	updates/8.0/discovery/com.jboss.jbds.central.discovery.integration-stack.earlyaccess_8.0.2.GA-v20150220-1139-B91.jar
#	updates/8.0/integration-stack/earlyaccess/
----

==== Test Eclipse p2 Update

[source,bash]
----
Start jbdevstudio or eclipse-with-jbds, then:  
    Help > Install New Software...  
    Add...  
    - use this for 'Location:'  
    https://devstudio.redhat.com/updates/7.0-development/integration-stack/  
----

==== Test JBDSIS JBoss Central Discovery Update

[source,bash]
----
./jbdevstudio -vmargs -Djboss.discovery.directory.url=http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.2.CR2/devstudio-integration-stack-directory.xml  
      -Djboss.discovery.site.url=http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.2.CR2

./jbdevstudio -vmargs -Djboss.discovery.directory.url=http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.0.Beta2/devstudio-integration-stack-directory.xml  
      -Djboss.discovery.site.url=http://www.qa.jboss.com/binaries/RHDS/discovery/integration/integration-stack/8.0.0.Beta2

----

==== Test JBDSIS Offline Install

To install JBDSIS in a completely offline way, you need three zips or jars to act as update sites:

* JBDS target platform zip
* JBDS installer or update site zip
* JBDS IS update site zip

Retrieve the offline JBDS zips:

https://devstudio.redhat.com/updates/8.0/#offline

If you don't already have installFromTarget.sh, see this:

https://gist.github.com/nickboldt/e899f4e22a0654af667e

Install JBDS into ~/offline, then:

[source,bash]
----
~/bin/installFromTarget.sh -ECLIPSE ~/offline/studio/ -INSTALL_PLAN  
'jar:file:///home/pleacu/install/jbdevstudio-integration-stack-updatesite-8.0.2.CR1.zip!/,jar:file:///home/pleacu/install/jbdevstudio-updatesite-7.1.1.GA-v20140314-2145-B688.zip!/,jar:file:///home/pleacu/install/jbdevstudiotarget-4.32.0.Final.zip!/'  
----

==== Update the Customer Support Portal

Generate a ticket with engineering services. 
[source,bash]
---- 
Ref: https://engineering.redhat.com/rt/Ticket/Display.html?id=296645
Ref: https://engineering.redhat.com/rt/Ticket/Display.html?id=341933
----
Verify:

https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=8.0.0

*This completes the JBDSIS aggregate/ discovery build/ release process.*
