= Start of Sprint Steps

At the start of a sprint, a number of things need to be done:

* Create New & Noteworthy JIRAs

* Close out previous sprint and start a new one in JIRA

* Verify correct versions in JIRA for JBIDE and JBDS, including start/end/code freeze dates (or else jiralint will break)

* Update jobs to run against the correct branch / target platform versions (if applicable)

* Update jobs to run against the correct Eclipse Platform / EPP bundle

== Create New & Noteworthy JIRAs

Configure, then run this job: https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-00-new-and-noteworthy-jiras/

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

versionWithRespin_jbt=4.4.4.AM2
versionWithRespin_ds=10.4.0.AM2

ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-00-new-and-noteworthy-jiras; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

Or, you can run this script:

[source,bash]
----

python /tmp/jbt.github/jbosstools-build-ci/util/createnewandnoteworthy.py -u usernameJIRA -p passwordJIRA -s https://issues.stage.redhat.com \
  -i ${versionWithRespin_jbt} -d ${versionWithRespin_ds}

----

NOTE: Replace issues.stage.redhat.com with issues.redhat.com to create real issues.

== Close out previous sprint and start a new one in JIRA

See:

* https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=3484&view=planning.nodetail
* https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=3410&view=planning.nodetail
* https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=641&view=planning.nodetail
* https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=3482&view=planning.nodetail
* https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=3382&view=planning.nodetail

== Verify correct versions in JIRA for JBIDE and JBDS, including start/end/code freeze dates (or else jiralint will break)

See:

* https://issues.redhat.com/plugins/servlet/project-config/JBIDE/versions
* https://issues.redhat.com/plugins/servlet/project-config/JBDS/versions

Then run:

* https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-jiralint-daily/
* https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-jiralint-weekly/


== Update jobs to run against the correct branch / target platform versions

If applicable, you might need to update jobs to pull sources from a new branch (4.4.x or 4.4.4.x) or a new target platform.

== Update jobs to run against the correct Eclipse Platform / EPP bundle

Remember to update this file as it's the one that automated tests used to know which version of Eclipse to use:

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/jbosstools-jenkins.properties

This should be updated every time the target platform is updated, so that the platform version matches the version in the target platform.

If these don't match, headless installation tests will fail, such as:

* https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/build_master/job/jbosstools-install-p2director.install-tests.matrix_master/
* https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/build_master/job/jbosstools-composite-install_master/
