= Staging milestone devstudio Installers & update sites for QE

This document describe how to provide a valid Red Hat Developer Studio build to QE so they can test us.

= Pre-Staging Steps

See link:1_Staging_preparation.adoc[Pre-Staging]

== Clone jbosstools-build-ci repo or link to it from elsewhere on disk

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ -d ~/tru/jbosstools-build-ci ]]; then ln -s ~/tru/jbosstools-build-ci; fi
if [[ ! -d jbosstools-build-ci ]] && [[ -L jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout master
chmod +x -R */*.sh */*/*.sh

----


= Staging steps

[IMPORTANT]
====

Before running any of the jobs or scripts below, make sure to set the correct versions to the values for the release you're staging or releasing.

* look for versionWithRespin_ or version_, update to version you're staging
* look for PREV and NEXT variables; set to previous / next milestone (AMx, AMy, AMz, Final/GA)
* check TARGET_PLATFORM_ versions are current w/ latest versions
* check parent pom version, version_parent, is current
* check Integration Stack variables like earlyaccess_IS, version_jbt_IS, version_ds_IS are correct. Double-check best values with Paul Leacu (pleacu).

Search for this regex:

versionWithRespin_(jbt|ds)=[0-9]|version_(parent|jbt|ds|jbt_IS|ds_IS)=[0-9]|_PREV=[0-9]|_NEXT=[0-9]|TARGET_PLATFORM_.+(MIN|MAX)=[0-9]

====

== Update Discovery Sites and URLs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Verify correct version set in com.jboss.devstudio.central.core

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Disable jobs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Stage to devstudio.redhat.com

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

=== Fetch devstudio installer (for later smoke test)

TIP: Once the staging build folder exists, start fetching the devstudio installer (we'll need it later to do a smoke test)

[source,bash]
----

## TODO CONTINUE HERE ##

cd ~/tmp
versionWithRespin_ds=12.9.0.GA
installerJar=$(wget -O - -q https://devstudio.redhat.com/12/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
if [[ ${installerJar} ]]; then
  time wget https://devstudio.redhat.com/12/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}
else
  echo ""; echo "[ERROR] No installer found! Try again later!"
fi

----

You'll use this downloaded installer later, but since it takes a while to download, it's more efficient to start it now.


=== Cleanup OLD builds

Optional step.

Run this job to move any old builds into an OLD/ folder for later cleanup, or delete them immediately.

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites/


=== Update /staging/updates/ sites and merge in Integration Stack content

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Release the latest staging site to ide-config.properties

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Smoke test the release (manually)

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Bring Your Own Eclipse category from

https://devstudio.redhat.com/12/staging/updates/

3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----

versionWithRespin_ds=12.9.0.GA
cd ~/tmp
installerJar=$(wget -O - -q https://devstudio.redhat.com/12/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"

# should have already downloaded this above
if [[ ! -f ${installerJar} ]]; then wget https://devstudio.redhat.com/12/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}; fi

if [[ -d ~/devstudio ]]; then mv ~/devstudio{,_BAK}; fi
echo 1 | java -jar ~/tmp/${installerJar} -console # install headlessly to ~/devstudio
mv ~/devstudio ~/${installerJar/.jar/} # rename install folder
if [[ -d ~/devstudio_BAK ]]; then mv ~/devstudio{_BAK,}; fi

cd ~/${installerJar/.jar/}/studio; ./devstudio -data /tmp/wksp-${installerJar/.jar/}

----

0. After downloading and installing devstudio from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Notify the team (send 1 email)

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Trigger QE Smoke tests (automated)

Trigger the QE smoke tests in https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

versionWithRespin_ds=12.9.0.GA
installerJar=$(wget -O - -q https://devstudio.redhat.com/12/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
version_ds_INST=${installerJar#devstudio-}
version_ds_INST=${version_ds_INST%-installer*}
echo "Devstudio installer version: ${version_ds_INST}"

# run the one buildflow job
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
jpcrumb=$(wget --no-check-certificate -q --auth-no-challenge --user ${KERBUSER} --password ${KERBPWD} --output-document - "${ccijenkins//\/job/}/crumbIssuer/api/xml?xpath=//crumb" | sed "s#<crumb>\([0-9a-f]\+\)</crumb>#\1#")
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in devstudio.buildflow.it.smoke; do
  prevJob=$(${JP} -s ${ccijenkins} -c ${jpcrumb} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="DEVSTUDIO_VERSION=${version_ds_INST}"
  nextJob=$(${JP} -s ${ccijenkins} -c ${jpcrumb} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s
done

----


== Verify install instructions are correct

Look at the .txt and .html files in https://devstudio.redhat.com/12/staging/builds/devstudio-12.9.0.GA-build-product/latest/all/

Verify that they contain correct install/usage instructions & versions.

If anything is wrong, fix it by hand, then also commit your changes to the templates.

https://github.com/jbdevstudio/jbdevstudio-product/commit/3827045dca85e73c5ae339cc13f514591e3c1835
https://github.com/jbdevstudio/jbdevstudio-product/commit/e6c2954207d1db7451f7adfd2d89c7ceccd6adbe


NOTE: If you're staging a non-GA release, you can ignore everything below this line!

---

= Staging GA devstudio Installers & update sites for QE

== Rename GA artifacts to remove timestamp and buildID

For GA releases only!

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`devstudio-10.4.0.GA-v20151002-2235-B124-installer-standalone.jar` must be renamed to `devstudio-10.4.0.GA-installer-standalone.jar`.

Configure, then run this job: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jbosstools-releng/job/jbosstools-releng-push-to-staging-06-rename-GA-artifacts/

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

versionWithRespin_ds=12.9.0.GA

if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  jpcrumb=$(wget --no-check-certificate -q --auth-no-challenge --user ${KERBUSER} --password ${KERBPWD} --output-document - "${ccijenkins//\/job/}/crumbIssuer/api/xml?xpath=//crumb" | sed "s#<crumb>\([0-9a-f]\+\)</crumb>#\1#")
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-staging-06-rename-GA-artifacts; do
    prevJob=$(${JP} -s ${ccijenkins} -c ${jpcrumb} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}"
    nextJob=$(${JP} -s ${ccijenkins} -c ${jpcrumb} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" == "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    else
      ${JP} -s ${ccijenkins} -c ${jpcrumb} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -c ${jpcrumb} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----

== Announce internally for push to CSP staging site

Submit an RCM ticket to request that the binaries be uploaded to the CSP (Red Hat Customer Portal) and Download Manager.

IMPORTANT: As this takes some time and requires coordination with other teams, this step should be initiated as part of staging the bits for QE, to allow processing time.

Communicate with Chris O'Brien (internal IRC: siege) to coordinate the release. All the above can happen in parallel / before the updates below.

The easiest approach is to clone an old ticket and update the links/versions to the new release version.

Previous tickets:

* https://projects.engineering.redhat.com/browse/RCM-42535
* https://projects.engineering.redhat.com/browse/RCM-37161


== Commit updates to release guide (including this document)

[source,bash]
----

cd ~/truu # ~

version_jbt=4.9.0.Final
version_ds=12.9.0.GA
cd jbdevstudio-devdoc/release_guide/
git commit -s -m "update release guide for ${version_jbt} and ${version_ds}" .
git push origin HEAD:master

----


== Commit updates to job configs

See https://github.com/jbosstools/jbosstools-devdoc/blob/master/building/jenkins_job_maintenance.adoc

Jobs are stored in this repo:

https://github.com/jbdevstudio/jbdevstudio-ci/tree/master/cache/https
