= Publishing JBT update sites for QE

This document describe how to provide a valid JBoss Tools build to QE so they can test us.

== Pre-Staging Steps

See link:1_Staging_preparation.adoc[Pre-Staging]

=== Clone jbosstools-build-ci repo or link to it from elsewhere on disk

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ -d ~/tru/jbosstools-build-ci ]]; then ln -s ~/tru/jbosstools-build-ci; fi
if [[ ! -d jbosstools-build-ci ]] && [[ -L jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout master
chmod +x -R */*.sh */*/*.sh

----

=== Remind people about jira triage

Kick this job to send reminder emails to the team re unresolved JIRAs with fixversion = current release.

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-jiralint-weekly; do
  ${JP} -s ${ccijenkins} -j ${j} -t build
done


# optional
browser=/usr/bin/google-chrome; if [[ ! -x ${browser} ]]; then browser=/usr/bin/firefox; fi
${browser} https://issues.redhat.com/plugins/servlet/project-config/JBIDE/versions \
  https://issues.redhat.com/plugins/servlet/project-config/JBDS/versions

----

== Staging steps

[NOTE]
====
Note that +sftp://tools@[IP FOR filemgmt]:/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+

(Use filemgmt IP instead of FQDN because it's 3x faster!)

If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools .
A Jenkins job can then be triggered to sync changes to download.jboss.org: https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-download.jboss.org-rsync-from-git/
====

[IMPORTANT]
====

Before running any of the jobs or scripts below, make sure to set the correct versions to the values for the release you're staging or releasing.

* look for *versionWithRespin_* or *version_*, update to version you're staging
* look for *PREV* and *NEXT* variables; set to previous / next milestone (AMx, AMy, AMz, Final/GA)
* check *TARGET_PLATFORM_* versions are current w/ latest versions
* check parent pom version, version_parent, is current
* check Integration Stack variables like *earlyaccess_IS*, *version_jbt_IS*, *version_ds_IS* are correct. Double-check best values with Paul Leacu (pleacu).

Search for this regex:

 versionWithRespin_|version_|PREV|NEXT|TARGET_PLATFORM_|version_parent|version_jbt_IS

====


=== Verify correct versions, branches exist, and root poms are correct

Configure, then run this job:

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

version_parent=4.14.0.Final-SNAPSHOT
versionWithRespin_jbt=4.14.0.Final
versionWithRespin_ds=12.14.0.GA
version_jbt=$(echo ${versionWithRespin_jbt} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
stream_jbt=master
github_branch=master

ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-01-check-versions-branches-root-poms; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="stream_jbt=${stream_jbt}&github_branch=${github_branch}&version_parent=${version_parent}&version_jbt=${version_jbt}&version_ds=${version_ds}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
    browser=/usr/bin/google-chrome; if [[ ! -x ${browser} ]]; then browser=/usr/bin/firefox; fi
    ${browser} ${ccijenkins}/${j} &
  else
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
  fi
done
echo "done."
exit 0

----

Once the above conditions have been met, you can proceed to the next steps.


=== Disable jobs

To prevent accidentally rebuilding something while you\'re copying it away, make sure that all the master branch jobs are disabled. These include all product, composite and aggregate jobs:

[source,bash]
----
# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

stream_jbt=master
stream_ds=master
ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/build_master/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
# MASTER jobs
for p in base build-ci build.parent central discovery forge fuse-extras fuse \
hibernate integration-tests.aggregate javaee-tests-matrix javaee jst \
livereload openshift-restclient-java openshift quarkus server vpe webservices \
install-p2director.install-tests.matrix composite-install \
build-sites.aggregate.site build-sites.aggregate.coretests-site build-sites.aggregate.child-sites; do
    j=jbosstools-${p}_master
    echo "[${JP}] ${ccijenkins}/${j} disable"
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
done

# DEVSTUDIO jobs
for p in product versionwatch; do
    j=devstudio.${p}_${stream_ds}
    echo "[${JP}] ${ccijenkins}/${j} disable"
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
done

# RELENG jobs
ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
for p in maven-plugins.tycho-plugins pipeline; do
    j=jbosstools-${p}_${stream_jbt}
    echo "[${JP}] ${ccijenkins}/${j} disable"
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
done

# CENTRAL PROJECTS jobs
ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/central-projects/job/
for p in fabric8analytics; do
    j=jbosstools-${p}_${stream_jbt}
    echo "[${JP}] ${ccijenkins}/${j} disable"
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
done

echo "done."
exit 0

----


=== Update Discovery Sites and URLs

[[update-discovery-urls]]
Update the *stable branch* (or master) discovery job ( https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/build_master/job/jbosstools-discovery_master/ ) to use the correct source URLs and versions 

Then respin the job:

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

versionWithRespin_jbt=4.14.0.Final
versionWithRespin_ds=12.14.0.GA
version_jbt=$(echo ${versionWithRespin_jbt} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
stream_jbt=master
TARGET_PLATFORM_VERSION_MAX=4.14.0.Final-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.14.0.Final-SNAPSHOT
version_jbt_IS=4.11.0.Final
version_ds_IS=12.11.0.GA
qual_IS=stable # or development
earlyaccess_IS="" # or earlyaccess/

ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/build_master/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-discovery_${stream_jbt}; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3

  data="buildType=staging&versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}&\
TARGET_PLATFORM_VERSION_MAX=${TARGET_PLATFORM_VERSION_MAX}&TARGET_PLATFORM_CENTRAL_MAX=${TARGET_PLATFORM_CENTRAL_MAX}&\
version_jbt_IS=${version_jbt_IS}&version_ds_IS=${version_ds_IS}&qual_IS=${qual_IS}&earlyaccess_IS=${earlyaccess_IS}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
    browser=/usr/bin/google-chrome; if [[ ! -x ${browser} ]]; then browser=/usr/bin/firefox; fi
    ${browser} ${ccijenkins}/${j} &
  else
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
  fi
done
echo "done."
exit 0

----


=== Download the latest Eclipse

You\'ll need this later for smoke testing. Start fetching it now to save time later.

[source,bash]
----

cd ~/tmp; wget http://download.eclipse.org/technology/epp/downloads/release/2019-09/R/eclipse-jee-2019-09-R-linux-gtk-x86_64.tar.gz &

----


=== Stage to download.jboss.org


==== Copy & rename builds & update sites from "snapshots" to "staging"

Here is a pair of jobs that perform the copy (& rename) from /snapshots/ to /staging/:

* https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_jbt/
* https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_ds/

NOTE: To save time, you can run this in parallel with the above step to create the Red Hat Central discovery site.

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

eclipseReleaseName=photon
devstudioReleaseVersion=12
versionWithRespin_jbt=4.14.0.Final
versionWithRespin_ds=12.14.0.GA
version_jbt=$(echo ${versionWithRespin_jbt} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
version_ds=$(echo ${versionWithRespin_ds} | sed -e '/[abcdwxyz]$/ s/\(^.*\)\(.$\)/\1/') # ***
TARGET_PLATFORM_VERSION_MAX=4.14.0.Final-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.14.0.Final-SNAPSHOT
stream_jbt=master
stream_ds=master

ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-03-verify-builds-update-sites; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  browser=/usr/bin/google-chrome; if [[ ! -x ${browser} ]]; then browser=/usr/bin/firefox; fi
  ${browser} ${ccijenkins}/${j} &
done
jobs="jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_ds jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_jbt"
for j in ${jobs}; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="eclipseReleaseName=${eclipseReleaseName}&devstudioReleaseVersion=${devstudioReleaseVersion}&stream_jbt=${stream_jbt}&stream_ds=${stream_ds}&\
versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}&skipdiscovery=false&onlydiscovery=false&buildType=staging&\
TARGET_PLATFORM_VERSION_MAX=${TARGET_PLATFORM_VERSION_MAX}&TARGET_PLATFORM_CENTRAL_MAX=${TARGET_PLATFORM_CENTRAL_MAX}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & # do not disable jobs as children may not all have started
  fi
  browser=/usr/bin/google-chrome; if [[ ! -x ${browser} ]]; then browser=/usr/bin/firefox; fi
  ${browser} ${ccijenkins}/${j} &
done
echo "done."
exit 0

----

If you can\'t get the job to run because CCI Jenkins is backlogged with a long queue, look in the job configuration and run the script manually on dev90.

https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_jbt/configure-readonly/

https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_ds//configure-readonly/

And now, we wait about 35 mins for the above jobs to complete.

```
Time passes...
```

When done, it\'s time to verify everything was pushed correctly.


==== Verify builds and update sites correctly pushed

[IMPORTANT]
====
This step should have fired automatically when the jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_* jobs completed.

But if it ran too early and not everything was ready, here\'s a job that verifies everything is published:

https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-03-verify-builds-update-sites/
====

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

eclipseReleaseName=photon
devstudioReleaseVersion=12
versionWithRespin_jbt=4.14.0.Final
versionWithRespin_ds=12.14.0.GA

ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-03-verify-builds-update-sites; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="eclipseReleaseName=${eclipseReleaseName}&devstudioReleaseVersion=${devstudioReleaseVersion}&\
versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}&\
skipdiscovery=false&onlydiscovery=false&buildType=staging"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
    browser=/usr/bin/google-chrome; if [[ ! -x ${browser} ]]; then browser=/usr/bin/firefox; fi
    ${browser} ${ccijenkins}/${j} &
  else
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
  fi
done

----


=== Update /staging/updates/ sites and merge in Integration Stack content

Here\'s a job that verifies everything is updated & merged:

https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-04-update-merge-composites-html/

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

## TODO CONTINUE HERE ##

versionWithRespin_jbt_PREV_GA=4.13.0.Final
versionWithRespin_jbt_PREV=4.14.0.AM1 # milestones
versionWithRespin_jbt=4.14.0.Final
versionWithRespin_jbt_NEXT=4.15.0.AM1

versionWithRespin_ds_PREV_GA=12.13.0.GA
versionWithRespin_ds_PREV=12.14.0.AM1 # milestones
versionWithRespin_ds=12.14.0.GA
versionWithRespin_ds_NEXT=12.15.0.AM1

buildType="staging"

version_jbt_IS=4.11.0.Final
version_ds_IS=12.11.0.GA
qual_IS=stable # or development
earlyaccess_IS="" # "" or "earlyaccess/" as applicable - see tip above

ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh

for j in jbosstools-releng-push-to-staging-00-validate-composites \
  jbosstools-releng-push-to-staging-04-update-ide-config.properties \
  jbosstools-releng-push-to-staging-04-update-merge-composites-html; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
done
sleep 3s

for j in jbosstools-releng-push-to-staging-04-update-merge-composites-html; do
  data="token=RELENG&buildType=${buildType}&\
versionWithRespin_jbt_PREV_GA=${versionWithRespin_jbt_PREV_GA}&versionWithRespin_jbt_PREV=${versionWithRespin_jbt_PREV}&versionWithRespin_jbt=${versionWithRespin_jbt}&\
versionWithRespin_jbt_NEXT=${versionWithRespin_jbt_NEXT}&versionWithRespin_ds_PREV_GA=${versionWithRespin_ds_PREV_GA}&versionWithRespin_ds_PREV=${versionWithRespin_ds_PREV}&\
versionWithRespin_ds=${versionWithRespin_ds}&versionWithRespin_ds_NEXT=${versionWithRespin_ds_NEXT}&version_jbt_IS=${version_jbt_IS}&version_ds_IS=${version_ds_IS}&\
qual_IS=${qual_IS}&earlyaccess_IS=${earlyaccess_IS}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"

  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
    browser=/usr/bin/google-chrome; if [[ ! -x ${browser} ]]; then browser=/usr/bin/firefox; fi
    ${browser} ${ccijenkins}/${j} &
  else
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
  fi
done
echo "done."
exit 0

----

==== Release the latest staging site to ide-config.properties

Here\'s a job that updates the ide-config.properties. Should have triggered in the previous step automatically.

https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-04-update-ide-config.properties/

==== Validate ide-config.properties - check composite sites

Here\'s a job that verifies everything is updated. Should have triggered in the previous step automatically.

https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-00-validate-composites/


==== Cleanup OLD builds

_Optional step._

Run this job to move any old builds into an OLD/ folder for later cleanup, or delete them immediately.

https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites/


=== Smoke test the release (manually)

Before notifying team of staged release, must check for obvious problems.

. Get a recent Eclipse (compatible with the target version of JBT)
. Install Abridged category from
http://download.jboss.org/jbosstools/photon/staging/updates/

. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
. Check log, start an example project, check log again

=== Notify the team (send 1 email)

Run this build:

https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/jbosstools-releng-push-to-staging-07-notification-emails/

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

versionWithRespin_jbt=4.14.0.Final
versionWithRespin_ds=12.14.0.GA
stream_jbt=master
github_branch=master
TARGET_PLATFORM_VERSION_MIN=4.14.0.Final-SNAPSHOT
TARGET_PLATFORM_VERSION_MAX=4.14.0.Final-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.14.0.Final-SNAPSHOT
respinSuffix=""
ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-07-notification-emails; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="github_branch=${github_branch}&versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}&\
TARGET_PLATFORM_VERSION_MIN=${TARGET_PLATFORM_VERSION_MIN}&TARGET_PLATFORM_VERSION_MAX=${TARGET_PLATFORM_VERSION_MAX}&TARGET_PLATFORM_CENTRAL_MAX=${TARGET_PLATFORM_CENTRAL_MAX}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
    browser=/usr/bin/google-chrome; if [[ ! -x ${browser} ]]; then browser=/usr/bin/firefox; fi
    ${browser} ${ccijenkins}/${j} &
  else
    { ${JP} -s ${ccijenkins} -j ${j} -t disable && ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep & }
  fi
done
echo "done."
exit 0

----


=== Disable staging jobs

You will need to disable the jobs once the bits are staged, so that they won\'t run accidentally.

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in \
  jbosstools-releng-push-to-staging-00-bootstrap-next-snapshot-sites \
  jbosstools-releng-push-to-staging-00-new-and-noteworthy-jiras \
  jbosstools-releng-push-to-staging-00-parent-pom-update-task-jiras \
  jbosstools-releng-push-to-staging-01-check-copy-speed \
  jbosstools-releng-push-to-staging-01-check-versions-branches-root-poms \
  jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_jbt \
  jbosstools-releng-push-to-staging-02-copy-builds-and-update-sites_ds \
  jbosstools-releng-push-to-staging-03-verify-builds-update-sites \
  jbosstools-releng-push-to-staging-04-update-ide-config.properties \
  jbosstools-releng-push-to-staging-04-update-merge-composites-html \
  jbosstools-releng-push-to-staging-00-validate-composites \
  jbosstools-releng-push-to-staging-07-notification-emails \
  jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites \
; do
  { ${JP} -s ${ccijenkins} -j ${j} -t disable & }
done
sleep 5s
echo "done."
exit 0

----


=== Enable Main jobs

You will need to re-enable the main (master) jobs once the bits are staged, so that CI builds can continue.

However, you do *NOT* do this until after QE approves, as the PRs are still enabled for day to day work.

If the next build WILL be a respin, you need to simply:

* re-enable all the jobs that were disabled above. If you committed a change to jbdevstudio-ci, you can simply revert that commit to re-enable the jobs!

[source,bash]
----

# kerberos login for the Jenkins server
KERBUSER=
KERBPWD=
export userpass=${KERBUSER}:${KERBPWD}

stream_jbt=master
stream_ds=master
ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/build_master/job/
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
# MASTER jobs
for p in base build-ci build.parent central discovery forge fuse-extras fuse \
hibernate integration-tests.aggregate javaee-tests-matrix javaee jst \
livereload openshift-restclient-java openshift quarkus server vpe webservices \
install-p2director.install-tests.matrix composite-install \
build-sites.aggregate.site build-sites.aggregate.coretests-site build-sites.aggregate.child-sites; do
    j=jbosstools-${p}_master
    echo "[${JP}] ${ccijenkins}/${j} enable"
    { ${JP} -s ${ccijenkins} -j ${j} -t enable & }
done

# DEVSTUDIO jobs
for p in product versionwatch; do
    j=devstudio.${p}_${stream_ds}
    echo "[${JP}] ${ccijenkins}/${j} enable"
    { ${JP} -s ${ccijenkins} -j ${j} -t enable & }
done

# RELENG jobs
ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/releng/job/
for p in maven-plugins.tycho-plugins pipeline; do
    j=jbosstools-${p}_${stream_jbt}
    echo "[${JP}] ${ccijenkins}/${j} enable"
    { ${JP} -s ${ccijenkins} -j ${j} -t enable & }
done

# CENTRAL PROJECTS jobs
ccijenkins=https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/central-projects/job/
for p in fabric8analytics; do
    j=jbosstools-${p}_${stream_jbt}
    echo "[${JP}] ${ccijenkins}/${j} enable"
    { ${JP} -s ${ccijenkins} -j ${j} -t enable & }
done
echo "done."
exit 0

----

IMPORTANT: TODO: if you switched the master branch jobs to run from origin/jbosstools-4.6.x or some other branch, make sure that the jobs are once again building from the correct branch.

If the next build will NOT be a respin, you will also need to ALSO make these changes to jobs, and upversion/release artifacts such as releng scripts or target platforms if you haven\'t done so already:

* set correct github branch, eg., switch from 4.5.3.x to 4.6.x
* upversion dependencies, eg., releng scripts move from version CR1 to CR1 (if that\'s been released)
* upversion target platforms / Central version (if those have been released)

