= Release JBoss Developer Studio Development Milestone

This document describe how to publish a valid JBoss Developer Studio build to production after being verified by QE.

CAUTION: TODO: when releasing GA make sure to :%s/development/stable/g and :%s/8.0-staging/8.0/g in product/features/com.jboss.jbds.product.feature/p2.inf

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten. 

Send an email to jbosstools-dev@ and external-exadel-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Rename artifacts to remove timestamp and buildID

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`jboss-devstudio-8.0.1.GA-v20141020-1042-B317-installer-standalone.jar` must be renamed to `jboss-devstudio-8.0.1.GA-installer-standalone.jar`.

To achieve that::
. Log in to dev01 or dev02
. `sudo su - hudson`
. `cd /qa/services/http/binaries/RHDS/${version}-build-core`
. `for f in $(ls jboss-devstudio-${version}-*); do echo $f; newName=$(echo $f | sed s#-v[[:digit:]]*-[[:digit:]]*-B[[:digit:]]*##); mv $f $newName; done`

== Announce internally for push to CSP staging site

First thing is to ask for availability of the binaries to CSP (Red Hat Customer Portal) and Golden Gate (JBoss products portal).

NOTE: As this takes some time and can be easily cancelled, this step can be anticipated a few days before release.
____
*To* release-engineering@redhat.com +
and +
*Cc* cobrien@redhat.com, ldimaggi@redhat.com, mmurray@redhat.com, jpallich@redhat.com, nboldt@redhat.com, mistria@redhat.com, maxanderse@redhat.com, bsutter@redhat.com +

[source,bash]
----
version=8.0.1.GA
versionWithRespin=8.0.1.GA # a, b, c...
echo "
Subject: 

JBoss Developer Studio ${version} available for push to CSP staging server

Body:

JBoss Developer Studio ${version} (to be renamed from ${versionWithRespin}) is available to push to CSP staging server, for subsequent smoke test & review by QE.

Please include the 5 jars/zips listed here:

* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/

We will also need GoldenGate links for the 5 artifacts above, as they need to be linked from these pages:

* https://www.jboss.org/products/devstudio/overview/
* https://www.jboss.org/products/devstudio/download/

Only ONE of those artifacts [0] require sign in, as it bundles EAP. The rest are free. 

[0] jboss-devstudio-*-installer-eap.jar 

Please note that the new CSP pages should include similar documentation
to the previous release but now I've pre-generated the HTML and text content in the above folder.

When pushed, please reply so that QE can review the CSP pages & files for push to production.

Note that in addition to the new CSP page, eg., [1] or [2], the CSP landing page [3] should also be updated to point to the latest release.

[1] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=8.0.0+CR1
[2] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=8.0.0
[3] https://access.redhat.com/downloads/

Thanks in advance,

"
----
____

As an answer, you get the links to the files on both portals. Keep them as you'll need them later.


== Move GA content to /static/

For GA releases ONLY, there are 4 update sites and 3 update site zips which should be moved to /static/ for Akamai caching.

[source,bash]
----
JBDS=devstudio@filemgmt.jboss.org:www_htdocs/devstudio
version=8.0.2.GA
jbtVersion=4.2.2.Final

for f in `echo ls | sftp $JBDS/updates/8.0.0/ 2>/dev/null | egrep "${jbtVersion}|${version}"`; do
  echo "rename updates/8.0.0/${f} static/updates/8.0.0/${f}" | sftp $JBDS
done

----

== Update composite files and devstudio-directory.xml to point at new discovery jar(s) from staging

[IMPORTANT]
====
TODO for CRx and GA: VERIFY CONTENTS OF DISCOVERY JAR ARE CORRECTLY POINTING AT

*  8.0 for /8.0/
*  8.0-development for /8.0-development/
*  8.0-staging for /8.0-staging/
====

You can run this script from your local machine:

[source,bash]
----
isGA=true # or true in case you're doing a GA
version=8.0.1.GA
versionWithRespin=8.0.1.GA
JBDS=devstudio@filemgmt.jboss.org:www_htdocs/devstudio

# set correct path for where you have project cloned on disk
pushd jbdevstudio-website/content
basedir=$(pwd)

dirs="8.0-staging 8.0-development"
if [[ $isGA == "true" ]]; then dirs="8.0-staging 8.0-development 8.0"; fi

for d in $dirs; do
  if [[ $d == "8.0-staging" ]]; then
    pushd ${basedir}/updates/${d}
      # Update URLs in discovery jars
      newJars=$(cat devstudio-directory.xml | grep entry | grep -v "integration-stack" | sed -e "s#.\+discovery/#discovery/#g" | sed -e "s#\.jar.\+#.jar#g")
      for newJar in $newJars; do 
        wget -q -nc https://devstudio.redhat.com/updates/${SRC_SITE}/discovery/${newJar}
        if [[ ! ${newJar##*.earlyaccess_*} ]] && [[ ${newJar##*integration-stack*} ]]; then
          newJarEA=${newJar}
          echo "EA: $newJarEA"
        elif [[ ${newJar##*integration-stack*} ]]; then
          newJarCore=${newJar}
          echo "Core: $newJarCore"
        fi
        git add $newJar
      done

      for newJar in ${newJarEA} ${newJarCore}; do
        unzip -q -d ${basedir}/updates/${d}/${newJar}{_,}
        pushd ${newJar}_ >/dev/null 
        if [ "$isGA" = true ]; then
          sed -i "s#/8.0-staging/#/8.0/#g" plugin.xml
          sed -i "s#/8.0-development/#/8.0/#g" plugin.xml
        else  # plugin points to the STAGING URL, not the RELEASE one
          sed -i "s#/8.0-staging/#/8.0-development/#g" plugin.xml
          sed -i "s#/8.0/#/8.0-development/#g" plugin.xml
        fi
        zip -u ${basedir}/updates/${d}/${newJar} plugin.xml
        git add ${basedir}/updates/${d}/${newJar}
        popd >/dev/null
        rm -fr ${basedir}/updates/${d}/${newJar}_
      done

      # cleanup previous discovery jars
      others=$(ls -1 ${basedir}/updates/${d}/discovery | egrep -v "$(basename $newJarEA)|$(basename $newJarCore)|integration-stack")
      echo "Clean these old jars: $others"
      git rm -f $others
    popd
  else  
    pushd ${basedir}/updates/8.0-staging
      rsync -aPrz --rsh=ssh --protocol=28 ./* ${basedir}/updates/${d}/
    popd
    # now fix URLs in html pages
    pushd ${basedir}/updates/${d}/
      # set correct page label
      if [[ $d == "8.0" ]]; then sed -i "s#Development Milestone#Stable Release#" index.html; fi
      if [[ $d == "8.0-development" ]]; then sed -i "s#8.0-staging#8.0-development#" index.html; fi
      sed -i "s#8.0-staging#8.0#" index.html
    popd

  fi
done

previous=8.0.0.GA
version=8.0.1.GA
sed -i "s#${previous}#${version}#" updates/index.html

popd

# verify all files are correct before pusing to git and server
# TODO: make sure we're using /static/updates/ not /updates/ in composite*.xml for all GA files, and just /updates/ for pre-GA files

git push origin HEAD:master

# push both staging and development folders to devstudio.redhat.com
JBDS=devstudio@filemgmt.jboss.org:www_htdocs/devstudio
for d in $dirs; do
  rsync -aPrz --rsh=ssh --protocol=28 ${basedir}/updates/${d}/* ${JBDS}/updates/${d}/
  rsync -aPrz --rsh=ssh --protocol=28 ${basedir}/earlyaccess/${d}/* ${JBDS}/earlyaccess/${d}/
done
----

== Put a copy of the update site zip on devstudio.redhat.com

First, ssh to www.qa server. Then, sudo to the hudson user, and run this:

[source,bash]
----
. /home/hudson/config_repository/scripts/jbds/prompt.sh
version=8.0.1.GA
cd ~/RHDS/builds/development/${version}-build-core/
scpr jboss-devstudio-${version}*-updatesite-core.zip jboss-devstudio-${version}*-updatesite-core.zip.MD5 $JBDS/static/updates/8.0.0/
----

== Cleanup builds and update sites under /development/ and /stable/

First, ssh to www.qa server. Then, sudo to the hudson user, and run this:

[source,bash]
----
. /home/hudson/config_repository/scripts/jbds/prompt.sh
version=8.0.1.GA
cd ~/RHDS/builds/development/
mv ${version}* ../stable
ln -s ../stable/${version}*
mv 8.0.1.CR* OLD/

cd ~/RHDS/updates/development/
mv ${version}* ../stable
ln -s ../stable/${version}*
mv 8.0.1.CR* OLD/
----


== Release the latest milestone to ide-config.properties

Check out this file: http://download.jboss.org/jbosstools/configuration/ide-config.properties from _http://github.com/jbosstools/jbosstools-download.jboss.org_ repository.

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
# adjust these steps to fit your own path location & git workflow
cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=8.0.1.Final # name to use in filenames ie fixVersion in JIRA
versionWithRespin=8.0.1.Final # Fully qualified version, including respin suffix

topic=release-jbosstools-${versionWithRespin}-to-production; branch=master; gw1

st ide-config.properties # or use another editor if not Sublime Text (st)

# something like this...
# jboss.discovery.directory.url|devstudio|8=https://devstudio.jboss.com/updates/8.0/devstudio-directory.xml
# jboss.discovery.site.url|devstudio|8=https://devstudio.jboss.com/updates/8.0/

# commit the change and push to master
ci "release JBDS ${version} (${versionWithRespin}) to production: link to latest dev milestone discovery site" ide-config.properties
gw2; gw3; gw4

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
rsync -Pzrlt --rsh=ssh --protocol=28 ide-config.properties $TOOLS/configuration/ide-config.properties
----

== Tag Git

[source,bash]
----
# if not already cloned, the do this:
git clone https://github.com/jbdevstudio/jbdevstudio-product
git clone https://github.com/jbdevstudio/jbdevstudio-ci
git clone https://github.com/jbdevstudio/jbdevstudio-website
git clone https://github.com/jbdevstudio/jbdevstudio-artwork
git clone https://github.com/jbdevstudio/jbdevstudio-devdoc

# now tag multiple projects in a single step, replacing existing tags if already exist
jbt_branch=jbosstools-4.2.x
version=8.0.1.GA
for d in product ci website artwork devdoc; do
  echo "====================================================================="
  echo "Tagging jbdevstudio-${d} from branch ${jbt_branch} as tag ${version}..."
  pushd ~/truu/jbdevstudio-${d}
  git stash
  git pull origin
  git fetch -t -p
  git checkout ${jbt_branch} && git tag -f jbdevstudio-${version} && git push origin jbdevstudio-${version}
  git checkout master; git stash pop
  echo ">>> https://github.com/jbdevstudio/jbdevstudio-${d}/tree/jbdevstudio-${version}"
  popd >/dev/null 
  echo "====================================================================="
  echo ""
done
----

== Commit updates to release guide (including this document):

[source,bash]
----
version=8.0.1.GA
cd jbdevstudio-devdoc/release_guide/8.0
git commit -m "update release guide for ${version}" .
git push origin HEAD:master
----


== Update websites

=== tools.jboss.org

Provide a PR to add the latest JBT & JBDS milestones to this listing:

https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml

Example: https://github.com/jbosstools/jbosstools-website/pull/193

== devstudio.jboss.com

Goal is to update the following pages: https://www.jboss.org/products/devstudio/download/ and https://www.jboss.org/products/devstudio/overview/

This can be achived by creating a JIRA to JBoss Developer (https://issues.jboss.org/secure/CreateIssue.jspa?pid=12313621&issuetype=3 ) and submitting pull requests for file _products/devstudio/_common/product.yml_ against repository https://github.com/jboss-developer/www.jboss.org 

Example past JIRA: https://issues.jboss.org/browse/DEVELOPER-733 . Relevant pull request is linked from here.

NOTE: you'll need to get an answer from release-engineering@redhat.com (cf first step) to get the URLs to use for the various files


== Update Marketplace entry

WARNING: Alpha versions are not published to market place. So ignore this step for Alpha versions.

=== If node doesn't exist yet

This is usually the case of first Beta version.

Create a new node on Marketplace, listing the single "BYOE" feature: com.jboss.devstudio.core.feature

=== If node already exists

Access it via +http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-luna/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Notes / warnings (if applicable, eg., JDK 7/8 issues)

== Mark release as complete in JIRA

If there are no unresolved issues, release the milestone version in JIRA.

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----


== Notify the team (send 2 or more emails)

____

*To* jbosstools-dev@lists.jboss.org +
and +
*To* external-exadel-list@redhat.com +
and +
*To* jboss-announce@redhat.com (optional for major milestones, recommended for GA releases) +
and +
*To* gss-support-readiness@redhat.com, dgeoffro@redhat.com, mmusaji@redhat.com (for all GA releases (major, minor, maintenance) ONLY)

[source,bash]
----
version=8.0.1.GA
echo "
Subject: 

JBoss Developer Studio ${version} is available

Body:

JBoss Developer Studio ${version} is available!

Download page and installer: 
* https://tools.jboss.org/downloads/devstudio/luna/${version}.html
* https://www.jboss.org/products/devstudio/overview/

Update site: https://devstudio.jboss.com/updates/8.0-development/

Early Access site: https://devstudio.jboss.com/earlyaccess/8.0-development/

--

Eclipse Marketplace: https://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-luna

--

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBDS#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

"
----
____

