= Release JBoss Developer Studio Development Milestone

This document describe how to publish a valid JBoss Developer Studio build to production after being verified by QE.

CAUTION: TODO: when releasing GA make sure to :%s/development/stable/g and :%s/8.0-staging/8.0/g in product/features/com.jboss.jbds.product.feature/p2.inf

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten. 

Send an email to jbosstools-dev@ and external-exadel-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Announce internally for push to CSP staging site

First thing is to ask for availability of the binaries to CSP (Red Hat Customer Portal) and Golden Gate (JBoss products portal).

NOTE: As this takes some time and can be easily cancelled, this step can be anticipated a few days before release.
____
*To* release-engineering@redhat.com +
and +
*Cc* cobrien@redhat.com, ldimaggi@redhat.com, mmurray@redhat.com, jpallich@redhat.com +

[source,bash]
----
version=8.0.0.Beta3
versionWithRespin=8.0.0.Beta3c # a, b, c...
version3=8.0.0.Beta3-v20140617-2058-B166
echo "
Subject: 

JBoss Developer Studio ${version} available for push to CSP staging server

Body:

JBoss Developer Studio ${version} (to be renamed from ${versionWithRespin}) is available to push to CSP staging server, for subsequent smoke test & review by QE.

Please include these 5 files:

* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-installer-standalone.jar 
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-installer-eap.jar
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-installer-src.zip
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-updatesite-core.zip
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-updatesite-central.zip

We will also need GoldenGate links for the 5 artifacts above, as they need to be linked from these pages for Early Access:

* https://www.jboss.org/products/devstudio/overview/
* https://www.jboss.org/products/devstudio/download/

Only ONE of those artifacts [0] require sign in, as it bundles EAP. The rest are free. 

[0] http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-installer-eap.jar

Please note that the new CSP pages should include similar documentation 
to the previous release ( 
https://access.redhat.com/jbossnetwork/restricted/listSoftware.html ) 
but with these string replacements / updates:
* s/Luna M6/Luna/g
* s/Luna M6 JEE bundle/Luna JEE bundle/g
* s/lunam6/luna/g

When pushed, please reply so that QE can review the CSP pages & files 
for push to production and use the Golden Gate links to update the 
public site.

Thanks in advance,

When pushed, please reply so that QE can review the CSP pages & files for push to production.

Thanks in advance,

"
----
____

As an answer, you get the links to the files on both portals. Keep them as you'll need them later.

== On devstudio.redhat.com, remove respin suffix

# TODO: Is this step really mandatory? Can't we keep respin there?

[source,bash]
----
version=8.0.0.CR1
versionWithRespin=8.0.0.CR1b; # a, b, c, ...

# Assuming devstudio_jboss_org is an empty dir
sshfs devstudio@filemgmt.jboss.org:www_htdocs/devstudio/ devstudio_jboss_org
cd devstudio_jboss_org

# clean out old update sites from previous milestones; rename update sites from "a,b,c" to ""
cd /updates/8.0.0/
if [[ ${version} != ${versionWithRespin} ]]; then 
  mv jboss-devstudio-${version}-updatesite-core jboss-devstudio-${version}-updatesite-core.DELETEME
  mv jboss-devstudio-${version}-target-platform jboss-devstudio-${version}-target-platform.DELETEME
  mv jboss-devstudio-${versionWithRespin}-updatesite-core jboss-devstudio-${version}-updatesite-core
  mv jboss-devstudio-${versionWithRespin}-target-platform jboss-devstudio-${version}-target-platform
fi
# TODO: do not run this next line if the above step fails!
rm -fr jboss-devstudio-${version}?-updatesite-core jboss-devstudio-${version}?-target-platform *.DELETEME
----

Then, update the various composite files to use URL not suffixed by respin. This can be done by editing repository _jbdevstudio-website_ locally.

[source,bash]
----
# "gw1" uses special aliases/scripts/shortcuts. Basically, we want to follow correct github workflows so that commits are pushed to user's fork, then later pull-requested (and the PR applied)
# "gw2" will create the PR, "gw3" will apply it, and "gw4" will delete the topic branch locally and in my fork
# the 4 steps are captured here: https://gist.github.com/nickboldt/4111850
alias   ga='git add'
alias   stat='git status'
alias   gd='git diff --color=always -w'
alias   ci='git commit -m'

pushd jbdevstudio-website/content/updates/8.0-staging
version=8.0.0.CR1
versionWithRespin=8.0.0.CR1b # a, b, c, ...
now=`date +%s000`
for d in composite*.xml index.html central/index.html central/core/index.html central/earlyaccess/index.html; do
  sed -i -e "s#${versionWithRespin}#${version}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
  git add $d
done

# commit to github
git commit -m "rename ${versionWithRespin} to ${version}"
git push jbdevstudio HEAD:master #jbdevstudio is remote repo alias, also sometimes called 'origin'

# rsync updated files to server
JBDS=devstudio@filemgmt.jboss.org:www_htdocs/devstudio
rsync -Pzrlt --rsh=ssh --protocol=28 ./* ${JBDS}/updates/8.0-staging/
popd

----

== Request an update to jboss.org/products/devstudio

Goal is to update the following pages: https://www.jboss.org/products/devstudio/download/ and https://www.jboss.org/products/devstudio/overview/

This can be achived by creating a JIRA to JBoss Developer (https://issues.jboss.org/secure/CreateIssue.jspa?pid=12313621&issuetype=3 ) and submitting pull requests for file _products/devstudio/_common/product.yml_ against repository https://github.com/jboss-developer/www.jboss.org 

Example past JIRA: https://issues.jboss.org/browse/DEVELOPER-733 . Relevant pull request is linked from here.

NOTE: you'll need to get an answer from release-engineering@redhat.com (cf first step) to get the URLs to use for the various files

== Update https://devstudio.redhat.com/updates/8.0*/devstudio-directory.xml to point at new discovery jar(s) from staging.

[IMPORTANT]
====
TODO for CR1 and GA: VERIFY CONTENTS OF DISCOVERY JAR ARE CORRECTLY POINTING AT

*  8.0 for /8.0/
*  8.0-development for /8.0-development/
*  8.0-staging for /8.0-staging/
====

You can run this script from your local machine:

[source,bash]
----

isGA=false # or true in case you're doing a GA
version=8.0.0.Beta3
SRC_SITE=8.0-staging
DESTSITE=8.0-development # or 8.0/ for a GA release


# set correct path for where you have project cloned on disk
cd jbdevstudio-website/content

topic="release-${version}";branch=master; gw1

# check in / sync changes

rsync -aPrz --rsh=ssh updates/${SRC_SITE}/* updates/${DESTSITE}/

pushd updates/${DESTSITE}/
# Update URLs in discovery jars
newJars=$(cat devstudio-directory.xml | grep entry | grep -v "integration-stack" | sed -e "s#.\+discovery/#discovery/#g" | sed -e "s#\.jar.\+#.jar#g")
for newJar in $newJars; do 
  wget -q -nc http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}/${newJar}
  if [[ ! ${newJar##*.earlyaccess_*} ]]; then
    newJarEA=${newJar}
    echo "EA: $newJarEA"
  else
    newJarCore=${newJar}
    echo "Core: $newJarCore"
  fi
  git add $newJar
done

for newJar in ${newJarEA} ${newJarCore}; do
  unzip -q -d ${basedir}/updates/${DESTSITE}/${newJar}{_,}
  pushd ${newJar}_ >/dev/null 
  if [ "$isGA" = true ]; then
    sed -i "s#https://devstudio.jboss.com/updates/8.0-staging/central/core/#https://devstudio.jboss.com/updates/8.0/central/core/#g" plugin.xml
    sed -i "s#https://devstudio.jboss.com/updates/8.0-development/central/core/#https://devstudio.jboss.com/updates/8.0/central/core/#g" plugin.xml
  else  # plugin points to the STAGING URL, not the RELEASE one
    sed -i "s#https://devstudio.jboss.com/updates/8.0-staging/central/#https://devstudio.jboss.com/updates/8.0-development/central/#g" plugin.xml
    sed -i "s#https://devstudio.jboss.com/updates/8.0/central/#https://devstudio.jboss.com/updates/8.0-development/central/#g" plugin.xml
  fi
  zip -u ${basedir}/updates/${DESTSITE}/${newJar} plugin.xml
  popd >/dev/null
  rm -fr ${basedir}/updates/${DESTSITE}/${newJar}_
done

popd

----

[CAUTION]
====
Be sure to not overwrite integration-stack deltas (staging and development may not be the same)!
====

=== Update latest target platform composite files

[source,bash]
----

cd jbdevstudio-website/content # or...

pushd updates/8.0-staging/extras/
now=`date +%s000`

oldTP=4.40.0.Beta4
newTP=4.40.0.CR1
for d in composite*.xml; do
  sed -i -e "s#${oldTP}#${newTP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
  git add $d
done
popd

pushd updates
git add ${DESTSITE}
git commit -m "release ${version} from ${SRC_SITE} to ${DESTSITE}"
git push jbdevstudio HEAD:master
popd

# push both staging and development folders to download.jboss.org
rsync -Pzrlt --rsh=ssh --protocol=28 updates/${DESTSITE} updates/${SRC_SITE} $JBDS/updates/
----


== JBoss Central Early Access site must now be rebuilt 

WARNING: TODO: JBIDE-17826 - latest Central/EA TP may now be in an "a" or "b" folder so make sure you get the right one!

(This step is only required if it was skipped when releasing JBoss Tools. You should have already done it there.)

Since Beta3, JBoss Central includes part of JBoss Tools, in order to make it avaiable in JBDS. 
Therefore, once JBoss Tools is released, you must rebuild the Early Access site to include the final bits for that milestone.

1. Update jbosstools-discovery/jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
2. Run verifyTarget.sh to pull in the latest versions of the IUs and verify the TP can be resolved to disk
3. Kick this job https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-centraltarget_4.2.luna/
4. Send announcement email (?)

== Tag Git

[source,bash]
----
  # if not already cloned, the do this:
  git clone https://github.com/jbdevstudio/jbdevstudio-product
  git clone https://github.com/jbdevstudio/jbdevstudio-ci
  git clone https://github.com/jbdevstudio/jbdevstudio-website
  git clone https://github.com/jbdevstudio/jbdevstudio-artwork
  git clone https://github.com/jbdevstudio/jbdevstudio-devdoc

  # now tag multiple projects in a single step, replacing existing tags if already exist
  jbt_branch=jbosstools-4.2.0.Beta3x
  version=8.0.0.Beta3
  for d in product ci website artwork devdoc; do
    echo "====================================================================="
    echo "Tagging jbdevstudio-${d} from branch ${jbt_branch} as tag ${version}..."
    pushd ~/truu/jbdevstudio-${d}
    git stash
    git pull origin
    git fetch -t -p
    git checkout ${jbt_branch} && git tag -f jbdevstudio-${version} && git push origin jbdevstudio-${version}
    git checkout master; git stash pop
    echo ">>> https://github.com/jbdevstudio/jbdevstudio-${d}/tree/jbdevstudio-${version}"
    popd >/dev/null 
    echo "====================================================================="
    echo ""
  done
----

== Commit updates to release guide (including this document):

[source,bash]
----
version=8.0.0.CR1
cd jbdevstudio-devdoc/release_guide/8.0
git commit -m "update release guide for ${version}" .
git push origin HEAD:master
----

== Move installers from "a" or "b" folder to base folder; purge old stuff from OLD/ folder

TODO: Is this step really useful? Also, it seems conflicting with URLs provided in request for CSP/GoldenGate

These steps required to be logged as _hudson_ on dev01.
[source,bash]
----
ssh dev01.mw.lab.eng.bos.redhat.com
sudo su - hudson
----

[source,bash]
----
# TODO: (new for Beta3) make sure this works as expected when renaming CR1!
version=8.0.0.CR1
versionWithRespin=8.0.0.CR1b
if [[ ${version} != ${versionWithRespin} ]]; then
  for d in ~/RHDS/builds/development/ ~/RHDS/updates/development/ ~/RHDS/discovery/development/; do
    pushd $d
    others=`find ${d} -name "${version}*" -and -not -name "${versionWithRespin}*"`
    f=`find ${d} -name "${versionWithRespin}*"`
    g=${f/${versionWithRespin}/${version}}
    echo "Rename $f to $g ... and move old respins to OLD/" | grep $version
    mv ${others} OLD/
    mv ${f} ${g}
    popd
  done
fi
----

WARNING: For stable releases, move content from RHDS/{builds,updates,discovery}/development into RHDS/{builds,updates,discovery}/stable, then symlink it back so it appears in both places.

== Update jbosstools-website

Provide a PR to add the latest JBT & JBDS milestones to this listing:

https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml

Example: https://github.com/jbosstools/jbosstools-website/pull/193

== Update Marketplace entry

WARNING: Alpha versions are not published to market place. So ignore this step for Alpha versions.

=== If node doesn't exist yet

This is usually the case of first Beta version.

Create a new node on Marketplace, listing the single "BYOE" feature: com.jboss.devstudio.core.feature

=== If node already exists

Access it via +http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-luna/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Notes / warnings (if applicable, eg., JDK 7/8 issues)


== Release the latest milestone to ide-config.properties

Check out this file: http://download.jboss.org/jbosstools/configuration/ide-config.properties from _http://github.com/jbosstools/jbosstools-download.jboss.org_ repository.

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
jboss.discovery.directory.url|devstudio|8.0.0.CR1=https://devstudio.jboss.com/updates/8.0-development/devstudio-directory.xml
jboss.discovery.site.url|devstudio|8.0.0.CR1=https://devstudio.jboss.com/updates/8.0-development/central/core/
----

Then commit and push changes to the origin GitHub repo. Then either push the file back to download.jboss.org, either manually (sftp, scp...) or using this CI job: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/

== Mark release as complete in JIRA

If there are no unresolved issues, release the milestone version in JIRA.

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----


== Notify the team (send 2 emails)

____

*To* jbosstools-dev@lists.jboss.org +
and +
*To* external-exadel-list@redhat.com, jboss-announce@redhat.com (optional for major milestones/releases)+

[source,bash]
----
version=8.0.0.CR1
echo "
Subject: 

JBoss Developer Studio ${version} is available

Body:

JBoss Developer Studio ${version} is available!

Download page and installer: 
* https://tools.jboss.org/downloads/devstudio/luna/${version}.html
* https://www.jboss.org/products/devstudio/overview/

Update site: https://devstudio.jboss.com/updates/8.0-development/

Note that the update site may take a while to replicate from our staging server to publication. Please allow at least an hour before attempting to install from the site - if the page above still shows the previous milestone instead of ${version}, try again later.

--

Eclipse Marketplace: https://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-kepler

--

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBDS#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

"
----
____

