= Release JBoss Developer Studio Development Milestone

This document describe how to publish a valid JBoss Developer Studio build to production after being verified by QE.

CAUTION: TODO: when releasing GA make sure to :%s/development/stable/g and :%s/8.0-staging/8.0/g in product/features/com.jboss.jbds.product.feature/p2.inf

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten. 

Send an email to jbosstools-dev@ and external-exadel-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Announce internally for push to CSP staging site

First thing is to ask for availability of the binaries to CSP (Red Hat Customer Portal) and Golden Gate (JBoss products portal).

NOTE: As this takes some time and can be easily cancelled, this step can be anticipated a few days before release.
____
*To* release-engineering@redhat.com +
and +
*Cc* cobrien@redhat.com, ldimaggi@redhat.com, mmurray@redhat.com, jpallich@redhat.com +

[source,bash]
----
version=8.0.0.Beta3
versionWithRespin=8.0.0.Beta3c # a, b, c...
version3=8.0.0.Beta3-v20140617-2058-B166
echo "
Subject: 

JBoss Developer Studio ${version} available for push to CSP staging server

Body:

JBoss Developer Studio ${version} (to be renamed from ${versionWithRespin}) is available to push to CSP staging server, for subsequent smoke test & review by QE.

Please include these 5 files:

* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-installer-standalone.jar 
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-installer-eap.jar
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-installer-src.zip
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-updatesite-core.zip
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-updatesite-central.zip

We will also need GoldenGate links for the 5 artifacts above, as they need to be linked from these pages for Early Access:

* https://www.jboss.org/products/devstudio/overview/
* https://www.jboss.org/products/devstudio/download/

Only ONE of those artifacts [0] require sign in, as it bundles EAP. The rest are free. 

[0] http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/jboss-devstudio-${version3}-installer-eap.jar

Please note that the new CSP pages should include similar documentation 
to the previous release ( 
https://access.redhat.com/jbossnetwork/restricted/listSoftware.html ) 
but with these string replacements / updates:
* s/Luna M6/Luna/g
* s/Luna M6 JEE bundle/Luna JEE bundle/g
* s/lunam6/luna/g

When pushed, please reply so that QE can review the CSP pages & files 
for push to production and use the Golden Gate links to update the 
public site.

Thanks in advance,

When pushed, please reply so that QE can review the CSP pages & files for push to production.

Thanks in advance,

"
----
____

As an answer, you get the links to the files on both portals. Keep them as you'll need them later.

== Update composite files and devstudio-directory.xml to point at new discovery jar(s) from staging

[IMPORTANT]
====
TODO for CR2 and GA: VERIFY CONTENTS OF DISCOVERY JAR ARE CORRECTLY POINTING AT

*  8.0 for /8.0/
*  8.0-development for /8.0-development/
*  8.0-staging for /8.0-staging/
====

You can run this script from your local machine:

[source,bash]
----
isGA=false # or true in case you're doing a GA
version=8.0.0.CR2
versionWithRespin=8.0.0.CR2b
SRC_SITE=8.0-staging
if [ "$isGA" == "true" ]; then
  DESTSITE=8.0
else
  DESTSITE=8.0-development # or 8.0/ for a GA release
fi
JBDS=devstudio@filemgmt.jboss.org:www_htdocs/devstudio

# set correct path for where you have project cloned on disk
cd jbdevstudio-website/content
basedir=$(pwd)

# check in / sync changes
rm -r updates/${DESTSITE}
scp -r $JBDS/updates/${SRC_SITE} updates/${DESTSITE}/

pushd updates/${DESTSITE}/
# Update URLs in discovery jars
newJars=$(cat devstudio-directory.xml | grep entry | grep -v "integration-stack" | sed -e "s#.\+discovery/#discovery/#g" | sed -e "s#\.jar.\+#.jar#g")
for newJar in $newJars; do 
  wget -q -nc https://devstudio.redhat.com/updates/${SRC_SITE}/discovery/${newJar}
  if [[ ! ${newJar##*.earlyaccess_*} ]]; then
    newJarEA=${newJar}
    echo "EA: $newJarEA"
  else
    newJarCore=${newJar}
    echo "Core: $newJarCore"
  fi
  git add $newJar
done

for newJar in ${newJarEA} ${newJarCore}; do
  unzip -q -d ${basedir}/updates/${DESTSITE}/${newJar}{_,}
  pushd ${newJar}_ >/dev/null 
  if [ "$isGA" = true ]; then
    sed -i "s#updates/8.0-staging/#updates/8.0/#g" plugin.xml
    sed -i "s#updates/8.0-development/#updates/8.0/#g" plugin.xml
  else  # plugin points to the STAGING URL, not the RELEASE one
    sed -i "s#updates/8.0-staging/#updates/8.0-development/#g" plugin.xml
    sed -i "s#updates/8.0/#updates/8.0-development/#g" plugin.xml
  fi
  zip -u ${basedir}/updates/${DESTSITE}/${newJar} plugin.xml
  git add ${basedir}/updates/${DESTSITE}/${newJar}
  popd >/dev/null
  rm -fr ${basedir}/updates/${DESTSITE}/${newJar}_
done

# cleanup previous discovery jars
others=$(ls -1 ${basedir}/updates/${DESTSITE}/discovery | grep -v $(basename $newJarEA) | grep -v $(basename $newJarCore))
git rm -f others

popd
----

[CAUTION]
====
Be sure to not overwrite integration-stack deltas (staging and development may not be the same)!
====

=== Update latest Central and Early Access (extras) target platform

NOTE: Now that Central content is merged into the same composite as JBDS and its target platform, you MAY have to edit this file by hand if the JBDS TP and JBDS Central TP versions are not the same.

[source,bash]
----
cd jbdevstudio-website/content # or...


now=`date +%s000`
oldTP=4.40.0.CR1b
newTP=4.40.0.CR2

pushd updates/${DESTSITE}/extras/
for d in composite*.xml; do
  sed -i -e "s#${oldTP}#${newTP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
  git add $d
done
popd
pushd earlyaccess/${DESTSITE}/
for d in composite*.xml; do
  sed -i -e "s#${oldTP}#${newTP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
  git add $d
done
popd

pushd updates
git add ${DESTSITE}
git commit -m "release ${version} from ${SRC_SITE} to ${DESTSITE}"

# repeat for EA site too
pushd ../earlyaccess
git add ${DESTSITE}
git commit -m "release ${version} from ${SRC_SITE} to ${DESTSITE}"
popd

git push jbdevstudio HEAD:master
popd

# push both staging and development folders to download.jboss.org
JBDS=devstudio@filemgmt.jboss.org:www_htdocs/devstudio
scp -r updates/${DESTSITE} $JBDS/updates/
scp -r earlyaccess/${DESTSITE} $JBDS/earlyaccess/
----

== Release the latest milestone to ide-config.properties

Check out this file: http://download.jboss.org/jbosstools/configuration/ide-config.properties from _http://github.com/jbosstools/jbosstools-download.jboss.org_ repository.

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
jboss.discovery.directory.url|devstudio|8.0.0.CR2=https://devstudio.jboss.com/updates/8.0-development/devstudio-directory.xml
jboss.discovery.site.url|devstudio|8.0.0.CR2=https://devstudio.jboss.com/updates/8.0-development/
----

Then commit and push changes to the origin GitHub repo. Then either push the file back to download.jboss.org, either manually (sftp, scp...) or using this CI job: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/


== Tag Git

[source,bash]
----
# if not already cloned, the do this:
git clone https://github.com/jbdevstudio/jbdevstudio-product
git clone https://github.com/jbdevstudio/jbdevstudio-ci
git clone https://github.com/jbdevstudio/jbdevstudio-website
git clone https://github.com/jbdevstudio/jbdevstudio-artwork
git clone https://github.com/jbdevstudio/jbdevstudio-devdoc

# now tag multiple projects in a single step, replacing existing tags if already exist
jbt_branch=jbosstools-4.2.0.Beta3x
version=8.0.0.Beta3
for d in product ci website artwork devdoc; do
  echo "====================================================================="
  echo "Tagging jbdevstudio-${d} from branch ${jbt_branch} as tag ${version}..."
  pushd ~/truu/jbdevstudio-${d}
  git stash
  git pull origin
  git fetch -t -p
  git checkout ${jbt_branch} && git tag -f jbdevstudio-${version} && git push origin jbdevstudio-${version}
  git checkout master; git stash pop
  echo ">>> https://github.com/jbdevstudio/jbdevstudio-${d}/tree/jbdevstudio-${version}"
  popd >/dev/null 
  echo "====================================================================="
  echo ""
done
----

== Commit updates to release guide (including this document):

[source,bash]
----
version=8.0.0.CR2
cd jbdevstudio-devdoc/release_guide/8.0
git commit -m "update release guide for ${version}" .
git push origin HEAD:master
----


== Update websites

=== tools.jboss.org

Provide a PR to add the latest JBT & JBDS milestones to this listing:

https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml

Example: https://github.com/jbosstools/jbosstools-website/pull/193

== devstudio.jboss.com

Goal is to update the following pages: https://www.jboss.org/products/devstudio/download/ and https://www.jboss.org/products/devstudio/overview/

This can be achived by creating a JIRA to JBoss Developer (https://issues.jboss.org/secure/CreateIssue.jspa?pid=12313621&issuetype=3 ) and submitting pull requests for file _products/devstudio/_common/product.yml_ against repository https://github.com/jboss-developer/www.jboss.org 

Example past JIRA: https://issues.jboss.org/browse/DEVELOPER-733 . Relevant pull request is linked from here.

NOTE: you'll need to get an answer from release-engineering@redhat.com (cf first step) to get the URLs to use for the various files


== Update Marketplace entry

WARNING: Alpha versions are not published to market place. So ignore this step for Alpha versions.

=== If node doesn't exist yet

This is usually the case of first Beta version.

Create a new node on Marketplace, listing the single "BYOE" feature: com.jboss.devstudio.core.feature

=== If node already exists

Access it via +http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-luna/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Notes / warnings (if applicable, eg., JDK 7/8 issues)

== Mark release as complete in JIRA

If there are no unresolved issues, release the milestone version in JIRA.

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----


== Notify the team (send 2 emails)

____

*To* jbosstools-dev@lists.jboss.org +
and +
*To* external-exadel-list@redhat.com, jboss-announce@redhat.com (optional for major milestones/releases)+

[source,bash]
----
version=8.0.0.CR2
echo "
Subject: 

JBoss Developer Studio ${version} is available

Body:

JBoss Developer Studio ${version} is available!

Download page and installer: 
* https://tools.jboss.org/downloads/devstudio/luna/${version}.html
* https://www.jboss.org/products/devstudio/overview/

Update site: https://devstudio.jboss.com/updates/8.0-development/

Early Access site: https://devstudio.jboss.com/earlyaccess/8.0-development/

Note that the update sites may take a while to replicate from our staging server to publication. Please allow at least an hour before attempting to install from the site - if the page above still shows the previous milestone instead of ${version}, try again later.

--

Eclipse Marketplace: https://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-kepler

--

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBDS#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

"
----
____

