= Publishing JBDS Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

TODO:

* in product/features/com.jboss.jbds.product.feature/p2.inf
* when releasing GA make sure to :%s/development/stable/g and :%s/8.0-staging/8.0/g


== Update Discovery Sites and URLs

See details in link:JBT_4.2.0.Beta3_Staging_For_QE.adoc[Staging JBT For QE]


== Disable jobs

All stable branch jobs from the https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_8.0.luna/[8.0.luna view] should be disabled.

Quick way to do so is with https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py[toggleJenkinsJobs.py]. See https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py.examples.txt[usage examples].

Should a respin be needed, they can be re-enabled at that time.


== Stage to qa.jboss.org

*qa.jboss.org* is actually mapped to folder +/qa/services/http/binaries/RHDS+ accessible from CI machines (such as dev01.mw.lab.eng.bos.redhat.com). So first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then copy the latest JBDS artifacts:

* installer
* update site
* discovery site

WARNING: Don't use symlinks are they are too risky to use. Those operations can be done in parallel (using multiple terminals is the easiest way)

=== Push installers, update site, and discovery site

[source,bash]
----

# can run 3 steps these in parallel 

version=8.0.0.Beta3c # a, b, c...
rsync -aPrz /qa/services/http/binaries/RHDS/builds/staging/devstudio.product_8.0.luna/installer/* /qa/services/http/binaries/RHDS/builds/development/${version}-build-core/
cd /qa/services/http/binaries/RHDS/builds/development/
find . -maxdepth 1 -type d -name "${version}*" | grep ${version}
find . -maxdepth 1 -type d -name "${version}*" | sed "s#\.# >> http://www.qa.jboss.com/binaries/RHDS/builds/development#" | egrep ">>|${version}"

version=8.0.0.Beta3c # a, b, c...
rsync -aPrz /qa/services/http/binaries/RHDS/builds/staging/devstudio.product_8.0.luna/all/repo/* /qa/services/http/binaries/RHDS/updates/development/${version}-updatesite-core/
cd /qa/services/http/binaries/RHDS/updates/development/
find . -maxdepth 1 -type d -name "${version}*" | grep ${version}
find . -maxdepth 1 -type d -name "${version}*" | sed "s#\.# >> http://www.qa.jboss.com/binaries/RHDS/updates/development#" | egrep ">>|${version}"

version=8.0.0.Beta3c # a, b, c...
# earlyaccess site includes one directory.xml file which lists both core and earlyaccess plugins, so use that instead of core site
rsync -aPrz /qa/services/http/binaries/RHDS/discovery/nightly/earlyaccess/4.2.luna/* /qa/services/http/binaries/RHDS/discovery/development/${version}/
----

=== Update discovery composite sites

[source,bash]
----
cd /qa/services/http/binaries/RHDS/discovery/development/${version}/
for c in compositeContent.xml compositeArtifacts.xml; do 
  sed -i -e "s#http://www.qa.jboss.com/binaries/RHDS/builds/staging/devstudio.product.\+/all/.\+/#http://www.qa.jboss.com/binaries/RHDS/updates/development/${version}-updatesite-core/#" $c
  sed -i -e "s#http://www.qa.jboss.com/binaries/RHDS/updates/development/${version}-updatesite-core/repo/#http://www.qa.jboss.com/binaries/RHDS/updates/development/${version}-updatesite-core/#" $c
  cat $c | egrep "${version}"
done
cd /qa/services/http/binaries/RHDS/discovery/development/
find . -maxdepth 1 -type d -name "${version}*" | grep ${version}
find . -maxdepth 1 -type d -name "${version}*" | sed "s#\.# >> http://www.qa.jboss.com/binaries/RHDS/discovery/development#" | egrep ">>|${version}"
----

== Stage files to devstudio.jboss.com

WARNING: Skip this test for Alpha

=== Push content

# TODO: change all refs to wallace (wallace.intranet.prod.int.rdu2.redhat.com); files are now on devstudio@filemgmt.jboss.org:/www_htdocs/devstudio

# Can no longer ssh onto wallace to PULL files. Instead, will have to PUSH files from 

+devstudio.jboss.com+ is actually hosted a machine called +wallace.intranet.prod.int.rdu2.redhat.com+, accessible from inside Red Hat VPN. So you need both VPN enabled and permissions to write to wallace. The wallace login should be your Kerberos ID.

First, connect to the wallace machine
[source,bash]
----
me@local$ ssh me@wallace
me@wallace$ cd /mnt/devstudio/updates
----

Then, copy stuff from dev01 (CI build publishing to qa.jboss.org) to wallace

[source,bash]
----

# can run 2 steps these in parallel 

version=8.0.0.Beta3c # a, b, c...
rsync -aPrz --rsh=ssh dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/builds/staging/devstudio.product_8.0.luna/all/repo/* /mnt/devstudio/updates/8.0.0/jboss-devstudio-${version}-updatesite-core/
chmod -R g+w /mnt/devstudio/updates/8.0.0/jboss-devstudio-${version}-updatesite-core 2>/dev/null
chgrp -R devstudio /mnt/devstudio/updates/8.0.0/jboss-devstudio-${version}-updatesite-core 2>/dev/null

version=8.0.0.Beta3c # a, b, c...
# TODO: verify correct URL and filename for the target zip
TARGET_PLATFORM_VERSION_MAX=4.40.0.Beta4
rsync -aPrz --rsh=ssh dev01.mw.lab.eng.bos.redhat.com:/qa/services/http/binaries/RHDS/targetplatforms/jbdevstudiotarget/${TARGET_PLATFORM_VERSION_MAX}/jbdevstudiotarget-${TARGET_PLATFORM_VERSION_MAX}.zip /mnt/devstudio/updates/8.0.0/
pushd /mnt/devstudio/updates/8.0.0; unzip -d jboss-devstudio-${version}-target-platform jbdevstudiotarget-${TARGET_PLATFORM_VERSION_MAX}.zip; popd
chmod -R g+w /mnt/devstudio/updates/8.0.0/jboss-devstudio-${version}-target-platform 2>/dev/null
chgrp -R devstudio /mnt/devstudio/updates/8.0.0/jboss-devstudio-${version}-target-platform 2>/dev/null

# TODO: verify correct URL and filename for the target zip
# TODO also push Central TP onto devstudio.redhat.com (JBDS-3125, JBDS-3086)
# eg., push http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/4.40.0.Beta4b-SNAPSHOT/jbtcentraltarget-4.40.0.Beta4b-SNAPSHOT.zip into 
# /www_htdocs/devstudio/updates/8.0.0, then unpack and link to it from jbdevstudio-website/content/updates/8.0*/compositeContent.xml

# TODO: verify correct URL and filename for the target zip
# TODO also push Early Access TP onto devstudio.redhat.com (JBDS-3125, JBDS-3086)
# eg., push http://download.jboss.org/jbosstools/targetplatforms/jbtearlyaccesstarget/4.40.0.Beta4b-SNAPSHOT/jbtearlyaccesstarget-4.40.0.Beta4b-SNAPSHOT.zip into 
# /www_htdocs/devstudio/updates/8.0.0, then unpack and link to it from jbdevstudio-website/content/earlyaccess/8.0*/compositeContent.xml

----

=== Update latest target platform composite files

Then, update the composite files to have public URLs pointing to these artifacts. Get a clone of repository +https://github.com/jbdevstudio/jbdevstudio-website+, then we can update the necessary composite files to reference new locations. This imply tweaks on some files of the jbdevstudio-website repository. This repo will get later published to devstudio.jboss.com. Those changes can then be performed on your local machine.

[source,bash]
----
pushd jbdevstudio-website/content/updates/8.0-staging/extras/
now=`date +%s000`

oldTP=4.40.0.Beta4
newTP=4.40.0.Beta4
for d in composite*.xml; do
  sed -i -e "s#${oldTP}#${newTP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done
popd

----

=== Update composite discovery files

[source,bash]
----
isGA=false # or true in case you're doing a GA
previousFull=8.0.0.Beta3b # a, b, c...
version=8.0.0.Beta3c # a, b, c...

#TODO: make sure you're the correct folder here!
pushd jbdevstudio-website/content/updates/8.0-staging/
now=`date +%s000`
for d in *.*ml extras/*.*ml central/core/*.*ml; do
  # update composite timestamp
  sed -i -e "s#${previousFull}#${version}#g" -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done
popd

# update https://devstudio.jboss.com/updates/8.0-staging/devstudio-directory.xml to point at new Core discovery jar.
# Latest discovery site is here: http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}
pushd jbdevstudio-website/content/updates/8.0-staging/discovery/
wget -q -nc http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}/devstudio-directory.xml
newJars=$(cat devstudio-directory.xml | grep entry | sed -e "s#.\+plugins#plugins#g" | sed -e "s#\.jar.\+#.jar#g")
for newJar in $newJars; do 
  wget -q -nc http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}/${newJar}
  if [[ ! ${newJar##*.earlyaccess_*} ]]; then
    newJarEA=${newJar/plugins/discovery}
    echo "EA: $newJarEA"
  else
    newJarCore=${newJar/plugins/discovery}
    echo "Core: $newJarCore"
  fi
done
rm -f devstudio-directory.xml
popd

# update XML
pushd jbdevstudio-website/content/updates/8.0-staging/
sed -i -e "s#discovery/com.jboss.jbds.central.discovery.earlyaccess_.\+\.jar#${newJarEA}#g" devstudio-directory.xml
sed -i -e "s#discovery/com.jboss.jbds.central.discovery_.\+\.jar#${newJarCore}#g" devstudio-directory.xml
  
unzip -q -d ${newJarEA}{_,}
pushd ${newJarEA}_ 

if [ "$isGA" = true ]; then
  sed -i "s#https://devstudio.jboss.com/updates/8.0-staging/central/earlyaccess/#https://devstudio.jboss.com/updates/8.0/central/earlyaccess/#g" plugin.xml
  sed -i "s#https://devstudio.jboss.com/updates/8.0-development/central/earlyaccess/#https://devstudio.jboss.com/updates/8.0/central/earlyaccess/#g" plugin.xml
else  # plugin points to the STAGING URL, not the RELEASE one
  sed -i "s#https://devstudio.jboss.com/updates/8.0/central/earlyaccess/#https://devstudio.jboss.com/updates/8.0-staging/central/earlyaccess/#g" plugin.xml
  sed -i "s#https://devstudio.jboss.com/updates/8.0-development/central/earlyaccess/#https://devstudio.jboss.com/updates/8.0-staging/central/earlyaccess/#g" plugin.xml
fi
zip -u ../../${newJarEA} plugin.xml
popd
rm -fr ${newJarEA}_

unzip -q -d ${newJarCore}{_,}
pushd ${newJarCore}_ 

if [ "$isGA" = true ]; then
  sed -i "s#https://devstudio.jboss.com/updates/8.0-staging/central/core/#https://devstudio.jboss.com/updates/8.0/central/core/#g" plugin.xml
  sed -i "s#https://devstudio.jboss.com/updates/8.0-development/central/core/#https://devstudio.jboss.com/updates/8.0/central/core/#g" plugin.xml
else  # plugin points to the STAGING URL, not the RELEASE one
  sed -i "s#https://devstudio.jboss.com/updates/8.0/central/core/#https://devstudio.jboss.com/updates/8.0-staging/central/core/#g" plugin.xml
  sed -i "s#https://devstudio.jboss.com/updates/8.0-development/central/core/#https://devstudio.jboss.com/updates/8.0-staging/central/core/#g" plugin.xml
fi
zip -u ../../${newJarCore} plugin.xml
popd
rm -fr ${newJarCore}_

popd # all the way back out

# don't do this until you're ready to release the content -- not for QE
# TODO: move this to the Release doc, not the Staging for QE doc
#if [ "$isGA" = true ]; then # new plugin is also in 8.0/ and 8.0-development/ as well as 8.0-staging/
#  cp -f jbdevstudio-website/content/updates/8.0-staging/${newJar} jbdevstudio-website/content/updates/8.0-development/${newJar}
#  cp -f jbdevstudio-website/content/updates/8.0-staging/devstudio-directory.xml jbdevstudio-website/content/updates/8.0-development/devstudio-directory.xml
#
#  cp -f jbdevstudio-website/content/updates/8.0-staging/${newJar} jbdevstudio-website/content/updates/8.0/${newJar}
#  cp -f jbdevstudio-website/content/updates/8.0-staging/devstudio-directory.xml jbdevstudio-website/content/updates/8.0/devstudio-directory.xml
#fi

# check in / sync changes
pushd jbdevstudio-website/content/updates/8.0-staging/
git add ${newJarEA} ${newJarCore}
git status .
git diff --color=always -w .
# TODO: make sure you're using a PR & topic branch!
git commit -m "release ${version} for QE: add new discovery plugins ${newJarCore}, ${newJarEA} + update devstudio-directory.xml + update HTML pages" . discovery/*.jar
# TODO: make sure you've merged in others' changes!
git push origin master # in case of doubt, prefer pushing to a local repostiory and using a pull-request to ask for review
popd

# TODO: change all refs to wallace (wallace.intranet.prod.int.rdu2.redhat.com); files are now on devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
rsync -aPrz --rsh=ssh jbdevstudio-website/content/updates/8.0-staging/* wallace.intranet.prod.int.rdu2.redhat.com:/mnt/devstudio/updates/8.0-staging/

if [ "$isGA" = true ]; then
  pushd jbdevstudio-website/content/updates/8.0/
  git add ${newJar}
  git status .
  gd diff --color=always -w .
  # TODO: make sure you're using a PR & topic branch!
  git commit "release ${version} for QE: add new discovery plugins ${newJarCore}, ${newJarEA} + update devstudio-directory.xml" . discovery/*.jar
  # TODO: make sure you've merged in others' changes!
  git push origin master # in case of doubt, prefer pushing to a local repostiory and using a pull-request to ask for review
  popd
  # TODO: change all refs to wallace (wallace.intranet.prod.int.rdu2.redhat.com); files are now on devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
  rsync -aPrz --rsh=ssh jbdevstudio-website/updates/8.0/*  wallace.intranet.prod.int.rdu2.redhat.com:/mnt/devstudio/updates/8.0/
fi
----

=== Fix permissions

# TODO: change all refs to wallace (wallace.intranet.prod.int.rdu2.redhat.com); files are now on devstudio@filemgmt.jboss.org:/www_htdocs/devstudio

Then, fix permissions. From machine +wallace.intranet.prod.int.rdu2.redhat.com+
[source,bash]
----
# TODO: change all refs to wallace (wallace.intranet.prod.int.rdu2.redhat.com); files are now on devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
ssh wallace.intranet.prod.int.rdu2.redhat.com "\
  chmod -R g+w /mnt/devstudio/updates/8.0* 2>/dev/null && \
  chgrp -R devstudio /mnt/devstudio/updates/8.0* 2>/dev/null \
"
----

== Update documentation

In case something change, update relevant documentation in +jbdevstudio-devdoc+ repository. As this is a shared documentation, it's better to create a pull request and ask reviews from other potential users (Nick, Mickael, Max, Denis... and anyone else who can be interested). 


== Release the latest QE snapshot to ide-config.properties

Check out this file:

http://download.jboss.org/jbosstools/configuration/ide-config.properties

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
jboss.discovery.directory.url|devstudio|8.0.0.Beta3=https://devstudio.jboss.com/updates/8.0-staging/devstudio-directory.xml
jboss.discovery.site.url|devstudio|8.0.0.Beta3=https://devstudio.jboss.com/updates/8.0-staging/central/core/
jboss.discovery.earlyaccess.site.url|devstudio|8.0.0.Beta3=https://devstudio.jboss.com/updates/8.0-staging/central/earlyaccess/
----


== Notify the team (send 1 email)
____
*To* external-exadel-list@redhat.com +

[source,bash]
----
version=8.0.0.Beta3c # a, b, c...
respin="respin-c"
TARGET_PLATFORM_VERSION_MIN=4.40.0.Beta4
TARGET_PLATFORM_VERSION_MAX=4.40.0.Beta4
TARGET_PLATFORM_CENTRAL_MAX=4.40.0.Beta4b-SNAPSHOT
TARGET_PLATFORM_EARLYACCESS_MAX=4.40.0.Beta4b-SNAPSHOT
jbdsVersion=8.0.0.Beta3 # no respin suffix here
jbtVersion=4.2.0.Beta3 # no respin suffix here
echo "
Subject: 

JBDS ${version} Core bits available for QE testing

Body:

As always, these are not FINAL bits, but preliminary results for QE testing. Not for redistribution to customers. Links in this section are all internal (VPN required), except for the target platform.

Universal Installers (Internal): http://www.qa.jboss.com/binaries/RHDS/builds/development/${version}-build-core/build-info.html

Update Sites (Internal): http://www.qa.jboss.com/binaries/RHDS/updates/development/${version}-updatesite-core/

Target Platforms (Public):

* http://download.jboss.org/jbosstools/targetplatforms/jbdevstudiotarget/${TARGET_PLATFORM_VERSION_MAX}/ (upcoming milestone)

Until the above target platform site is released, you will need to add it to Eclipse to resolve dependencies at install time. 
Once released, dependencies will be found automatically from here:

* http://download.jboss.org/jbosstools/targetplatforms/jbdevstudiotarget/luna/ (latest release)


** SKIP THIS FOR Alpha **
--

The sites below will take about 1 hour to appear. These are public-facing for staging purposes (no VPN required). 

Update Sites (Public, Staging):

* https://devstudio.jboss.com/updates/8.0-staging/ (includes ${version} Core + Target Platform)
* https://devstudio.jboss.com/updates/8.0-staging/central/core/ (includes ${version} Core + Target Platform + 3rd party site mirrors)
* https://devstudio.jboss.com/updates/8.0-staging/central/earlyaccess/ (as in /core/ but with Early Access content too)

--

New + Noteworthy (subject to change):

* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule / Upcoming Releases: 

https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

Note: if your DNS won't resolve it, use 10.16.89.17 instead of www.qa.jboss.com.
"
if [[ $respin != "respin-" ]]; then
echo " 

--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${jbdsVersion}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${jbtVersion}%22%29%29%29

To compare the upcoming version of Central (${version}) against an older version, add lines similar to these your ~/jbdevstudio/studio/jbdevstudio.ini file after the -vmargs line for the appropriate version & URLs:
  -Djboss.discovery.directory.url=http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}/devstudio-directory.xml
  -Djboss.discovery.site.url=http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}/
  -Djboss.discovery.earlyaccess.site.url=http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}/

or, if available:
  -Djboss.discovery.directory.url=https://devstudio.jboss.com/updates/8.0-staging/devstudio-directory.xml
  -Djboss.discovery.site.url=https://devstudio.jboss.com/updates/8.0-staging/central/core/
  -Djboss.discovery.earlyaccess.site.url=https://devstudio.jboss.com/updates/8.0-staging/central/earlyaccess/

"
fi


----
____
