= Release JBoss Developer Studio Development Milestone

[IMPORTANT]
====
JBIDE-13283, JBDS-2730 use Akamai publishing for update sites, target platforms & zips. +
Use:

  * http://download.jboss.org/jbosstools/static/releases/ instead of 
  * http://download.jboss.org/jbosstools/updates/ +
  and
  * http://download.jboss.org/jbosstools/static/targetplatforms/ instead of 
  * http://download.jboss.org/jbosstools/targetplatforms/
====

[CAUTION]
====
JBIDE-16871 For *Beta2* filename refactoring is coming, so all files/paths will be lowercase. +
Use:

  * jbostools instead of JBossTools
  * update instead of Update
  * etc.
====

This document describe how to publish a valid JBoss Developer Studio build to production after being verified by QE.

WARNING: This requires write access to wallace.redhat.com, but in future will require access to devstudio@filemgmt.jboss.org.

CAUTION: TODO: when releasing GA make sure to :%s/development/stable/g and :%s/8.0-staging/8.0/g in product/features/com.jboss.jbds.product.feature/p2.inf

== SSH to wallace.redhat.com, then fetch zips if not already there

[source,bash]
----
screen

# clean out old update sites from previous milestones; rename update sites from "a,b,c" to ""
version=8.0.0.Beta2
version2=8.0.0.Beta2; # a, b, c, ...
cd /mnt/devstudio/updates/8.0.0/
if [[ ${version} != ${version2} ]]; then 
  mv jboss-devstudio-${version}-updatesite-core jboss-devstudio-${version}-updatesite-core.DELETEME
  mv jboss-devstudio-${version}-target-platform jboss-devstudio-${version}-target-platform.DELETEME
  mv jboss-devstudio-${version2}-updatesite-core jboss-devstudio-${version}-updatesite-core
  mv jboss-devstudio-${version2}-target-platform jboss-devstudio-${version}-target-platform
fi
# TODO: do not run this next line if the above step fails!
rm -fr jboss-devstudio-${version}?-updatesite-core ${version}?-target-platform *.DELETEME
----

== Rename milestones from Foo1b to Foo1; fix html pages in 8.0-staging

[source,bash]
----
# NOTE: ~/truu/devstudio.jboss.com is a symlink on my local machine to this folder in github: https://github.com/jbdevstudio/jbdevstudio-website/tree/master/content
# "gw1" uses special aliases/scripts/shortcuts. Basically, we want to follow correct github workflows so that commits are pushed to user's fork, then later pull-requested (and the PR applied)
# "gw2" will create the PR, "gw3" will apply it, and "gw4" will delete the topic branch locally and in my fork
# the 4 steps are captured here: https://gist.github.com/nickboldt/4111850
alias   ga='git add'
alias   stat='git status'
alias   gd='git diff --color=always -w'
alias   scpr='rsync -aPrz --rsh=ssh'
alias   ci='git commit -m'

cd ~/truu/devstudio.jboss.com/updates/8.0-staging
version=8.0.0.Beta2
version2=8.0.0.Beta2; # a, b, c, ...
now=`date +%s000`
for d in composite*.xml index.html central/core/index.html ; do
  sed -i -e "s#${version2}#${version}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done

# commit to github   
topic="release-${version2}";branch=master; gw1
ci "rename ${version2} to ${version}" .
gw2;gw3;gw4
----

== Update https://www.jboss.org/author/products/devstudio

Log in to magnolia using the "marketing" login.

Release Engineering will provide you with the new file paths to use when linking to jars and zips. 

For example: https://engineering.redhat.com/trac/rcm/wiki/Middleware/ReleaseNotes/JBDS/8.0.0

Review your changes w/ Max & Len before publishing them. 

== Update https://devstudio.jboss.com/updates/8.0*/devstudio-directory.xml to point at new discovery jar(s) from staging.

[IMPORTANT]
====
TODO for CR1 and GA: VERIFY CONTENTS OF DISCOVERY JAR ARE CORRECTLY POINTING AT

*  8.0 for /8.0/
*  8.0-development for /8.0-development/
*  8.0-staging for /8.0-staging/
====

[source,bash]
----

isGA=false # or true in case you're doing a GA
version=8.0.0.Beta2
SRC_SITE=8.0-staging
DESTSITE=8.0-development # or 8.0/ for a GA release

topic="release-${version}";branch=master; gw1

# check in / sync changes
scpr ~/truu/devstudio.jboss.com/updates/${SRC_SITE}/* ~/truu/devstudio.jboss.com/updates/${DESTSITE}/

cd ~/truu/devstudio.jboss.com/updates/${DESTSITE}/discovery/
#git rm -f com.jboss.jbds.central.discovery_*.jar
wget -q -nc http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}/devstudio-directory.xml
newJar=$(cat devstudio-directory.xml | grep entry | sed -e "s#.\+plugins#plugins#g" | sed -e "s#\.jar.\+#.jar#g"); echo $newJar
wget -q -nc http://www.qa.jboss.com/binaries/RHDS/discovery/development/${version}/${newJar}
newJar=${newJar/plugins/discovery}; echo $newJar
rm -f ~/truu/devstudio.jboss.com/updates/${DESTSITE}/discovery/devstudio-directory.xml

# update XML
cd ~/truu/devstudio.jboss.com/updates/${DESTSITE}/
sed -i -e "s#discovery/com.jboss.jbds.central.discovery_.\+\.jar#${newJar}#g" devstudio-directory.xml

unzip -q -d ~/truu/devstudio.jboss.com/updates/${DESTSITE}/${newJar}{_,}
pushd ~/truu/devstudio.jboss.com/updates/${DESTSITE}/${newJar}_ >/dev/null 

if [ "$isGA" = true ]; then
  sed -i "s#https://devstudio.jboss.com/updates/8.0-staging/central/core/#https://devstudio.jboss.com/updates/8.0/central/core/#g" plugin.xml
  sed -i "s#https://devstudio.jboss.com/updates/8.0-development/central/core/#https://devstudio.jboss.com/updates/8.0/central/core/#g" plugin.xml
else  # plugin points to the STAGING URL, not the RELEASE one
  sed -i "s#https://devstudio.jboss.com/updates/8.0-staging/central/#https://devstudio.jboss.com/updates/8.0-development/central/#g" plugin.xml
  sed -i "s#https://devstudio.jboss.com/updates/8.0/central/#https://devstudio.jboss.com/updates/8.0-development/central/#g" plugin.xml
fi

zip -u ~/truu/devstudio.jboss.com/updates/${DESTSITE}/${newJar} plugin.xml
popd >/dev/null
rm -fr ~/truu/devstudio.jboss.com/updates/${DESTSITE}/${newJar}_
----

[CAUTION]
====
Be sure to not overwrite integration-stack deltas (staging and development may not be the same)!
====

=== Update latest target platform composite files

[source,bash]
----

pushd jbdevstudio-website/content/updates/8.0-staging/extras/
now=`date +%s000`

oldTP=4.40.0.Beta1a
newTP=4.40.0.Beta3-SNAPSHOT
for d in composite*.xml; do
  sed -i -e "s#${oldTP}#${newTP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done
popd


[source,bash]
----
# check in / sync changes
ga ${newJar}; stat .
gd .

cd ~/truu/devstudio.jboss.com/updates/
ga ${DESTSITE}
ci "release ${version} from ${SRC_SITE} to ${DESTSITE}" . 
gw2;gw3;gw4

# push both staging and development folders to wallace
scpr ~/truu/devstudio.jboss.com/updates/${DESTSITE} ~/truu/devstudio.jboss.com/updates/${SRC_SITE} $WALL/updates/
----

== Fix file permissions on wallace (pull from dev01):

[source,bash]
----
  ssh nboldt@wallace "
    chmod -R g+w       /mnt/devstudio/updates/8.0* /mnt/devstudio/earlyaccess 2>/dev/null;
    chgrp -R devstudio /mnt/devstudio/updates/8.0* /mnt/devstudio/earlyaccess 2>/dev/null
  "
----

== Tag Git

[source,bash]
----
  # if not already cloned, the do this:
  git clone https://github.com/jbdevstudio/jbdevstudio-product
  git clone https://github.com/jbdevstudio/jbdevstudio-ci
  git clone https://github.com/jbdevstudio/jbdevstudio-website
  git clone https://github.com/jbdevstudio/jbdevstudio-artwork
  git clone https://github.com/jbdevstudio/jbdevstudio-devdoc

  # now tag multiple projects in a single step, replacing existing tags if already exist
  jbt_branch=jbosstools-4.2.0.Beta2x
  version=8.0.0.Beta2
  for d in product ci website artwork devdoc; do
    echo "====================================================================="
    echo "Tagging jbdevstudio-${d} from branch ${jbt_branch} as tag ${version}..."
    pushd ~/truu/jbdevstudio-${d}
    git stash
    git pull origin
    git fetch -t -p
    git checkout ${jbt_branch} && git tag -f jbdevstudio-${version} && git push origin jbdevstudio-${version}
    git checkout master; git stash pop
    echo ">>> https://github.com/jbdevstudio/jbdevstudio-${d}/tree/jbdevstudio-${version}"
    popd >/dev/null 
    echo "====================================================================="
    echo ""
  done
----

== Commit updates to release guide (including this document):

[source,bash]
----
  version=8.0.0.Beta2
  cd ~/truu/doc/release_guide/8.0
  topic="release-${version}";branch=master; gw1
  ci "update release guide for ${version}" .
  g2;gw3;gw4
----

== Move installers from "a" or "b" folder to base folder; purge old stuff from OLD/ folder

  ssh to dev01.mw.lab.eng.bos.redhat.com, sudo to hudson user, then

[source,bash]
----
  cd ~/RHDS/builds/development/
  mv 8.0.0.CR7x.installer OLD/
  mv 8.0.0.CR7x.installer 8.0.0.CR7.installer
  # repeat for updates/development and discovery/development
----

WARNING: For stable releases, move content from RHDS/{builds,updates,discovery}/development into RHDS/{builds,updates,discovery}/stable, then symlink it back so it appears in both places.

== Update Marketplace entry

WARNING: Alpha versions are not published to market place. So ignore this step for Alpha versions.

=== If node doesn't exist yet

This is usually the case of first Beta version.

Create a new node on Marketplace, listing the single "BYOE" feature: com.jboss.devstudio.core.feature

=== If node already exists

Access it via +http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-luna/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Notes / warnings (if applicable, eg., JDK 7/8 issues)

== Release JIRA:

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten. 

Send an email to jbosstools-dev@, external-exadel-list@ and jbds-pm-list@ reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Release the latest milestone to ide-config.properties

Check out this file:

http://download.jboss.org/jbosstools/configuration/ide-config.properties

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
jboss.discovery.directory.url|devstudio|8.0.0.Beta2=https://devstudio.jboss.com/updates/8.0-staging/devstudio-directory.xml
jboss.discovery.site.url|devstudio|8.0.0.Beta2=https://devstudio.jboss.com/updates/8.0-staging/central/core/
----


== Notify the team (send 2 emails)

____

*To* jbosstools-dev@lists.jboss.org +
and +
*To* external-exadel-list@redhat.com, jboss-announce@redhat.com (optional for major milestones/releases)+

[source,bash]
----
version=8.0.0.Beta2
version2=8.0.0.Beta2 # a, b, c...
echo "
Subject: 

JBoss Developer Studio ${version} on Early Access

Body:

JBoss Developer Studio ${version} is available on Early Access!

Download page and installer: https://www.jboss.org/products/devstudio#earlyaccess
Update site: https://devstudio.jboss.com/updates/8.0-development/

Note that the update site may take a while to replicate from our staging server to publication. Please allow at least an hour before attempting to install from the site - if the page above still shows the previous milestone instead of ${version}, try again later.

--

Eclipse Marketplace: https://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-kepler

--

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBDS#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

"
----
____


== Announce internally for push to CSP staging site

____
*To* jbds-pm-list@redhat.com, release-engineering@redhat.com +
and +
*Cc* cobrien@redhat.com, ldimaggi@redhat.com, mmurray@redhat.com, jpallich@redhat.com +

[source,bash]
----
version=8.0.0.Beta2
version2=8.0.0.Beta2 # a, b, c...
version3=8.0.0.Beta2-v20140408-2350-B93
echo "
Subject: 

JBoss Developer Studio ${version} available for push to CSP staging server

Body:

JBoss Developer Studio ${version} (to be renamed from ${version2}) is available to push to CSP staging server, for subsequent smoke test & review by QE.

Please include these 5 files:

* http://www.qa.jboss.com/binaries/RHDS/builds/development/${version}.installer/jboss-devstudio-${version3}-installer-standalone.jar 
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${version}.installer/jboss-devstudio-${version3}-installer-eap.jar
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${version}.installer/jboss-devstudio-${version3}-installer-src.zip
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${version}.installer/jboss-devstudio-${version3}-updatesite-core.zip
* http://www.qa.jboss.com/binaries/RHDS/builds/development/${version}.installer/jboss-devstudio-${version3}-updatesite-central.zip

We will also need GoldenGate links for the 5 artifacts above, as they need to be linked from these pages for Early Access:

* https://www.jboss.org/products/
* https://www.jboss.org/products/devstudio

Only ONE of those artifacts [0] require sign in, as it bundles EAP. The rest are free. 

[0] http://www.qa.jboss.com/binaries/RHDS/builds/development/${version}.installer/jboss-devstudio-${version3}-installer-eap.jar

Please note that the new CSP pages should include similar documentation to the previous release [1] but with these string replacements / updates:

* s/Luna M6/Luna M7/g
* s/Luna M6 JEE bundle/Luna M7 JEE bundle/g
* s/lunam6/lunam7/g
* s/Universal Binary/Installer/g

[1] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html

When pushed, please reply so that QE can review the CSP pages & files for push to production.

Thanks in advance,

"
----
____
