= Publishing JBDS Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

TODO:

* in product/features/com.jboss.jbds.product.feature/p2.inf
* when releasing GA make sure to :%s/development/stable/g and :%s/8.0-staging/8.0/g


== Update Discovery Sites and URLs

See details in link:JBT_4.2.0.CR1_Staging_For_QE.adoc[Staging JBT For QE]


== Disable jobs

All stable branch jobs from the https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_8.0.luna/[8.0.luna view] should be disabled.

Quick way to do so is with https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py[toggleJenkinsJobs.py]. See https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py.examples.txt[usage examples].

Should a respin be needed, they can be re-enabled at that time.


== Stage to qa.jboss.org

*qa.jboss.org* is actually mapped to folder +/qa/services/http/binaries/RHDS+ accessible from CI machines (such as dev01.mw.lab.eng.bos.redhat.com). So first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then copy the latest JBDS artifacts:

* installer
* update site
* discovery site

WARNING: Don't use symlinks are they are too risky to use. Those operations can be done in parallel (using multiple terminals is the easiest way)

=== Push installers, update site, and discovery site

[source,bash]
----
versionWithRespin=8.0.0.CR1 # a, b, c...
# can run 3 steps these in parallel 

rsync -aPrz /qa/services/http/binaries/RHDS/builds/staging/devstudio.product_8.0.luna/installer/* /qa/services/http/binaries/RHDS/builds/development/${versionWithRespin}-build-core/
rsync -aPrz /qa/services/http/binaries/RHDS/builds/staging/devstudio.product_8.0.luna/logs/* /qa/services/http/binaries/RHDS/builds/development/${versionWithRespin}-build-core/
cd /qa/services/http/binaries/RHDS/builds/development/
find . -maxdepth 1 -type d -name "${versionWithRespin}*" | grep ${versionWithRespin}
find . -maxdepth 1 -type d -name "${versionWithRespin}*" | sed "s#\.# >> http://www.qa.jboss.com/binaries/RHDS/builds/development#" | egrep ">>|${versionWithRespin}"

rsync -aPrz /qa/services/http/binaries/RHDS/builds/staging/devstudio.product_8.0.luna/all/repo/* /qa/services/http/binaries/RHDS/updates/development/${versionWithRespin}-updatesite-core/
cd /qa/services/http/binaries/RHDS/updates/development/
find . -maxdepth 1 -type d -name "${versionWithRespin}*" | grep ${versionWithRespin}
find . -maxdepth 1 -type d -name "${versionWithRespin}*" | sed "s#\.# >> http://www.qa.jboss.com/binaries/RHDS/updates/development#" | egrep ">>|${versionWithRespin}"

# earlyaccess site includes one directory.xml file which lists both core and earlyaccess plugins, so use that instead of core site
rsync -aPrz /qa/services/http/binaries/RHDS/discovery/nightly/earlyaccess/4.2.luna/* /qa/services/http/binaries/RHDS/discovery/development/${versionWithRespin}/
----

=== Update discovery composite sites

[source,bash]
----
cd /qa/services/http/binaries/RHDS/discovery/development/${versionWithRespin}/
for c in compositeContent.xml compositeArtifacts.xml; do 
  sed -i -e "s#http://www.qa.jboss.com/binaries/RHDS/builds/staging/devstudio.product.\+/all/.\+/#http://www.qa.jboss.com/binaries/RHDS/updates/development/${versionWithRespin}-updatesite-core/#" $c
  sed -i -e "s#http://www.qa.jboss.com/binaries/RHDS/updates/development/${versionWithRespin}-updatesite-core/repo/#http://www.qa.jboss.com/binaries/RHDS/updates/development/${versionWithRespin}-updatesite-core/#" $c
  cat $c | egrep "${versionWithRespin}"
done
cd /qa/services/http/binaries/RHDS/discovery/development/
find . -maxdepth 1 -type d -name "${versionWithRespin}*" | grep ${versionWithRespin}
find . -maxdepth 1 -type d -name "${versionWithRespin}*" | sed "s#\.# >> http://www.qa.jboss.com/binaries/RHDS/discovery/development#" | egrep ">>|${version}"
----

== Stage files to devstudio.redhat.com

WARNING: Skip this test for Alpha

=== Push content

+devstudio.redhat.com+ is actually hosted on +filemgmt.jboss.org+, accessible from inside Red Hat VPN. So you need both VPN enabled and permissions to write to devstudio@filemgmt. If you don't have access, send a copy of your public SSH key to eng-ops@redhat.com.

First, ssh to dev01, and sudo to the hudson user. From there you will be able to push files to filemgmt.

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

In case target-platform wasn't released (still -SNAPSHOT in version), make sure you clean the various locations before
runnung this script

[source,bash]
----

# can run 4 steps these in parallel 

versionWithRespin=8.0.0.CR1 # a, b, c...
JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
rsync -aPrz --rsh=ssh --protocol=28 /qa/services/http/binaries/RHDS/builds/staging/devstudio.product_8.0.luna/all/repo/* ${JBDS}/updates/8.0.0/jboss-devstudio-${versionWithRespin}-updatesite-core/

# TODO: verify correct URL and filename for the target zip
TARGET_PLATFORM_VERSION_MAX=4.40.0.CR1-SNAPSHOT
unzip -q /qa/services/http/binaries/RHDS/targetplatforms/jbdevstudiotarget/${TARGET_PLATFORM_VERSION_MAX}/jbdevstudiotarget-${TARGET_PLATFORM_VERSION_MAX}.zip -d /tmp/jboss-devstudio-${versionWithRespin}-target-platform
rsync -aPrz --rsh=ssh --protocol=28 /qa/services/http/binaries/RHDS/targetplatforms/jbdevstudiotarget/${TARGET_PLATFORM_VERSION_MAX}/jbdevstudiotarget-${TARGET_PLATFORM_VERSION_MAX}.zip ${JBDS}/updates/8.0.0/
rsync -aPrz --rsh=ssh --protocol=28 /tmp/jboss-devstudio-${version}-target-platform ${JBDS}/updates/8.0.0/

CENTRAL_TARGET_VERSION=4.40.0.CR1-SNAPSHOT
# Central discovery
rm -rf /qa/services/http/binaries/RHDS/targetplatforms/jbtcentraltarget/${CENTRAL_TARGET_VERSION}
mkdir -p /qa/services/http/binaries/RHDS/targetplatforms/jbtcentraltarget/${CENTRAL_TARGET_VERSION}/
pushd /qa/services/http/binaries/RHDS/targetplatforms/jbtcentraltarget/${CENTRAL_TARGET_VERSION}/
wget http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/${CENTRAL_TARGET_VERSION}/jbtcentraltarget-${CENTRAL_TARGET_VERSION}.zip
popd
rm -fr /tmp/jboss-devstudio-${versionWithRespin}-updatesite-central
unzip -q /qa/services/http/binaries/RHDS/targetplatforms/jbtcentraltarget/${TARGET_PLATFORM_VERSION_MAX}/jbtcentraltarget-${CENTRAL_TARGET_VERSION}.zip -d /tmp/jboss-devstudio-${versionWithRespin}-updatesite-central
rsync -aPrz --rsh=ssh --protocol=28 --delete /tmp/jboss-devstudio-${version}-updatesite-central/* ${JBDS}/updates/8.0.0/jboss-devstudio-${versionWithRespin}-updatesite-central/
rsync -aPrz --rsh=ssh --protocol=28 /qa/services/http/binaries/RHDS/targetplatforms/jbtcentraltarget/${CENTRAL_TARGET_VERSION}/jbtcentraltarget-${CENTRAL_TARGET_VERSION}.zip ${JBDS}/updates/8.0.0/
# Early Access
rm -rf /qa/services/http/binaries/RHDS/targetplatforms/jbtearlyaccesstarget/${CENTRAL_TARGET_VERSION}/
mkdir -p /qa/services/http/binaries/RHDS/targetplatforms/jbtearlyaccesstarget/${CENTRAL_TARGET_VERSION}/
pushd /qa/services/http/binaries/RHDS/targetplatforms/jbtearlyaccesstarget/${CENTRAL_TARGET_VERSION}/
wget http://download.jboss.org/jbosstools/targetplatforms/jbtearlyaccesstarget/${CENTRAL_TARGET_VERSION}/jbtearlyaccesstarget-${CENTRAL_TARGET_VERSION}.zip
popd
rm -fr /tmp/jboss-devstudio-${versionWithRespin}-updatesite-earlyaccess
unzip -q /qa/services/http/binaries/RHDS/targetplatforms/jbtearlyaccesstarget/${TARGET_PLATFORM_VERSION_MAX}/jbtearlyaccesstarget-${CENTRAL_TARGET_VERSION}.zip -d /tmp/jboss-devstudio-${versionWithRespin}-updatesite-earlyaccess
rsync -aPrz --rsh=ssh --protocol=28 --delete /tmp/jboss-devstudio-${version}-updatesite-earlyaccess/* ${JBDS}/updates/8.0.0/jboss-devstudio-${versionWithRespin}-updatesite-earlyaccess/
rsync -aPrz --rsh=ssh --protocol=28 /qa/services/http/binaries/RHDS/targetplatforms/jbtearlyaccesstarget/${CENTRAL_TARGET_VERSION}/jbtearlyaccesstarget-${CENTRAL_TARGET_VERSION}.zip ${JBDS}/updates/8.0.0/

----

=== Update latest target platform composite files

Then, update the composite files to have public URLs pointing to these artifacts. Get a clone of repository +https://github.com/jbdevstudio/jbdevstudio-website+, then we can update the necessary composite files to reference new locations. This imply tweaks on some files of the jbdevstudio-website repository. This repo will get later published to devstudio.redhat.com. Those changes can then be performed on your local machine.

[source,bash]
----
pushd jbdevstudio-website/content/updates/8.0-staging/
now=`date +%s000`

oldTP=jboss-devstudio-8.0.0.Beta3
newTP=jboss-devstudio-${version}
# Example for a respin
# oldTP=jboss-devstudio-8.0.0.CR1
# newTP=jboss-devstudio-8.0.0.CR1a
for d in composite*.xml; do
  sed -i -e "s#${oldTP}#${newTP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done
popd

----

=== Update composite discovery files

[source,bash]
----
isGA=false # or true in case you're doing a GA
previousFull=8.0.0.Beta3 # a, b, c...
versionWithRespin=8.0.0.CR1 # a, b, c...

#TODO: make sure you're the correct folder here!
pushd jbdevstudio-website/content/
now=`date +%s000`
for d in updates/8.0-staging/*.*ml earlyaccess/8.0-staging/*.*ml; do
  # update composite timestamp
  sed -i -e "s#${previousFull}#${versionWithRespin}#g" -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done
popd

# update https://devstudio.redhat.com/updates/8.0-staging/devstudio-directory.xml to point at new Core discovery jar.
# Latest discovery site is here: http://www.qa.jboss.com/binaries/RHDS/discovery/development/${versionWithRespin}
pushd jbdevstudio-website/content/updates/8.0-staging/discovery/
wget -q -nc http://www.qa.jboss.com/binaries/RHDS/discovery/development/${versionWithRespin}/devstudio-directory.xml
newJars=$(cat devstudio-directory.xml | grep entry | sed -e "s#.\+plugins#plugins#g" | sed -e "s#\.jar.\+#.jar#g")
for newJar in $newJars; do 
  wget -q -nc http://www.qa.jboss.com/binaries/RHDS/discovery/development/${versionWithRespin}/${newJar}
  if [[ ! ${newJar##*.earlyaccess_*} ]]; then
    newJarEA=${newJar/plugins/discovery}
    echo "EA: $newJarEA"
  else
    newJarCore=${newJar/plugins/discovery}
    echo "Core: $newJarCore"
  fi
done
rm -f devstudio-directory.xml
popd

# update XML
pushd jbdevstudio-website/content/updates/8.0-staging/
sed -i -e "s#discovery/com.jboss.jbds.central.discovery.earlyaccess_.\+\.jar#${newJarEA}#g" devstudio-directory.xml
sed -i -e "s#discovery/com.jboss.jbds.central.discovery_.\+\.jar#${newJarCore}#g" devstudio-directory.xml
  
unzip -q -d ${newJarEA}{_,}
pushd ${newJarEA}_ 

if [ "$isGA" = true ]; then
  sed -i "s#https://devstudio.redhat.com/updates/8.0-staging/central/earlyaccess/#https://devstudio.redhat.com/updates/8.0/central/earlyaccess/#g" plugin.xml
  sed -i "s#https://devstudio.redhat.com/updates/8.0-development/central/earlyaccess/#https://devstudio.redhat.com/updates/8.0/central/earlyaccess/#g" plugin.xml
else  # plugin points to the STAGING URL, not the RELEASE one
  sed -i "s#https://devstudio.redhat.com/updates/8.0/central/earlyaccess/#https://devstudio.redhat.com/updates/8.0-staging/central/earlyaccess/#g" plugin.xml
  sed -i "s#https://devstudio.redhat.com/updates/8.0-development/central/earlyaccess/#https://devstudio.redhat.com/updates/8.0-staging/central/earlyaccess/#g" plugin.xml
fi
zip -u ../../${newJarEA} plugin.xml
popd
rm -fr ${newJarEA}_

unzip -q -d ${newJarCore}{_,}
pushd ${newJarCore}_ 

if [ "$isGA" = true ]; then
  sed -i "s#https://devstudio.redhat.com/updates/8.0-staging/#https://devstudio.redhat.com/updates/8.0/#g" plugin.xml
  sed -i "s#https://devstudio.redhat.com/updates/8.0-development/#https://devstudio.redhat.com/updates/8.0/#g" plugin.xml
else  # plugin points to the STAGING URL, not the RELEASE one
  sed -i "s#https://devstudio.redhat.com/updates/8.0/#https://devstudio.redhat.com/updates/8.0-staging/#g" plugin.xml
  sed -i "s#https://devstudio.redhat.com/updates/8.0-development/#https://devstudio.redhat.com/updates/8.0-staging/#g" plugin.xml
fi
zip -u ../../${newJarCore} plugin.xml
popd
rm -fr ${newJarCore}_

popd # all the way back out

# don't do this until you're ready to release the content -- not for QE
# TODO: move this to the Release doc, not the Staging for QE doc
#if [ "$isGA" = true ]; then # new plugin is also in 8.0/ and 8.0-development/ as well as 8.0-staging/
#  cp -f jbdevstudio-website/content/updates/8.0-staging/${newJar} jbdevstudio-website/content/updates/8.0-development/${newJar}
#  cp -f jbdevstudio-website/content/updates/8.0-staging/devstudio-directory.xml jbdevstudio-website/content/updates/8.0-development/devstudio-directory.xml
#
#  cp -f jbdevstudio-website/content/updates/8.0-staging/${newJar} jbdevstudio-website/content/updates/8.0/${newJar}
#  cp -f jbdevstudio-website/content/updates/8.0-staging/devstudio-directory.xml jbdevstudio-website/content/updates/8.0/devstudio-directory.xml
#fi

# check in / sync changes
pushd jbdevstudio-website/content/updates/8.0-staging/
git add ${newJarEA} ${newJarCore}
git status .
git diff --color=always -w .
# TODO: make sure you're using a PR & topic branch!
git commit -m "release ${versionWithRespin} for QE: add new discovery plugins ${newJarCore}, ${newJarEA} + update devstudio-directory.xml + update HTML pages" . discovery/*.jar
# TODO: make sure you've merged in others' changes!
git push origin master # in case of doubt, prefer pushing to a local repostiory and using a pull-request to ask for review
popd

JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
rsync -aPrz --rsh=ssh --protocol=28 jbdevstudio-website/content/updates/8.0-staging/* ${JBDS}/updates/8.0-staging/
rsync -aPrz --rsh=ssh --protocol=28 jbdevstudio-website/content/earlyaccess/8.0-staging/* ${JBDS}/earlyaccess/8.0-staging/

if [ "$isGA" = true ]; then
  pushd jbdevstudio-website/content/updates/8.0/
  git add ${newJar}
  git status .
  gd diff --color=always -w .
  # TODO: make sure you're using a PR & topic branch!
  git commit "release ${versionWithRespin} for QE: add new discovery plugins ${newJarCore}, ${newJarEA} + update devstudio-directory.xml" . discovery/*.jar
  # TODO: make sure you've merged in others' changes!
  git push origin master # in case of doubt, prefer pushing to a local repostiory and using a pull-request to ask for review
  popd
  
  rsync -aPrz --rsh=ssh --protocol=28 jbdevstudio-website/updates/8.0/*  devstudio@filemgmt.jboss.org:/www_htdocs/devstudio/updates/8.0/
fi
----

== Update documentation

In case something change, update relevant documentation in +jbdevstudio-devdoc+ repository. As this is a shared documentation, it's better to create a pull request and ask reviews from other potential users (Nick, Mickael, Max, Denis... and anyone else who can be interested). 


== Release the latest QE snapshot to ide-config.properties

Check out this file:

http://download.jboss.org/jbosstools/configuration/ide-config.properties

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
jboss.discovery.directory.url|devstudio|8.0.0.CR1=https://devstudio.redhat.com/updates/8.0-staging/devstudio-directory.xml
jboss.discovery.site.url|devstudio|8.0.0.CR1=https://devstudio.redhat.com/updates/8.0-staging/
jboss.discovery.earlyaccess.site.url|devstudio|8.0.0.CR1=https://devstudio.redhat.com/earlyaccess/8.0-staging/
----


== Release the latest devstudio-earlyaccess.properties

NOTE: Should be automated together with publication of new discovery site, so this operation would be automatically part
of moving/copying discovery site to staging location.

Get the file __earlyaccess.properties__ from discovery job, in workspace folder __jbdevstudio/com.jboss.devstudio.discovery.earlyaccess__: 
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_8.0.luna/job/jbosstools-discovery_4.2.luna/ws/sources/jbdevstudio/com.jboss.jbds.central.discovery.earlyaccess/devstudio-earlyaccess.properties
and copy it do __https://devstudio.redhat.com/updates/8.0-staging/discovery/devstudio-earlyaccess.properties__.

== Notify the team (send 1 email)
____
*To* external-exadel-list@redhat.com +

[source,bash]
----
versionWithRespin=8.0.0.CR1 # a, b, c...
respin="respin-"
TARGET_PLATFORM_VERSION_MIN=4.40.0.CR1-SNAPSHOT
TARGET_PLATFORM_VERSION_MAX=4.40.0.CR1-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.40.0.CR1-SNAPSHOT
TARGET_PLATFORM_EARLYACCESS_MAX=4.40.0.CR1-SNAPSHOT
jbdsVersion=8.0.0.CR1 # no respin suffix here
jbtVersion=4.2.0.CR1 # no respin suffix here
echo "
Subject: 

JBDS ${versionWithRespin} Core bits available for QE testing

Body:

As always, these are not FINAL bits, but preliminary results for QE testing. Not for redistribution to customers. Links in this section are all internal (VPN required), except for the target platform.

Universal Installers (Internal): http://www.qa.jboss.com/binaries/RHDS/builds/development/${versionWithRespin}-build-core/build-info.html
Update Sites (Internal): http://www.qa.jboss.com/binaries/RHDS/updates/development/${versionWithRespin}-updatesite-core/

Target Platforms (Public): http://download.jboss.org/jbosstools/targetplatforms/jbdevstudiotarget/${TARGET_PLATFORM_VERSION_MAX}/ (upcoming milestone)
Until the above target platform site is released, you will need to add it to Eclipse to resolve dependencies at install time. 
Once released, dependencies will be found automatically from here: http://download.jboss.org/jbosstools/targetplatforms/jbdevstudiotarget/luna/ (latest release)

--

The sites below are public-facing for staging purposes (no VPN required). 

Update Sites (Public, Staging):

* https://devstudio.redhat.com/updates/8.0-staging/ (includes ${version} Core + Target Platform + 3rd party site mirrors)
* https://devstudio.redhat.com/earlyaccess/8.0-staging/ (as in /core/ but with Early Access content too)

--

New + Noteworthy (subject to change):
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

"

if [[ $respin != "respin-" ]]; then
echo " 
Changes prompting this $respin are: https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${jbdsVersion}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${jbtVersion}%22%29%29%29
"
fi


----
____
