= Publishing JBT update sites for QE

This document describe how to provide a valid JBoss Tools build to QE so they can test us.

[NOTE]
====
Note that +sftp://tools@filemgmt.jboss.org/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+ +

If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools

A Jenkins job can then be triggered to sync changes to download.jboss.org: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-download.jboss.org-rsync-from-svn/
====


== Verify all branches have been created & all master branch root poms point to the NEXT parent pom version.

Chances are you opened a JIRA like https://issues.jboss.org/browse/JBIDE-18149 and asked everyone to branch and then upversion the references to the parent pom in their root poms.
Chances are also that someone might have forgotten to do this.

So, to ensure everyone has done what they need to do, you can run two scripts:

* ensure all the branches exist.

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/getProjectSHAs.sh

* ensure the root poms are correct

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/getProjectRootPomParents.sh

If any branches have not yet been created, you can either:
* Ask Denis, Fred, or Max to get them created
* Reconfigure the jobs to build from your fork, and create the branch there

If any of the root poms have not been correctly updated, simply re-open the task JIRAs like https://issues.jboss.org/browse/JBIDE-18167 and ask that the root pom be updated.

Once the above conditions have been met, you can proceed to the next steps.


== Stage to download.jboss.org

=== Promote builds from "nightly" to "development"

*Development* where we store builds for staging. This contains build metadata. The URL for development sites pattern is +http://download.jboss.org/jbosstools/staging/<version>.<siteName>/<buildId>::
. *Core* site (which contains JBoss Tools): Move the most recent build available from +http://downloads.jboss.org/jbosstools/builds/nightly/core/4.2.luna+ to +http://downloads.jboss.org/jbosstools/builds/staging/jbosstools-4.2.0.CR2-updatesite-core/+
. *Core Tests* site (which contains JBoss Tools tests): Move the most recent build available from +http://downloads.jboss.org/jbosstools/builds/nightly/coretests/4.2.luna+ to +http://downloads.jboss.org/jbosstools/builds/staging/jbosstools-4.2.0.CR2-updatesite-coretests/+
. *WebTools* site (which contains only WTP connectors for AS/WildFly/EAP): Move the most recent build available from +http://downloads.jboss.org/jbosstools/builds/nightly/webtools/4.2.luna+ to +http://downloads.jboss.org/jbosstools/builds/staging/jbosstools-4.2.0.CR2-updatesite-webtools/+ 
. *Hibernate Tools* site (which contains Hibernate Tools, a subset of JBoss Tools): Move the most recent build available from +http://downloads.jboss.org/jbosstools/builds/nightly/hibernatetools/4.2.luna+ to +http://downloads.jboss.org/jbosstools/builds/staging/jbosstools-4.2.0.CR2-updatesite-hibernatetools/+

Here is a script that does this:
[source,bash]
----
stream=4.2.luna
version=4.2.0.CR2 # a, b, c...

site=core
# Retrieve latest build and remove trailing slash
coreBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1) 
coreBuildID=${coreBuildID%%/*}
echo "Latest build for ${site}: ${coreBuildID}"
# Create target directory and populate it
echo "mkdir staging/jbosstools-${version}-build-${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${coreBuildID} staging/jbosstools-${version}-build-${site}/${coreBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

site=coretests
# Repeat operation
coretestsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1)
coretestsBuildID=${coretestsBuildID%%/*}
echo "Latest build for ${site}: ${coretestsBuildID}"
echo "mkdir staging/jbosstools-${version}-build-${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${coretestsBuildID} staging/jbosstools-${version}-build-${site}/${coretestsBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  
site=hibernatetools
hibernatetoolsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1)
hibernatetoolsBuildID=${hibernatetoolsBuildID%%/*}
echo "Latest build for ${site}: ${hibernatetoolsBuildID}"
echo "mkdir staging/jbosstools-${version}-build-${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${hibernatetoolsBuildID} staging/jbosstools-${version}-build-${site}/${hibernatetoolsBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  
site=webtools
webtoolsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1)
webtoolsBuildID=${webtoolsBuildID%%/*}
echo "Latest build for ${site}: ${webtoolsBuildID}"
echo "mkdir staging/jbosstools-${version}-build-${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${webtoolsBuildID} staging/jbosstools-${version}-build-${site}/${webtoolsBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  
echo " >> http://download.jboss.org/jbosstools/builds/staging/jbosstools-${version}-build-core/${coreBuildID}" | egrep ">>|${version}"
echo " >> http://download.jboss.org/jbosstools/builds/staging/jbosstools-${version}-build-coretests/${coretestsBuildID}" | egrep ">>|${version}"
echo " >> http://download.jboss.org/jbosstools/builds/staging/jbosstools-${version}-build-hibernatetools/${hibernatetoolsBuildID}" | egrep ">>|${version}"
echo " >> http://download.jboss.org/jbosstools/builds/staging/jbosstools-${version}-build-webtools/${webtoolsBuildID}" | egrep ">>|${version}"

----

Then verify sites are correctly populated with build metadata. To do so, you can simply make sure that under each one of these build sites, you find a file /logs/GIT_REVISION.txt.

=== Stage update sites

p2 repositories are expected to be under the +http://download.jboss.org/jbosstools/updates+ directory. Similarly to the build sites, we move them there.

[source,bash]
----
stream=4.2.luna
version=4.2.0.CR2 # a, b, c...

site=core
echo "rename nightly/${site}/${stream} staging/luna/jbosstools-${version}-updatesite-${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates  
echo " >> http://download.jboss.org/jbosstools/updates/staging/luna/jbosstools-${version}-updatesite-${site}/" | egrep ">>|${version}"

site=coretests
echo "rename nightly/${site}/${stream} staging/luna/jbosstools-${version}-updatesite-${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates  
echo " >> http://download.jboss.org/jbosstools/updates/staging/luna/jbosstools-${version}-updatesite-${site}/" | egrep ">>|${version}"

site=hibernatetools
echo "rename nightly/${site}/${stream} staging/luna/jbosstools-${version}-updatesite-${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates
echo " >> http://download.jboss.org/jbosstools/updates/staging/luna/jbosstools-${version}-updatesite-${site}/" | egrep ">>|${version}"

site=webtools
echo "rename nightly/${site}/${stream} staging/luna/jbosstools-${version}-updatesite-${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates
echo " >> http://download.jboss.org/jbosstools/updates/staging/luna/jbosstools-${version}-updatesite-${site}/" | egrep ">>|${version}"

----

Then verify those 4 sites are correctly populated.

=== Regenerate composite site metadata for staged updates

Update files __http://download.jboss.org/jbosstools/updates/staging/luna/composite*.xml__ , with SFTP/SCP via command-line or your 
favourite SFTP GUI client (such as Eclipse RSE).

This site needs to contain:
* The new JBoss Tools core site
* It's recomended target-platform site
* JBoss Tools Central site

Optionally, run this script, then verify the resulting composite site:

[source,bash]
----

~/tru/buildci/util/cleanup/jbosstools-cleanup.sh --regen-metadata-only --no-subdirs --dirs-to-scan updates/staging/luna
firefox "view-source:http://download.jboss.org/jbosstools/updates/staging/luna/compositeContent.xml"

----


== Rebuild Target Platforms for Central and Early Access

WARNING: This step is very important!

Central and Early Access target platforms contain parts of JBoss Tools which have not yet been released, so these target platforms need to be rebuilt with every push to QE.

Without this step, QE will be confused why there are Beta2 bits in the CR2 Central - eg., for Arquillian or Cordovasim.

* Update the .target files and pom.xml files to include the correct respin label ("" for a first build, "a" or "b" for subsequent respins). 
* Update the .target files to pull the latest JBT bits and verify it works with verifyTarget.sh. 

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/verifyTarget.sh

* Commit your changes.

* Run the job to pick up the new commit, and verify that it publishes to the correct folder, eg. with "a" or "b":

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_8.0.luna/job/jbosstools-centraltarget_4.2.luna
http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/4.41.0.CR2-SNAPSHOT/
http://download.jboss.org/jbosstools/targetplatforms/jbtearlyaccesstarget/4.41.0.CR2-SNAPSHOT/


== Update Discovery URLs

[[update-discovery-urls]]
Update the *stable branch* discovery job ( https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_8.0.luna/job/jbosstools-discovery_4.2.luna/configure ) to publish to the right URL, according to JBT and JBDS versions +

* Update property +JBTCENTRALTARGET_VERSION+ to 4.41.0.CR2-SNAPSHOT
* Update property +JBTEARLYACCESSTARGET_VERSION+ to 4.41.0.CR2-SNAPSHOT

* Update property +JBT_UPDATE_SITE+ to http://download.jboss.org/jbosstools/updates/staging/luna/
* Update property +JBDS_UPDATE_SITE+ to http://www.qa.jboss.com/binaries/RHDS/updates/development/8.0.0.CR2-updatesite-core/

Then respin the job and verify that sites were correctly populated:

* http://download.jboss.org/jbosstools/discovery/nightly/core/4.2.luna/
* http://www.qa.jboss.com/binaries/RHDS/discovery/nightly/core/4.2.luna/


=== Stage discovery site 

WARNING: Make sure you performed the step <<update-discovery-urls,Update Discovery URLs>> above.

[source,bash]
----
stream=4.2.luna
version=4.2.0.CR2 # a, b, c...
# earlyaccess site includes one directory.xml file which lists both core and earlyaccess plugins, so use that instead of core site
echo "rename nightly/earlyaccess/${stream} staging/${version}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/
echo " >> http://download.jboss.org/jbosstools/discovery/staging/${version}/" | egrep ">>|${version}"
----

Then verify the site is correctly populated.

=== Preserve a copy of the nightly sites after the move

NOTE:
This step is mandatory only because we dont have a good way to copy stuff remotely (sftp only allows rename). If we could be granted something more powerful with remote copies, we could copy stuff in previous steps instead of moving it, and this step would becomme useless.

First, run it as +hudson+ user from a ci machine
[source,bash]
----
local$ ssh dev01.mw.lab.eng.bos.redhat.com
dev01$ sudo su - hudson
dev01$ # set up command prompt and load aliases
dev01$ . /home/hudson/config_repository/scripts/jbds/prompt.sh 
----
or, if you didn't run prompt.sh above, you'll need this
[source,bash]
----
alias   scpr="rsync -aPrz --rsh=ssh --protocol=28"
----

Them you can run this 4 steps in parallel:
[source,bash]
----
version=4.2.0.CR2 #a, b, c...
stream=4.2.luna
branch=core/${stream}
scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging/luna/jbosstools-${version}-updatesite-core/* /tmp/jbosstools-${version}-updatesite-core/
scpr /tmp/jbosstools-${version}-updatesite-core/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
rm -fr /tmp/jbosstools-${version}-updatesite-core/
echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

version=4.2.0.CR2 #a, b, c...
stream=4.2.luna
branch=coretests/${stream}
scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging/luna/jbosstools-${version}-updatesite-coretests/* /tmp/jbosstools-${version}-updatesite-coretests/
scpr /tmp/jbosstools-${version}-updatesite-coretests/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
rm -fr /tmp/jbosstools-${version}-updatesite-coretests/
echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

version=4.2.0.CR2 #a, b, c...
stream=4.2.luna
branch=hibernatetools/${stream}
scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging/luna/jbosstools-${version}-updatesite-hibernatetools/* /tmp/jbosstools-${version}-updatesite-hibernatetools/
scpr /tmp/jbosstools-${version}-updatesite-hibernatetools/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
rm -fr /tmp/jbosstools-${version}-updatesite-hibernatetools/
echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

version=4.2.0.CR2 #a, b, c...
stream=4.2.luna
branch=webtools/${stream}
scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging/luna/jbosstools-${version}-updatesite-webtools/* /tmp/jbosstools-${version}-updatesite-webtools/
scpr /tmp/jbosstools-${version}-updatesite-webtools/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
rm -fr /tmp/jbosstools-${version}-updatesite-webtools/
echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

# now, discovery site
version=4.2.0.CR2 #a, b, c...
stream=4.2.luna
branch=earlyaccess/${stream}
scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/staging/${version}/* /tmp/jbosstools-${version}-updatesite-discovery/
scpr /tmp/jbosstools-${version}-updatesite-discovery/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/nightly/${branch}/ --delete
rm -fr /tmp/jbosstools-${version}-updatesite-discovery/
echo " >> http://download.jboss.org/jbosstools/discovery/nightly/${branch}/" | egrep ">>|${branch}"
----

== Release the latest QE snapshot to ide-config.properties

Check out this file:

http://download.jboss.org/jbosstools/configuration/ide-config.properties

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
version=4.2.0.CR2 #a, b, c...
# adjust these steps to fit your own path location & git workflow
cd jbosstools-download.jboss.org/jbosstools/configuration
git fetch jbosstools master
git checkout FETCH_HEAD

vim ide-config.properties # or use another editor 

# replace existing lines with these to make the ${version} stuff live. ${version} must be exanded in the file
  jboss.discovery.directory.url|jbosstools|4.2.0.CR2=http://download.jboss.org/jbosstools/discovery/staging/${version}/jbosstools-directory.xml
  jboss.discovery.site.url|jbosstools|4.2.0.CR2=http://download.jboss.org/jbosstools/updates/staging/luna/
  jboss.discovery.earlyaccess.site.url|jbosstools|4.2.0.CR2=http://download.jboss.org/jbosstools/discovery/staging/${version}/
  jboss.discovery.earlyaccess.list.url|jbosstools|4.2.0.CR2=http://download.jboss.org/jbosstools/discovery/staging/${version}/jbosstools-earlyaccess.properties

# commit the change and push to master
git add ide-config.properties
git commit -m "release JBT ${version} to QE: link to latest dev milestone discovery site" ide-config.properties
git push jbosstools HEAD:master

# push updated file to server
scp ide-config.properties tools@filemgmt.jboss.org:/downloads_htdocs/tools/configuration/ide-config.properties
----
== Disable jobs

All stable branch jobs from the https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_8.0.luna/[8.0.luna view] should be disabled.

Quick way to do so is with https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py[toggleJenkinsJobs.py]. 
See https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py.examples.txt[usage examples].

Should a respin be needed, they can be re-enabled at that time.


== Notify the team

____
*To* jbosstools-dev@lists.jboss.org +

[source,bash]
----
version=4.2.0.CR2 # a, b, c...
respin="respin-"
TARGET_PLATFORM_VERSION_MIN=4.40.0.CR2-SNAPSHOT
TARGET_PLATFORM_VERSION_MAX=4.41.0.CR2-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.41.0.CR2-SNAPSHOT
TARGET_PLATFORM_EARLYACCESS_MAX=4.41.0.CR2-SNAPSHOT
jbdsFixVersion=8.0.0.CR2 # no respin suffix here
jbtFixVersion=4.2.0.CR2 # no respin suffix here
echo "
Subject: 

JBoss Tools Core ${version} bits available for QE testing

Body:

As always, these are not FINAL bits, but preliminary results for QE & community testing. Not for use by customers or end users. 

Update site: http://download.jboss.org/jbosstools/updates/staging/luna/jbosstools-${version}-updatesite-core/

Target platforms: 
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MIN} (upcoming Luna R milestone)
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX} (upcoming Luna SR1 milestone)

Until the above target platform site is released, you will need to add it to Eclipse to resolve dependencies at install time. 
Once released, dependencies will be found automatically from here:
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/luna/ (latest release)
* http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/${TARGET_PLATFORM_CENTRAL_MAX}/ (upcoming milestone)
* http://download.jboss.org/jbosstools/targetplatforms/jbtearlyaccesstarget/${TARGET_PLATFORM_EARLYACCESS_MAX}/ (upcoming milestone)

New + noteworthy (subject to change): 
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule: https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

--

Additional update sites & builds:
* http://download.jboss.org/jbosstools/updates/staging/luna/jbosstools-${version}-updatesite-coretests/
* http://download.jboss.org/jbosstools/updates/staging/luna/jbosstools-${version}-updatesite-hibernatetools/
* http://download.jboss.org/jbosstools/updates/staging/luna/jbosstools-${version}-updatesite-webtools/

* http://download.jboss.org/jbosstools/builds/staging/jbosstools-${version}-build-core/
* http://download.jboss.org/jbosstools/builds/staging/jbosstools-${version}-build-coretests/
* http://download.jboss.org/jbosstools/builds/staging/jbosstools-${version}-build-hibernatetools/
* http://download.jboss.org/jbosstools/builds/staging/jbosstools-${version}-build-webtools/

"
if [[ $respin != "respin-" ]]; then
echo " 

--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${jbdsFixVersion}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${jbtFixVersion}%22%29%29%29

To compare the upcoming version of Central (${version}) against an older version, add lines similar to these your eclipse.ini file after the -vmargs line for the appropriate version & URLs:
 -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/staging/${version}/jbosstools-directory.xml
 -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/discovery/staging/${version}/
 -Djboss.discovery.earlyaccess.site.url=http://download.jboss.org/jbosstools/discovery/staging/${version}/
"
fi

----
____
