= Release JBoss Tools Development Milestone

[CAUTION]
====
JBIDE-16871 For *Beta2* filename refactoring is coming, so all files/paths will be lowercase. +
Use:

  * jbostools instead of JBossTools
  * update instead of Update
  * etc.
====

This document describe how to publish a valid JBoss Tools build to production after being verified by QE.

WARNING: this requires write access to http://sourceforge.net/projects/jboss/files/JBossTools/

== Summary

Here are some generalities site promotion/release process. It's not an exhaustive list so you need to read the full document to do a release, but it gives an overview of the various steps.

. CI build output is published the 'builds/staging' folder, while aggregated update-sites goes to 'updates/nightly' folder
. After branching, component repository are rebuilt from branch (instead of 'master') and new aggregated updatesites are created as well.  A site is promoted from nightly to staging for QE, and moves from 'updates/nightly' to 'updates/staging', including a respin suffix if required.
.. If QE finds a blocker issue, let's go for a respin
... On Jira, add a 'respin-a' or 'respin-b' or 'respin-x' label to bugs that needs for be fixed for the respin
... Edit CI jobs to the next respin label (eg Beta1a -> Beta1b)
... Re-run necessary jobs
... Go To 1
.. If QE approves, release is accepted and promoted
... Zips get published on sourceforge
... Site moves from 'updates/staging' with respin label to 'static/releases' without respin label
... Links to 'updates/luna' are replaced to link to new version
... JBoss Tools website is updated
... Git repositories are tagged
... Eclipse Marketplace entries are created or updated
... Interested parties are notified


== Zips on sf.net

Zips (recommanded for offline installation) are made available on sf.net. sf.net provides interesting metrics on download and other stuff.

=== Prepare files

On your local machine, using a SFTP client (or the script suggested above), move the files to publish to +http://download.jboss.org/jbosstools/builds/development/sf.net/+ and rename them to conform to pattern.

[CAUTION]
====
JBIDE-16632 For *Beta2* verify source zip actually contains github sources for the projects, not just from jbosstools-build-sites! Should be about 40MB, not 30KB!
====

[source,bash]
----
stream=4.2.luna
version=4.2.0.Beta2 # name to use in filenames ie fixVersion in JIRA
echo "mkdir development/sf.net/${version}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

versionWithRespin=4.2.0.Beta2 # Fully qualified version, including respin suffix
coreBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/development/jbosstools-${versionWithRespin}-build-core/ 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); buildID=${coreBuildID%%/*}
echo "Latest build: ${corebuildID}"
echo "rename development/jbosstools-${versionWithRespin}-build-core/${coreBuildID}/all/jbosstools-build-sites.aggregate.site_${stream}-updatesite-${coreBuildID}.zip      development/sf.net/${version}/jbosstools-${version}_${coreBuildID}-updatesite-core.zip"         | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename development/jbosstools-${versionWithRespin}-build-core/${coreBuildID}/all/jbosstools-build-sites.aggregate.site_${stream}-updatesite-${coreBuildID}.zip.MD5  development/sf.net/${version}/jbosstools-${version}_${coreBuildID}-updatesite-core.zip.MD5"     | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename development/jbosstools-${versionWithRespin}-build-core/${coreBuildID}/all/jbosstools-build-sites.aggregate.site_${stream}-Sources-${coreBuildID}.zip     development/sf.net/${version}/jbosstools-${version}_${coreBuildID}-src.zip.zip"        | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename development/jbosstools-${versionWithRespin}-build-core/${coreBuildID}/all/jbosstools-build-sites.aggregate.site_${stream}-Sources-${coreBuildID}.zip.MD5 development/sf.net/${version}/jbosstools-${version}_${coreBuildID}-src.zip.zip.MD5"    | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

hibernateToolsVersionWithRespin=4.2.0.Beta2 #it is highly possible that hibernate tools didn't require a respin and hence have another fully qualified version
hibernateToolsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/development/${hibernateToolsVersionWithRespin}.hibernatetools/ 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); hibernateToolsBuildID=${hibernateToolsBuildID%%/*}
echo "Latest build: ${hibernateToolsBuildID}"
echo "rename development/jbosstools-${versionWithRespin}-build-hibernatetools/${hibernateToolsBuildID}/all/jbosstools-build-sites.aggregate.hibernatetools-site_${stream}-updatesite-${hibernateToolsBuildID}.zip development/sf.net/${version}/jbosstools-${version}_${hibernateToolsBuildID}-updatesite-hibernatetools.zip.zip" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename development/jbosstools-${versionWithRespin}-build-hibernatetools/${hibernateToolsBuildID}/all/jbosstools-build-sites.aggregate.hibernatetools-site_${stream}-updatesite-${hibernateToolsBuildID}.zip.MD5 development/sf.net/${version}/jbosstools-${version}_${hibernateToolsBuildID}-updatesite-hibernatetools.zip.zip.MD5" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
----

=== Pull files to sf.net

There are many ways to push files to sf.net (SFTP, SCP, SSH...). Any alternative that puts the files under +JBossTools/jbosstools${version}+ is fine. Here, we'll show a shell-based approach that allows to save a few minutes.

First, connect to sf.net. Replace user by your sf.net id:

[source,bash]
----
ssh -t user,jboss@shell.sourceforge.net create
----

Once granted a shell, download the files. 

[source,bash]
----
branch=4.2.0.x # if this is a Final or build, use 4.1.x instead of 4.2.x
version=4.2.0.Beta2
cd /home/frs/project/jboss/JBossTools/
mkdir -p jbosstools${branch}
cd jbosstools${branch}
wget http://download.jboss.org/jbosstools/builds/development/sf.net/${version} -k -O /tmp/index.html
for f in $(cat /tmp/index.html | egrep -v "C=D|title>|h1>" | grep "${version}" | sed 's#.\+href="\([^"]\+\)".\+#\1#g'); do
  wget -nc $f
done
rm -f /tmp/index.html
exit
----
  
=== Release notes

Go to https://issues.jboss.org/secure/ConfigureReport!default.jspa?selectedProjectId=10020&projectOrFilterId=project-10020&projectOrFilterName=Tools%20%28JBoss%20Tools%29&reportKey=org.jboss.labs.jira.plugin.release-notes-report-plugin:releasenotes . Then select the target release (4.2.0.Beta2 for example), type of issues = "All", style = "HTML". Keep the URL of the report page (which looks like https://issues.jboss.org/secure/ConfigureReport.jspa?versions=12323827&sections=all&style=html&selectedProjectId=10020&reportKey=org.jboss.labs.jira.plugin.release-notes-report-plugin%3Areleasenotes&Next=Next )

Then, still on sf.net, create a file +/home/fts/project/jboss/JBossTools/jbosstools${branch}/zz_Release_Notes_${version}.readme.html+. Edit this file as following

[source,html]
----
<html>
  <head>
    <meta http-equiv="refresh" content="0, url=PUT_URL_HERE"/>
  </head>
</html>
----

=== bookmarks.xml

Bookmarks.xml keeps links from sf.net to the actual JBoss Tools update sites.
Still on sf.net, verify the following file (adapt it to the version you're pushing: +/home/frs/project/jboss/JBossTools/jbosstools4.2_bookmarks.xml+. In case you're starting a new stream, you probably need to update those files (for example rename from kepler to Luna).

== Move sites

These steps happens on filemgmt.jboss.org, in the jbosstools download area.

=== If publishing a respin, remove respin suffix from sites

The goal of this task is to make latest respin is available in the 'updates/staging/${version}' location, without respin attribute.

Via sftp, remove older respins and rename the latest respin to remove its respin (a, b) suffix. 
The principle is to keep only the latest respin and make it the actual release.

Example: assuming you are publishing the 2nd respin of 4.2.0.Beta2, then its folders will be called 4.2.0.Beta2.

[source,bash]
----
  version=4.2.0.Beta2
  versionWithRespin=4.2.0.Beta2 # a, b, c, d...

  # rename discovery site, http://download.jboss.org/jbosstools/discovery/development/${versionWithRespin}/
  echo "rename development/${version}  development/${version}.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery
  echo "rename development/${versionWithRespin} development/${version}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery

  # rename the development build
  echo "rename development/jbosstools-${version}-build-core  development/jbosstools-${version}-build-core.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  echo "rename development/jbosstools-${versionWithRespin}-build-core development/jbosstools-${version}-build-core" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename development/jbosstools-${version}-build-coretests  development/jbosstools-${version}-build-coretests.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  echo "rename development/jbosstools-${versionWithRespin}-build-coretests development/jbosstools-${version}-build-coretests" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename development/jbosstools-${version}-build-webtools  development/jbosstools-${version}-build-webtools.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  echo "rename development/${versionWithRespin}.webtools development/jbosstools-${version}-build-webtools" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename development/jbosstools-${version}-build-hibernatetools  development/jbosstools-${version}-build-hibernatetools.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  echo "rename development/jbosstools-${versionWithRespin}-build-hibernatetools development/jbosstools-${version}-build-hibernatetools" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

  # rename the update site
  echo "rename jbosstools-${version}-updatesite-core  jbosstools-${version}-updatesite-core.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging
  echo "rename staging/jbosstools-${versionWithRespin}-updatesite-core jbosstools-${version}-updatesite-core" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename jbosstools-${version}-updatesite-coretests  jbosstools-${version}-updatesite-coretests.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging
  echo "rename staging/jbosstools-${versionWithRespin}-updatesite-coretests jbosstools-${version}-updatesite-coretests" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename jbosstools-${version}-updatesite-webtools  jbosstools-${version}-updatesite-webtools.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging
  echo "rename staging/jbosstools-${versionWithRespin}.webtools jbosstools-${version}-updatesite-webtools" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename jbosstools-${version}-updatesite-hibernatetools  jbosstools-${version}-updatesite-hibernatetools.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging
  echo "rename staging/jbosstools-${versionWithRespin}-updatesite-hibernatetools jbosstools-${version}-updatesite-hibernatetools" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates
----

If everything above completed OK, you can then in the backgroun delete all the *.DELETEME folders while you continue with the next steps.

A graphical sftp client such as FileZilla or FireFTP (plugin for Firefox) seems to be the easiest way to perform these operations. Looks in the following locations:

* /downloads_htdocs/tools/discovery/development/
* /downloads_htdocs/tools/builds/development/
* /downloads_htdocs/tools/updates/staging/
* /downloads_htdocs/tools/static/releases/

=== Promote sites to from staging to Akamai

To improve download performance, Akamai is enabled in the 'static' folder. Akamai is a STATIC location, which cannot be cleaned easily. So don't use it as a sandbox

Via SFTP on filemgmt.jboss.org:downloads_htdocs/tools/
[source,bash]
----
versionWithRespin=4.2.0.Beta2 # a, b, c, d...

rename updates/staging/jbosstools-${versionWithRespin}-updatesite-core static/releases/jbosstools-${version}-updatesite-core
rename updates/staging/jbosstools-${versionWithRespin}-updatesite-core static/releases/jbosstools-${version}-updatesite-coretests
rename updates/staging/jbosstools-${versionWithRespin}-updatesite-core static/releases/jbosstools-${version}-updatesite-hibernatetools
# Can't do it for webtools yet: https://bugs.eclipse.org/bugs/show_bug.cgi?id=434185
----
=== WebTools

==== Publish Site

Webtools site is expected to be found in +http://download.jboss.org/tools/updates/webtools/${eclipseTrain}+ (where eclipseTrain is for example "luna"). So, with a sftp client, on filemgmt.jboss.org

1. Rename +/downloads_htdocs/tools/updates/webtools/${eclipseTrain}+ into +/downloads_htdocs/tools/updates/webtools/${eclipseTrain}_${previousVersion}+, with ${previous} being the name of previous release (for example 4.2.0.Alpha1 when releasing 4.2.0.Beta2)
1. Move last build in +/downloads_htdocs/tools/updates/staging/jbosstools-${version}-updatesite-webtools+ to +/downloads_htdocs/tools/updates/webtools/${eclipseTrain}+

Here is an example of a script doing that:
[source,bash]
----
version=4.2.0.Alpha1
previous=4.2.0.Alpha

echo "rename webtools/kepler webtools/kepler_${previous}"         | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/
echo "rename jbosstools-${version}-updatesite-webtools webtools/kepler"      | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/
----

[TODO]
====
. When https://bugs.eclipse.org/bugs/show_bug.cgi?id=434185 has good fix
.. actually put webtools under 'static/releases/JBossTools-${version}.webtools
.. make 'updates/webtools' a composite repo referencing 'static/releases/JBossTools-${version}.webtools'
====

==== Notify webtools project

If this is the first milestone release (ie if you had to create the 'updates/webtools/${eclipseReleaseTrain}' directory (where ${eclipseReleaseTrain} can be for example 'kepler' or 'luna'), ensure that upstream project Web Tools (WTP) knows to include this new URL in their server adapter wizard. New bugzilla required!

== Update target-platforms

This is only necessary if this new milestone uses a new target-platform. In case there is no change in target-platform between this milestone/release and the previous one, you can ignore those steps.

=== "Normal" targets

Those change happen by editing files on the +jbosstools-download.jboss.org+ repository, and then synchronizing them with the actual content on download.jboss.org using this CI job: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/

So, assuming you are editing the jbosstools-download.jboss.org repository, here are the things to do:

* Replace *target-platform version* and update *p2.timestamp* in +jbosstools/targetplatforms/jbosstoolstarget/${eclipseTrain}/composite*.xml+ files to reference the release of Target-Platform that was used to build this release (It's the TARGET_PLATFORM_MAXIMUM defined in the parent pom)
* Same thing for +jbosstools/targetplatforms/jbdevstudiotarget/${eclipseTrain}/composite*.xml+

Here is a script doing that, from the +download.jboss.org+ folder.
[source,bash]
----
eclipseTrain=luna
now=`date +%s000`

oldTP=4.40.0.Alpha2
newTP=4.40.0.Beta2

pushd jbosstools/targetplatforms/
  for f in jbosstoolstarget/${eclipseTrain} jbdevstudiotarget/${eclipseTrain}; do
    pushd ${f};
      for d in composite*.xml; do
        sed -i -e "s#${oldTP}#${newTP}#g" $d
        sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
      done
    popd
  done
popd
----

When this is done

1. Commit your changes locally
2. Push your changes to the public repository
3. Run the CI job to sync with download.jboss.org https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/
4. Check the changes are available on download.jboss.org (read composite*.xml files)

=== Central Target-Platform

*If* target-platform is compatible with previous release consuming them, then update +jbosstools/targetplatforms/jbdevstudiotarget/${eclipseTrain}/composite*.xml+ to point to this target-platform. This can be done similarly as explained above:

[source,bash]
----
eclipseTrain=luna
now=`date +%s000`

oldTP=4.40.0.Beta2
newTP=4.40.0.Beta2a

pushd jbosstools/targetplatforms/
  for f in jbtcentraltarget/${eclipseTrain}; do
    pushd ${f};
      for d in composite*.xml; do
        sed -i -e "s#${oldTP}#${newTP}#g" $d
        sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
      done
    popd
  done
popd
----

*Else If* target-platform isn't compatible with previous release (for example introducing new incompatible feature - gwt.e42 -> gwt.e43), then don't change the composite, and instead, you'd should tweak the +updates/development/${eclipseTrain}/central/core/composite*.xml+ files to point at a specific TP version.

In any case:

* Commit changes
* Push changes to remote repository
* Synchronize with download.jboss.org by running https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/

=== Update composite, discovery and index.html

+composite*.xml+ and +*-directory.xml+ files allow to control the public URLs we give to users and allow to "select" what is the new release.
So we update them to make sure public URLs reference our latest stuff.


Changes also happen on the +jbosstools-download.jboss.org+ repository, which is synchronized with download.jboss.org using https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/ .

On this repository:

* Update +jbosstools/updates/development/${eclipseTrain}/composite*.xml+ to use newer version and timestamp
* Replace +jbosstools/updates/development/${eclipseTrain}/index.xml+ with the one you can fetch at +http://download.jboss.org/jbosstools/static/releases/jbosstools-${version}-updatesite-core/index.html+
* In the new +index.html+ replace relative paths by absolute paths. In order to do so, check for "href" occurrences

As usual, a script to do that:
[source,bash]
----
version=4.2.0.Beta2
eclipseTrain=luna
previous=4.2.0.Alpha2

now=`date +%s000`

pushd jbosstools/updates/development/${eclipseTrain}/
for d in composite*.xml; do
  sed -i -e "s#${previous}#${version}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done

rm -f index.html
wget -nc http://download.jboss.org/jbosstools/static/releases/jbosstools-${version}-updatesite-core/index.html
sed -i -e "s#href=\"#href=\"http://download.jboss.org/jbosstools/static/releases/jbosstools-${version}-updatesite-core/#g" -e "s#href=\"http://download.jboss.org/jbosstools/static/releases/jbosstools-${version}-updatesite-core/http#href=\"http#g" index.html
popd
----

Then make the necessary updates for *discovery*

* Replace +jbosstools/updates/development/${eclipseTrain}/jbosstools-directory.xml+ by +http://download.jboss.org/jbosstools/discovery/development/${version}/jbosstools-directory.xml+
* Remove previous discovery jar in +plugins+
* Fetch the jar listed in +jbosstools-directory.xml+ into the +http://download.jboss.org/jbosstools/discovery/development/${version}/plugins+ directory.
* Verify that plugin.xml in the discovery jar contains the right URL:
** If this is a *pre-final*, the plugin must point to *staging* URL, not release one. So URL should be +http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/central/core/+
** IF this is a *Final*, the plugin must reference the *release* URL, not the staging one. So URL should look like +http://download.jboss.org/jbosstools/updates/stable/kepler/central/core/+

Script:
[source,bash]
----
version=4.2.0.Beta2
eclipseTrain=luna

isFinal=false # or true in case you're doing a Final
# set correct path for where you have project cloned on disk
basedir=${HOME}/tru/jbosstools-download.jboss.org/ # or...
basedir=`pwd`

pushd ${basedir}/jbosstools/updates/development/${eclipseTrain}/
# Replace jbosstools-directory.xml by newest
rm -f jbosstools-directory.xml
wget -nc http://download.jboss.org/jbosstools/discovery/development/${version}/jbosstools-directory.xml
# Get newest discovery plugins

###########################################################################################
#TODO: FIX THIS - section is now broken (there are 2 new jars, not just 1)
#See link:JBDS8.0.0.Beta2_Staging_For_QE.adoc[JBDS8.0.0.Beta2_Staging_For_QE.adoc line 155]
###########################################################################################

newJar=$(cat jbosstools-directory.xml | grep entry | sed -e "s#.\+plugins/#plugins/#g" | sed -e "s#\.jar.\+#.jar#g")
echo $newJar
mkdir -p plugins
pushd plugins
wget http://download.jboss.org/jbosstools/discovery/development/${version}/${newJar}
popd
 
if [ "$isFinal" = true ]; then
  # IF THIS IS Final, ensure that your plugin points to the RELEASE URL, not the STAGING one:
  unzip -q -d ${basedir}/jbosstools/updates/development/${eclipseTrain}/${newJar}{_,}
  pushd ${basedir}/jbosstools/updates/development/${eclipseTrain}/${newJar}_
  sed -i "s#http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/central/core/#http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/central/core/#g" plugin.xml
  ## *** make sure we do not point at http://download.jboss.org/jbosstools/discovery/development/${version} instead
  zip -u ${basedir}/jbosstools/updates/development/${eclipseTrain}/${newJar} plugin.xml
  popd
  rm -fr ${basedir}/jbosstools/updates/development/${eclipseTrain}/${newJar}_
else
  # IF THIS IS pre-Final, ensure that your plugin points to the STAGING URL, not the RELEASE one:
  unzip -q -d ${basedir}/jbosstools/updates/development/${eclipseTrain}/${newJar}{_,}
  pushd ${basedir}//jbosstools/updates/development/${eclipseTrain}/${newJar}_ >/dev/null 
  sed -i "s#http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/central/core/#http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/central/core/#g" plugin.xml
  zip -u ${basedir}/jbosstools/updates/development/${eclipseTrain}/${newJar} plugin.xml
  popd >/dev/null
  rm -fr ${basedir}/jbosstools/updates/development/${eclipseTrain}/${newJar}_
fi

###########################################################################################
#TODO: FIX THIS - section is now broken (there are 2 new jars, not just 1)
#See link:JBDS8.0.0.Beta2_Staging_For_QE.adoc[JBDS8.0.0.Beta2_Staging_For_QE.adoc line 155]
###########################################################################################

----

When all changes are done:

* Commit them (should show 4 files changed, 1 jar deleted, 1 jar added)
* Push to remote repo
* Publish to download.jboss.org using the synchronization job https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/
* Check the following URL show the right versions and reference content under the 'static/releases' directory (not 'updates/${version}' nor 'updates/staging/*'
** For milestones
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/compositeArtifacts.xml
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/central/core/compositeArtifacts.xml
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/jbosstools-directory.xml
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/plugins/${newJar}
** Or, for Final builds
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/compositeArtifacts.xml
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/central/core/compositeArtifacts.xml
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/jbosstools-directory.xml
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/plugins/${newJar}

== Update jbosstools-website

Provide a PR to add the latest JBT milestone to this listing:

https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml

Example: https://github.com/jbosstools/jbosstools-website/pull/106

== Update Eclipse Marketplace (add/remove features)

WARNING: Alpha versions are not published to market place. So ignore this step for Alpha versions

=== If node doesn't exist yet

This is usually the case of first Beta version.

Create a new node on Marketplace, use content of +http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.Beta2.core/site.properties+

=== If node already exists

Access it via +https://marketplace.eclipse.org/content/jboss-tools-luna/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Update list of features, using content of +http://download.jboss.org/jbosstools/static/releases/jbosstools-4.2.0.Beta2.core/site.properties+

== Git tags

=== Create tags for build-related repositories

Tag the following repositories:

* https://github.com/jbosstools/jbosstools-build
* https://github.com/jbosstools/jbosstools-build-ci
* https://github.com/jbosstools/jbosstools-build-sites
* https://github.com/jbosstools/jbosstools-devdoc
* https://github.com/jbosstools/jbosstools-discovery
* https://github.com/jbosstools/jbosstools-download.jboss.org
* https://github.com/jbosstools/jbosstools-maven-plugins

Assuming you have the above proejcts already cloned, this script will create the tags if run from the location with your git clones:

[source,bash]
----
jbt_branch=jbosstools-4.2.0.Beta2x
version=4.2.0.Beta2
for d in build build-ci build-sites devdoc discovery download.jboss.org maven-plugins; do
  echo "====================================================================="
  echo "Tagging jbosstools-${d} from branch ${jbt_branch} as tag ${version}..."
  pushd jbosstools-${d}
  git stash
  git pull origin
  git fetch -t -p
  git checkout ${jbt_branch} && git tag -f jbosstools-${version} && git push origin jbosstools-${version}
  git checkout master; git stash pop
  echo ">>> https://github.com/jbosstools/jbosstools-${d}/tree/jbosstools-${version}"
  popd >/dev/null 
  echo "====================================================================="
  echo ""
done
----

=== Announce requirement of tag creation

Send email to team.

____
*To:* jbosstools-dev@lists.jboss.org + 

[source,bash]
----
branchName=jbosstools-4.2.0.Beta2x
tagName=jbosstools-4.2.0.Beta2
echo "
Subject:

ACTION REQUIRED: Project leads, please tag your projects [ branch ${branchName} -> tag ${tagName} ] 

Body:

Project leads, please tag your projects!

  co ${branchName}
  git tag ${tagName}
  git push origin ${tagName}

"
----
____

== Release the latest milestone to ide-config.properties

Check out this file:

http://download.jboss.org/jbosstools/configuration/ide-config.properties

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
jboss.discovery.directory.url|jbosstools|4.2.0.Beta2=http://download.jboss.org/jbosstools/discovery/development/4.2.0.Beta2/jbosstools-directory.xml 
jboss.discovery.site.url|jbosstools|4.2.0.Beta2=http://download.jboss.org/jbosstools/discovery/development/4.2.0.Beta2/ 
----

== Notify the team (send 2 emails)

____
*To:* "jbosstools-dev@lists.jboss.org" <jbosstools-dev@lists.jboss.org> +
and +
*To:* "external-exadel-list@redhat.com" <external-exadel-list@redhat.com>, jboss-announce@redhat.com +

[source,bash]
----
version=4.2.0.Beta2
echo "
Subject: 

JBoss Tools ${version} is now available.

Body:

This is a development release aimed at Eclipse 4.4.M6 (Luna M6) users.


Eclipse Marketplace: https://marketplace.eclipse.org/content/jboss-tools-luna

Update Site: http://download.jboss.org/jbosstools/updates/development/luna/

Update Site Zips:
* http://sourceforge.net/projects/jboss/files/JBossTools/jbosstools4.2.0.x/
* http://download.jboss.org/jbosstools/builds/development/sf.net/${version}/

Installation instructions: http://tools.jboss.org/downloads/installation.html

New + Noteworthy (subject to change):
* http://htmlpreview.github.com/?https://raw.github.com/jbosstools/jbosstools-documentation/master/whatsnew/index.html
* http://docs.jboss.org/tools/whatsnew/

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel
"

----
____

