= Release JBoss Tools Development Milestone

[IMPORTANT]
====
JBIDE-13283, JBDS-2730 use Akamai publishing for update sites, target platforms & zips. +
Use:

  * http://download.jboss.org/jbosstools/static/releases/ instead of 
  * http://download.jboss.org/jbosstools/updates/ +
  and
  * http://download.jboss.org/jbosstools/static/targetplatforms/ instead of 
  * http://download.jboss.org/jbosstools/targetplatforms/
====

[CAUTION]
====
JBIDE-16871 For *Beta2* filename refactoring is coming, so all files/paths will be lowercase. +
Use:

  * jbostools instead of JBossTools
  * update instead of Update
  * etc.
====

This document describe how to publish a valid JBoss Tools build to production after being verified by QE.

WARNING: this requires write access to http://sourceforge.net/projects/jboss/files/JBossTools/

----
"gw1" uses special aliases/scripts/shortcuts. Basically, we want to follow correct github workflows so that commits are pushed to user's fork, then later pull-requested (and the PR applied)
"gw2" will create the PR, "gw3" will apply it, and "gw4" will delete the topic branch locally and in my fork
the 4 steps are captured here: https://gist.github.com/nickboldt/4111850
"stat" is short for "git status"; "gd" is short for "git diff"; "ga" is short for "git add"
----

== Zips on sf.net

Zips (recommanded for offline installation) are made available on sf.net. sf.net provides interesting metrics on download and other stuff.

=== Prepare files

On your local machine, using a SFTP client (or the script suggested above), move the files to publish to +http://download.jboss.org/jbosstools/builds/development/sf.net/+ and rename them to conform to pattern.

[source,bash]
----
stream=4.2.luna
version=4.2.0.Beta1 # name to use in filenames ie fixVersion in JIRA
echo "mkdir development/sf.net/${version}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

fullVersion=4.2.0.Beta1b # Fully qualified version, including respin suffix
coreBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/development/${version2}.core/ 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); buildID=${coreBuildID%%/*}
echo "Latest build: ${corebuildID}"
echo "rename development/${fullVersion}.core/${coreBuildID}/all/jbosstools-build-sites.aggregate.site_${stream}-Update-${coreBuildID}.zip      development/sf.net/${version}/jbosstools-Update-${version}_${coreBuildID}.zip"         | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename development/${fullVersion}.core/${coreBuildID}/all/jbosstools-build-sites.aggregate.site_${stream}-Update-${coreBuildID}.zip.MD5  development/sf.net/${version}/jbosstools-Update-${version}_${coreBuildID}.zip.MD5"     | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename development/${fullVersion}.core/${coreBuildID}/all/jbosstools-build-sites.aggregate.site_${stream}-Sources-${coreBuildID}.zip     development/sf.net/${version}/jbosstools-Sources-${version}_${coreBuildID}.zip"        | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename development/${fullVersion}.core/${coreBuildID}/all/jbosstools-build-sites.aggregate.site_${stream}-Sources-${coreBuildID}.zip.MD5 development/sf.net/${version}/jbosstools-Sources-${version}_${coreBuildID}.zip.MD5"    | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

hibernateToolsFullVersion=4.2.0.Beta1 #it is highly possible that hibernate tools didn't require a respin and hence have another fully qualified version
hibernateToolsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/development/${hibernateToolsFullVersion}.hibernatetools/ 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); hibernateToolsBuildID=${hibernateToolsBuildID%%/*}
echo "Latest build: ${hibernateToolsBuildID}"
echo "rename development/${hibernateToolsFullVersion}.hibernatetools/${hibernateToolsBuildID}/all/jbosstools-build-sites.aggregate.hibernatetools-site_${stream}-Update-${hibernateToolsBuildID}.zip development/sf.net/${version}/hibernatetools-Update-${version}_${hibernateToolsBuildID}.zip" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename development/${hibernateToolsFullVersion}.hibernatetools/${hibernateToolsBuildID}/all/jbosstools-build-sites.aggregate.hibernatetools-site_${stream}-Update-${hibernateToolsBuildID}.zip.MD5 development/sf.net/${version}/hibernatetools-Update-${version}_${hibernateToolsBuildID}.zip.MD5" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
----

=== Pull files to sf.net

There are many ways to push files to sf.net (SFTP, SCP, SSH...). Any alternative that puts the files under +JBossTools/JBossTools${version}+ is fine. Here, we'll show a shell-based approach that allows to save a few minutes.

First, connect to sf.net. Replace user by your sf.net id:

[source,bash]
----
ssh -t user,jboss@shell.sourceforge.net create
----

Once granted a shell, download the files. 

[source,bash]
----
branch=4.2.0.x # if this is a Final or build, use 4.1.x instead of 4.2.x
version=4.2.0.Beta1
cd /home/frs/project/jboss/JBossTools/
mkdir -p JBossTools${branch}
cd JBossTools${branch}
wget http://download.jboss.org/jbosstools/builds/development/sf.net/${version} -k -O /tmp/index.html
for f in $(cat /tmp/index.html | egrep -v "C=D|title>|h1>" | grep "${version}" | sed 's#.\+href="\([^"]\+\)".\+#\1#g'); do
  wget -nc $f
done
rm -f /tmp/index.html
exit
----
  
=== Release notes

Go to https://issues.jboss.org/secure/ConfigureReport!default.jspa?selectedProjectId=10020&projectOrFilterId=project-10020&projectOrFilterName=Tools%20%28JBoss%20Tools%29&reportKey=org.jboss.labs.jira.plugin.release-notes-report-plugin:releasenotes . Then select the target release (4.2.0.Beta1 for example), type of issues = "All", style = "HTML". Keep the URL of the report page (which looks like https://issues.jboss.org/secure/ConfigureReport.jspa?versions=12323827&sections=all&style=html&selectedProjectId=10020&reportKey=org.jboss.labs.jira.plugin.release-notes-report-plugin%3Areleasenotes&Next=Next )

Then, still on sf.net, create a file +/home/fts/project/jboss/JBossTools/JBossTools${branch}/zz_Release_Notes_${version}.readme.html+. Edit this file as following

[source,html]
----
<html>
  <head>
    <meta http-equiv="refresh" content="0, url=PUT_URL_HERE"/>
  </head>
</html>
----

=== bookmarks.xml

Bookmarks.xml keeps links from sf.net to the actual JBoss Tools update sites.
Still on sf.net, verify the following file (adapt it to the version you're pushing: +/home/frs/project/jboss/JBossTools/jbosstools4.2_bookmarks.xml+. In case you're starting a new stream, you probably need to update those files (for example rename from kepler to Luna).

== Move sites

These steps happens on filemgmt.jboss.org, in the jbosstools download area.

=== (If publishing a respin) Remove respin suffix from sites

Via sftp, remove older respins and rename the latest respin to remove its respin (a, b) suffix. 
The principle is to keep only the latest respin and make it the actual release.

Example: assuming you are publishing the 2nd respin of 4.2.0.Beta1, then its folders will be called 4.2.0.Beta1b.

[source,bash]
----
  version=4.2.0.Beta1
  version2=4.2.0.Beta1b # a, b, c, d...

  # rename discovery site, http://download.jboss.org/jbosstools/discovery/development/${version2}/
  echo "rename development/${version}  development/${version}.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery
  echo "rename development/${version2} development/${version}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery

  # rename the development build
  echo "rename development/${version}.core  development/${version}.core.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  echo "rename development/${version2}.core development/${version}.core" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename development/${version}.coretests  development/${version}.coretests.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  echo "rename development/${version2}.coretests development/${version}.coretests" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename development/${version}.webtools  development/${version}.webtools.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  echo "rename development/${version2}.webtools development/${version}.webtools" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename development/${version}.hibernatetools  development/${version}.hibernatetools.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  echo "rename development/${version2}.hibernatetools development/${version}.hibernatetools" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

  # rename the update site
  echo "rename JBossTools-${version}.core  JBossTools-${version}.core.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging
  echo "rename staging/JBossTools-${version2}.core JBossTools-${version}.core" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename JBossTools-${version}.coretests  JBossTools-${version}.coretests.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging
  echo "rename staging/JBossTools-${version2}.coretests JBossTools-${version}.coretests" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename JBossTools-${version}.webtools  JBossTools-${version}.webtools.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging
  echo "rename staging/JBossTools-${version2}.webtools JBossTools-${version}.webtools" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates

  # TODO: make sure this exists - might be only "a" while core is on "c"
  echo "rename JBossTools-${version}.hibernatetools  JBossTools-${version}.hibernatetools.DELETEME" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging
  echo "rename staging/JBossTools-${version2}.hibernatetools JBossTools-${version}.hibernatetools" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates
----

If everything above completed OK, you can then in the backgroun delete all the *.DELETEME folders while you continue with the next steps.

A graphical sftp client such as FileZilla or FireFTP (plugin for Firefox) seems to be the easiest way to perform these operations. Looks in the following locations:

* /downloads_htdocs/tools/discovery/development/
* /downloads_htdocs/tools/builds/development/
* /downloads_htdocs/tools/updates/staging/

=== WebTools

==== Publish Site

Webtools site is expected to be found in +http://download.jboss.org/tools/updates/webtools/${eclipseTrain}+ (where eclipseTrain is for example "luna"). So, with a sftp client, on filemgmt.jboss.org

[IMPORTANT]
====
Use staging for QE builds:

  * http://download.jboss.org/jbosstools/updates/staging/<buildName> instead of 
  * http://download.jboss.org/jbosstools/updates/<buildName>
====

1. Rename +/downloads_htdocs/tools/updates/webtools/${eclipseTrain}+ into +/downloads_htdocs/tools/updates/webtools/${eclipseTrain}_${previousVersion}+, with ${previous} being the name of previous release (for example 4.2.0.Alpha1 when releasing 4.2.0.Beta1)
1. Move last build in +/downloads_htdocs/tools/updates/JBossTools-${version}.webtools+ to +/downloads_htdocs/tools/updates/webtools/${eclipseTrain}+

Here is an example of a script doing that:
[source,bash]
----
version=4.2.0.Alpha1
previous=4.2.0.Alpha

echo "rename webtools/kepler webtools/kepler_${previous}"         | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/
echo "rename JBossTools-${version}.webtools webtools/kepler"      | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/
----

==== Notify webtools project

If this is the first milestone release, ensure that upstream project Web Tools (WTP) knows to include this new URL in their server adapter wizard. New bugzilla required!

=== Update target-platforms

This is only necessary if this new milestone uses a new target-platform. In case there is no change in target-platform between this milestone/release and the previous one, you can ignore those steps.

==== "Normal" targets

Those change happen by editing files on the +jbosstools-download.jboss.org+ repository, and then synchronizing them with the actual content on download.jboss.org using this CI job: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/

So, assuming you are editing the jbosstools-download.jboss.org repository, here are the things to do:

* Replace *target-platform version* and update *p2.timestamp* in +jbosstools/targetplatforms/jbosstoolstarget/${eclipseTrain}/composite*.xml+ files to reference the release of Target-Platform that was used to build this release (It's the TARGET_PLATFORM_MAXIMUM defined in the parent pom)
* Same thing for +jbosstools/targetplatforms/jbdevstudiotarget/${eclipseTrain}/composite*.xml+

Here is a script doing that, from the +download.jboss.org+ folder.
[source,bash]
----
version=4.2.0.Beta1
newTP=4.40.0.Beta1
eclipseTrain=luna

oldTP=4.40.0.Alpha1

now=`date +%s000`

pushd jbosstools/targetplatforms/jbosstoolstarget/${eclipseTrain}
for d in composite*.xml; do
  sed -i -e "s#${oldTP}#${newTP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done
popd

pushd jbosstools/targetplatforms/jbdevstudiotarget/${eclipseTrain}/
for d in composite*.xml; do
  sed -i -e "s#${oldTP}#${newTP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done
----

When this is done

1. Commit your changes locally
2. Push your changes to the public repository
3. Run the CI job to sync with download.jboss.org https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/
4. Check the changes are available on download.jboss.org (read composite*.xml files)

==== Central Target-Platform

*If* target-platform is compatible with previous release consuming them, then update +jbosstools/targetplatforms/jbdevstudiotarget/${eclipseTrain}/composite*.xml+ to point to this target-platform. This can be done similarly as explained above:

[source,bash]
----
pushd jbosstools/targetplatforms/jbtcentraltarget/${eclipseTrain}/
for d in composite*.xml; do
  sed -i -e "s#${OLD_CENTRAL_TP}#${NEW_CENTRAL_TP}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done
popd
----

*Else If* target-platform isn't compatible with previous release (for example introducing new incompatible feature - gwt.e42 -> gwt.e43), then don't change the composite, and instead, you'd should tweak the +updates/development/${eclipseTrain}/central/core/composite*.xml+ files to point at a specific TP version.

In any case:

* Commit changes
* Push changes to remote repository
* Synchronize with download.jboss.org by running https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/

=== Update composite, discovery and index.html

Changes also happen on the +jbosstools-download.jboss.org+ repository, which is synchronized with download.jboss.org using https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/ .

[IMPORTANT]
====
Use staging for QE builds:

  * http://download.jboss.org/jbosstools/updates/staging/<buildName> instead of 
  * http://download.jboss.org/jbosstools/updates/<buildName>
====

On this repository:

* Update +jbosstools/updates/development/${eclipseTrain}/composite*.xml+ to use newer version and timestamp
* Replace +jbosstools/updates/development/${eclipseTrain}/index.xml+ with the one you can fetch at +http://download.jboss.org/jbosstools/updates/JBossTools-${version}.core/index.html+
* In the new +index.html+ replace relative paths by absolute paths. In order to do so, check for "href" occurrences

As usual, a script to do that:
[source,bash]
----
version=4.2.0.Beta1
eclipseTrain=luna
previousVersion=4.2.0.Alpha1

now=`date +%s000`

pushd jbosstools/updates/development/${eclipseTrain}/
for d in composite*.xml; do
  sed -i -e "s#${previous}#${version}#g" $d
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
done

rm -f index.html
wget -nc http://download.jboss.org/jbosstools/updates/JBossTools-${version}.core/index.html
sed -i -e "s#href=\"#href=\"http://download.jboss.org/jbosstools/updates/JBossTools-${version}.core/#g" -e "s#href=\"http://download.jboss.org/jbosstools/updates/JBossTools-${version}.core/http#href=\"http#g" index.html
popd
----

Then make the necessary updates for *discovery*

* Replace +jbosstools/updates/development/${eclipseTrain}/jbosstools-directory.xml+ by +http://download.jboss.org/jbosstools/discovery/development/${version}/jbosstools-directory.xml+
* Remove previous discovery jar in +plugins+
* Fetch the jar listed in +jbosstools-directory.xml+ into the +http://download.jboss.org/jbosstools/discovery/development/${version}/plugins+ directory.
* Verify that plugin.xml in the discovery jar contains the right URL:
** If this is a *pre-final*, the plugin must point to *staging* URL, not release one. So URL should be +http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/central/core/+
** IF this is a *Final*, the plugin must reference the *release* URL, not the staging one. So URL should look like +http://download.jboss.org/jbosstools/updates/stable/kepler/central/core/+

Script:
[source,bash]
----
version=4.2.0.Beta1
eclipseTrain=luna
pushd jbosstools/updates/development/${eclipseTrain}/
# Replace jbosstools-directory.xml by newest
rm -f jbosstools-directory.xml
wget -nc http://download.jboss.org/jbosstools/discovery/development/${version}/jbosstools-directory.xml
# Get newest discovery plugins
newJar=$(cat jbosstools-directory.xml | grep entry | sed -e "s#.\+plugins/#plugins/#g" | sed -e "s#\.jar.\+#.jar#g")
echo $newJar
mkdir -p plugins
pushd plugins
wget http://download.jboss.org/jbosstools/discovery/development/${version}/${newJar}
popd
 
# IF THIS IS pre-Final, ensure that your plugin points to the STAGING URL, not the RELEASE one:
#unzip -q -d ~/tru/download.jboss.org/jbosstools/updates/development/kepler/${newJar}{_,}
#pushd ~/tru/download.jboss.org/jbosstools/updates/development/kepler/${newJar}_ >/dev/null 
#sed -i "s#http://download.jboss.org/jbosstools/updates/stable/kepler/central/core/#http://download.jboss.org/jbosstools/updates/development/kepler/central/core/#g" plugin.xml
#zip -u ~/tru/download.jboss.org/jbosstools/updates/development/kepler/${newJar} plugin.xml
#popd >/dev/null
#rm -fr ~/tru/download.jboss.org/jbosstools/updates/development/kepler/${newJar}_

# IF THIS IS Final, ensure that your plugin points to the RELEASE URL, not the STAGING one:
unzip -q -d jbosstools/updates/development/kepler/${newJar}{_,}
pushd jbosstools/updates/development/kepler/${newJar}_
sed -i "s#http://download.jboss.org/jbosstools/updates/development/kepler/central/core/#http://download.jboss.org/jbosstools/updates/stable/kepler/central/core/#g" plugin.xml
## *** make sure we do not point at http://download.jboss.org/jbosstools/discovery/development/${version} instead
zip -u jbosstools/updates/development/kepler/${newJar} plugin.xml
popd
rm -fr jbosstools/updates/development/kepler/${newJar}_
----

When all changes are done:

[IMPORTANT]
====
JBIDE-13283 use Akamai publishing for update sites, target platforms & zips. +
Use:

  * http://download.jboss.org/jbosstools/static/releases/ instead of 
  * http://download.jboss.org/jbosstools/updates/ +
  and
  * http://download.jboss.org/jbosstools/static/targetplatforms/ instead of 
  * http://download.jboss.org/jbosstools/targetplatforms/
====

* Commit them (should show 4 files changed, 1 jar deleted, 1 jar added)
* Push to remote repo
* Publish to download.jboss.org using the synchronization job https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstools-download.jboss.org-rsync-from-git/
* Check the following URL show the right versions
** For milestones
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/compositeArtifacts.xml
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/central/core/compositeArtifacts.xml
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/jbosstools-directory.xml
*** http://download.jboss.org/jbosstools/updates/development/${eclipseTrain}/plugins/${newJar}
** Or, for Final builds
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/compositeArtifacts.xml
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/central/core/compositeArtifacts.xml
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/jbosstools-directory.xml
*** http://download.jboss.org/jbosstools/updates/stable/${eclipseTrain}/plugins/${newJar}

== Magnolia

Magnolia is the place where we can edit the content of the +http://jboss.org/tools+ site. You can log into it using user *tools*.

WARNING: you need a password to get there. In case you don't have it, ask it to Nick, Mickael or Max

Go to the following URLs and update the link to "latest development build".

* https://www.jboss.org/author/tools/download
* https://www.jboss.org/author/tools/download/dev
* https://www.jboss.org/author/tools/download/stable
* https://www.jboss.org/author/tools/download/installation/update_4_2

When publishing a new Development Milestone, simply replace all references to previous one.

When you're done, publish those pages: go to https://www.jboss.org/author/ and publish

== Update Eclipse Marketplace (add/remove features)

WARNING: Alpha versions are not published to market place. So ignore this step for Alpha versions

=== If node doesn't exist yet

This is usually the case of first Beta version.

Create a new node on Marketplace, use content of +http://download.jboss.org/jbosstools/updates/JBossTools-<version>.core/site.properties+

=== If node already exists

Access it via +https://marketplace.eclipse.org/node/xxxxxx/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Update list of features, using content of +http://download.jboss.org/jbosstools/updates/JBossTools-<version>.core/site.properties+

== Git tags

=== Create tags for build-related repositories

Similarly to what's explained about, tag the following repositories:

* https://github.com/jbosstools/jbosstools-build
* https://github.com/jbosstools/jbosstools-build-ci
* https://github.com/jbosstools/jbosstools-build-sites
* https://github.com/jbosstools/jbosstools-devdoc
* https://github.com/jbosstools/jbosstools-discovery
* https://github.com/jbosstools/jbosstools-download.jboss.org
* https://github.com/jbosstools/jbosstools-maven-plugins

Here is a magic script for that, which runs from the location containing your git repositories:

[source,bash]
----
jbt_branch=jbosstools-4.2.0.Beta1x
version=4.2.0.Beta1
for d in build build-ci build-sites devdoc discovery download.jboss.org maven-plugins; do
  echo "====================================================================="
  echo "Tagging jbosstools-${d} from branch ${jbt_branch} as tag ${version}..."
  pushd jbosstools-${d}
  git stash
  git pull origin
  git fetch -t -p
  git checkout ${jbt_branch} && git tag -f jbosstools-${version} && git push origin jbosstools-${version}
  git checkout master; git stash pop
  echo ">>> https://github.com/jbosstools/jbosstools-${d}/tree/jbosstools-${version}"
  popd >/dev/null 
  echo "====================================================================="
  echo ""
done
----

=== Announce requirement of tag creation

Send email to team.

____
*To:* jbosstools-dev@lists.jboss.org + 

[source,bash]
----
version1=jbosstools-4.2.0.Beta1x
version2=jbosstools-4.2.0.Beta1
echo "
Subject:

ACTION REQUIRED: Project leads, please tag your projects [ branch ${version1} -> tag ${version2} ] 

Body:

Project leads, please tag your projects!

  co ${version1}
  git tag ${version2}
  git push origin ${version2}

"
----
____

== Announce availability of new release.

Send email to team.

____
*To:* "jbosstools-dev@lists.jboss.org" <jbosstools-dev@lists.jboss.org> +
and +
*To:* jbds-pm-list <jbds-pm-list@redhat.com>, "external-exadel-list@redhat.com" <external-exadel-list@redhat.com>, jboss-announce@redhat.com +

[source,bash]
----
version=jbosstools-4.2.0.Beta1
echo "
Subject: 

JBoss Tools ${version} is now available.

Body:

This is a development release aimed at Eclipse 4.4.M6 (Luna M6) users.

Eclipse Marketplace: 

https://marketplace.eclipse.org/content/jboss-tools-luna

Update Site: 

http://download.jboss.org/jbosstools/updates/development/luna/

Installation + Download Pages:

* http://www.jboss.org/tools/download
* http://www.jboss.org/tools/download/dev/4_2_x
* http://www.jboss.org/tools/download/installation/update_4_2

JBoss Central: 

This release includes changes to JBoss Central. To see these updates, launch Eclipse with this extra -vmarg in your eclipse.ini:

* -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/updates/development/luna/jbosstools-directory.xml


New + Noteworthy:

Subject to change, the latest N&N is here:

* http://htmlpreview.github.com/?https://raw.github.com/jbosstools/jbosstools-documentation/master/whatsnew/index.html
* http://docs.jboss.org/tools/whatsnew/

Schedule / Upcoming Releases:

* https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel
----
____
