= Publishing JBT update sites for QE

[IMPORTANT]
====
JBIDE-13283, JBDS-2730 use Akamai publishing for update sites, target platforms & zips. +
Use:

  * http://download.jboss.org/jbosstools/static/releases/ instead of 
  * http://download.jboss.org/jbosstools/updates/ +
  and
  * http://download.jboss.org/jbosstools/static/targetplatforms/ instead of 
  * http://download.jboss.org/jbosstools/targetplatforms/
====

[CAUTION]
====
JBIDE-16871 For *Beta2* filename refactoring is coming, so all files/paths will be lowercase. +
Use:

  * jbostools instead of JBossTools
  * update instead of Update
  * etc.
====

This document describe how to provide a valid JBoss Tools build to QE so they can test us.

[NOTE]
====
Note that +sftp://tools@filemgmt.jboss.org/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+ +

If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools

A Jenkins job can then be triggered to sync changes to download.jboss.org: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-download.jboss.org-rsync-from-svn/
====

== Update Discovery URLs

[[update-discovery-urls]]
Update the *stable branch* discovery job [1] to publish to the right URL, according to JBT and JBDS versions +

* Update property +JBT_UPDATE_SITE+ to http://download.jboss.org/jbosstools/updates/staging/JBossTools-4.2.0.Beta1.core/
* Update property +JBDS_UPDATE_SITE+ to http://www.qa.jboss.com/binaries/RHDS/updates/development/8.0.0.Beta1.core/

Then respin the job and verify that sites were correctly populated:

* http://download.jboss.org/jbosstools/discovery/nightly/core/4.2.luna/
* http://www.qa.jboss.com/binaries/RHDS/discovery/nightly/core/4.2.luna/

[1] https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_8.0.luna/job/jbosstools-discovery_4.2.luna/configure


== Stage to download.jboss.org

=== Promote builds from "nightly" to "development"

*Development* where we store builds for staging. This contains build metadata. The URL for development sites pattern is +http://download.jboss.org/jbosstools/development/<version>.<siteName>/<buildId>::
. *Core* site (which contains JBoss Tools): Move the most recent build available from +http://downloads.jboss.org/tools/build/nightly/core/4.2.luna+ to +http://downloads.jboss.org/tools/development/4.2.0.Beta1.core/+
. *Core Tests* site (which contains JBoss Tools tests): Move the most recent build available from +http://downloads.jboss.org/tools/build/nightly/coretests/4.2.luna+ to +http://downloads.jboss.org/tools/development/4.2.0.Beta1.coretests/+
. *WebTools* site (which contains only WTP connectors for AS/WildFly/EAP): Move the most recent build available from +http://downloads.jboss.org/tools/build/nightly/webtools/4.2.luna+ to +http://downloads.jboss.org/tools/development/4.2.0.Beta1.webtools/+ 

Here is a script that does this:
[source,bash]
----
stream=4.2.luna
version=4.2.0.Beta1b # a, b, c...

site=core
# Retrieve latest build and remove trailing slash
coreBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1) 
coreBuildID=${coreBuildID%%/*}
echo "Latest build for ${site}: ${coreBuildID}"
# Create target directory and populate it
echo "mkdir development/${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${coreBuildID} development/${version}.${site}/${coreBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

site=coretests
# Repeat operation
coretestsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1)
coretestsBuildID=${coretestsBuildID%%/*}
echo "Latest build for ${site}: ${coretestsBuildID}"
echo "mkdir development/${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${coretestsBuildID} development/${version}.${site}/${coretestsBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  
site=hibernatetools
hibernatetoolsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1)
hibernatetoolsBuildID=${hibernatetoolsBuildID%%/*}
echo "Latest build for ${site}: ${hibernatetoolsBuildID}"
echo "mkdir development/${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${hibernatetoolsBuildID} development/${version}.${site}/${hibernatetoolsBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  
site=webtools
webtoolsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1)
webtoolsBuildID=${webtoolsBuildID%%/*}
echo "Latest build for ${site}: ${webtoolsBuildID}"
echo "mkdir development/${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${webtoolsBuildID} development/${version}.${site}/${webtoolsBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  
echo " >> http://download.jboss.org/jbosstools/builds/development/${version}.core/${coreBuildID}" | egrep ">>|${version}"
echo " >> http://download.jboss.org/jbosstools/builds/development/${version}.coretests/${coretestsBuildID}" | egrep ">>|${version}"
echo " >> http://download.jboss.org/jbosstools/builds/development/${version}.hibernatetools/${hibernatetoolsBuildID}" | egrep ">>|${version}"
echo " >> http://download.jboss.org/jbosstools/builds/development/${version}.webtools/${webtoolsBuildID}" | egrep ">>|${version}"
----

Then verify sites are correctly populated with build metadata. To do so, you can simply make sure that under each one of these build sites, you find a file /logs/GIT_REVISION.txt.

=== Stage update sites

p2 repositories are expected to be under the +http://download.jboss.org/jbosstools/updates+ directory. Similarly to the build sites, we move them there.

[source,bash]
----
stream=4.2.luna
version=4.2.0.Beta1b  # a, b, c...

site=core
echo "rename nightly/${site}/${stream} staging/JBossTools-${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates  
echo " >> http://download.jboss.org/jbosstools/updates/staging/JBossTools-${version}.${site}/" | egrep ">>|${version}"

site=coretests
echo "rename nightly/${site}/${stream} staging/JBossTools-${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates  
echo " >> http://download.jboss.org/jbosstools/updates/staging/JBossTools-${version}.${site}/" | egrep ">>|${version}"

site=hibernatetools
echo "rename nightly/${site}/${stream} staging/JBossTools-${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates
echo " >> http://download.jboss.org/jbosstools/updates/staging/JBossTools-${version}.${site}/" | egrep ">>|${version}"

site=webtools
echo "rename nightly/${site}/${stream} staging/JBossTools-${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates
echo " >> http://download.jboss.org/jbosstools/updates/staging/JBossTools-${version}.${site}/" | egrep ">>|${version}"
----

Then verify those 4 sites are correctly populated.

=== Stage discovery site 

WARNING: Make sure you performed the step <<update-discovery-urls,Update Discovery URLs>> above.

[source,bash]
----
stream=4.2.luna
version=4.2.0.Beta1b # a, b, c...

echo "rename nightly/core/${stream} development/${version}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/
echo " >> http://download.jboss.org/jbosstools/discovery/development/${version}/" | egrep ">>|${version}"
----

Then verify the site is correctly populated.

=== Preserve a copy of the nightly sites after the move

NOTE:
This step is mandatory only because we dont have a good way to copy stuff remotely (sftp only allows rename). If we could be granted something more powerful with remote copies, we could copy stuff in previous steps instead of moving it, and this step would becomme useless.

First, run it as +hudson+ user from a ci machine
----
local$ ssh dev01.mw.lab.eng.bos.redhat.com
dev01$ sudo su - hudson
dev01$ # set up command prompt and load aliases
dev01$ . /home/hudson/config_repository/scripts/jbds/prompt.sh 
----
 
  # if you didn't run prompt.sh above, you'll need this
  alias   scpr=rsync -aPrz --rsh=ssh --protocol=28

  # can run 5 steps these in parallel 

  version=4.2.0.Beta1b # a, b, c...
  branch=core/4.2.luna
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging/JBossTools-${version}.core/* /tmp/JBossTools-${version}.core/
  scpr /tmp/JBossTools-${version}.core/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.core/
  echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

  version=4.2.0.Beta1b # a, b, c...
  branch=coretests/4.2.luna
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging/JBossTools-${version}.coretests/* /tmp/JBossTools-${version}.coretests/
  scpr /tmp/JBossTools-${version}.coretests/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.coretests/
  echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

  version=4.2.0.Beta1b # a, b, c...
  branch=hibernatetools/4.2.luna
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging/JBossTools-${version}.hibernatetools/* /tmp/JBossTools-${version}.hibernatetools/
  scpr /tmp/JBossTools-${version}.hibernatetools/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.hibernatetools/
  echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

  version=4.2.0.Beta1b # a, b, c...
  branch=webtools/4.2.luna
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/staging/JBossTools-${version}.webtools/* /tmp/JBossTools-${version}.webtools/
  scpr /tmp/JBossTools-${version}.webtools/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.webtools/
  echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

  # now, discovery site
  version=4.2.0.Beta1b # a, b, c...
  branch=core/4.2.luna
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/development/${version}/* /tmp/JBossTools-${version}.discovery/
  scpr /tmp/JBossTools-${version}.discovery/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.discovery/
  echo " >> http://download.jboss.org/jbosstools/discovery/nightly/${branch}/" | egrep ">>|${branch}"


== Notify the team (send 2 emails)

____
*To* jbosstools-dev@lists.jboss.org +
*To* jbds-pm-list@redhat.com, external-exadel-list@redhat.com 

[source,bash]
----
version=4.2.0.Beta1b # a, b, c...
respin="respin-b"
TARGET_PLATFORM_VERSION_MIN=4.40.0.Beta1
TARGET_PLATFORM_VERSION_MAX=4.40.0.Beta1
TARGET_PLATFORM_CENTRAL_MAX=4.40.0.Beta2-SNAPSHOT
version2=8.0.0.Beta1 # no respin suffix here
version3=4.2.0.Beta1 # no respin suffix here
echo "
Subject: 

JBoss Tools Core ${version} bits available for QE testing

Body:

As always, these are not FINAL bits, but preliminary results for QE testing. Not for redistribution to customers. 

Update Sites:

* http://download.jboss.org/jbosstools/updates/staging/JBossTools-${version}.core/
* http://download.jboss.org/jbosstools/updates/staging/JBossTools-${version}.coretests/
* http://download.jboss.org/jbosstools/updates/staging/JBossTools-${version}.hibernatetools/
* http://download.jboss.org/jbosstools/updates/staging/JBossTools-${version}.webtools/

Builds:

* http://download.jboss.org/jbosstools/builds/development/${version}.core/${coreBuildID}
* http://download.jboss.org/jbosstools/builds/development/${version}.coretests/${coretestsBuildID}
* http://download.jboss.org/jbosstools/builds/development/${version}.hibernatetools/${hibernatetoolsBuildID}
* http://download.jboss.org/jbosstools/builds/development/${version}.webtools/${webtoolsBuildID}

JBoss Central:

* http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/${TARGET_PLATFORM_CENTRAL_MAX}/ (upcoming milestone)

To test the upcoming version of Central, add this to your eclipse.ini file after the -vmargs line:
 -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/development/${version}/jbosstools-directory.xml
 -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/discovery/development/${version}/

Target Platforms:

* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX} (upcoming milestone)

Until the above target platform site is released, you will need to add it to Eclipse to resolve dependencies at install time. 
Once released, dependencies will be found automatically from here:

* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/luna/ (latest release)

New + Noteworthy (subject to change): 

* http://htmlpreview.github.com/?https://raw.github.com/jbosstools/jbosstools-documentation/master/whatsnew/index.html
* http://docs.jboss.org/tools/whatsnew/

Schedule / Upcoming Releases: 

https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel
"
if [[ $respin != "respin-" ]]; then
echo " 

--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${version2}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${version3}%22%29%29%29
"
fi

----
____
