Publishing JBT update sites for QE
==================================

This document describe how to promote a valid build from a branch to QE so they can test us.

TIP:
Note that +sftp://tools@filemgmt.jboss.org/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+ +
If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools, a Jenkins job will be triggered to upload your change from Git repository to download.jboss.org (job is https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_All/job/jbosstools-download.jboss.org-rsync-from-svn/ )

Discovery URLs
--------------

Update the discovery job on *branch* ( https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_8.0.luna/job/jbosstools-discovery_4.2.luna/configure ) to publish to the right URL, according to JBT and JBDS versions::
* Update property +JBT_UPDATE_SITE+ to http://download.jboss.org/jbosstools/updates/JBossTools-4.2.0.Alpha2.core/
* Update property +JBDE_UPDATE_SITE+ to http://www.qa.jboss.com/binaries/RHDS/updates/development/8.0.0.Alpha2.core/

Then Respin jobs and verify that sites were correctly populated

Promote builds from "nightly" to "development"
----------------------------------------------

*Development* where we store builds for staging. This contains build metadata. The URL for development sites pattern is +http://download.jboss.org/jbosstools/development/<version>.<siteName>/<buildId>::
. *Core* site (which contains JBoss Tools): Move the most recent build available from +http://downloads.jboss.org/tools/build/nightly/core/4.2.luna+ to +http://downloads.jboss.org/tools/development/4.2.0.Alpha2.core/+
. *Core Tests* site (which contains JBoss Tools tests): Move the most recent build available from +http://downloads.jboss.org/tools/build/nightly/coretests/4.2.luna+ to +http://downloads.jboss.org/tools/development/4.2.0.Alpha2.coretests/+
. *WebTools* site (which contains only WTP connectors for AS/WildFly/EAP): Move the most recent build available from +http://downloads.jboss.org/tools/build/nightly/webtools/4.2.luna+ to +http://downloads.jboss.org/tools/development/4.2.0.Alpha2.webtools/+ 

Here is a script that does this:
[source,bash]
----
stream=4.2.luna
version=4.2.0.Alpha2

site=core
# Retrieve latest build and remove trailing slash
coreBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1) 
coreBuildID=${coreBuildID%%/*}
echo "Latest build for ${site}: ${coreBuildID}"
# Create target directory and populate it
echo "mkdir development/${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${coreBuildID} development/${version}.${site}/${coreBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds

site=coretests
# Repeat operation
coretestsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1)
coretestsBuildID=${coretestsBuildID%%/*}
echo "Latest build for ${site}: ${coretestsBuildID}"
echo "mkdir development/${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${coretestsBuildID} development/${version}.${site}/${coretestsBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  
site=webtools
webtoolsBuildID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds/nightly/${site}/${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1)
webtoolsBuildID=${webtoolsBuildID%%/*}
echo "Latest build for ${site}: ${webtoolsBuildID}"
echo "mkdir development/${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
echo "rename nightly/${site}/${stream}/${webtoolsBuildID} development/${version}.${site}/${webtoolsBuildID}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/builds
  
echo " >> http://download.jboss.org/jbosstools/builds/development/${version}.core/${coreBuildID}" | egrep ">>|${version}"
echo " >> http://download.jboss.org/jbosstools/builds/development/${version}.coretests/${coretestsBuildID}" | egrep ">>|${version}"
echo " >> http://download.jboss.org/jbosstools/builds/development/${version}.webtools/${webtoolsBuildID}" | egrep ">>|${version}"
----

Then verify sites are correctly populated with build metadata. To do so, you can simply make sure that under each one of these build sites, you find a file '/logs/GIT_REVISION.txt'.

Move update sites to "updates"
------------------------------

p2 repositories are expected to be under the +http://download.jboss.org/jbosstools/updates+ directory. Similarly to the build sites, we move them there.
[source,bash]
----
stream=4.2.luna
version=4.2.0.Alpha2

site=core
echo "rename nightly/${site}/${stream} JBossTools-${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates  
echo " >> http://download.jboss.org/jbosstools/updates/JBossTools-${version}.${site}/" | egrep ">>|${version}"

site=coretests
echo "rename nightly/${site}/${stream} JBossTools-${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates  
echo " >> http://download.jboss.org/jbosstools/updates/JBossTools-${version}.${site}/" | egrep ">>|${version}"

site=webtools
echo "rename nightly/${site}/${stream} JBossTools-${version}.${site}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates
echo " >> http://download.jboss.org/jbosstools/updates/JBossTools-${version}.${site}/" | egrep ">>|${version}"
----

And it is also necessary to populate the *discovery* sites for the version(cf 1st step)

[source,bash]
----
stream=4.2.luna
version=4.2.0.Alpha2

echo "rename nightly/core/${stream} development/${version}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/
echo " >> http://download.jboss.org/jbosstools/discovery/development/${version}/" | egrep ">>|${version}"
----

Then verify those 4 sites are correctly populated.

Preserve a copy of the nightly sites after the move
---------------------------------------------------

NOTE:
This step is mandatory only because we don't have a good way to copy stuff remotely (sftp only allows rename). If we could be granted something more powerful with remote copies, we could copy stuff in previous steps instead of moving it, and this step would becomme useless.

First, run it as +hudson+ user from a ci machine
----
local$ ssh dev01.mw.lab.eng.bos.redhat.com
dev01$ sudo su - hudson
----
 
  alias   scpr='rsync -aPrz --rsh=ssh --protocol=28'

  # can run these in parallel 

  version=4.1.1.CR2 # a, b, c...
  branch=core/4.1.kepler
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/JBossTools-${version}.core/* /tmp/JBossTools-${version}.core/
  scpr /tmp/JBossTools-${version}.core/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.core/
  echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

  version=4.1.1.CR2 # a, b, c...
  branch=coretests/4.1.kepler
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/JBossTools-${version}.coretests/* /tmp/JBossTools-${version}.coretests/
  scpr /tmp/JBossTools-${version}.coretests/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.coretests/
  echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

  version=4.1.1.CR2 # a, b, c...
  branch=webtools/4.1.kepler
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/JBossTools-${version}.webtools/* /tmp/JBossTools-${version}.webtools/
  scpr /tmp/JBossTools-${version}.webtools/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/updates/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.webtools/
  echo " >> http://download.jboss.org/jbosstools/updates/nightly/${branch}/" | egrep ">>|${branch}"

  version=4.1.1.CR2 # a, b, c...
  branch=core/4.1.kepler
  scpr tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/development/${version}/* /tmp/JBossTools-${version}.discovery/
  scpr /tmp/JBossTools-${version}.discovery/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/nightly/${branch}/ --delete
  rm -fr /tmp/JBossTools-${version}.discovery/
  echo " >> http://download.jboss.org/jbosstools/discovery/nightly/${branch}/" | egrep ">>|${branch}"



Notify the team
---------------

____
*To* jbosstools-dev@lists.jboss.org +
*Subject* JBoss Tools Core 4.2.0.Alpha2 bits available for QE testing +
*Body*
----
JBoss Tools Core 4.2.0.Alpha2 bits available for QE testing

As always, these are not FINAL bits, but preliminary results for QE testing. Not for redistribution to customers. 

Update Sites:
* http://download.jboss.org/jbosstools/updates/JBossTools-${version}.core/
* http://download.jboss.org/jbosstools/updates/JBossTools-${version}.coretests/
* http://download.jboss.org/jbosstools/updates/JBossTools-${version}.webtools/

Builds:
* http://download.jboss.org/jbosstools/builds/development/${version}.core/${coreBuildID}
* http://download.jboss.org/jbosstools/builds/development/${version}.coretests/${coretestsBuildID}
* http://download.jboss.org/jbosstools/builds/development/${version}.webtools/${webtoolsBuildID}

JBoss Central:
* http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/kepler/ (JBoss Central - current release)
* http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/${TARGET_PLATFORM_CENTRAL_MAX}/ (JBoss Central - upcoming milestone)

To test the upcoming version of Central, add this to your eclipse.ini file after the -vmargs line:
 -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/development/${version}/jbosstools-directory.xml
 -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/discovery/development/${version}/

JBoss Tools Target Platforms (This is loaded automatically into Eclipse when installing JBoss Tools. Provided here simply for reference):
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/kepler/ (JBoss Tools - current release)
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX} (JBoss Tools - upcoming milestone)



New + Noteworthy: http://htmlpreview.github.com/?https://raw.github.com/jbosstools/jbosstools-documentation/master/whatsnew/index.html (subject to change) and http://docs.jboss.org/tools/whatsnew/

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

Changes prompting this $respin are:
https://issues.jboss.org/issues/?jql=labels%20in%20%28%22'${respin}'%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22'${version2}'%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22'${version3}'%22%29%29%29
----

____

And send a copy of this mail to jbds-pm-list@redhat.com and external-exadel-list@redhat.com

