= Pre-Staging steps

Before beginning a stage at the end of a sprint, a number of things need to be done:

* Send reminder note to jbosstools-dev@lists.jboss.org of upcoming target platform freeze

* Send reminder note to jbosstools-dev@lists.jboss.org of upcoming code freeze (last Wed of sprint)

* Send reminder note to jmaury@redhat.com to ask that next sprint version be added so triage can be done

* Send reminder note to jbosstools-dev@lists.jboss.org to ask that triage can be done
** TODO: https://issues.jboss.org/browse/JBIDE-24674
** blocker/critical issues: make these your priority work for the forthcoming sprint - move to .next version & assign to the forthcoming sprint
** other issues that WILL be done in the next sprint: move to .next version & assign to the forthcoming sprint, but lower down
** non-blocker & non-critical issues that won't be done in the next sprint: move to .x

* Confirm latest Integration Stack (IS) release & URLs


== Send reminder note(s) to jbosstools-dev@lists.jboss.org of upcoming target platform freeze, code freeze, and JIRA triage

1. If there have been significant changes to target platforms this sprint, on the Monday prior to the last Wednesday of the sprint, send a note to jbosstools-dev@lists.jboss.org reminding people of these changes and calling for any last minute updates that might be needed to be done to the TARGET PLATFORMS before code freeze. Changes must be committed, built, and live by EOD Tuesday, one day before code freeze.

This will also serve as a reminder of the upcoming CODE FREEZE on the last Wednesday of the sprint.

2. For GA releases, the target plaform must also be link:5_Release_nexus.adoc[released to Nexus].


== Confirm latest Integration Stack (IS) release & URLs

Contact Paul Leacu (pleacu@redhat.com) to ask what the latest IS releases are (4.5.x, 11.x) and the URLs to use when merging this content into the Central Discovery sites.

The job that will handles this merge step is:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jbosstools-releng/job/jbosstools-releng-push-to-staging-04-update-merge-composites-html/

