= Staging devstudio Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

= Pre-Staging Steps

See link:1_Staging_preparation.adoc[Pre-Staging]

== Clone jbosstools-build-ci repo

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ ! -d jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout master # later jbosstools-4.5.x
chmod +x -R */*.sh */*/*.sh

----


= Staging steps

[IMPORTANT]
====

Before running any of the jobs or scripts below, make sure to set the correct versions to the values for the release you're staging or releasing.

* look for versionWithRespin_ or version_, update to version you're staging
* look for PREV and NEXT variables; set to previous / next milestone (AMx, AMy, AMz, Final/GA)
* check TARGET_PLATFORM_ versions are current w/ latest versions
* check parent pom version, version_parent, is current
* check Integration Stack variables like earlyaccess_IS, version_jbt_IS, version_ds_IS are correct. Double-check best values with Paul Leacu (pleacu).

====

== Update Discovery Sites and URLs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Verify correct version set in com.jboss.devstudio.central.core

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Disable jobs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Stage to devstudio.redhat.com

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

=== Fetch devstudio installer (for later smoke test)

TIP: Once the staging build folder exists, start fetching the devstudio installer (we'll need it later to do a smoke test)

[source,bash]
----

cd ~/tmp
versionWithRespin_ds=11.1.0.AM1
installerJar=$(wget -O - -q https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
time wget https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}

----

You'll use this downloaded installer later, but since it takes a while to download, it's more efficient to start it now.


=== Cleanup OLD builds

Optional step.

Run this job to move any old builds into an OLD/ folder for later cleanup, or delete them immediately.

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites/


=== Update /staging/updates/ sites and merge in Integration Stack content

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Release the latest staging site to ide-config.properties

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Smoke test the release (manually)

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Bring Your Own Eclipse category from

https://devstudio.redhat.com/11/staging/updates/

3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----

versionWithRespin_ds=11.1.0.AM1
cd ~/tmp
installerJar=$(wget -O - -q https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"

# should have already downloaded this above
if [[ ! -f ${installerJar} ]]; then wget https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}; fi

if [[ -d ~/devstudio ]]; then mv ~/devstudio{,_BAK}; fi
echo 1 | java -jar ~/tmp/${installerJar} -console # install headlessly to ~/devstudio
mv ~/devstudio ~/${installerJar/.jar/} # rename install folder
if [[ -d ~/devstudio_BAK ]]; then mv ~/devstudio{_BAK,}; fi

cd ~/${installerJar/.jar/}/studio; ./devstudio -data /tmp/wksp-${installerJar/.jar/}

----

0. After downloading and installing devstudio from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Notify the team (send 1 email)

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Trigger QE Smoke tests (automated)

Trigger the QE smoke tests in https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.1.0.AM1
installerJar=$(wget -O - -q https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
version_ds_INST=${installerJar#devstudio-}
version_ds_INST=${version_ds_INST%-installer*}
echo "Devstudio installer version: ${version_ds_INST}"

# run the one buildflow job
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in devstudio.buildflow.it.smoke; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="DEVSTUDIO_VERSION=${version_ds_INST}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s
done

----


== Sign RPM

0. This section only applies to GA builds. No need to sign AMx milestones!

1. give URL link to Chris via RCM ticket, eg., https://projects.engineering.redhat.com/browse/RCM-12825

TODO: switch to gold key, not dev key?

https://www.redhat.com/security/data/fd431d51.txt
https://access.redhat.com/security/team/key

[source,bash]
----

# TODO: use ticket template https://mojo.redhat.com/docs/DOC-1096582 for request-email

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.1.0.AM1
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-05-sign-rpm-request-email; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

2. Chris signs it, and gives back a URL,eg., http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/devstudio-11.0.0/rpms/signed/

3. Fetch rpms, regen metadata

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

# NOTE: do not use http://download-node-02.eng.bos.redhat.com as it may not resolve from within Jenkins
signedURL=http://download.devel.redhat.com/devel/candidates/jboss/devstudio/devstudio-11.1.0.AM1/rpms/signed
versionWithRespin_ds=11.1.0.GA
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-06-sign-rpm-fetch; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&signedURL=${signedURL}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

4. Next, update your /etc/yum.repos.d/rh-eclipse47-devstudio.repo file like this:

5. NOTE: Run the following commands as root user:

[source,bash]
----

cat <<EOF > /etc/yum.repos.d/rh-eclipse47-devstudio.repo

[rh-eclipse47-devstudio-staging-11.0]
name=rh-eclipse47-devstudio-staging-11.0
baseurl=https://devstudio.redhat.com/11/staging/builds/devstudio-11.1.0.AM1-build-rpm/latest/x86_64/
enabled=1
gpgcheck=1
upgrade_requirements_on_install=1
metadata_expire=2m

[rh-eclipse47-devstudio-snapshots-11.0]
name=rh-eclipse47-devstudio-snapshots-11.0
baseurl=https://devstudio.redhat.com/11/snapshots/rpms/11.0.0/x86_64/
enabled=0
gpgcheck=0
upgrade_requirements_on_install=1
metadata_expire=120m

EOF

# If you already have rh-eclipse47-devstudio installed (can add --best flag for Fedora install)
yum update rh-eclipse47-devstudio -y

# Or, if not already installed
yum install rh-eclipse47-devstudio -y

# note, if verifying unsigned rpms, use:
yum update --nogpgcheck # or
yum install --nogpgcheck

----

[WARNING]
====
Installation should complete without any problems. Should NOT see an error like this:
[source,bash]
----
Error: Package rh-eclipse47-devstudio-11.0-0.20170809.1307.el7.x86_64.rpm is not signed
----

Alternatively, you could download the rpms from https://devstudio.redhat.com/11/staging/builds/devstudio-11.1.0.AM1-build-rpm/latest/x86_64/
and test them like this to verify their signatures:

[source,bash]
----
rpm -K  *.rpm | grep pgp
----
====

== Push RPM to DevTools channel

@since 11.0

For a GA build, you'll have requested RPM signing via here: link:2_Staging_devstudio.adoc[Sign RPM]. Use that signingTicket value below.

Here is a job that creates the RCM ticket to push the signed RPMs to the DevTools channel:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-06-publish-to-channel-request-email/configure

[source,bash]
----

# TODO: use ticket template https://mojo.redhat.com/docs/DOC-1096582 for request-email

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.1.0.AM1
if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  # signingTicket from https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-05-sign-rpm-request-email
  signingTicket="https://projects.engineering.redhat.com/browse/RCM-19657"
  STAGE_DATE="2017-08-10"
  GOLIVEDATE="2017-08-14"
  TOrecipients="release-engineering@redhat.com"
  CCrecipients="nboldt@redhat.com, rhartman@redhat.com, rzima@redhat.com, mat.booth@redhat.com, vkadlcik@redhat.com, timoran@redhat.com, bodavis@redhat.com, mbenitez@redhat.com"
  CCrecipients=${CCrecipients// /%20}
  recipientOverride="" # or "nboldt@redhat.com"
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-staging-06-publish-to-channel-request-email; do
    prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&GOLIVEDATE=${GOLIVEDATE}&STAGE_DATE=${STAGE_DATE}\
&TOrecipients=${TOrecipients}&CCrecipients=${CCrecipients}&recipientOverride=${recipientOverride}&signingTicket=${signingTicket}"
    nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" != "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    else
      ${JP} -s ${ccijenkins} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----
