= Staging devstudio Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

= Pre-Staging Steps

See link:1_Staging_preparation.adoc[Pre-Staging]

== Clone jbosstools-build-ci repo or link to it from elsewhere on disk

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ -d ~/tru/jbosstools-build-ci ]]; then ln -s ~/tru/jbosstools-build-ci; fi
if [[ ! -d jbosstools-build-ci ]] && [[ -L jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout master # later jbosstools-4.5.x
chmod +x -R */*.sh */*/*.sh

----


= Staging steps

[IMPORTANT]
====

Before running any of the jobs or scripts below, make sure to set the correct versions to the values for the release you're staging or releasing.

* look for versionWithRespin_ or version_, update to version you're staging
* look for PREV and NEXT variables; set to previous / next milestone (AMx, AMy, AMz, Final/GA)
* check TARGET_PLATFORM_ versions are current w/ latest versions
* check parent pom version, version_parent, is current
* check Integration Stack variables like earlyaccess_IS, version_jbt_IS, version_ds_IS are correct. Double-check best values with Paul Leacu (pleacu).

====

== Update Discovery Sites and URLs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Verify correct version set in com.jboss.devstudio.central.core

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Disable jobs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

== Stage to devstudio.redhat.com

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]

=== Fetch devstudio installer (for later smoke test)

TIP: Once the staging build folder exists, start fetching the devstudio installer (we'll need it later to do a smoke test)

[source,bash]
----

# TODO HERE

cd ~/tmp
versionWithRespin_ds=11.2.0.GA
installerJar=$(wget -O - -q https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
if [[ ${installerJar} ]]; then
  time wget https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}
else
  echo ""; echo "[ERROR] No installer found! Try again later!"
fi

----

You'll use this downloaded installer later, but since it takes a while to download, it's more efficient to start it now.


=== Cleanup OLD builds

Optional step.

Run this job to move any old builds into an OLD/ folder for later cleanup, or delete them immediately.

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-08-delete-builds-and-update-sites/


=== Update /staging/updates/ sites and merge in Integration Stack content

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Release the latest staging site to ide-config.properties

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Smoke test the release (manually)

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Bring Your Own Eclipse category from

https://devstudio.redhat.com/11/staging/updates/

3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----

versionWithRespin_ds=11.2.0.GA
cd ~/tmp
installerJar=$(wget -O - -q https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"

# should have already downloaded this above
if [[ ! -f ${installerJar} ]]; then wget https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/${installerJar}; fi

if [[ -d ~/devstudio ]]; then mv ~/devstudio{,_BAK}; fi
echo 1 | java -jar ~/tmp/${installerJar} -console # install headlessly to ~/devstudio
mv ~/devstudio ~/${installerJar/.jar/} # rename install folder
if [[ -d ~/devstudio_BAK ]]; then mv ~/devstudio{_BAK,}; fi

cd ~/${installerJar/.jar/}/studio; ./devstudio -data /tmp/wksp-${installerJar/.jar/}

----

0. After downloading and installing devstudio from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Notify the team (send 1 email)

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Trigger QE Smoke tests (automated)

Trigger the QE smoke tests in https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.2.0.GA
installerJar=$(wget -O - -q https://devstudio.redhat.com/11/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/ | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
version_ds_INST=${installerJar#devstudio-}
version_ds_INST=${version_ds_INST%-installer*}
echo "Devstudio installer version: ${version_ds_INST}"

# run the one buildflow job
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in devstudio.buildflow.it.smoke; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="DEVSTUDIO_VERSION=${version_ds_INST}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s
done

----


== Verify install instructions are correct

Look at the .txt and .html files in https://devstudio.redhat.com/11/staging/builds/devstudio-11.2.0.GA-build-product/latest/all/

Verify that they contain correct install/usage instructions & versions.

If anything is wrong, fix it by hand, then also commit your changes to the templates.

https://github.com/jbdevstudio/jbdevstudio-product/commit/3827045dca85e73c5ae339cc13f514591e3c1835
https://github.com/jbdevstudio/jbdevstudio-product/commit/e6c2954207d1db7451f7adfd2d89c7ceccd6adbe


== Rename GA artifacts to remove timestamp and buildID

For GA releases only!

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`devstudio-10.4.0.GA-v20151002-2235-B124-installer-standalone.jar` must be renamed to `devstudio-10.4.0.GA-installer-standalone.jar`.

Configure, then run this job: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jbosstools-releng/job/jbosstools-releng-push-to-staging-06-rename-GA-artifacts/

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.2.0.GA

if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-staging-06-rename-GA-artifacts; do
    prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}"
    nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" == "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    else
      ${JP} -s ${ccijenkins} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----


== Submit RCM ticket to sign RPM

@since 11.0

For GA builds only.

Give URL link to Chris via RCM ticket, eg., https://projects.engineering.redhat.com/browse/RCM-27209

https://www.redhat.com/security/data/a5787476.txt
https://access.redhat.com/security/team/key

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.2.0.GA
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-05-sign-rpm-request-email; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
    google-chrome ${ccijenkins}/${j} &
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

== Submit RCM ticket to push RPM to DevTools channel (once signed)

@since 11.0

For GA builds only.

Here is a job that creates the RCM ticket to push the signed RPMs to the DevTools channel:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-06-publish-to-channel-request-email/configure

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.2.0.GA
if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  # signingTicket from https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-05-sign-rpm-request-email
  signingTicket="https://projects.engineering.redhat.com/browse/RCM-27209"
  STAGE_DATE="2018-01-24"
  GOLIVEDATE="2018-01-29"
  TOrecipients="release-engineering@redhat.com"
  CCrecipients="nboldt@redhat.com, rhartman@redhat.com, rzima@redhat.com, mat.booth@redhat.com, vkadlcik@redhat.com, timoran@redhat.com, bodavis@redhat.com, mbenitez@redhat.com, scela@redhat.com"
  CCrecipients=${CCrecipients// /%20}
  recipientOverride="" # or "nboldt@redhat.com"
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-staging-06-publish-to-channel-request-email; do
    prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&GOLIVEDATE=${GOLIVEDATE}&STAGE_DATE=${STAGE_DATE}\
&TOrecipients=${TOrecipients}&CCrecipients=${CCrecipients}&recipientOverride=${recipientOverride}&signingTicket=${signingTicket}"
    nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" != "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    google-chrome ${ccijenkins}/${j} &
    else
      ${JP} -s ${ccijenkins} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----

== Announce internally for push to CSP staging site

Submit an RCM ticket to release-engineering@redhat.com to requet that the binaries be uploaded to the CSP (Red Hat Customer Portal) and Download Manager.

IMPORTANT: As this takes some time and requires coordination with other teams, this step should be initiated a few days before release to allow processing time.

Previous ticket:

* https://projects.engineering.redhat.com/browse/RCM-20050
* https://projects.engineering.redhat.com/browse/RCM-12959

Communicate with Chris O'Brien (internal IRC: siege) to coordinate the release. All the above can happen in parallel / before the updates below.

For a GA build, you'll have requested RPM signing via here: link:2_Staging_devstudio.adoc[Sign RPM]. Use that signingTicket value below.

Here is a job that creates the RCM ticket:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-06-releng-request-email/configure

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.2.0.GA
if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  # signingTicket from https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-05-sign-rpm-request-email
  signingTicket="https://projects.engineering.redhat.com/browse/RCM-27209"
  errataTicket="https://errata.devel.redhat.com/advisory/31862"
  STAGE_DATE="2018-01-24"
  GOLIVEDATE="2018-01-29"
  TOrecipients="release-engineering@redhat.com"
  CCrecipients="cobrien@redhat.com, erooney@redhat.com, rkratky@redhat.com, sbharadw@redhat.com, nboldt@redhat.com, mat.booth@redhat.com, jmaury@redhat.com, mbenitez@redhat.com, scela@redhat.com, timoran@redhat.com, bodavis@redhat.com"
  CCrecipients=${CCrecipients// /%20}
  recipientOverride="" # or "nboldt@redhat.com"
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-staging-06-releng-request-email; do
    prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&GOLIVEDATE=${GOLIVEDATE}&STAGE_DATE=${STAGE_DATE}\
&TOrecipients=${TOrecipients}&CCrecipients=${CCrecipients}&recipientOverride=${recipientOverride}&signingTicket=${signingTicket}&errataTicket=${signingTicket}"
    nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" != "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    else
      ${JP} -s ${ccijenkins} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----

== Fetch signed RPMs

Once signed, the RCM ticket above will include a URL,eg., http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/devstudio-11.2.0/rpms/signed/

1. Fetch rpms, regen metadata.

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

signedURL=http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/devstudio-11.2.0/rpms/signed/
versionWithRespin_ds=11.2.0.GA
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-06-sign-rpm-fetch; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&signedURL=${signedURL}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
    google-chrome ${ccijenkins}/${j} &
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

2. Download the rpms from https://devstudio.redhat.com/11/staging/builds/devstudio-11.2.0.GA-build-rpm/latest/x86_64/
and test them like this to verify their signatures. You'll want to run these commands as ROOT

[source,bash]
----

# if not already imported, as ROOT, you need to import the signing key:
cd /tmp; wget -q https://www.redhat.com/security/data/a5787476.txt
gpg --import /tmp/a5787476.txt
rpm --import /tmp/a5787476.txt
rm -f /tmp/a5787476.txt

# now you can check the signature against the key

signedURL=https://devstudio.redhat.com/11/snapshots/builds/devstudio.rpm_master/latest/x86_64/ # unsigned
signedURL=http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/devstudio-11.2.0/rpms/signed/ # signed
signedURL=https://devstudio.redhat.com/11/staging/builds/devstudio-11.2.0.GA-build-rpm/latest/x86_64/ # if updated from the step above, must be signed

theFiles=$(curl -s -S -k ${signedURL} | grep href=\" | grep rpm\" | sed -e "s#.\+href=\"\([^\"]\+\)\".\+#\1#")
for theFile in ${theFiles}; do
  echo "Downloading ${signedURL}${theFile} ..."
  curl -S -k -# ${signedURL}${theFile} > /tmp/${theFile}
  echo "Check pgp signature in /tmp/${theFile}.rpm ..."
  gpgcheck=$(rpm -K  /tmp/${theFile} | grep "signatures OK")
  if [[ ! ${gpgcheck} ]]; then
    echo "[ERROR] rpm is not signed (or you forgot to import the key)!"
    rpm -K /tmp/${theFile}
  else
    echo "[INFO] ${gpgcheck}"
  fi
done

#cleanup
rm -fr /tmp/index.thml /tmp/rh-eclipse47-devstudio*.rpm

----

3. On a RHEL7 box (not Fedora), as ROOT, update your /etc/yum.repos.d/rh-eclipse47-devstudio.repo file like this:

[source,bash]
----

cat <<EOF > /etc/yum.repos.d/rh-eclipse47-devstudio.repo
[rh-eclipse47-devstudio-staging-11.2.0]
name=rh-eclipse47-devstudio-staging-11.2.0
baseurl=https://devstudio.redhat.com/11/staging/builds/devstudio-11.2.0.GA-build-rpm/latest/x86_64/
enabled=1
gpgcheck=1
upgrade_requirements_on_install=1
metadata_expire=2m

[rh-eclipse47-devstudio-snapshots-11.2.0]
name=rh-eclipse47-devstudio-snapshots-11.2.0
baseurl=https://devstudio.redhat.com/11/snapshots/rpms/11.2.0/x86_64/
enabled=0
gpgcheck=0
upgrade_requirements_on_install=1
metadata_expire=120m
EOF

cat <<EOF > /etc/yum.repos.d/rh-eclipse47-build.repo
[rh-eclipse47-build]
name=rh-eclipse47-build
baseurl=http://brewweb.engineering.redhat.com/brewroot/repos/devtools-2018.1-rh-eclipse47-rhel-7-build/latest/x86_64/
enabled=1
sslverify=0
gpgcheck=0
EOF

----

4. On a RHEL7 box (not Fedora), install the signing key and then devstudio:

[source,bash]
----

# if not already imported, as ROOT, you need to import the signing key:
cd /tmp; wget -q https://www.redhat.com/security/data/a5787476.txt
gpg --import /tmp/a5787476.txt
rpm --import /tmp/a5787476.txt
rm -f /tmp/a5787476.txt

# If you already have rh-eclipse47-devstudio installed (can add --best flag for Fedora install)
yum update rh-eclipse47-devstudio -y

# Or, if not already installed
yum install rh-eclipse47-devstudio -y

# note, if verifying unsigned rpms, use:
yum update --nogpgcheck # or
yum install --nogpgcheck

----

[WARNING]
====
Installation should complete without any problems. Should NOT see an error like this:
[source,bash]
----
Error: Package rh-eclipse47-devstudio-11.2.0.20170809.1307.el7.x86_64.rpm is not signed
----
====
