= Pre-Release Steps

These steps can be done before the actual release (eg., on the Thurs or Fri before the Monday release, as long as QE has more-or-less signed off). Check with QE before proceeding.


== Verify that all JIRAs assigned to the current milestone are resolved

Kick this job to send reminder emails to the team, in case some issues are not yet resolved:

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-jiralint-weekly; do
  ${JP} -s ${ccijenkins} -j ${j} -t build
done

google-chrome && google-chrome https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions

----

The new policy is to bump issues to the next fixversion if they're in the next sprint target, or to the .x fixversion if they're not.

So, for a query like this, you will bulk-move all the issues not resolved for AM1 to AM2.

https://issues.jboss.org/issues/?jql=(project%20%3D%20JBIDE%20AND%20resolution%20%3D%20Unresolved%20AND%20fixVersion%20%3D%20%2212331862%22%20OR%20project%20%3D%20JBDS%20AND%20resolution%20%3D%20Unresolved%20AND%20fixVersion%20%3D%20%2212331860%22)%20and%20sprint%20%3D%20%22devex%20%23134%20Jun%202017%22

Note that you cannot move JBIDE and JBDS issues to new fixversions at the same time.

TODO: script this so we can bulk move issues in seconds instead of minutes.


== Rename GA artifacts to remove timestamp and buildID

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`devstudio-10.4.0.GA-v20151002-2235-B124-installer-eap.jar` must be renamed to `devstudio-10.4.0.GA-installer-eap.jar`.

Configure, then run this job: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jbosstools-releng/job/jbosstools-releng-push-to-dev-stable-00-rename-GA-artifacts/

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=10.4.0.GA

if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-dev-stable-00-rename-GA-artifacts; do
    prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}"
    nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" == "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    else
      ${JP} -s ${ccijenkins} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----


== Verify install instructions are correct

Look at the .txt and .html files in /qa/services/http/binaries/RHDS/10.0/staging/builds/devstudio-${versionWithRespin_ds}-build-product/latest/all/

Verify that they contain correct install/usage instructions & versions.

If anything is wrong, fix it by hand, then also commit your changes to the templates.

https://github.com/jbdevstudio/jbdevstudio-product/commit/3827045dca85e73c5ae339cc13f514591e3c1835
https://github.com/jbdevstudio/jbdevstudio-product/commit/e6c2954207d1db7451f7adfd2d89c7ceccd6adbe


== File bug to update http://developers.redhat.com/products/devstudio/

Goal is to update the following pages to include links to guides and to set the correct latest GA release version:

* http://developers.redhat.com/products/devstudio/download/
* http://developers.redhat.com/products/devstudio/hello-world/
* http://developers.redhat.com/products/devstudio/docs-and-apis/

The download page will be automatically updated when new downloads are uploaded into "Download Manager" and no further action is needed. For changes to the other pages that need making manually in Drupal, where they are managed, a bug must be filed. For example:

* https://issues.jboss.org/browse/DEVELOPER-3908

Once the release is completed and the download page reflects the latest GA version, the necessary changes will be made by someone who has the necessary permissions (currently Mike Guerette).

Once you have the JIRA, you can link to it when sending the note to release-engineering@ below.

NOTE: If we ever decide to drop the EAP-bundled installer, or there's a newer version of EAP than is bundled, we could add the EAP 7 zip / installer to list of devstudio artifacts on both developers.redhat.com and www.jboss.org. Explicit listing of files used to be done like this:
* https://github.com/redhat-developer/developers.redhat.com/blob/25640af93a8d7d219c189d37c528534acda17483/products/devstudio/_common/product.yml and
* https://github.com/redhat-developer/developers.redhat.com/blob/25640af93a8d7d219c189d37c528534acda17483/products/eap/_common/product.yml


== Clone jbosstools-build-ci repo

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Announce internally for push to CSP staging site

Submit an RCM ticket to release-engineering@redhat.com to requet that the binaries be uploaded to the CSP (Red Hat Customer Portal) and Download Manager.

IMPORTANT: As this takes some time and requires coordination with other teams, this step should be initiated a few days before release to allow processing time.

Previous ticket:

* https://projects.engineering.redhat.com/browse/RCM-12959

Communicate with Chris O'Brien (internal IRC: siege) to coordinate the release. All the above can happen in parallel / before the updates below.

For a GA build, you'll have requested RPM signing via here: link:2_Staging_devstudio.adoc[Sign RPM]. Use that signingTicket value below.

Here is a job that creates the RCM ticket:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-dev-stable-00-releng-request-email/configure

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=10.4.0.GA
if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  # signingTicket from https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-05-sign-rpm-request-email
  signingTicket="RCM-----"
  GOLIVEDATE="Mon, Aug 14, 2017"
  TOrecipients="release-engineering@redhat.com"
  CCrecipients="cobrien@redhat.com, mhusnain@redhat.com, nboldt@redhat.com, jmaury@redhat.com, timoran@redhat.com, bodavis@redhat.com"
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-dev-stable-00-releng-request-email; do
    prevJob=$(prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable" -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&signingTicket=${signingTicket}&\
GOLIVEDATE=${GOLIVEDATE}&TOrecipients=${TOrecipients}&CCrecipients=${CCrecipients}"
    nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" != "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    else
      ${JP} -s ${ccijenkins} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----
