= Pre-Release Steps

These steps can be done before the actual release (eg., on the Thurs or Fri before the Monday release, as long as QE has more-or-less signed off). Check with QE before proceeding.


== Clone jbosstools-build-ci repo or link to it from elsewhere on disk

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ -d ~/tru/jbosstools-build-ci ]]; then ln -s ~/tru/jbosstools-build-ci; fi
if [[ ! -d jbosstools-build-ci ]] && [[ -L jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout master # later jbosstools-4.5.x
chmod +x -R */*.sh */*/*.sh

----

== Remind devs about JIRA triage

Kick this job to send reminder emails to the team, in case some issues are not yet resolved.

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-jiralint-weekly; do
  ${JP} -s ${ccijenkins} -j ${j} -t build
done

----

== Rename GA artifacts to remove timestamp and buildID

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`devstudio-10.4.0.GA-v20151002-2235-B124-installer-eap.jar` must be renamed to `devstudio-10.4.0.GA-installer-eap.jar`.

Configure, then run this job: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jbosstools-releng/job/jbosstools-releng-push-to-dev-stable-00-rename-GA-artifacts/

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.1.0.GA

if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-dev-stable-00-rename-GA-artifacts; do
    prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="versionWithRespin_jbt=${versionWithRespin_jbt}&versionWithRespin_ds=${versionWithRespin_ds}"
    nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" == "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    else
      ${JP} -s ${ccijenkins} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----


== Verify install instructions are correct

Look at the .txt and .html files in https://devstudio.redhat.com/11/staging/builds/devstudio-11.1.0.GA-build-product/latest/all/

Verify that they contain correct install/usage instructions & versions.

If anything is wrong, fix it by hand, then also commit your changes to the templates.

https://github.com/jbdevstudio/jbdevstudio-product/commit/3827045dca85e73c5ae339cc13f514591e3c1835
https://github.com/jbdevstudio/jbdevstudio-product/commit/e6c2954207d1db7451f7adfd2d89c7ceccd6adbe


== File bug to update http://developers.redhat.com/products/devstudio/

Ping Mike Guerette & Erin Rooney a couple weeks in advance to get this stuff ready in in time for GA.

Goal is to update the following pages to include links to guides and to set the correct latest GA release version:

* http://developers.redhat.com/products/devstudio/download/
* http://developers.redhat.com/products/devstudio/hello-world/
* http://developers.redhat.com/products/devstudio/docs-and-apis/

The download page will be automatically updated when new downloads are uploaded into "Download Manager" and no further action is needed.


== Clone jbosstools-build-ci repo

See link:2_Staging_jbosstools.adoc[JBoss Tools Staging]


== Announce internally for push to CSP staging site

Submit an RCM ticket to release-engineering@redhat.com to requet that the binaries be uploaded to the CSP (Red Hat Customer Portal) and Download Manager.

IMPORTANT: As this takes some time and requires coordination with other teams, this step should be initiated a few days before release to allow processing time.

Previous ticket:

* https://projects.engineering.redhat.com/browse/RCM-20050
* https://projects.engineering.redhat.com/browse/RCM-12959

Communicate with Chris O'Brien (internal IRC: siege) to coordinate the release. All the above can happen in parallel / before the updates below.

For a GA build, you'll have requested RPM signing via here: link:2_Staging_devstudio.adoc[Sign RPM]. Use that signingTicket value below.

Here is a job that creates the RCM ticket:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-dev-stable-00-releng-request-email/configure

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

versionWithRespin_ds=11.1.0.GA
if [[ ${versionWithRespin_ds} == *"GA" ]]; then
  # signingTicket from https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-releng-push-to-staging-05-sign-rpm-request-email
  signingTicket="https://projects.engineering.redhat.com/browse/RCM-23772"
  STAGE_DATE="2017-11-01"
  GOLIVEDATE="2017-11-06"
  TOrecipients="release-engineering@redhat.com"
  CCrecipients="cobrien@redhat.com, erooney@redhat.com, rkratky@redhat.com, sbharadw@redhat.com, nboldt@redhat.com, mat.booth@redhat.com, jmaury@redhat.com, mbenitez@redhat.com, timoran@redhat.com, bodavis@redhat.com"
  CCrecipients=${CCrecipients// /%20}
  recipientOverride="" # or "nboldt@redhat.com"
  ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
  JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
  for j in jbosstools-releng-push-to-dev-stable-00-releng-request-email; do
    prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
    sleep 3s

    data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&GOLIVEDATE=${GOLIVEDATE}&STAGE_DATE=${STAGE_DATE}\
&TOrecipients=${TOrecipients}&CCrecipients=${CCrecipients}&recipientOverride=${recipientOverride}&signingTicket=${signingTicket}"
    nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
    sleep 15s

    if [[ "${prevJob}" != "${nextJob}" ]]; then
      echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
      echo "[WARN] ${ccijenkins}/${j}"
    else
      ${JP} -s ${ccijenkins} -j ${j} -t disable
      ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
    fi
  done
fi

----
