= Pre-Release Steps

These steps can be done before the actual release (eg., on the Thurs or Fri before the Monday release, as long as QE has more-or-less signed off). Check with QE before proceeding.


== Clone jbosstools-build-ci repo or link to it from elsewhere on disk

[source,bash]
----

mkdir -p /tmp/jbt.github
cd /tmp/jbt.github
if [[ -d ~/tru/jbosstools-build-ci ]]; then ln -s ~/tru/jbosstools-build-ci; fi
if [[ ! -d jbosstools-build-ci ]] && [[ -L jbosstools-build-ci ]]; then git clone git@github.com:jbosstools/jbosstools-build-ci.git; fi
cd jbosstools-build-ci
git checkout master # later jbosstools-4.5.x
chmod +x -R */*.sh */*/*.sh

----


== Fetch signed RPMs

Once signed, the RCM ticket above will include a URL,eg., http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/devstudio-11.2.0/rpms/signed/

1. Fetch rpms, regen metadata.

[source,bash]
----

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

# TODO HERE

# NOTE: do not use http://download-node-02.eng.bos.redhat.com as it may not resolve from within Jenkins
signedURL=http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/devstudio-11.2.0/rpms/signed/
versionWithRespin_ds=11.2.0.GA
ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-releng-push-to-staging-06-sign-rpm-fetch; do
  prevJob=$(${JP} -s ${ccijenkins} -j ${j} -t enable -q); echo "[${prevJob}] ${ccijenkins}/${j} enable"
  sleep 3s

  data="token=RELENG&versionWithRespin_ds=${versionWithRespin_ds}&signedURL=${signedURL}"
  nextJob=$(${JP} -s ${ccijenkins} -j ${j} -t buildWithParameters -q -d ${data}); echo "[${nextJob}] ${ccijenkins}/${j} buildWithParameters ${data}"
  sleep 15s

  if [[ "${prevJob}" == "${nextJob}" ]]; then
    echo "[WARN] Build has not started yet! Must manually disable and toggle keeping the log once the job has started."
    echo "[WARN] ${ccijenkins}/${j}"
    google-chrome ${ccijenkins}/${j} &
  else
    ${JP} -s ${ccijenkins} -j ${j} -t disable
    ${JP} -s ${ccijenkins} -j ${j} -t lastBuild/toggleLogKeep
  fi
done

----

2. Download the rpms from https://devstudio.redhat.com/11/staging/builds/devstudio-11.2.0.GA-build-rpm/latest/x86_64/
and test them like this to verify their signatures. You'll want to run these commands as ROOT

[source,bash]
----

# if not already imported, as ROOT, you need to import the signing key:
cd /tmp; wget -q https://www.redhat.com/security/data/a5787476.txt
gpg --import /tmp/a5787476.txt
rpm --import /tmp/a5787476.txt
rm -f /tmp/a5787476.txt

# now you can check the signature against the key

signedURL=https://devstudio.redhat.com/11/snapshots/builds/devstudio.rpm_master/latest/x86_64/ # unsigned
signedURL=http://download-node-02.eng.bos.redhat.com/devel/candidates/jboss/devstudio/devstudio-11.2.0/rpms/signed/ # signed
signedURL=https://devstudio.redhat.com/11/staging/builds/devstudio-11.2.0.GA-build-rpm/latest/x86_64/ # if updated from the step above, must be signed

theFiles=$(curl -s -S -k ${signedURL} | grep href=\" | grep rpm\" | sed -e "s#.\+href=\"\([^\"]\+\)\".\+#\1#")
for theFile in ${theFiles}; do
  echo "Downloading ${signedURL}${theFile} ..."
  curl -S -k -# ${signedURL}${theFile} > /tmp/${theFile}
  echo "Check pgp signature in /tmp/${theFile}.rpm ..."
  gpgcheck=$(rpm -K  /tmp/${theFile} | grep "signatures OK")
  if [[ ! ${gpgcheck} ]]; then
    echo "[ERROR] rpm is not signed (or you forgot to import the key)!"
    rpm -K /tmp/${theFile}
  else
    echo "[INFO] ${gpgcheck}"
  fi
done

#cleanup
rm -fr /tmp/index.thml /tmp/rh-eclipse47-devstudio*.rpm

----

3. On a RHEL7 box (not Fedora), as ROOT, update your /etc/yum.repos.d/rh-eclipse47-devstudio.repo file like this:

[source,bash]
----

cat <<EOF > /etc/yum.repos.d/rh-eclipse47-devstudio.repo
[rh-eclipse47-devstudio-staging-11.2.0]
name=rh-eclipse47-devstudio-staging-11.2.0
baseurl=https://devstudio.redhat.com/11/staging/builds/devstudio-11.2.0.GA-build-rpm/latest/x86_64/
enabled=1
gpgcheck=1
upgrade_requirements_on_install=1
metadata_expire=2m

[rh-eclipse47-devstudio-snapshots-11.2.0]
name=rh-eclipse47-devstudio-snapshots-11.2.0
baseurl=https://devstudio.redhat.com/11/snapshots/rpms/11.2.0/x86_64/
enabled=0
gpgcheck=0
upgrade_requirements_on_install=1
metadata_expire=120m
EOF

cat <<EOF > /etc/yum.repos.d/rh-eclipse47-build.repo
[rh-eclipse47-build]
name=rh-eclipse47-build
baseurl=http://brewweb.engineering.redhat.com/brewroot/repos/devtools-2018.1-rh-eclipse47-rhel-7-build/latest/x86_64/
enabled=1
sslverify=0
gpgcheck=0
EOF

----

4. On a RHEL7 box (not Fedora), install the signing key and then devstudio:

[source,bash]
----

# if not already imported, as ROOT, you need to import the signing key:
cd /tmp; wget -q https://www.redhat.com/security/data/a5787476.txt
gpg --import /tmp/a5787476.txt
rpm --import /tmp/a5787476.txt
rm -f /tmp/a5787476.txt

# If you already have rh-eclipse47-devstudio installed (can add --best flag for Fedora install)
yum update rh-eclipse47-devstudio -y

# Or, if not already installed
yum install rh-eclipse47-devstudio -y

# note, if verifying unsigned rpms, use:
yum update --nogpgcheck # or
yum install --nogpgcheck

----

[WARNING]
====
Installation should complete without any problems. Should NOT see an error like this:
[source,bash]
----
Error: Package rh-eclipse47-devstudio-11.2.0.20170809.1307.el7.x86_64.rpm is not signed
----
====


== Remind devs about JIRA triage

Kick this job to send reminder emails to the team, in case some issues are not yet resolved.

[source,bash]
----

###### TODO just this one step left to do here.

# kerberos login for the Jenkins server
export userpass=KERBUSER:PASSWORD

ccijenkins=https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job
JP=/tmp/jbt.github/jbosstools-build-ci/util/jenkinsPost.sh
for j in jbosstools-jiralint-weekly; do
  ${JP} -s ${ccijenkins} -j ${j} -t build
done

----

== Update http://developers.redhat.com/products/devstudio/

Ping Mike Guerette & Erin Rooney a couple weeks in advance to get this stuff ready in in time for GA.

Goal is to update the following pages to include links to guides and to set the correct latest GA release version:

* http://developers.redhat.com/products/devstudio/download/
* http://developers.redhat.com/products/devstudio/hello-world/
* http://developers.redhat.com/products/devstudio/docs-and-apis/

The download page will be automatically updated when new downloads are uploaded into "Download Manager" and no further action is needed.


