Before you can build anything in JBoss Tools / Devstudio release for a new release stream (eg. Neon -> Oxygen, Oxygen -> Photon) you need to do some initial bootstrapping.

== Create JBoss Tools composite sites

Every year we need a new pair of composite sites. These are used to determine when a new JBoss Tools aggregate must be built, based on polling the p2 metadata of the composite.

Latest versions are here:

* http://download.jboss.org/jbosstools/neon/snapshots/builds/_composite_/core/
* http://download.jboss.org/jbosstools/oxygen/snapshots/builds/_composite_/core/

== Create Stable, Development, Staging, Snapshots placeholder update sites & build folders

Every year we need to create placeholder URLs for these locations:

* http://download.jboss.org/jbosstools/oxygen/snapshots/updates/
* http://download.jboss.org/jbosstools/oxygen/snapshots/builds/
* http://download.jboss.org/jbosstools/oxygen/staging/updates/
* http://download.jboss.org/jbosstools/oxygen/staging/builds/
* http://download.jboss.org/jbosstools/oxygen/development/updates/ (copy content from oxygen/development/ site)
* http://download.jboss.org/jbosstools/oxygen/stable/updates/ (copy content from neon/stable/ site)

* https://devstudio.redhat.com/11/snapshots/updates/
* https://devstudio.redhat.com/11/snapshots/builds/
* https://devstudio.redhat.com/11/staging/updates/
* https://devstudio.redhat.com/11/staging/builds/
* https://devstudio.redhat.com/11/development/updates/ (copy content from 10.0/development/ site)
* https://devstudio.redhat.com/11/stable/updates/ (copy content from 10.0/stable/ site)

== Update Web Tools Server Adapter Discovery plugin w/ link to new URL

Every year the WTP Server Adapter discovery plugin needs to be updated to point to the new year's JBoss Tools stuff.

See https://issues.jboss.org/browse/JBIDE-24080 and https://bugs.eclipse.org/513578

In addition to making the change in the webtools project, the destination folder must also ezist as a valid update site.

Initially, this will be a symlink to the latest CI build or last year's stable site (if no CI available). Once a stable is available, the symlink then needs to be updated. So in order, the symlinks from http://download.jboss.org/jbosstools/updates/webtools/oxygen/ could be:

* http://download.jboss.org/jbosstools/neon/stable/updates/
* http://download.jboss.org/jbosstools/oxygen/snapshots/updates/ (once available)
* http://download.jboss.org/jbosstools/oxygen/development/updates/ (once first AM milestone is released)
* http://download.jboss.org/jbosstools/oxygen/stable/updates/ (once first GA/Final is released)

== Update ide-config.properties

With the maintenance branch moving from master to 4.4.x links need to be updated.

Eg., https://github.com/jbosstools/jbosstools-download.jboss.org/pull/623

We then also need to add entries for 4.5/11 snapshots.

Eg., https://github.com/jbosstools/jbosstools-download.jboss.org/commit/ce5c4c29a8dfdf809643dbe03746250591894800

Once 4.4.4.Final/10.4.0.GA are done, we can then update ide-config.*-fragment.properties to include staging and development URLs for 4.5/11.

== More?

There are probably more steps to be done. This doc is a work in progress and more will be added here as they are remembered/needed.
