= Release JBoss Developer Studio Development Milestone

This document describe how to publish a valid JBoss Developer Studio build to production after being verified by QE.

= Prerelease Steps

These steps can be done before the actual release (eg., on the Thurs or Fri before the Monday release, as long as QE has more-or-less signed off). Check with QE before proceeding.

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten. 

Send an email to jbosstools-dev@ and jboss-devstudio-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Rename artifacts to remove timestamp and buildID

To comply with Goldengate URL rules, we need to rename artifacts before they go to the CSP. For example
`jboss-devstudio-9.1.0.Beta1-v20151002-2235-B124-installer-eap.jar` must be renamed to `jboss-devstudio-9.1.0.Beta1-installer-eap.jar`.

Connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then:

[source,bash]
----
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...
pushd /qa/services/http/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/
for f in $(ls *latest*); do echo "rm $f"; rm -f $f; done
for f in $(ls jboss-devstudio-${version}-* | grep -v latest); do g=$(echo $f | sed s#-v[[:digit:]]*-[[:digit:]]*-B[[:digit:]]*##); echo "mv $f $g"; mv $f $g; done
touch *
chmod +x *.jar
ls -l
popd
----

== Verify install instructions are correct

Look at the .txt and .html files in /qa/services/http/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/ 

Verify that they contain correct install/usage instructions & versions.

If anything is wrong, fix it by hand, then also commit your changes to the templates. 

https://github.com/jbdevstudio/jbdevstudio-product/commit/3827045dca85e73c5ae339cc13f514591e3c1835
https://github.com/jbdevstudio/jbdevstudio-product/commit/e6c2954207d1db7451f7adfd2d89c7ceccd6adbe

== Submit JIRA and PR to update https://www.jboss.org/products/devstudio/

Goal is to update the following pages: https://www.jboss.org/products/devstudio/download/ and https://www.jboss.org/products/devstudio/overview/

* Open a JIRA: https://issues.jboss.org/secure/CreateIssue.jspa?pid=12313621&issuetype=3 
* Past example: https://issues.jboss.org/browse/DEVELOPER-1410, https://issues.jboss.org/browse/DEVELOPER-1403, https://issues.jboss.org/browse/DEVELOPER-1371
* Attach a pull request for https://github.com/jboss-developer/www.jboss.org/blob/master/products/devstudio/_common/product.yml_
* Past example: https://github.com/jboss-developer/www.jboss.org/pull/970, https://github.com/jboss-developer/www.jboss.org/pull/929

Once you have the JIRA, you can link to it when sending the note to release-engineering@ below.

== Announce internally for push to CSP staging site

First thing is to ask for availability of the binaries to CSP (Red Hat Customer Portal) and Golden Gate (JBoss products portal).

NOTE: As this takes some time and can be easily cancelled, this step can be anticipated a few days before release.

*To* release-engineering@redhat.com +
and +
*Cc* cobrien@redhat.com, ldimaggi@redhat.com, mhusnain@redhat.com, jpallich@redhat.com, nboldt@redhat.com, mistria@redhat.com, alkazako@redhat.com, manderse@redhat.com, bsutter@redhat.com, pmuir@redhat.com, paul.robinson@redhat.com, dcoughli@redhat.com +

[source,bash]
----
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...
JIRA=-1453

if [[ ${version} != ${versionWithRespin} ]]; then
  versionFriendlyName="${version} (to be renamed from ${versionWithRespin})"
else
  versionFriendlyName="${version}"
fi
echo "
Subject: 

JBoss Developer Studio ${versionFriendlyName} available for push to CSP staging server

Body:

JBoss Developer Studio ${versionFriendlyName} is available to push to CSP staging server, for subsequent smoke test & review by QE.

Please include the 5 jars/zips listed here:

* http://www.qa.jboss.com/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/

Please include the pre-generated the HTML and text content in the above folder when creating new CSP pages.

We will also need GoldenGate links for the 5 artifacts above, as they need to be linked from these pages:

* https://www.jboss.org/products/devstudio/overview/
* https://www.jboss.org/products/devstudio/download/

Please provide the GoldenGate links on this JIRA:

* https://issues.jboss.org/browse/DEVELOPER${JIRA}

Only ONE of those artifacts [0] require sign in, as it bundles EAP. The rest are free. 

[0] jboss-devstudio-*-installer-eap.jar 

When pushed, please reply so that QE can review the CSP pages & files for push to production.

Note that in addition to the new CSP page, eg., [1] or [2], the CSP landing page [3] should also be updated to point to the latest release.

[1] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=${version}
[2] https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jbossdeveloperstudio&version=9.1.0
[3] https://access.redhat.com/downloads/

Thanks in advance,

"

----

As an answer, you get the links to the GoldenGate files, eg., /content/origin/files/sha256/2c/2c92b68d122db901e3acbb74f06950116f4fe29402c25f4391761f9a93e65bba/jboss-devstudio-9.1.0.Beta1-updatesite-core.zip

Communicate with Paul Robinson / Daniel Coughlin, Chris O'Brien, etc. to coordinate the release. All the above can happen in parallel / before the updates below.

= Release steps

Once QE has signed off, and bits are staged to CSP, you can proceed w/ the rest of the release.

== Copy from /staging/ into /development/

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then copy the latest JBDS artifacts:

* installer
* target platforms & zips
* update sites & zips
* discovery sites

[source,bash]
----
#TODO: https://issues.jboss.org/browse/JBIDE-20904 script this and run as Jenkins job

# can run these 4 steps in parallel to save time


# copy JBDS update site (> 800M)
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...
tmpdir=/tmp/release_${version}_update_site
quals="development"; if [[ ${version##*GA} == "" ]]; then quals="development stable"; fi
for site in core; do
  mkdir -p ${tmpdir}/9.0/development/updates/${site}/${version}
  # rename from staging/*/versionWithRespin to development/*/version/
  rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/9.0/development/updates/${site}/${version}/
  # push to remote
  for qual in $quals; do
    echo "mkdir ${site} | sftp ${JBDS}/9.0/${qual}/updates/"
    echo "mkdir ${version} | sftp ${JBDS}/9.0/${qual}/updates/${site}"
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/9.0/development/updates/${site}/${version} ${JBDS}/9.0/${qual}/updates/${site}/
  done
done
rm -fr $tmpdir
echo "copy JBDS update site" | grep "copy JBDS update site"


# copy Central/EA/Discovery sites (< 8M), and update metadata refs in discovery sites
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...
quals="development"; if [[ ${version##*GA} == "" ]]; then quals="development stable"; fi
for site in central earlyaccess discovery.central discovery.earlyaccess; do
  tmpdir=/tmp/release__${site}__${version}
  mkdir -p ${tmpdir}/9.0/development/updates/${site}/${version}
  # rename from staging/*/versionWithRespin to development/*/version/
  rsync -arzq --rsh=ssh --protocol=28 ${JBDS}/9.0/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/9.0/development/updates/${site}/${version}/
  for qual in $quals; do
    # sed .xml files to point at /${qual}/ instead of /staging/, and ${version} instead of $versionWithRespin}
    if [[ ${site/discovery/} != ${site} ]]; then 
      pushd ${tmpdir}/9.0/development/updates/${site}/${version}/ >/dev/null
      now=`date +%s000`
      for c in compositeContent.xml compositeArtifacts.xml; do 
        sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
        sed -i -e "s#staging#${qual}#" $c
        sed -i -e "s#${versionWithRespin}#${version}#" $c
      done
      cat compositeContent.xml | egrep "staging|${qual}|${version}|${versionWithRespin}"
      popd >/dev/null
    fi
    # push to remote
    echo "mkdir ${site}" | sftp ${JBDS}/9.0/${qual}/updates/
    echo "mkdir ${version}" | sftp ${JBDS}/9.0/${qual}/updates/${site}
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/9.0/development/updates/${site}/${version} ${JBDS}/9.0/${qual}/updates/${site}/
  done
  rm -fr $tmpdir
done
echo "copy Central/EA/Discovery sites" | grep "copy Central/EA/Discovery sites"


# copy 6 zips & SHAs
# jboss-devstudio-9.0.0.CR2b-target-platform-central.zip           jboss-devstudio-9.0.0.CR2b-target-platform.zip          jboss-devstudio-9.0.0.CR2b-updatesite-core.zip
# jboss-devstudio-9.0.0.CR2b-target-platform-earlyaccess.zip       jboss-devstudio-9.0.0.CR2b-updatesite-central.zip       jboss-devstudio-9.0.0.CR2b-updatesite-earlyaccess.zip
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...
tmpdir=/tmp/release_${version}_zips
quals="development"; if [[ ${version##*GA} == "" ]]; then quals="development stable"; fi
for site in core; do
  mkdir -p ${tmpdir}/9.0/development/updates/${site}
  # get zips
  rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/staging/updates/${site}/jboss-devstudio-${versionWithRespin}*.zip* ${tmpdir}/9.0/development/updates/${site}/
  for qual in $quals; do
    echo "mkdir ${site}" | sftp ${JBDS}/9.0/${qual}/updates/
    # rename from staging/*/versionWithRespin/ to ${qual}/*/version/
    for zip in ${tmpdir}/9.0/development/updates/${site}/jboss-devstudio-${versionWithRespin}*.zip*; do
      zipNew=${zip/${versionWithRespin}/${version}}; echo $zipNew
      zipNew=${zipNew##*/}; echo $zipNew
      rsync -aPrz --rsh=ssh --protocol=28 ${zip} ${JBDS}/9.0/${qual}/updates/${site}/${zipNew}
    done
  done
done
rm -fr $tmpdir
echo "copy zips & SHAs" | grep "copy zips & SHAs"


# copy installer jar
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...
tmpdir=/tmp/release_${version}_installer
quals="development"; if [[ ${version##*GA} == "" ]]; then quals="development stable"; fi
for site in builds; do
  mkdir -p ${tmpdir}/9.0/development/${site}/installer/${version}
  # rename from staging/*/versionWithRespin to development/*/version/
  rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/staging/${site}/devstudio-${versionWithRespin}-build-product/latest/all/jboss-devstudio-*.jar* ${tmpdir}/9.0/development/${site}/installer/${version}
  # push to remote
  for qual in $quals; do
    echo "mkdir ${site}" | sftp ${JBDS}/9.0/${qual}/
    echo "mkdir installer" | sftp ${JBDS}/9.0/${qual}/${site}
    echo "mkdir ${version}" | sftp ${JBDS}/9.0/${qual}/${site}/installer
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/9.0/development/${site}/installer/${version} ${JBDS}/9.0/${qual}/${site}/installer/
  done
done
rm -fr $tmpdir
echo "copy installer jar" | grep "copy installer jar"


#  verify sites are correctly populated (run locally, not on dev01):
version=9.1.0.Beta1
tmpfile=/tmp/devstudio-staging__verify.txt
quals="development"; if [[ ${version##*GA} == "" ]]; then quals="development stable"; fi
for site in site central-site earlyaccess-site; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  for qual in $quals; do
    echo "https://devstudio.redhat.com/9.0/${qual}/updates/${sitename}/${version}/ " >> $tmpfile
  done
done
for site in discovery.central discovery.earlyaccess; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  for qual in $quals; do
    echo "https://devstudio.redhat.com/9.0/${qual}/updates/${sitename}/${version}/ " >> $tmpfile
  done
done
# zip & installers
for qual in $quals; do
  echo "https://devstudio.redhat.com/9.0/${qual}/updates/core/#_____(6_zips_+_SHAs,_and_${version}_folder) " >> $tmpfile
  echo "https://devstudio.redhat.com/9.0/${qual}/builds/installer/${version}/ " >> $tmpfile
done
echo "" >> $tmpfile
cat $tmpfile && firefox `cat $tmpfile` && rm -fr $tmpfile


----

== Update https://devstudio.redhat.com/9.0/development/updates/

To update the content in https://devstudio.redhat.com/9.0/development/updates/ ...

[source,bash]
----
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...

# adjust these steps to fit your own path location & git workflow
cd ~/truu
pushd jbdevstudio-website/content/9.0/
git fetch origin master
git checkout FETCH_HEAD

# merge updates in 9.0/staging/updates/ into 9.0/development/updates/
rsync -aPrz staging/updates/*.*ml development/updates/

# sed *.*ml files to point at /development/ instead of /staging/, and ${version} instead of $versionWithRespin}
pushd development/updates/ >/dev/null
now=`date +%s000`
for c in compositeContent.xml compositeArtifacts.xml index.html; do 
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
  sed -i -e "s#staging#development#" $c
  sed -i -e "s#${versionWithRespin}#${version}#" $c
done
git status -s
egrep "staging|development|${version}|${versionWithRespin}" index.html
echo "------------"
egrep "staging|development|${version}|${versionWithRespin}" compositeContent.xml

# update EA site
pushd earlyaccess >/dev/null
rm -f composite*.xml
wget https://devstudio.redhat.com/9.0/development/updates/discovery.earlyaccess/${version}/compositeContent.xml
wget https://devstudio.redhat.com/9.0/development/updates/discovery.earlyaccess/${version}/compositeArtifacts.xml
echo "------------"
egrep "staging|development|${version}|${versionWithRespin}" compositeContent.xml
popd >/dev/null

popd >/dev/null

# commit changes to git
git add development/updates/
git commit -m "release JBDS ${version} (${versionWithRespin}) to production" development/updates/
git push origin HEAD:master

# push changes to server
rsync -Pzrlt --rsh=ssh --protocol=28 development/updates/*.*ml $JBDS/9.0/development/updates/
rsync -Pzrlt --rsh=ssh --protocol=28 development/updates/earlyaccess/*.*ml $JBDS/9.0/development/updates/earlyaccess/

# done
popd >/dev/null

# review changes
firefox \
https://devstudio.redhat.com/9.0/development/updates/ \
https://devstudio.redhat.com/9.0/development/updates/earlyaccess/ \
https://devstudio.redhat.com/9.0/development/updates/compositeContent.xml \
https://devstudio.redhat.com/9.0/development/updates/earlyaccess/compositeContent.xml 

----

NOTE: If this is a GA release, merge these changes into 9.0/stable/ too.


== Release the latest milestone to ide-config.properties

Check out this file: http://download.jboss.org/jbosstools/configuration/ide-config.properties from _http://github.com/jbosstools/jbosstools-download.jboss.org_ repository.

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----
# adjust these steps to fit your own path location & git workflow
cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...

git fetch origin master
git checkout FETCH_HEAD

# then edit ide-config.properties 
# vim ide-config.properties 
st ide-config.properties 

# verify
firefox \
https://devstudio.redhat.com/9.0/development/updates/discovery.central/${version}/devstudio-directory.xml \
https://devstudio.redhat.com/9.0/development/updates/ \
https://devstudio.redhat.com/9.0/development/updates/compositeContent.xml \
https://devstudio.redhat.com/9.0/development/updates/earlyaccess/ \
https://devstudio.redhat.com/9.0/development/updates/earlyaccess/compositeContent.xml \
https://devstudio.redhat.com/9.0/development/updates/discovery.earlyaccess/${version}/devstudio-earlyaccess.properties

# commit the change and push to master
ci "release JBDS ${version} (${versionWithRespin}) to public: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
rsync -Pzrlt --rsh=ssh --protocol=28 ide-config.properties $TOOLS/configuration/ide-config.properties
popd

----

== Submit PR to update tools.jboss.org

Provide a PR to add the latest JBDS milestones to this listing:

https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml_

Examples: 

* https://github.com/jbosstools/jbosstools-website/pull/418 (JBT / JBDS Beta1)
* https://github.com/jbosstools/jbosstools-website/pull/449 (JBT Beta2)
* https://github.com/jbosstools/jbosstools-website/pull/489 (JBDS CR2)
* https://github.com/jbosstools/jbosstools-website/pull/513 (JBDS GA)

==== SHA256 values 

To get the SHA256 values for easy pasting into the product.yml file, first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then run this:

[source,bash]
----
version=9.1.0.Beta1
versionWithRespin=9.1.0.Beta1a # a, b, c...

cd ~/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/
for f in *.jar *.zip; do 
  size=$(du -h $f); size=${size%*M*};
  sha=$(cat ${f}.sha256); sh=${sha:0:2};  
  echo "            url: http://www.redhat.com/j/elqNow/elqRedir.htm?ref=http://www.jboss.org/download-manager/content/origin/files/sha256/${sh}/${sha}/${f}" >> /tmp/yml.txt
  echo "            file_size: ${size}MB" >> /tmp/yml.txt
done
cd /tmp
f=jboss-devstudio-${version}-target-platform.zip
size=$(wget https://devstudio.redhat.com/9.0/development/updates/core/ --no-check-certificate -q -O - | egrep jboss-devstudio-${version}-target-platform.zip | egrep -v sha256 | sed "s#.\+>\([0-9]\+M\)</td.\+#\1#")
# sha=$(wget https://devstudio.redhat.com/9.0/development/updates/core/${f}.sha256 --no-check-certificate -q -O -); sh=${sha:0:2}
echo "            url: https://devstudio.redhat.com/9.0/development/updates/core/${f}" >> /tmp/yml.txt
echo "            file_size: ${size}B" >> /tmp/yml.txt
done
cat /tmp/yml.txt; rm -f /tmp/yml.txt

----

Commit changes and submit PR.


== Tag Git

Once cloned to disk, this script will create the tags if run from the location with your git clones. If tags exist, no new tag will be created.

[source,bash]
----

# if not already cloned, the do this:
git clone https://github.com/jbdevstudio/jbdevstudio-product
git clone https://github.com/jbdevstudio/jbdevstudio-ci
git clone https://github.com/jbdevstudio/jbdevstudio-website
git clone https://github.com/jbdevstudio/jbdevstudio-artwork
git clone https://github.com/jbdevstudio/jbdevstudio-devdoc

jbt_branch=jbosstools-4.3.x
version=9.1.0.Beta1
for d in product ci website artwork devdoc; do
  echo "====================================================================="
  echo "Tagging jbdevstudio-${d} from branch ${jbt_branch} as tag ${version}..."
  pushd jbdevstudio-${d}
  git fetch origin ${jbt_branch}
  git tag jbdevstudio-${version} FETCH_HEAD
  git push origin jbdevstudio-${version}
  echo ">>> https://github.com/jbdevstudio/jbdevstudio-${d}/tree/jbdevstudio-${version}"
  popd >/dev/null 
  echo "====================================================================="
  echo ""
done

----

== Commit updates to release guide (including this document):

[source,bash]
----

version=9.1.0.Beta1
cd jbdevstudio-devdoc/release_guide/9.x
git commit -m "update release guide for ${version}" .
git push origin HEAD:master

----


== Update Marketplace entry

WARNING: Only applies to Beta and better versions.
NOTE: for 9.1.*, we will skip this step until GA (no Betas)!

=== If node doesn't exist yet

Create a new node on Marketplace, listing the single "BYOE" feature, com.jboss.devstudio.core.feature

=== If node already exists

Access it via +http://marketplace.eclipse.org/content/red-hat-jboss-developer-studio/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Notes / warnings (if applicable, eg., JDK issues)

== Mark release as complete in JIRA

If there are no unresolved issues, release the milestone version in JIRA.

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

[source,bash]
----

firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions

----

== Smoke test the release

Before notifying team of release, must check for obvious problems. Any failure there should be fixed with highest priority. In general, it could be wrong URLs in a composite site.

=== Validate update site install (BYOE)

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install BYOE category from https://devstudio.redhat.com/9.0/development/updates/ and/or https://devstudio.redhat.com/9.0/stable/updates/
3. Restart. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

=== Validate installer install

1. Download JBDS installer from https://devstudio.redhat.com/9.0/development/builds/installer/ or https://devstudio.redhat.com/9.0/stable/builds/installer/
2. Install via UI or headlessly with `java -jar jboss-devstudio-*.jar -console -options /dev/null`
3. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----

version=9.1.0.Beta1
qual="development"; if [[ ${version##*GA} == "" ]]; then qual="stable"; fi
cd /tmp
wget https://devstudio.redhat.com/9.0/${qual}/builds/installer/${version}/
installerJar=$(cat index.html | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/9.0/${qual}/builds/installer/${version}/${installerJar}

----

=== Validate Marketplace install

1. Get a compatible Eclipse
2. Install from Marketplace
3. Install everything from Central + Earlyaccess
4. Test a project example

== Enable jobs

TODO: JBIDE-21407 verify this process is fleshed out for Beta2 staging/release

NOTE: This should have been done after staging, but just in case it was not, here's a reminder.

As you have just released something, the next build will be a CI snapshot for the following milestone.

Thus, you need to:

* re-enable jobs that were disabled during staging
* set correct github branch, eg., switch from 4.3.1.Beta2x to 4.3.x
* upversion dependencies, eg., releng scripts move from version Beta2 to CR1 (if that's been released)
* upversion target platforms / Central version (if those have been released)


== Notify the team lead

____

*To:* alkazako@redhat.com +
*Cc:* max.andersen@redhat.com, fbricon@redhat.com +

[source,bash]
----
version_JBT=4.3.1.Beta1
version=9.1.0.Beta1
qual=development # development or stable
pullrequestURL=https://github.com/jbosstools/jbosstools-website/pull/540
blogURL=/blog/beta1-for-mars2.html

echo "
Subject: 

Ready for JBoss Developer Studio ${version} blog & announcement

Body:

Here's a PR for adding ${version} JBoss Tools download page:

${pullrequestURL}

Suggested blog filename: ${blogURL}

Below is a sample email you could send to these 4 sets of recipients when the blog is live. 
Do not cross-post to both internal and external lists! Better to send 4 separate (identical) emails.

To: jbosstools-dev@lists.jboss.org 
To: jboss-devstudio-list@redhat.com 
To: jboss-announce@redhat.com (optional for major milestones, recommended for GA releases) 
To: gss-support-readiness@redhat.com, dgeoffro@redhat.com, mmusaji@redhat.com (for all GA releases (major, minor, maintenance) ONLY)

--

Subject:

JBoss Developer Studio ${version} is available

Body:

JBoss Developer Studio ${version} is available!

Download page: https://www.jboss.org/products/devstudio/overview/

Update site: https://devstudio.redhat.com/9.0/${qual}/updates/

Eclipse Marketplace: https://marketplace.eclipse.org/content/red-hat-jboss-developer-studio-mars

Blog Announcement: http://tools.jboss.org/blog/

New + Noteworthy: http://tools.jboss.org/documentation/whatsnew/jbosstools/${version_JBT}.html

--

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBDS#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

"
----
____

