= Publishing JBDS Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

TODO: use consistent instructions for fetching sources from git & pushing changes
TODO: add step that automatically keeps all staged builds in Jenkins, using /lastBuild/toggleLogKeep

== Update Discovery Sites and URLs

See details in JBT_Staging_For_QE.adoc


== Verify correct version set in com.jboss.devstudio.central.core

Check c.j.d.central.core's currentversion.properties for the correct value of default.version

[sources,bash]
----
# @since JBT 4.3.0 / JBDS 9.0.0 - JBIDE-18820, JBIDE-18806

version=9.1.0.CR1 # or .GA
versionWithRespin=9.1.0.CR1 # a, b, c...

if [[ ${version:0:1} == "4" ]]; then # JBT
  pluginName=foundation.core
  updatesiteURL=http://download.jboss.org/jbosstools/mars/staging/updates/core/${versionWithRespin}/plugins/
  updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/4.3.mars/plugins/
  #updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/master/plugins/
else
  pluginName=core.central
  updatesiteURL=https://devstudio.redhat.com/9.0/staging/updates/core/${versionWithRespin}/plugins/
  updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/4.3.mars/plugins/
  #updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/master/plugins/
fi
pushd /tmp; wget -q -nc $updatesiteURL
thejars=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort`
echo "Found: $thejars" | egrep ${pluginName}
thejar=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort | tail -1; rm -f index.html`
echo ${updatesiteURL}/${thejar} | egrep ${pluginName}
wget -q -nc ${updatesiteURL}/${thejar}
theversion=`unzip -p ${thejar} */currentversion.properties | grep version= | sed -e "s/version=//" | tail -1`; theversion=${theversion/-SNAPSHOT/} # remove -SNAPSHOT suffix from version
rm -f ${thejar}
popd
echo "In ${pluginName}, want ${version}, got $theversion" | egrep "${pluginName}|${version}"

----

If value found above for `$theversion` != current release version, then you need to rebuild foundation or JBDS w/ a new value inserted.


== Disable jobs

All stable branch jobs from the https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/[9.0.mars view] should be disabled, EXCEPT the integration tests job (not published as part of the release and continues to be updated during staging):

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-integration-tests.aggregate_4.3.mars/

Quick way to do so is with https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py[toggleJenkinsJobs.py]. See https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py.examples.txt[usage examples].

Should a respin be needed, they can be re-enabled at that time.

== Variables to use

Whenever you're starting a new shell, you should set those variables:

[sources,bash]
----
version=9.1.0.CR1
versionWithRespin=9.1.0.CR1 # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.52.0.CR1-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.52.0.CR1-SNAPSHOT
now=$(date +%s000)
isGA=false
JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
----

== Stage to qa.jboss.org

*qa.jboss.org* is actually mapped to folder +/qa/services/http/binaries/RHDS+ accessible from CI machines (such as dev01.mw.lab.eng.bos.redhat.com). So first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then copy the latest JBDS artifacts:

* installer
* target platforms & zips
* update sites & zips
* discovery sites

WARNING: Don't use symlinks are they are too risky to use. Those operations can be done in parallel (using multiple terminals is the easiest way)

=== Push installers, update site, and discovery site

[source,bash]
----
# can run these 6 steps in parallel

# 1. copy JBDS target platform zips
versionWithRespin=9.1.0.CR1 # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.52.0.CR1-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.52.0.CR1-SNAPSHOT
for targetname in jbdevstudio jbtcentral jbtearlyaccess; do
  if [[ ${targetname} == "jbdevstudio" ]]; then
    TARGET_PLATFORM_VERSION=${TARGET_PLATFORM_VERSION_MAX}
    suffix="-target-platform"
  else
    TARGET_PLATFORM_VERSION=${TARGET_PLATFORM_CENTRAL_MAX}
    suffix="-target-platform-${targetname:3}"
  fi
  y=/qa/services/http/binaries/RHDS/targetplatforms/${targetname}target/${TARGET_PLATFORM_VERSION}/${targetname}target-${TARGET_PLATFORM_VERSION}.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${y} ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${versionWithRespin}${suffix}.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${y}.sha256 ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${versionWithRespin}${suffix}.zip.sha256
done
echo "DONE: copy JBDS target platform zips" | grep "copy JBDS target platform zips"


# 2. copy JBDS Central/EA update sites & zips
versionWithRespin=9.1.0.CR1 # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
JBT_stream=4.3.mars
for site in central-site earlyaccess-site; do
  ID=""
  ID=$(echo "ls 20*" | sftp ${TOOLS}/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${JBT_stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/devstudio-staging__${site}_${JBT_stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${JBT_stream}/${ID}/* ${tmpdir}/
    # copy build folder
    echo "mkdir devstudio-${versionWithRespin}-build-${sitename}" | sftp ${JBDS}/9.0/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${JBDS}/9.0/staging/builds/devstudio-${versionWithRespin}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp ${JBDS}/9.0/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* ${JBDS}/9.0/staging/updates/${sitename}/${versionWithRespin}/
    # copy update site zip
    y=${tmpdir}/all/repository.zip
    suffix=-updatesite-${sitename}
    rsync -aPrz --rsh=ssh --protocol=28 ${y} ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${versionWithRespin}${suffix}.zip
    rsync -aPrz --rsh=ssh --protocol=28 ${y}.sha256 ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${versionWithRespin}${suffix}.zip.sha256
    du -sh $tmpdir
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done
echo "DONE: copy JBDS Central/EA update sites & zips" | grep "copy JBDS Central/EA update sites & zips"


# 3. copy JBDS installers: snapshots/builds/ to staging/builds/ [INTERNAL - both installers]
versionWithRespin=9.1.0.CR1 # a, b, c...
JBDS_stream=9.0.mars
ID=""
ID=$(cd /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${JBDS_stream} && ls 20* | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%:*}
if [[ $ID ]]; then
  echo "Latest build for installers: ${ID}"
  tmpdir=/tmp/jboss-devstudio-${versionWithRespin}-build-product_INTERNAL__${ID}
  # copy build folder
  mkdir -p /qa/services/http/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/${ID}/
  rsync -aPrz --rsh=ssh --protocol=28 /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${JBDS_stream}/${ID}/* /qa/services/http/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/${ID}/ --exclude="repo"
  # create latest symlinks
  mkdir -p ${tmpdir}; pushd $tmpdir >/dev/null; ln -s ${ID} latest
    rm -f /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${JBDS_stream}/latest
    rsync --protocol=28 -l latest /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${JBDS_stream}/
    rm -f /qa/services/http/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest
    rsync --protocol=28 -l latest /qa/services/http/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/
  popd >/dev/null
  du -sh $tmpdir
  rm -fr $tmpdir
else
  echo "ERROR: no latest build found for installers" | grep ERROR
fi
echo "DONE: copy JBDS installers: snapshots/builds/ to staging/builds/ [INTERNAL - both installers]" | egrep "copy JBDS installers|INTERNAL"


# 4. copy JBDS installers: snapshots/builds/ to staging/builds/ [EXTERNAL - Standalone installer only]
versionWithRespin=9.1.0.CR1 # a, b, c...
JBDS_stream=9.0.mars
ID=""
ID=$(echo "ls 20*" | sftp ${JBDS}/9.0/snapshots/builds/devstudio.product_${JBDS_stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
if [[ $ID ]]; then
  echo "Latest build for installer: ${ID}"
  # copy build folder
  tmpdir=/tmp/jboss-devstudio-${versionWithRespin}-build-product_EXTERNAL__${ID}
  rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/snapshots/builds/devstudio.product_${JBDS_stream}/${ID}/* ${tmpdir}/ --exclude="repo"
  # copy standalone installer
  echo "mkdir devstudio-${versionWithRespin}-build-product" | sftp ${JBDS}/9.0/staging/builds/
  rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${JBDS}/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/${ID}/ --exclude="repo"
  # create latest symlink
  mkdir -p ${tmpdir}; pushd $tmpdir >/dev/null; ln -s ${ID} latest; rsync --protocol=28 -l latest ${JBDS}/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/; rm -f latest; popd >/dev/null
  du -sh $tmpdir
  rm -fr $tmpdir
else
  echo "ERROR: no latest build found for installer" | grep ERROR
fi
echo "DONE: copy JBDS installers: snapshots/builds/ to staging/builds/ [EXTERNAL - Standalone installer only]" | egrep "copy JBDS installers|EXTERNAL"


# 5. copy JBDS update: snapshots/builds/*/repo/* to staging/updates/core/${versionWithRespin}; also copy updatesite-core.zip
versionWithRespin=9.1.0.CR1 # a, b, c...
JBDS_stream=9.0.mars
ID=""
ID=$(cd /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${JBDS_stream} && ls 20* | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%:*}
sitename="core"
# copy update site
echo "mkdir ${sitename}" | sftp ${JBDS}/9.0/staging/updates/
rsync -aPrz --rsh=ssh --protocol=28 /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${JBDS_stream}/${ID}/all/repo/* ${JBDS}/9.0/staging/updates/${sitename}/${versionWithRespin}/

# don't copy the "latest" symlink, just the actual file
y=$(find /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${JBDS_stream}/${ID}/all/ -name "jboss-devstudio-*-updatesite-core.zip" -a -not -name "*latest*")
rsync -aPrz --rsh=ssh --protocol=28 ${y} ${JBDS}/9.0/staging/updates/${sitename}/jboss-devstudio-${versionWithRespin}-updatesite-core.zip
rsync -aPrz --rsh=ssh --protocol=28 ${y}.sha256 ${JBDS}/9.0/staging/updates/${sitename}/jboss-devstudio-${versionWithRespin}-updatesite-core.zip.sha256
echo "DONE: copy JBDS update: snapshots/builds/*/repo/* to staging/updates/core/${versionWithRespin}; also copy updatesite-core.zip" | grep "copy JBDS update"


# TODO: make sure you've rebuilt the discovery sites and disabled the job first before doing this step!
# 6. copy JBDS discovery sites to staging/builds/ and staging/updates/
versionWithRespin=9.1.0.CR1 # a, b, c...
JBT_stream=4.3.mars
for site in discovery.central discovery.earlyaccess; do
  ID=""
  ID=$(echo "ls 20*" | sftp ${JBDS}/9.0/snapshots/builds/jbosstools-${site}_${JBT_stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/devstudio-staging__${site}_${JBT_stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/snapshots/builds/jbosstools-${site}_${JBT_stream}/${ID}/* ${tmpdir}/
    # copy build folder (and rename from jbosstools to devstudio)
    echo "mkdir devstudio-${versionWithRespin}-build-${sitename}" | sftp ${JBDS}/9.0/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${JBDS}/9.0/staging/builds/devstudio-${versionWithRespin}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp ${JBDS}/9.0/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* ${JBDS}/9.0/staging/updates/${sitename}/${versionWithRespin}/
    du -sh $tmpdir
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done
echo "DONE: copy JBDS discovery sites to staging/builds/ and staging/updates/" | grep "copy JBDS discovery sites to staging/builds/ and staging/updates/"

----

Verify sites are correctly populated (run locally, not on dev01).

Note that Akamai caching might result in the appearance of missing files (apache directories may look incomplete) but if you ping specific files, they should be there.

[source,bash]
----

versionWithRespin=9.1.0.CR1 # a, b, c...
tmpfile=/tmp/jbosstools-staging__verify.txt
for site in central earlyaccess discovery.central discovery.earlyaccess; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-${sitename}/ " >> $tmpfile
  echo "https://devstudio.redhat.com/9.0/staging/updates/${sitename}/${versionWithRespin}/ " >> $tmpfile
done
echo "https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/ " >> $tmpfile
echo "http://www.qa.jboss.com/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/ " >> $tmpfile
echo "https://devstudio.redhat.com/9.0/staging/builds/#_____(5_folders_w/_${versionWithRespin}) " >> $tmpfile
echo "https://devstudio.redhat.com/9.0/staging/updates/core/#_____(6_zips,_6_sums,_1_folder_w/_${versionWithRespin}) " >> $tmpfile
echo "" >> $tmpfile
cat $tmpfile
firefox `cat $tmpfile`
popd >/dev/null
rm -fr $tmpfile

----

=== Cleanup OLD builds

First, use sshfs to mount filemgmt file paths.

[source,bash]
----

JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
sshfs $JBDS /media/JBDS-ssh

----

Then move old builds into an OLD/ folder to they're less visible and ready for deletion later.

[source,bash]
----
version_PREV=9.1.0.Beta2 # a, b, c...
for d in updates/core updates/central updates/earlyaccess updates/discovery.central updates/discovery.earlyaccess builds; do
  if [[ -d /media/JBDS-ssh/9.0/staging/${d}/ ]]; then
    echo "${d}/*${version_PREV}* ..."
    mkdir -p /media/JBDS-ssh/9.0/staging/${d}/OLD/
    mv /media/JBDS-ssh/9.0/staging/${d}/*${version_PREV}* /media/JBDS-ssh/9.0/staging/${d}/OLD/
  fi
done

----

=== Update https://devstudio.jboss.com/9.0/staging/updates/

This should point to the latest staging bits. Just copy what's in discovery.central/composite*.xml into this folder.

[source,bash]
----

version=9.1.0.CR1
versionWithRespin_PREV=9.1.0.Beta2a # a, b, c...
versionWithRespin=9.1.0.CR1 # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.52.0.CR1-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.52.0.CR1-SNAPSHOT

cd ~/truu
pushd jbdevstudio-website/content/9.0/staging/updates

git fetch origin master
git checkout FETCH_HEAD

for d in discovery.central discovery.earlyaccess; do
  mkdir -p ${d}/${versionWithRespin}/; pushd ${d}/${versionWithRespin}/
  rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/staging/updates/${d}/${versionWithRespin}/composite*xml ./
  # replace dl.jb.o and 4.3-> ds.rh.c and 9.0
  now=`date +%s000`
  for c in compositeContent.xml compositeArtifacts.xml; do
    sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
    # TODO: are these next 3 sed steps still needed?
      sed -i -e "s#http://download.jboss.org/jbosstools/mars/#https://devstudio.redhat.com/9.0/#" $c
      sed -i -e "s#http://download.jboss.org/jbosstools/targetplatforms/#https://devstudio.redhat.com/targetplatforms/#" $c
      sed -i -e "s#4\.3\.0#9\.0\.0#" $c
  done
  cat $c | egrep "${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${TARGET_PLATFORM_CENTRAL_MAX}|timestamp"
  popd
done
rsync discovery.central/${versionWithRespin}/composite*.xml ./

# update index.html
sed -i "s#${versionWithRespin_PREV}#${versionWithRespin}#" index.html
cat index.html | egrep "${versionWithRespin_PREV}|${versionWithRespin}"

# push changes to server
rsync -aPrz --rsh=ssh --protocol=28 discovery.central/${versionWithRespin}/composite*xml ${JBDS}/9.0/staging/updates/discovery.central/${versionWithRespin}/
rsync -aPrz --rsh=ssh --protocol=28 discovery.earlyaccess/${versionWithRespin}/composite*xml ${JBDS}/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/
rsync -aPrz --rsh=ssh --protocol=28 ./composite*xml ./index.html ${JBDS}/9.0/staging/updates/

# verify changes
echo "Check 4 URLs:"
firefox \
https://devstudio.redhat.com/9.0/staging/updates/discovery.central/${versionWithRespin}/compositeContent.xml \
https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/compositeContent.xml \
https://devstudio.redhat.com/9.0/staging/updates/compositeContent.xml \
https://devstudio.redhat.com/9.0/staging/updates/

rm -fr discovery.central/${versionWithRespin}/composite*.xml discovery.earlyaccess/${versionWithRespin}/composite*.xml

# commit the change and push to master
ci "release JBDS ${version} (${versionWithRespin}) to staging" .
git push origin HEAD:master

# done
popd

----

=== Merge in Integration Stack content

See details in Merge_IS_Discovery.adoc

== Release the latest staging site to ide-config.properties

See details in JBT_Staging_For_QE.adoc


== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install BYOE category from https://devstudio.redhat.com/9.0/staging/updates/
3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----
versionWithRespin=9.1.0.CR1 # a, b, c...
cd ~/tmp
wget https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/${installerJar}

java -jar ~/tmp/${installerJar}

----

0. After downloading and installing JBDS from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See details in JBT_Staging_For_QE.adoc


== Notify the team (send 1 email)
____
*To* jboss-devstudio-list@redhat.com +

[source,bash]
----
version_JBT=4.3.1.CR1
version=9.1.0.CR1
versionWithRespin=9.1.0.CR1 # a, b, c...
respin="respin-a"
echo "
Subject:

JBDS ${versionWithRespin} Core bits available for QE testing

Body:

As always, these are not FINAL bits, but preliminary results for QE testing. Not for redistribution to customers. Update sites are public; installers require VPN access.

Universal Installers:
* http://www.qa.jboss.com/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/ (EAP bundles; VPN required)
* https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/ (Standalone + other zips)

Update Sites:
* https://devstudio.redhat.com/9.0/staging/updates/ (includes ${versionWithRespin} Core + Target Platform + JBoss Central)
* https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/ (includes the above site + Early Access)

New + Noteworthy (subject to change):
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule / Upcoming Releases: https://issues.jboss.org/projects/JBDS?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page

"
if [[ $respin != "respin-" ]]; then
echo "

--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${version}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${version_JBT}%22%29%29%29

To compare the upcoming version of Central (${versionWithRespin}) against an older version, add lines similar to these your eclipse.ini file after the -vmargs line for the appropriate version & URLs:
 -Djboss.discovery.directory.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.central/${versionWithRespin}/devstudio-directory.xml
 -Djboss.discovery.site.url=https://devstudio.redhat.com/9.0/staging/updates/
 -Djboss.discovery.earlyaccess.site.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/
 -Djboss.discovery.earlyaccess.list.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/devstudio-earlyaccess.properties

"
fi


----
____
