= Publishing JBDS Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

TODO JBDS-3462: when releasing GA make sure to :%s/development/stable/g and :%s/9.0-staging/9.0/g

TODO: use consistent variables for version, versionWithRespin, previous, previousFull, versionWithRespin_PREV

TODO: use consistent instructions for fetching sources from git & pushing changes

TODO: use consistent instructions for updating ide-config.properties

== Update Discovery Sites and URLs

See details in JBT_Staging_For_QE.adoc


== Verify correct version set in com.jboss.devstudio.central.core

# @since JBT 4.3.0 / JBDS 9.0.0
# JBIDE-18820, JBIDE-18806 check the version set in c.j.d.central.core's currentversion.properties value of default.version
# TODO: verify that for Beta2, we only get ONE copy of the plugin, not multiple old (orphaned?) ones too.
version=9.0.0.Beta1 #a, b, c...
pluginName=core.central
updatesiteURL=https://devstudio.redhat.com/9.0/staging/updates/core/${version}/plugins/
updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/4.3.mars/plugins/
pushd /tmp; wget -q -nc $updatesiteURL
thejars=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort`
echo "Found: $thejars" | egrep ${pluginName}
thejar=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort | tail -1; rm -f index.html`
echo ${updatesiteURL}/${thejar} | egrep ${pluginName}
cd /tmp; wget -q -nc ${updatesiteURL}/${thejar}
theversion=`unzip -p ${thejar} */currentversion.properties | grep version= | sed -e "s/version=//" | tail -1`
rm -f ${thejar}
popd
echo "Want ${version}, got $theversion" | grep ${version}

# if value found above for $jbosstoolsversion != current release version, then you need to rebuild foundation or JBDS w/ a new value inserted.


== Disable jobs

All stable branch jobs from the https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/[9.0.mars view] should be disabled.

Quick way to do so is with https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py[toggleJenkinsJobs.py]. See https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py.examples.txt[usage examples].

Should a respin be needed, they can be re-enabled at that time.

== Variables to use

Whenever you're starting a new shell, you should set those variables:

[sources,bash]
----
versionWithRespin=9.0.0.Beta1b # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.50.0.Beta1-SNAPSHOT
CENTRAL_TARGET_VERSION=4.50.0.Beta1-SNAPSHOT
previousFull=9.0.0.Beta1a
now=$(date +%s000)
isGA=false
JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
----

== Stage to qa.jboss.org

*qa.jboss.org* is actually mapped to folder +/qa/services/http/binaries/RHDS+ accessible from CI machines (such as dev01.mw.lab.eng.bos.redhat.com). So first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then copy the latest JBDS artifacts:

* installer
* target platforms & zips
* update sites & zips
* discovery sites

WARNING: Don't use symlinks are they are too risky to use. Those operations can be done in parallel (using multiple terminals is the easiest way)

=== Push installers, update site, and discovery site

[source,bash]
----
# can run these 6 steps in parallel

# copy JBDS target platform zips
version=9.0.0.Beta1b # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.50.0.Beta1-SNAPSHOT
CENTRAL_TARGET_VERSION=4.50.0.Beta1-SNAPSHOT
for targetname in jbdevstudio jbtcentral jbtearlyaccess; do
  if [[ ${targetname} == "jbdevstudio" ]]; then
    TARGET_PLATFORM_VERSION=${TARGET_PLATFORM_VERSION_MAX}
    suffix="-target-platform"
  else
    TARGET_PLATFORM_VERSION=${CENTRAL_TARGET_VERSION}
    suffix="-target-platform-${targetname:3}"
  fi
  y=/qa/services/http/binaries/RHDS/targetplatforms/${targetname}target/${TARGET_PLATFORM_VERSION}/${targetname}target-${TARGET_PLATFORM_VERSION}.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${y} ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${version}${suffix}.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${y}.sha1 ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${version}${suffix}.zip.sha1
done


# copy JBT Central/EA update sites & zips
version=9.0.0.Beta1b # a, b, c...
stream=4.3.mars # NOT 9.0, use jbosstools stream here
for site in central-site earlyaccess-site; do
  ID=""
  ID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/devstudio-build-sites.aggregate.${site}_${stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream}/${ID}/* ${tmpdir}/
    # copy build folder
    echo "mkdir devstudio-${version}-build-${sitename}" | sftp ${JBDS}/9.0/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${JBDS}/9.0/staging/builds/devstudio-${version}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp ${JBDS}/9.0/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* ${JBDS}/9.0/staging/updates/${sitename}/${version}/
    # copy update site zip
    y=${tmpdir}/all/repository.zip
    suffix=-updatesite-${sitename}
    rsync -aPrz --rsh=ssh --protocol=28 ${y} ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${version}${suffix}.zip
    rsync -aPrz --rsh=ssh --protocol=28 ${y}.sha1 ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${version}${suffix}.zip.sha1
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done


# copy JBDS installers: snapshots/builds/ to staging/builds/ [INTERNAL - both installers]
version=9.0.0.Beta1b # a, b, c...
stream=9.0.mars
ID=""
ID=$(cd /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${stream} && ls 20* | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%:*}
if [[ $ID ]]; then
  echo "Latest build for installers: ${ID}"
  # copy build folder
  mkdir -p /qa/services/http/binaries/RHDS/9.0/staging/builds/jboss-devstudio-${version}-build-product/${ID}/
  rsync -aPrz --rsh=ssh --protocol=28 /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${stream}/${ID}/* /qa/services/http/binaries/RHDS/9.0/staging/builds/jboss-devstudio-${version}-build-product/${ID}/
else
  echo "ERROR: no latest build found for installers" | grep ERROR
fi


# copy JBDS installers: snapshots/builds/ to staging/builds/ [EXTERNAL - Standalone installer only]
version=9.0.0.Beta1b # a, b, c...
stream=9.0.mars
ID=""
ID=$(echo "ls 20*" | sftp ${JBDS}/9.0/snapshots/builds/devstudio.product_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
if [[ $ID ]]; then
  echo "Latest build for installer: ${ID}"
  # copy build folder
  tmpdir=/tmp/jboss-devstudio-${version}-build-product__${ID}
  rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/snapshots/builds/devstudio.product_${stream}/${ID}/* ${tmpdir}/
  # copy standalone installer
  echo "mkdir jboss-devstudio-${version}-build-product" | sftp ${JBDS}/9.0/staging/builds/
  rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${JBDS}/9.0/staging/builds/jboss-devstudio-${version}-build-product/${ID}/
  rm -fr $tmpdir
else
  echo "ERROR: no latest build found for installer" | grep ERROR
fi


# copy JBDS update: snapshots/builds/*/repo/* to staging/updates/core/${version}; also copy updatesite-core.zip
version=9.0.0.Beta1b # a, b, c...
stream=9.0.mars
ID=""
ID=$(cd /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${stream} && ls 20* | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%:*}
sitename="core"
# copy update site
echo "mkdir ${sitename}" | sftp ${JBDS}/9.0/staging/updates/
rsync -aPrz --rsh=ssh --protocol=28 /qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${stream}/${ID}/all/repo/* ${JBDS}/9.0/staging/updates/${sitename}/${version}/
y=/qa/services/http/binaries/RHDS/9.0/snapshots/builds/devstudio.product_${stream}/${ID}/installer/jboss-devstudio-*-updatesite-core.zip
rsync -aPrz --rsh=ssh --protocol=28 ${y} ${JBDS}/9.0/staging/updates/${sitename}/jboss-devstudio-${version}-updatesite-core.zip
rsync -aPrz --rsh=ssh --protocol=28 ${y}.sha1 ${JBDS}/9.0/staging/updates/${sitename}/jboss-devstudio-${version}-updatesite-core.zip.sha1


# copy JBDS discovery sites to staging/builds/ and staging/updates/
version=9.0.0.Beta1b # a, b, c...
stream=4.3.mars # NOT 9.0, use jbosstools stream here
for site in discovery.central discovery.earlyaccess; do
  ID=""
  ID=$(echo "ls 20*" | sftp ${JBDS}/9.0/snapshots/builds/jbosstools-${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-build-sites.aggregate.site_${stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/snapshots/builds/jbosstools-${site}_${stream}/${ID}/* ${tmpdir}/
    # copy build folder (and rename from jbosstools to devstudio)
    echo "mkdir devstudio-${version}-build-${sitename}" | sftp ${JBDS}/9.0/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${JBDS}/9.0/staging/builds/devstudio-${version}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp ${JBDS}/9.0/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* ${JBDS}/9.0/staging/updates/${sitename}/${version}/
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done
#  verify sites are correctly populated:
for site in central earlyaccess discovery.central discovery.earlyaccess; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "https://devstudio.redhat.com/9.0/staging/builds/devstudio-${version}-build-${sitename}/ *AND* https://devstudio.redhat.com/9.0/staging/updates/${sitename}/${version}/"
done
echo "https://devstudio.redhat.com/9.0/staging/builds/devstudio-${version}-build-product/ *AND* http://www.qa.jboss.com/binaries/RHDS/9.0/staging/builds/devstudio-${version}-build-product/"
echo "https://devstudio.redhat.com/9.0/staging/builds/ *AND* https://devstudio.redhat.com/9.0/staging/updates/core/ (all the zips)"

----

=== Update contents of devstudio.jboss.com/9.0/staging/updates

This should point to the latest staging bits. Just copy what's in discovery.central/composite*.xml into this folder.

[source,bash]
----

stream=4.3.mars # NOT 9.0, use jbosstools stream here
versionWithRespin=9.0.0.Beta1b # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.50.0.Beta1
CENTRAL_TARGET_VERSION=4.50.0.Beta1-SNAPSHOT

pushd ~/truu/jbdevstudio-website/content/9.0/staging/updates

for d in discovery.central discovery.earlyaccess; do
  mkdir -p ${d}/${versionWithRespin}/; pushd ${d}/${versionWithRespin}/
  rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/staging/updates/${d}/${versionWithRespin}/composite*xml ./
  # replace dl.jb.o and 4.3-> ds.rh.c and 9.0
  now=`date +%s000`
  for c in compositeContent.xml compositeArtifacts.xml; do 
    sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
    # TODO: are these next 3 sed steps still needed?
      sed -i -e "s#http://download.jboss.org/jbosstools/mars/#https://devstudio.redhat.com/9.0/#" $c
      sed -i -e "s#http://download.jboss.org/jbosstools/targetplatforms/#https://devstudio.redhat.com/targetplatforms/#" $c
      sed -i -e "s#4\.3\.0#9\.0\.0#" $c
  done
  cat $c | egrep "${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${CENTRAL_TARGET_VERSION}|timestamp"
  popd
done
rsync discovery.central/${versionWithRespin}/composite*.xml ./

# update index.html 
previous=9.0.0.Beta1a
sed -i "s#${previous}#${versionWithRespin}#" index.html

# push changes to server
rsync -aPrz --rsh=ssh --protocol=28 discovery.central/${versionWithRespin}/composite*xml ${JBDS}/9.0/staging/updates/discovery.central/${versionWithRespin}/
rsync -aPrz --rsh=ssh --protocol=28 discovery.earlyaccess/${versionWithRespin}/composite*xml ${JBDS}/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/
rsync -aPrz --rsh=ssh --protocol=28 ./composite*xml ./index.html ${JBDS}/9.0/staging/updates/

# verify changes
echo "https://devstudio.redhat.com/9.0/staging/updates/discovery.central/${versionWithRespin}/compositeContent.xml
https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/compositeContent.xml
https://devstudio.redhat.com/9.0/staging/updates/compositeContent.xml"

# then push changes to github (no need to commit new folders, just changes to staging/updates/*ml)
# and remove new discovery.central/ and discovery.earlyaccess/ folders
rm -fr discovery.central/${versionWithRespin}/composite*.xml discovery.earlyaccess/${versionWithRespin}/composite*.xml

# done
popd

----

== Release the latest QE snapshot to ide-config.properties

Check out this file:

http://download.jboss.org/jbosstools/configuration/ide-config.properties

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----

version=9.0.0.Beta1 #a, b, c...
# adjust these steps to fit your own path location & git workflow
cd jbosstools-download.jboss.org/jbosstools/configuration
git fetch origin master
git checkout FETCH_HEAD
vim ide-config.properties # or use another editor 

----

== Minimal testing

Make sure that the very basic installation scenario works:

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install all content from http://devstudio.redhat.com/9.0/staging/updates/ in it
3. Restart as suggested
4. Open Central Software/Updates tab, enable Early-Access select and install all connectors

1. Download JBDS installer and install it
2. Go to Central > Software Updates page
3. Enable Early-Access
4. Select all
5. Run installation

If this fails, it most likely highlight a bug or a failure in the previous steps, so fix it before notifying team.

== Notify the team (send 1 email)
____
*To* external-exadel-list@redhat.com +

[source,bash]
----
versionWithRespin=9.0.0.Beta1b # a, b, c...
respin="respin-b"
jbdsVersion=9.0.0.Beta1 # no respin suffix here
jbtVersion=4.3.0.Beta1 # no respin suffix here
echo "
Subject: 

JBDS ${versionWithRespin} Core bits available for QE testing

Body:

As always, these are not FINAL bits, but preliminary results for QE testing. Not for redistribution to customers. Update sites are public; installers require VPN access.

Universal Installers: 
* http://www.qa.jboss.com/binaries/RHDS/9.0/staging/builds/jboss-devstudio-${versionWithRespin}-build-product/ (VPN required)
* https://devstudio.redhat.com/9.0/staging/builds/jboss-devstudio-${versionWithRespin}-build-product/

Update Sites:
* https://devstudio.redhat.com/9.0/staging/updates/ (includes ${versionWithRespin} Core + Target Platform + JBoss Central)
* https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/ (includes the above site + Early Access)

New + Noteworthy (subject to change):
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

"
if [[ $respin != "respin-" ]]; then
echo " 

--

Changes prompting this $respin are: https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${jbdsVersion}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${jbtVersion}%22%29%29%29

To compare the upcoming version of Central (${versionWithRespin}) against an older version, add lines similar to these your eclipse.ini file after the -vmargs line for the appropriate version & URLs:
 -Djboss.discovery.directory.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.central/${versionWithRespin}/devstudio-directory.xml
 -Djboss.discovery.site.url=https://devstudio.redhat.com/9.0/staging/updates/
 -Djboss.discovery.earlyaccess.site.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/
 -Djboss.discovery.earlyaccess.list.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/devstudio-earlyaccess.properties

"
fi


----
____
