= Publishing JBDS Installers & update sites for QE

This document describe how to provide a valid JBoss Developer Studio build to QE so they can test us.

TODO: use consistent instructions for fetching sources from git & pushing changes
TODO: add step that automatically keeps all staged builds in Jenkins, using /lastBuild/toggleLogKeep

== Update Discovery Sites and URLs

See details in JBT_Staging_For_QE.adoc


== Verify correct version set in com.jboss.devstudio.central.core

See details in JBT_Staging_For_QE.adoc

== Disable jobs

See details in JBT_Staging_For_QE.adoc

== Variables to use

Whenever you're starting a new shell, you should set those variables:

[sources,bash]
----
version=9.1.0.CR1
versionWithRespin=9.1.0.CR1b # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.52.0.Final
TARGET_PLATFORM_CENTRAL_MAX=4.52.0.Final-SNAPSHOT
now=$(date +%s000)
isGA=false
JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
----

== Stage to qa.jboss.org

*qa.jboss.org* is actually mapped to folder +/qa/services/http/binaries/RHDS+ accessible from CI machines (such as dev01.mw.lab.eng.bos.redhat.com). So first connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Then copy the latest JBDS artifacts:

* installer
* target platforms & zips
* update sites & zips
* discovery sites

WARNING: Don't use symlinks are they are too risky to use. Those operations can be done in parallel (using multiple terminals is the easiest way)

=== Push installers, update site, and discovery site

[source,bash]
----
# can run these 6 steps in parallel

# 1. copy JBDS target platform zips from INTERNAL (www.qa) to EXTERNAL (devstudio.redhat.com)
versionWithRespin=9.1.0.CR1b # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.52.0.Final
TARGET_PLATFORM_CENTRAL_MAX=4.52.0.Final-SNAPSHOT
for targetname in jbdevstudio jbtcentral jbtearlyaccess; do
  if [[ ${targetname} == "jbdevstudio" ]]; then
    TARGET_PLATFORM_VERSION=${TARGET_PLATFORM_VERSION_MAX}
    suffix="-target-platform"
  else
    TARGET_PLATFORM_VERSION=${TARGET_PLATFORM_CENTRAL_MAX}
    suffix="-target-platform-${targetname:3}"
  fi
  y=/qa/services/http/binaries/RHDS/targetplatforms/${targetname}target/${TARGET_PLATFORM_VERSION}/${targetname}target-${TARGET_PLATFORM_VERSION}.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${y} ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${versionWithRespin}${suffix}.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${y}.sha256 ${JBDS}/9.0/staging/updates/core/jboss-devstudio-${versionWithRespin}${suffix}.zip.sha256
done
echo "DONE: copy JBDS target platform zips" | grep "copy JBDS target platform zips"


# 2. central/earlyaccess & discovery
cd /tmp
if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.3.x/publish/stage.sh --no-check-certificate
chmod +x stage.sh
stream=4.3.mars
versionWithRespin=9.1.0.CR1b # a, b, c...
for site in central-site earlyaccess-site; do
  ./stage.sh -sites $site -dd 9.0 -stream ${stream} -vr ${versionWithRespin} -JOB_NAME jbosstools-build-sites.aggregate.\${site}_\${stream} \
    -DESTINATION ${JBDS} -DEST_URL https://devstudio.redhat.com &
done
wait && echo $#


# 3. copy JBDS installers: snapshots/builds/ to staging/builds/ [INTERNAL - both installers]
#    copy JBDS update: snapshots/builds/*/repo/* to staging/updates/core/${versionWithRespin}; also copy updatesite-core.zip
cd /tmp
if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.3.x/publish/stage.sh --no-check-certificate
chmod +x stage.sh
stream=9.0.mars
versionWithRespin=9.1.0.CR1b # a, b, c...
for site in product; do
  ./stage.sh -sites $site -dd 9.0 -stream ${stream} -vr ${versionWithRespin} -JOB_NAME devstudio.\${site}_\${stream} \
    -DESTINATION /qa/services/http/binaries/RHDS -DEST_URL http://www.qa.jboss.com/binaries/RHDS &
done


# 4. copy JBDS installers: snapshots/builds/ to staging/builds/ [EXTERNAL - Standalone installer only]
# 5. copy JBDS update: snapshots/builds/*/repo/* to staging/updates/core/${versionWithRespin}; also copy updatesite-core.zip
cd /tmp
if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.3.x/publish/stage.sh --no-check-certificate
chmod +x stage.sh
stream=9.0.mars
versionWithRespin=9.1.0.CR1b # a, b, c...
for site in product; do
  ./stage.sh -sites $site -dd 9.0 -stream ${stream} -vr ${versionWithRespin} -JOB_NAME devstudio.\${site}_\${stream} \
    -DESTINATION ${JBDS} -DEST_URL https://devstudio.redhat.com &
done


# TODO: make sure you've rebuilt the discovery sites and disabled the job first before doing this step!
# 6. copy JBDS discovery sites to staging/builds/ and staging/updates/
cd /tmp
if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.3.x/publish/stage.sh --no-check-certificate
chmod +x stage.sh
stream=4.3.mars
versionWithRespin=9.1.0.CR1b # a, b, c...
for site in discovery.central discovery.earlyaccess; do
  ./stage.sh -sites $site -dd 9.0 -stream ${stream} -vr ${versionWithRespin} -JOB_NAME jbosstools-\${site}_\${stream} \
    -DESTINATION ${JBDS} -DEST_URL https://devstudio.redhat.com &
done

----

Verify sites are correctly populated (run locally, not on dev01).

Note that Akamai caching might result in the appearance of missing files (apache directories may look incomplete) but if you ping specific files, they should be there.

[source,bash]
----

versionWithRespin=9.1.0.CR1b # a, b, c...
tmpfile=/tmp/jbosstools-staging__verify.txt
for site in central earlyaccess discovery.central discovery.earlyaccess; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-${sitename}/ " >> $tmpfile
  echo "https://devstudio.redhat.com/9.0/staging/updates/${sitename}/${versionWithRespin}/ " >> $tmpfile
done
echo "https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/ " >> $tmpfile
echo "http://www.qa.jboss.com/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/ " >> $tmpfile
echo "https://devstudio.redhat.com/9.0/staging/builds/#_____(5_folders_w/_${versionWithRespin}) " >> $tmpfile
echo "https://devstudio.redhat.com/9.0/staging/updates/core/#_____(6_zips,_6_sums,_1_folder_w/_${versionWithRespin}) " >> $tmpfile
echo "" >> $tmpfile
cat $tmpfile
firefox `cat $tmpfile`
popd >/dev/null
rm -fr $tmpfile

# once the staging build folder exists, start fetching the JBDS installer (we'll need it later to do a smoke test)

cd ~/tmp
wget https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html
wget https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/${installerJar}

----

You'll use this downloaded installer later, but since it takes a while to download, it's more efficient to start it now.


=== Cleanup OLD builds

Optional step.

First, use sshfs to mount filemgmt file paths.

[source,bash]
----

JBDS=devstudio@filemgmt.jboss.org:/www_htdocs/devstudio
sshfs $JBDS /media/JBDS-ssh

----

Then move old builds into an OLD/ folder to they're less visible and ready for deletion later.

[source,bash]
----
version_PREV=9.1.0.Beta2 # a, b, c...
for d in updates/core updates/central updates/earlyaccess updates/discovery.central updates/discovery.earlyaccess builds; do
  if [[ -d /media/JBDS-ssh/9.0/staging/${d}/ ]]; then
    echo "${d}/*${version_PREV}* ..."
    mkdir -p /media/JBDS-ssh/9.0/staging/${d}/OLD/
    mv /media/JBDS-ssh/9.0/staging/${d}/*${version_PREV}* /media/JBDS-ssh/9.0/staging/${d}/OLD/
  fi
done

----

=== Update https://devstudio.jboss.com/9.0/staging/updates/

This should point to the latest staging bits. Just copy what's in discovery.central/composite*.xml into this folder.

[source,bash]
----

version=9.1.0.CR1
versionWithRespin_PREV=9.1.0.CR1a # a, b, c...
versionWithRespin=9.1.0.CR1b # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.52.0.Final
TARGET_PLATFORM_CENTRAL_MAX=4.52.0.Final-SNAPSHOT

cd ~/truu
pushd jbdevstudio-website/content/9.0/staging/updates

git fetch origin master
git checkout FETCH_HEAD

for d in discovery.central discovery.earlyaccess; do
  mkdir -p ${d}/${versionWithRespin}/; pushd ${d}/${versionWithRespin}/
  rsync -aPrz --rsh=ssh --protocol=28 ${JBDS}/9.0/staging/updates/${d}/${versionWithRespin}/composite*xml ./
  # replace dl.jb.o and 4.3-> ds.rh.c and 9.0
  now=`date +%s000`
  for c in compositeContent.xml compositeArtifacts.xml; do
    sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
    # TODO: are these next 3 sed steps still needed?
      sed -i -e "s#http://download.jboss.org/jbosstools/mars/#https://devstudio.redhat.com/9.0/#" $c
      sed -i -e "s#http://download.jboss.org/jbosstools/targetplatforms/#https://devstudio.redhat.com/targetplatforms/#" $c
      sed -i -e "s#4\.3\.0#9\.0\.0#" $c
  done
  cat $c | egrep "${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${TARGET_PLATFORM_CENTRAL_MAX}|timestamp"
  popd
done
rsync discovery.central/${versionWithRespin}/composite*.xml ./

# update index.html
sed -i "s#${versionWithRespin_PREV}#${versionWithRespin}#" index.html
cat index.html | egrep "${versionWithRespin_PREV}|${versionWithRespin}"

# push changes to server
rsync -aPrz --rsh=ssh --protocol=28 discovery.central/${versionWithRespin}/composite*xml ${JBDS}/9.0/staging/updates/discovery.central/${versionWithRespin}/
rsync -aPrz --rsh=ssh --protocol=28 discovery.earlyaccess/${versionWithRespin}/composite*xml ${JBDS}/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/
rsync -aPrz --rsh=ssh --protocol=28 ./composite*xml ./index.html ${JBDS}/9.0/staging/updates/

# verify changes
echo "Check 4 URLs:"
firefox \
https://devstudio.redhat.com/9.0/staging/updates/discovery.central/${versionWithRespin}/compositeContent.xml \
https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/compositeContent.xml \
https://devstudio.redhat.com/9.0/staging/updates/compositeContent.xml \
https://devstudio.redhat.com/9.0/staging/updates/

rm -fr discovery.central/${versionWithRespin}/composite*.xml discovery.earlyaccess/${versionWithRespin}/composite*.xml

# commit the change and push to master
ci "release JBDS ${version} (${versionWithRespin}) to staging" .
git push origin HEAD:master

# done
popd

----

=== Merge in Integration Stack content

See details in Merge_IS_Discovery.adoc

== Release the latest staging site to ide-config.properties

See details in JBT_Staging_For_QE.adoc


== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install BYOE category from https://devstudio.redhat.com/9.0/staging/updates/
3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

[source,bash]
----
versionWithRespin=9.1.0.CR1b # a, b, c...
cd ~/tmp
wget https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/
installerJar=$(cat index.html | grep -v latest | grep installer-standalone.jar\" | sed "s#.\+href=\"\([^\"]\+\)\">.\+#\1#")
echo "Installer jar: ${installerJar}"
rm -f index.html

# should have already downloaded this above
if [[ ! -f ${installerJar} ]]; then wget https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/${installerJar}; fi

java -jar ~/tmp/${installerJar}

----

0. After downloading and installing JBDS from the step above...
1. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
2. Check log, start an example project, check log again

If this fails, it is most likely due to a bug or a failure in a step above. If possible, fix it before notifying team below.


== Enable jobs

See details in JBT_Staging_For_QE.adoc


== Kick downstream Dev Platform Installer

Now that JBDS installer is staged, you can submit a PR against the dev platform installer and have that built.

See: https://github.com/redhat-developer-tooling/developer-platform-install/blob/master/requirements.json#L24

Build: http://machydra.brq.redhat.com:8080/job/developer-platform-installer-build-aggregate


== Notify the team (send 1 email)

Run this on dev01 so that we can use /bin/mail. Email should be generated automatically rather than requiring copy & paste into your mail client.

____
*To* jboss-devstudio-list@redhat.com +

[source,bash]
----
version_JBT=4.3.1.CR1
version=9.1.0.CR1
versionWithRespin=9.1.0.CR1b # a, b, c...
respin="respin-a"
recipients=jboss-devstudio-list@redhat.com
sender=nboldt@redhat.com
subject="JBDS ${versionWithRespin} Core bits available for QE testing"
echo "
These are not FINAL bits, but preliminary results for QE & community testing. Not for redistribution to customers or end users.

Universal Installers:
* http://www.qa.jboss.com/binaries/RHDS/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/ (EAP bundles; VPN required)
* https://devstudio.redhat.com/9.0/staging/builds/devstudio-${versionWithRespin}-build-product/latest/all/ (Standalone + other zips)

Update Sites:
* https://devstudio.redhat.com/9.0/staging/updates/ (includes ${versionWithRespin} Core + Target Platform + JBoss Central)
* https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/ (includes the above site + Early Access)

New + Noteworthy (subject to change):
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule / Upcoming Releases: https://issues.jboss.org/projects/JBDS?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page
" > /tmp/mailbody.jbds.txt
if [[ $respin != "respin-" ]]; then
echo "
--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${version}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${version_JBT}%22%29%29%29

To compare the upcoming version of Central (${versionWithRespin}) against an older version, add lines similar to these your eclipse.ini file after the -vmargs line for the appropriate version & URLs:
 -Djboss.discovery.directory.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.central/${versionWithRespin}/devstudio-directory.xml
 -Djboss.discovery.site.url=https://devstudio.redhat.com/9.0/staging/updates/
 -Djboss.discovery.earlyaccess.site.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/
 -Djboss.discovery.earlyaccess.list.url=https://devstudio.redhat.com/9.0/staging/updates/discovery.earlyaccess/${versionWithRespin}/devstudio-earlyaccess.properties

" >> /tmp/mailbody.jbds.txt
fi

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" $recipients -- -f"$sender" < /tmp/mailbody.jbds.txt
rm -f /tmp/mailbody.jbds.txt

----
____

