= Publishing JBT update sites for QE

This document describe how to provide a valid JBoss Tools build to QE so they can test us.

TODO: use consistent variables for version, versionWithRespin, previous, previousFull, versionWithRespin_PREV

TODO: use consistent instructions for fetching sources from git & pushing changes

TODO: use consistent instructions for updating ide-config.properties

[NOTE]
====
Note that +sftp://tools@filemgmt.jboss.org/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+ +

If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools . 
A Jenkins job can then be triggered to sync changes to download.jboss.org: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-download.jboss.org-rsync-from-svn/
====

== Verify correct version set in org.jboss.tools.foundation.core

# @Since JBT 4.2.1 / JBDS 8.0.1
# JBIDE-18820, JBIDE-18806 check the version set in o.j.t.foundation.core's currentversion.properties value of default.version
# TODO: verify that for Beta2, we only get ONE copy of the plugin, not multiple old (orphaned?) ones too.
version=4.3.0.Beta1 #a, b, c...
pluginName=foundation.core
updatesiteURL=https://devstudio.redhat.com/9.0/staging/updates/core/${version}/plugins/
updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/4.3.mars/plugins/
updatesiteURL=http://download.jboss.org/jbosstools/mars/staging/updates/core/${version}/plugins/
updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/4.3.mars/plugins/
pushd /tmp; wget -q -nc $updatesiteURL
thejars=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort`
echo "Found: $thejars" | egrep ${pluginName}
thejar=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort | tail -1; rm -f index.html`
echo ${updatesiteURL}/${thejar} | egrep ${pluginName}
wget -q -nc ${updatesiteURL}/${thejar}
theversion=`unzip -p ${thejar} */currentversion.properties | grep version= | sed -e "s/version=//" | tail -1`
theversion=${theversion/-SNAPSHOT/} # remove -SNAPSHOT suffix from version
rm -f ${thejar}
popd
echo "Want ${version}, got $theversion" | grep ${version}

# if value found above for $jbosstoolsversion != current release version, then you need to rebuild foundation or JBDS w/ a new value inserted.


== Verify all branches have been created & all master branch root poms point to the NEXT parent pom version.

Chances are you opened a JIRA like https://issues.jboss.org/browse/JBIDE-18149 and asked everyone to branch and then upversion the references to the parent pom in their root poms.
Chances are also that someone might have forgotten to do this.

So, to ensure everyone has done what they need to do, you can run two scripts:

* ensure all the branches exist.

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/getProjectSHAs.sh

* ensure the root poms are correct

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/getProjectRootPomParents.sh

If any branches have not yet been created, you can either:
* Ask Denis, Fred, or Max to get them created
* Reconfigure the jobs to build from your fork, and create the branch there

If any of the root poms have not been correctly updated, simply re-open the task JIRAs like https://issues.jboss.org/browse/JBIDE-18167 and ask that the root pom be updated.

Once the above conditions have been met, you can proceed to the next steps.

== Disable jobs

To prevent accidentally rebuilding something while you're copying it away, make sure that all the stable branch jobs (4.3.mars, 9.0.mars) are disabled. These include all product, composite and aggregate jobs:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-composite-install_4.3.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-browsersim-standalone_4.3.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-build-sites.aggregate.site_4.3.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-build-sites.aggregate.coretests-site_4.3.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-build-sites.aggregate.child-sites_4.3.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/devstudio.product_9.0.mars/

You may also want to disable these:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-build.parent_4.3.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-buildflow_4.3.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-centraltarget_4.3.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/devstudio.versionwatch_9.0.mars/
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstoolstargetplatforms-matrix/

If you want to disable all jobs from the https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/[9.0.mars view], see https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py[toggleJenkinsJobs.py]. See also https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py.examples.txt[usage examples].

Should a respin be needed, they can be re-enabled as needed.

== Stage to download.jboss.org

=== Copy & rename builds & update sites from "snapshots" to "staging"

@Since JBT 4.3.0.Beta1 / JBDS 9.0.Beta1

Nightly builds are continuously built in http://download.jboss.org/jbosstools/mars/snapshots/builds/. Aggregate sites are also copied into http://download.jboss.org/jbosstools/mars/snapshots/updates/.

Staging builds are the ones prepped for QE, which are then moved to /development/ if approved.

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Here is a script that performs the copy (& rename) from /snapshots/ to /staging/:

[source,bash]
----

# JBT aggregate site
for site in site; do
  stream=4.3.mars
  version=4.3.0.Beta1b # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-build-sites.aggregate.${site}_${stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream}/${ID}/* ${tmpdir}/
    # copy build folder
    echo "mkdir jbosstools-${version}-build-${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/jbosstools-${version}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/${sitename}/${version}/
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done

# JBT tests site
for site in coretests-site; do
  stream=4.3.mars
  version=4.3.0.Beta1b # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-build-sites.aggregate.${site}_${stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream}/${ID}/* ${tmpdir}/
    # copy build folder
    echo "mkdir jbosstools-${version}-build-${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/jbosstools-${version}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/${sitename}/${version}/
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done

#TODO: JBIDE-19757 as of Beta1 we should no longer require the webtools-site anymore; instead we need to create a symlink from http://download.jboss.org/jbosstools/updates/webtools/mars/ into http://download.jboss.org/jbosstools/mars/development/updates/
# webtools sites
for site in webtools-site; do
  stream=4.3.mars
  version=4.3.0.Beta1b # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-build-sites.aggregate.${site}_${stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream}/${ID}/* ${tmpdir}/
    # copy build folder
    echo "mkdir jbosstools-${version}-build-${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/jbosstools-${version}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/${sitename}/${version}/
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done

# Central and EA sites
for site in central-site earlyaccess-site; do
  stream=4.3.mars
  version=4.3.0.Beta1b # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-build-sites.aggregate.${site}_${stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream}/${ID}/* ${tmpdir}/
    # copy build folder
    echo "mkdir jbosstools-${version}-build-${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/jbosstools-${version}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/${sitename}/${version}/
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done

# Browsersim Standalone Zip, ~16M
for site in browsersim-standalone; do
  stream=4.3.mars
  version=4.3.0.Beta1b # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-${site}_${stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-${site}_${stream}/${ID}/* ${tmpdir}/
    # copy build folder
    echo "mkdir jbosstools-${version}-build-${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/jbosstools-${version}-build-${sitename}/${ID}/
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done

#  verify sites are correctly populated:
for site in site coretests-site webtools-site central-site earlyaccess-site; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "http://download.jboss.org/jbosstools/mars/staging/builds/jbosstools-${version}-build-${sitename}/ *AND* http://download.jboss.org/jbosstools/mars/staging/updates/${sitename}/${version}/"
done
for site in browsersim-standalone; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "http://download.jboss.org/jbosstools/mars/staging/builds/jbosstools-${version}-build-${sitename}/"
done


----

=== Update composite site metadata for staged updates

Update files __http://download.jboss.org/jbosstools/mars/staging/updates/composite*.xml__ , with SFTP/SCP via command-line or your 
favourite SFTP GUI client (such as Eclipse RSE).

This site needs to contain:
* The latest JBoss Tools core site
* The latest matching target platform site
* The latest matching JBoss Tools Central site

[source,bash]
----
versionWithRespin_PREV=4.3.0.Beta1a
TARGET_PLATFORM_VERSION_MAX_PREV=4.50.0.Beta1
TARGET_PLATFORM_CENTRAL_MAX_PREV=4.50.0.Beta1-SNAPSHOT

versionWithRespin=4.3.0.Beta1b # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.50.0.Beta1
TARGET_PLATFORM_CENTRAL_MAX=4.50.0.Beta1-SNAPSHOT

cd jbosstools-download.jboss.org/jbosstools/mars/staging/updates
git fetch origin master
git checkout FETCH_HEAD

# replace static/releases with mars/staging/updates, then replace all the versions
now=`date +%s000`
for c in compositeContent.xml compositeArtifacts.xml; do 
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
  sed -i -e "s#/static/releases/#/mars/staging/updates/#" $c
  sed -i -e "s#${TARGET_PLATFORM_CENTRAL_MAX_PREV}#${TARGET_PLATFORM_CENTRAL_MAX}#" $c
  sed -i -e "s#${TARGET_PLATFORM_VERSION_MAX_PREV}#${TARGET_PLATFORM_VERSION_MAX}#" $c
  sed -i -e "s#${versionWithRespin_PREV}#${versionWithRespin}#" $c
done
cat $c | egrep "${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${TARGET_PLATFORM_CENTRAL_MAX}|timestamp"

# commit the change and push to master
git add composite*.xml
git commit -m "release JBT ${versionWithRespin} to QE" composite*.xml
git push origin HEAD:master

# push updated file to server
scp composite*.xml tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/

----


== Update Discovery URLs

[[update-discovery-urls]]
Update the *stable branch* discovery job ( https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-discovery_4.3.mars/configure ) to use the correct source URLs and versions +

VERSION = "Beta1b" (not SNAPSHOT!)
TARGET_PLATFORM_VERSION_MAXIMUM  = "4.50.0.Beta1"
JBTCENTRALTARGET_VERSION   = "4.50.0.Beta1-SNAPSHOT"

Then respin the job and verify that sites were correctly populated:

* http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-discovery.central_4.3.mars/
* http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-discovery.earlyaccess_4.3.mars/


=== Stage discovery site 

WARNING: Make sure you performed the step <<update-discovery-urls,Update Discovery URLs>> above.

There are 2 things to do:

. copy & rename the discovery sites from /snapshots/ to /staging/
. ensure any references to the latest Integration Stack jar(s) are included

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

[source,bash]
----

for site in discovery.central discovery.earlyaccess; do
  stream=4.3.mars
  version=4.3.0.Beta1b # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-build-sites.aggregate.site_${stream}__${ID}
    rsync -aPrz --rsh=ssh --protocol=28 tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/snapshots/builds/jbosstools-${site}_${stream}/${ID}/* ${tmpdir}/
    # copy build folder
    echo "mkdir jbosstools-${version}-build-${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/builds/jbosstools-${version}-build-${sitename}/${ID}/
    # copy update site
    echo "mkdir ${sitename}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* tools@filemgmt.jboss.org:/downloads_htdocs/tools/mars/staging/updates/${sitename}/${version}/
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done

#  verify sites are correctly populated:
for site in discovery.central discovery.earlyaccess; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "http://download.jboss.org/jbosstools/mars/staging/builds/jbosstools-${version}-build-${sitename}/ *AND* http://download.jboss.org/jbosstools/mars/staging/updates/${sitename}/${version}/"
done

----

[source,bash]
----

# TODO: write a new mechanism for 4.3.0.Beta2 to pull in integration stack jars!
# new EA properties is here: http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/4.3.0.Beta1/jbosstools-earlyaccess.properties

stream=4.3.mars
version=4.3.0.Beta1b # a, b, c...
# earlyaccess site includes one directory.xml file which lists both core and earlyaccess plugins, so use that instead of core site
echo "rename nightly/earlyaccess/${stream} staging/${version}" | sftp tools@filemgmt.jboss.org:/downloads_htdocs/tools/discovery/
echo " >> http://download.jboss.org/jbosstools/discovery/staging/${version}/" | egrep ">>|${version}"

# TODO: ensure that the latest IS plugin jar is also available in the staging JBT discovery site
# TODO: remember to include IS jar in jbosstools-directory.xml AND the plugin in the site too

isjar=""
isjar=`curl -s http://download.jboss.org/jbosstools/updates/stable/mars/jbosstools-directory.xml | grep integration-stack`
isjar=`curl -s http://download.jboss.org/jbosstools/updates/development/mars/jbosstools-directory.xml | grep integration-stack`
if [[ ${isjar} ]]; then 
  # echo "Found integration-stack jar: ${isjar}"
	curl -s http://download.jboss.org/jbosstools/discovery/staging/${version}/jbosstools-directory.xml > /tmp/jbosstools-directory.xml
  isjar2=`cat /tmp/jbosstools-directory.xml | grep integration-stack`
  if [[ ! ${isjar2} ]]; then
    echo "ERROR: no integration stack jar listed in http://download.jboss.org/jbosstools/discovery/staging/${version}/" | grep ERROR
    echo "Must add this line:"
    echo ""
    echo "${isjar}"
    echo ""
    pushd jbosstools-download.jboss.org/jbosstools/discovery/staging/
	    git fetch origin master
	    git checkout master 
	    mkdir -p ${version}
	    pushd ${version}
		    mv /tmp/jbosstools-directory.xml jbosstools-directory.xml
		    cat jbosstools-directory.xml | egrep "<directory|<entry" > jbosstools-directory.xml.out
		    echo ${isjar} >> jbosstools-directory.xml.out
		    echo "</directory>" >> jbosstools-directory.xml.out
		    mv -f jbosstools-directory.xml.out jbosstools-directory.xml
		    cat jbosstools-directory.xml | grep integration-stack
		    git add jbosstools-directory.xml
		    git commit -m "add latest JBT IS jar to jbosstools/discovery/staging/${version}" jbosstools-directory.xml
		    git push origin master
        echo "TODO: make sure the above step worked" | grep TODO
		    scpr jbosstools-directory.xml $TOOLS/discovery/staging/${version}/
        echo "firefox http://download.jboss.org/jbosstools/discovery/staging/${version}/jbosstools-directory.xml"
		  popd
    popd
  else
    echo "OK: directory.xml includes ${isjar}" | egrep "OK|integration-stack"
    rm -f /tmp/jbosstools-directory.xml
  fi
fi
----


== Release the latest QE snapshot to ide-config.properties

Check out this file:

http://download.jboss.org/jbosstools/configuration/ide-config.properties

And update it it as required, so that the links for the latest milestone point to valid URLs, eg.,

[source,bash]
----

version=4.3.0.Beta1 #a, b, c...
# adjust these steps to fit your own path location & git workflow
cd jbosstools-download.jboss.org/jbosstools/configuration
git fetch origin master
git checkout FETCH_HEAD
vim ide-config.properties # or use another editor 

# otherwise, replace existing lines with these to make the lastest milestone live
jboss.discovery.directory.url|jbosstools|4.3.0.Beta1=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.central/4.3.0.Beta1/jbosstools-directory.xml
jboss.discovery.site.url|jbosstools|4.3.0.Beta1=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.central/4.3.0.Beta1/
jboss.discovery.earlyaccess.site.url|jbosstools|4.3.0.Beta1=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/4.3.0.Beta1/
jboss.discovery.earlyaccess.list.url|jbosstools|4.3.0.Beta1=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/4.3.0.Beta1/jbosstools-earlyaccess.properties
jboss.discovery.site.integration-stack.url|jbosstools|4.3.0.Beta1=

# commit the change and push to master
git add ide-config.properties
git commit -m "release JBT ${version} to QE: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
scp ide-config.properties tools@filemgmt.jboss.org:/downloads_htdocs/tools/configuration/ide-config.properties
----

== Test sites

Before notifying team of successful staging process completion, let's check there is no obvious issue

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install all content from http://download.jboss.org/jbosstools/mars/staging/updates/ in it
3. Restart as suggested
4. Open Central Software/Updates tab, enable Early-Access select and install all connectors
5. Restart as suggested
6. Check log, start an example project, check log again

== Notify the team

____
*To* jbosstools-dev@lists.jboss.org +

[source,bash]
----
versionWithRespin=4.3.0.Beta1b # a, b, c...
respin="respin-b"
#TARGET_PLATFORM_VERSION_MIN=4.50.0.Beta1
TARGET_PLATFORM_VERSION_MAX=4.50.0.Beta1
TARGET_PLATFORM_CENTRAL_MAX=4.50.0.Beta1-SNAPSHOT
jbdsFixVersion=9.0.0.Beta1 # no respin suffix here
jbtFixVersion=4.3.0.Beta1 # no respin suffix here
echo "
Subject: 

JBoss Tools Core ${versionWithRespin} bits available for QE testing

Body:

As always, these are not FINAL bits, but preliminary results for QE & community testing. Not for use by customers or end users. 

Update site: http://download.jboss.org/jbosstools/mars/staging/updates/

Target platform: 
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX} 

New + noteworthy (subject to change): 
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule: https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

--

Additional update sites:
* http://download.jboss.org/jbosstools/mars/staging/updates/core/${versionWithRespin}/
* http://download.jboss.org/jbosstools/mars/staging/updates/coretests/${versionWithRespin}/
* http://download.jboss.org/jbosstools/mars/staging/updates/webtools/${versionWithRespin}/

Discovery sites:
* http://download.jboss.org/jbosstools/mars/staging/updates/discovery.central/${versionWithRespin}/
* http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/

Build folders (for build logs & update site zips):
* http://download.jboss.org/jbosstools/mars/staging/builds/

"
if [[ $respin != "respin-" ]]; then
echo " 

--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${jbdsFixVersion}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${jbtFixVersion}%22%29%29%29

To compare the upcoming version of Central (${versionWithRespin}) against an older version, add lines similar to these your eclipse.ini file after the -vmargs line for the appropriate version & URLs:
 -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.central/${versionWithRespin}/jbosstools-directory.xml
 -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/mars/staging/updates/
 -Djboss.discovery.earlyaccess.site.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/
 -Djboss.discovery.earlyaccess.list.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/jbosstools-earlyaccess.properties
"
fi

----
____
