= Release JBoss Tools Development Milestone

This document describe how to publish a valid JBoss Tools build to production after being verified by QE.

With distractions (email, IRC), this process took ~90 mins for the Beta3 release. 

WARNING: this requires write access to http://sourceforge.net/projects/jboss/files/JBossTools/

TODO: JBIDE-20143 switch from SHA1 to SHA256

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten. 

Send an email to jbosstools-dev@ and jboss-devstudio-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Summary

Here are some generalities site promotion/release process. It's not an exhaustive list so you need to read the full document to do a release, but it gives an overview of the various steps.

. CI build output is published the 'builds/staging' folder, while aggregated update-sites goes to 'updates/nightly' folder
. After branching, component repository are rebuilt from branch (instead of 'master') and new aggregated updatesites are created as well.  A site is promoted from nightly to staging for QE, and moves from 'updates/nightly' to 'updates/staging', including a respin suffix if required.
.. If QE finds a blocker issue, a respin is requested
... On Jira, add a 'respin-a' or 'respin-b' or 'respin-x' label to bugs that needs for be fixed for the respin
... Edit CI jobs to the next respin label (eg Beta2a -> Beta2b)
... Re-run necessary jobs
... Go To 1
.. If QE approves, release is accepted and promoted
... JIRA is checked to ensure all JIRAs for this milestone are resolved
... Zips get published on sourceforge
... Site moves from 'updates/staging' with respin label to 'static/releases' without respin label
... Links to 'updates/mars' are replaced to link to new version
... JBoss Tools website is updated
... Git repositories are tagged
... Eclipse Marketplace entries are created or updated
... JIRA version can be released
... Interested parties are notified


== Zips on sf.net

@since 4.3.0.Beta2

As of JBT 4.3.0.Beta2, zips will no longer pushed to sourceforge.

=== Prepare files

On your local machine, using a SFTP client (or the script suggested above), copy the files to publish to +http://download.jboss.org/jbosstools/${TOOLS}/mars/staging/builds/sf.net/+ and rename them to conform to pattern.

[source,bash]
----

# can run these 3 steps in parallel

stream=4.3.mars
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
SFDIR=/tmp/development_sf.net_${version}; mkdir -p $SFDIR; pushd $SFDIR
echo "mkdir ${version}" | sftp ${TOOLS}/mars/staging/builds/sf.net/
buildID=$(echo "ls 20*" | sftp ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/ 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); buildID=${buildID%%/*}
echo "Latest build: ${buildID}"
y=$SFDIR/jbosstools-${version}_${buildID}-updatesite-core.zip
scpr ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/${buildID}/all/repository.zip $y
scpr ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/${buildID}/all/repository.zip.sha256 ${y}.sha256
popd


stream=4.3.mars
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
SFDIR=/tmp/development_sf.net_${version}; mkdir -p $SFDIR; pushd $SFDIR
echo "mkdir ${version}" | sftp ${TOOLS}/mars/staging/builds/sf.net/
buildID=$(echo "ls 20*" | sftp ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/ 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); buildID=${buildID%%/*}
echo "Latest build: ${buildID}"
y=$SFDIR/jbosstools-${version}_${buildID}-src.zip
scpr ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/${buildID}/all/jbosstools-${version}-src.zip $y
scpr ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/${buildID}/all/jbosstools-${version}-src.zip.sha256 ${y}.sha256
popd


stream=4.3.mars
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
SFDIR=/tmp/development_sf.net_${version}; mkdir -p $SFDIR; pushd $SFDIR
echo "mkdir ${version}" | sftp ${TOOLS}/mars/staging/builds/sf.net/
# get browsersim-standalone zip
buildID=$(echo "ls 20*" | sftp ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-browsersim-standalone/ 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); buildID=${buildID%%/*}
echo "Latest build: ${buildID}"
y=$SFDIR/jbosstools-${version}_${buildID}-browsersim-standalone.zip
scpr ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-browsersim-standalone/${buildID}/*.zip $y
for m in $(sha256sum ${y}); do if [[ $m != ${y} ]]; then echo $m > ${y}.sha256; fi; done
popd

# then, push zips and SHAs to destination
scpr $SFDIR ${TOOLS}/mars/staging/builds/sf.net/
echo "http://download.jboss.org/jbosstools/mars/staging/builds/sf.net/${version}/"

# if everything above worked...
popd; rm -fr $SFDIR

----
  
== Copy sites

These steps happens on filemgmt.jboss.org, in the jbosstools download area.

=== Copy content to release directory

We simply copy the content of the latest respin to the release directory (under _jbosstools/static_ which is using Akamai)

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Here is a script that performs the copy from /staging/ to /development/:

[source,bash]
----
# TODO: add a step to check if versionWithRespin ends with ".Final"; if so, use /stable/ instead of /development/
# copy from staging to development (under /static/ for Akamai performance)

# Do these 5 steps in parallel to save time

# JBT aggregate site
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in core; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/
  # copy update site
  echo "mkdir ${site}" | sftp ${TOOLS}/static/mars/development/updates/
  rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/static/mars/development/updates/${site}/${version}/
  rm -fr $tmpdir
done
echo "DONE: JBT aggregate site" | grep "JBT aggregate site"


# JBT tests site
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in coretests; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/
  # copy update site
  echo "mkdir ${site}" | sftp ${TOOLS}/static/mars/development/updates/
  rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/static/mars/development/updates/${site}/${version}/
  rm -fr $tmpdir
done
echo "DONE: JBT tests site" | grep "JBT tests site"


# Central and EA sites
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in central earlyaccess coretests; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/
  # copy update site
  echo "mkdir ${site}" | sftp ${TOOLS}/static/mars/development/updates/
  rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/static/mars/development/updates/${site}/${version}/
  rm -fr $tmpdir
done
echo "DONE: Central and EA sites" | grep "Central and EA sites"


# JBT discovery sites
# unlike above, don't use /static/ paths here because we're going to have to change the content to point to correct paths below
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in discovery.central discovery.earlyaccess; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/
  # sed .xml files to point at /development/ instead of /staging/, and ${version} instead of $versionWithRespin}
  if [[ ${site/discovery/} != ${site} ]]; then 
    pushd ${tmpdir}/ >/dev/null
    now=`date +%s000`
    for c in compositeContent.xml compositeArtifacts.xml; do 
      sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
      sed -i -e "s#jbosstools/mars#jbosstools/static/mars#" $c
      sed -i -e "s#staging#development#" $c
      sed -i -e "s#${versionWithRespin}#${version}#" $c
    done
    cat compositeContent.xml | egrep "staging|development|${version}|${versionWithRespin}|static"
    popd >/dev/null
  fi
  # copy update site
  echo "mkdir ${site}" | sftp ${TOOLS}/mars/development/updates/
  rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/mars/development/updates/${site}/${version}/
  rm -fr $tmpdir
done
echo "DONE: JBT discovery sites" | grep "JBT discovery sites"


# JBT zips into http://download.jboss.org/jbosstools/static/mars/development/updates/core/
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in core; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}_zips; mkdir -p ${tmpdir}
  # get updatesite-core.zip
  # TODO: the build should just create the correct zip name here, instead of "repository.zip"
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/latest/all/repository.zip ${tmpdir}/jbosstools-4.3.0.Beta2-updatesite-core.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/latest/all/repository.zip.sha256 ${tmpdir}/jbosstools-4.3.0.Beta2-updatesite-core.zip.sha256
  # get src.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/latest/all/jbosstools-4.3.0.Beta2-src.zip* ${tmpdir}/
  # get browsersim-standalone.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-browsersim-standalone/latest/jbosstools-*-browsersim-standalone.zip* ${tmpdir}/
  # TODO: generate SHA during the build
  y=$(ls ${tmpdir} | egrep "^jbosstools-.*-browsersim-standalone.zip$"); for m in $(sha256sum ${y}); do if [[ $m != ${y} ]]; then echo $m > ${y}.sha256; fi; done
  echo "mkdir ${site}" | sftp ${TOOLS}/static/mars/development/updates/
  rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/*.zip* ${TOOLS}/static/mars/development/updates/${site}/
  rm -fr $tmpdir
done
echo "DONE: JBT zips" | grep "JBT zips"


# verify site are correct:
version=4.3.0.Beta2
echo "
http://download.jboss.org/jbosstools/static/mars/development/updates/core/ (3 zips + SHAs)
http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}
http://download.jboss.org/jbosstools/static/mars/development/updates/coretests/${version}
http://download.jboss.org/jbosstools/static/mars/development/updates/central/${version}
http://download.jboss.org/jbosstools/static/mars/development/updates/earlyaccess/${version}
  and 
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/${version}
http://download.jboss.org/jbosstools/mars/development/updates/discovery.central/${version}
"

----

=== Update composite site metadata for update

Update files __http://download.jboss.org/jbosstools/mars/development/updates/composite*.xml__ , with SFTP/SCP via command-line or your 
favourite SFTP GUI client (such as Eclipse RSE).

This site needs to contain:
* The latest JBoss Tools core site
* The latest matching target platform site
* The latest matching JBoss Tools Central site

[source,bash]
----

cd ~/tru # or where you have jbosstools-download.jboss.org checked out

pushd jbosstools-download.jboss.org/jbosstools/mars/development/updates

git fetch origin master
git checkout FETCH_HEAD

versionWithRespin_PREV=4.3.0.Beta1
TARGET_PLATFORM_VERSION_MAX_PREV=4.50.0.Beta1
TARGET_PLATFORM_CENTRAL_MAX_PREV=4.50.0.Beta1-SNAPSHOT

version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.50.0.Beta2
TARGET_PLATFORM_CENTRAL_MAX=4.50.0.Beta2-SNAPSHOT

rsync ../../staging/updates/composite*.xml .

# replace static/releases with mars/development/updates, then replace all the versions & fix the update site name
# TODO for .Final, use /static/ paths for target platforms, too!

now=`date +%s000`
for c in compositeContent.xml compositeArtifacts.xml; do 
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
  sed -i -e "s#mars/staging/updates/#static/mars/development/updates/#" $c
  sed -i -e "s#${TARGET_PLATFORM_CENTRAL_MAX_PREV}#${TARGET_PLATFORM_CENTRAL_MAX}#" $c
  sed -i -e "s#${TARGET_PLATFORM_VERSION_MAX_PREV}#${TARGET_PLATFORM_VERSION_MAX}#" $c
  sed -i -e "s#${versionWithRespin_PREV}#${versionWithRespin}#" $c
  sed -i -e "s#${versionWithRespin}#${version}#" $c
  sed -i -e "s#JBoss Tools - static/mars/development/updates/#JBoss Tools ${version} Development Milestone Update Site#" $c
done
cat $c | egrep "${version}|${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${TARGET_PLATFORM_CENTRAL_MAX}|timestamp"

rsync ./composite*.xml core/

# fix core/index.html
pushd core
  rm -f index.html; wget http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/index.html
  sed -i -e "s#href=\"#href=\"http://download.jboss.org/jbosstools/static/mars/development/updates/core/#g" -e "s#href=\"http://download.jboss.org/jbosstools/static/mars/development/updates/core/http#href=\"http#g" -e "s#http://download.jboss.org/jbosstools/static/mars/development/updates/core/web/site.css#http://download.jboss.org/jbosstools/updates/web/site.css#" index.html
  sed -i -e "s#\-SNAPSHOT (\(.\+\))#.\1#" index.html
  if [[ $isFinal == "true" ]]; then
    sed -i -e "s#Development Milestone Update Site#Stable Release Update Site#" index.html
    sed -i -e "s#<b>Development Milestone</b>#<b>Stable Release</b>#" index.html
  fi
  echo "google-chrome file://`pwd`/$f/updates/core/index.html" &
  cat index.html | egrep "Latest Build|SNAPSHOT|Stable|Milestone|${version}|${versionWithRespin}"
popd

# fix EA site
# TODO verify this works for CR1
now=`date +%s000`
pushd earlyaccess
for c in compositeContent.xml compositeArtifacts.xml; do 
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
  sed -i -e "s#mars/staging/updates/#static/mars/development/updates/#" $c
  sed -i -e "s#${TARGET_PLATFORM_CENTRAL_MAX_PREV}#${TARGET_PLATFORM_CENTRAL_MAX}#" $c
  sed -i -e "s#${TARGET_PLATFORM_VERSION_MAX_PREV}#${TARGET_PLATFORM_VERSION_MAX}#" $c
  sed -i -e "s#${versionWithRespin_PREV}#${versionWithRespin}#" $c
  sed -i -e "s#${versionWithRespin}#${version}#" $c
  sed -i -e "s#JBoss Tools - static/mars/development/updates/#JBoss Tools ${version} Development Milestone Update Site#" $c
done
cat $c | egrep "${version}|${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${TARGET_PLATFORM_CENTRAL_MAX}|timestamp"
popd

# commit the change and push to master
git add composite*.xml core/composite*.xml core/index.html earlyaccess/composite*.xml
git commit -m "release JBT ${versionWithRespin} to public" composite*.xml core/composite*.xml core/index.html earlyaccess/composite*.xml
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
scp composite*.xml ${TOOLS}/mars/development/updates/
scp core/composite*.xml core/index.html ${TOOLS}/mars/development/updates/core/
scp earlyaccess/composite*.xml ${TOOLS}/mars/development/updates/earlyaccess/

popd

# verify site contents are shown
echo "http://download.jboss.org/jbosstools/mars/development/updates/compositeContent.xml
http://download.jboss.org/jbosstools/mars/development/updates/core/
http://download.jboss.org/jbosstools/mars/development/updates/core/compositeContent.xml
"

----


=== WebTools

==== Publish Site

Webtools site is expected to be found in +http://download.jboss.org/tools/updates/webtools/mars+. So, with a sftp client, on filemgmt.jboss.org


1. Rename +/updates/webtools/mars+ to +/updates/webtools/mars_${version_PREV}+, with ${version_PREV} being the name of last release before this one
2. Symlink from +/updates/webtools/mars+ to http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/

Here is an example of a script doing that:

[source,bash]
----
cd ~/tru # or where you have jbosstools-download.jboss.org checked out

version=4.3.0.Beta2
version_PREV=4.3.0.Beta1
versionWithRespin=4.3.0.Beta2b # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools

pushd jbosstools-download.jboss.org/jbosstools/updates/webtools
  git fetch origin master
  git checkout FETCH_HEAD

  # create new symlink
  mv mars mars_${version_PREV}
  ln -s ../../static/mars/development/updates/core/${version} mars
  # move the old symlink out of the way
  echo "rename webtools/mars webtools/mars_${version_PREV}" | sftp ${TOOLS}/updates/ #formatting_glitch_
  # push new symlink to server
  rsync -Pzrlt --rsh=ssh --protocol=28 mars $TOOLS/updates/webtools/
  # commit change to github
  git add mars
  git commit -m "update symlink to point at latest ../../static/mars/development/updates/webtools/${version} (${versionWithRespin}) release folder" mars
  git push origin HEAD:master
popd

# verify site contents are shown
echo "http://download.jboss.org/jbosstools/updates/webtools/
http://download.jboss.org/jbosstools/updates/webtools/mars"

----

==== Notify webtools project

If this is the first milestone release (ie if you had to create the 'updates/webtools/mars' directory (next year will be "neon"), ensure that upstream project Web Tools (WTP) knows to include this new URL in their server adapter wizard. New bugzilla required!

* https://issues.jboss.org/browse/JBIDE-18921
* https://bugs.eclipse.org/454810

== Update Target Platforms

If this new release includes a new Target Platform, you need to release the latest target platform. If not, there's nothing to do here.

=== Final/GA releases 

For Final or GA releases, the target platform folders should be moved to /static/ and composited back.

Thus for example, 

http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/4.*.*.Final/
http://download.jboss.org/jbosstools/targetplatforms/jbdevstudiotarget/4.*.*.Final/

should be moved to:

http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/4.*.*.Final/
http://download.jboss.org/jbosstools/static/targetplatforms/jbdevstudiotarget/4.*.*.Final/

Then you can create composites in the old locations pointing to the new one, like this:

https://github.com/jbosstools/jbosstools-download.jboss.org/commit/d5306ce9408144ef681627ad8f5bd1e6c491bcf4

[source,bash]
----

cd ~/tru # or where you have jbosstools-download.jboss.org checked out

TARGET_PLATFORM_VERSION_MAX_PREV=4.50.0.Beta1
TARGET_PLATFORM_VERSION_MAX=4.50.0.Beta2
now=`date +%s000`
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools

pushd jbosstools-download.jboss.org/jbosstools/targetplatforms/
  git fetch origin master
  git checkout FETCH_HEAD

  for f in jbosstools; do
    pushd ${f}target
      mkdir ${TARGET_PLATFORM_VERSION_MAX}
      for d in mars/composite*.xml; do
        sed -i -e "s#${TARGET_PLATFORM_VERSION_MAX_PREV}#${TARGET_PLATFORM_VERSION_MAX}#g" $d
        sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
      done
      mkdir -p ${TARGET_PLATFORM_VERSION_MAX}/REPO/
      cp -f mars/composite* ${TARGET_PLATFORM_VERSION_MAX}/
      cp -f mars/composite* ${TARGET_PLATFORM_VERSION_MAX}/REPO/
    popd
  done

  # check your changes here before changing stuff on the server!

  # for Final TPs only!
  for f in jbosstools; do
    git add ${f}target
    # move actual TP to /static/ folder
    echo "rename targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX} static/targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX}" | sftp ${TOOLS}/
    # create composite pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${f}target/${TARGET_PLATFORM_VERSION_MAX}/* $TOOLS/targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX}/
    # update mars pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${f}target/mars/* $TOOLS/targetplatforms/${f}target/mars/
  done

  for f in jbosstools; do
    # update mars pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${f}target/mars/* $TOOLS/targetplatforms/${f}target/mars/
  done

  # commit changes to github
  git commit -m "move target platforms into /static/ and update composite pointers to latest mars => ${TARGET_PLATFORM_VERSION_MAX}" .
  git push origin HEAD:master
popd

# for Final TPs only!
echo "
view-source:http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/compositeContent.xml (for Final TPs only!) \
view-source:http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/REPO/compositeContent.xml (for Final TPs only!) \
http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/ (for Final TPs only!) "

# verify files are correct
echo "view-source:http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/mars/compositeContent.xml"

----

=== JBoss Central, Early Access, and Discovery

There's nothing more to do here (it was done above). Just review these URLs:

[source,bash]
----

# verify site are correct:
version=4.3.0.Beta2
echo "http://download.jboss.org/jbosstools/static/mars/development/updates/central/${version}
http://download.jboss.org/jbosstools/static/mars/development/updates/earlyaccess/${version}
  and 
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/${version}
http://download.jboss.org/jbosstools/mars/development/updates/discovery.central/${version}
"
----

== Release the latest milestone to ide-config.properties

Check out http://download.jboss.org/jbosstools/configuration/ide-config.properties

Update it so that the links for the latest milestone point to valid URLs. Comment out staging links as required.

[source,bash]
----

# adjust these steps to fit your own path location & git workflow
cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=4.3.0.Beta2
versionWithRespin=4.3.0.Beta2b # a, b, c...

git fetch origin master
git checkout FETCH_HEAD

# then edit ide-config.properties 
# vim ide-config.properties 
# st ide-config.properties 

# verify
echo "
http://download.jboss.org/jbosstools/mars/development/updates/discovery.central/${version}/jbosstools-directory.xml
http://download.jboss.org/jbosstools/mars/development/updates/
http://download.jboss.org/jbosstools/mars/development/updates/compositeContent.xml
http://download.jboss.org/jbosstools/mars/development/updates/earlyaccess/
http://download.jboss.org/jbosstools/mars/development/updates/earlyaccess/compositeContent.xml
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/${version}/jbosstools-earlyaccess.properties
"

# commit the change and push to master
ci "release JBT ${version} (${versionWithRespin}) to public: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
rsync -Pzrlt --rsh=ssh --protocol=28 ide-config.properties $TOOLS/configuration/ide-config.properties
popd

----

== Update Eclipse Marketplace (add/remove features)

WARNING: Only for Beta, CR and GA! We do not release Alphas to Eclipse Marketplace.

=== If node does not yet exist

This is usually the case of first Beta version.

Create a new node on Marketplace, use content of +http://download.jboss.org/jbosstools/static/mars/development/updates/jbosstools-4.3.0.Beta2-updatesite-core/site.properties+

=== If node already exists

Access it via +https://marketplace.eclipse.org/content/jboss-tools/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Update list of features, using content of +http://download.jboss.org/jbosstools/static/mars/development/updates/jbosstools-4.3.0.Beta2-updatesite-core/site.properties+

To diff if any new features have been added/removed:

[source,bash]
----
versionWithRespin_PREV=4.3.0.Beta1
version=4.3.0.Beta2

cd /tmp
wget -O ${versionWithRespin_PREV}.properties http://download.jboss.org/jbosstools/static/mars/development/updates/core/${versionWithRespin_PREV}/site.properties
wget -O ${version}.properties http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/site.properties
diff -u ${versionWithRespin_PREV}.properties ${version}.properties

# then verify the the new feature(s) were added to the CoreTools category

rm -f /tmp/${versionWithRespin_PREV}.properties /tmp/${version}.properties

----


== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Abridged category from http://download.jboss.org/jbosstools/mars/development/updates/ ; restart
3. Open Central Software/Updates tab, enable Early-Access select and install all connectors; restart
4. Check log, start an example project, check log again


== Git tags

=== Create tags for build-related repositories

Once cloned to disk, this script will create the tags if run from the location with your git clones. If tags exist, no new tag will be created.

[source,bash]
----
# if not already cloned, the do this:
git clone https://github.com/jbosstools/jbosstools-build
git clone https://github.com/jbosstools/jbosstools-build-ci
git clone https://github.com/jbosstools/jbosstools-build-sites
git clone https://github.com/jbosstools/jbosstools-devdoc
git clone https://github.com/jbosstools/jbosstools-discovery
git clone https://github.com/jbosstools/jbosstools-download.jboss.org
git clone https://github.com/jbosstools/jbosstools-maven-plugins
git clone https://github.com/jbosstools/jbosstools-versionwatch

# maven-plugins does not get released/branched the same as other projects, but tag it anyway
# download.jboss.org tag might not be valid as tweaks to ide-config.properties happen frequently

jbt_branch=jbosstools-4.3.0.Beta2x
version=4.3.0.Beta2
for d in build build-ci build-sites devdoc discovery download.jboss.org maven-plugins versionwatch; do 
  echo "====================================================================="
  echo "Tagging jbosstools-${d} from branch ${jbt_branch} as tag ${version}..."
  pushd jbosstools-${d}
  git fetch origin ${jbt_branch}
  git tag jbosstools-${version} FETCH_HEAD
  git push origin jbosstools-${version}
  echo ">>> https://github.com/jbosstools/jbosstools-${d}/tree/jbosstools-${version}"
  popd >/dev/null 
  echo "====================================================================="
  echo ""
done
----

=== Announce requirement of tag creation

@deprecated @since 4.3.0.CR1

OLD WAY: Send email to team and have project leads tag their own projects. 

____
*To:* jbosstools-dev@lists.jboss.org + 

[source,bash]
----
version=4.3.0.Beta2
branchName=jbosstools-4.3.0.Beta2x
tagName=jbosstools-4.3.0.Beta2
echo "
Subject:

ACTION REQUIRED: Project leads, please tag your projects [ branch ${branchName} -> tag ${tagName} ] 

Body:

Component leads, please tag your repositories!

$ git fetch jbosstools ${branchName} #assuming remote is called jbosstools, also often called origin
$ git tag ${tagName} FETCH_HEAD
$ git push jbosstools ${tagName}

The complete list of projects in JBoss Tools, and the SHAs used to build those projects, can be seen here:

http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/buildinfo.json
"
----
____

=== Request bulk tag creation

@since 4.3.0.CR1

NEW WAY: bulk-tagging via script. This process is under development. See JBIDE-20152.

*To:* max.andersen@redhat.com, fbricon@redhat.com, alkazako@redhat.com +

[source,bash]
----
version=4.3.0.CR1
echo "
Subject:

Ready for JBT ${version} tag creation

Body:

cd ~/tru # to your clone of jbosstools-build-ci
pushd jbosstools-build-ci/util >/dev/null

# get CSV file & tag repos
curl http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/buildinfo.json | python buildinfo2tags.py \
-n jbosstools-${version} | python tagrepos.py GITHUBUSER GITHUBPWD

----


== Release JIRA

If there are no unresolved issues, release the milestone version in JIRA.

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----


== Update jbosstools-website

Provide a PR to add the latest JBT milestones to this listing: https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml

Example:

* https://github.com/jbosstools/jbosstools-website/pull/193 (note that the JBDS part is better done after & seprarately, while releasing JBDS)
* https://github.com/jbosstools/jbosstools-website/pull/211 (only JBT part of the change)
* https://github.com/jbosstools/jbosstools-website/pull/343 (ony JBT)
* https://github.com/jbosstools/jbosstools-website/pull/388 (only JBT)
* https://github.com/jbosstools/jbosstools-website/pull/418 (JBT / JBDS Beta1)
* https://github.com/jbosstools/jbosstools-website/pull/449 (JBT Beta2)

== Notify Alexey & Max 

Notifify Alexy & Max that the website is ready to be updated & blog ready to be posted. 

If co-releasing JBT and JBDS, make sure that JBDS is released too!

DO NOT send email notification until the above update to the website is done, and the new blog announcement is live, with image inclusion, spelling, & grammar checks done.

____
*To:* max.andersen@redhat.com, fbricon@redhat.com, alkazako@redhat.com +

[source,bash]
----
version=4.3.0.Beta2
eclipseVersion="Eclipse 4.5.0.R Mars"
pullrequestURL=https://github.com/jbosstools/jbosstools-website/pull/449
# NOTE: if releasing on Monday, use Tuesday's date since generally it takes a day for Max to get the blog out.
# TODO https://issues.jboss.org/browse/JBIDE-20144 what should the blog filename be?
blogURL=/blog/beta2-for-mars.html
echo "
Subject: 

Ready for JBT ${version} blog & announcement

Body:

Here's a PR for adding ${version} JBoss Tools download page:

${pullrequestURL}

Suggested blog filename: ${blogURL}

The complete list of projects in JBoss Tools, and the SHAs used to build those projects, can be seen here:

http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/buildinfo.json

From that list you can create all the jbosstools-${version} tags in Github, should you so desire.

Below is a sample email you could send to the jbosstools-dev mailing list when the blog is live.

--

Subject: 

JBoss Tools ${version} is now available

Body:

This is a development release aimed at ${eclipseVersion} users.

Announcement Blog: http://tools.jboss.org/blog/

Eclipse Marketplace: https://marketplace.eclipse.org/content/jboss-tools

Update Site: http://download.jboss.org/jbosstools/mars/development/updates/

Zips: http://download.jboss.org/jbosstools/static/mars/development/updates/core/

Installation instructions: http://tools.jboss.org/downloads/installation.html

New + Noteworthy (subject to change): http://tools.jboss.org/documentation/whatsnew/jbosstools/${version}.html

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBIDE?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel
"

----
____

