= Release JBoss Tools Development Milestone

This document describe how to publish a valid JBoss Tools build to production after being verified by QE.

With distractions (email, IRC), this process took ~90 mins for the Beta release. 

WARNING: this requires write access to http://sourceforge.net/projects/jboss/files/JBossTools/

== Verify that all JIRAs assigned to the current milestone are resolved

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

Note: If there are unresolved issues with a fixversion set to the current milestone, make sure those issues will not be lost / forgotten. 

Send an email to jbosstools-dev@ and jboss-devstudio-list@  reminding people to close out their JIRAs or move them to the next milestone fixversion.

Sample email: http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008799.html

DO NOT proceed with the release if there are any unresolved issues. Only JIRAs allowed before release should be bookeping JIRAs or issues that cannot be closed until the push is complete.

[source,bash]
----
firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions
----

== Summary

Here are some generalities site promotion/release process. It's not an exhaustive list so you need to read the full document to do a release, but it gives an overview of the various steps.

. CI build output is published the 'builds/staging' folder, while aggregated update-sites goes to 'updates/nightly' folder
. After branching, component repository are rebuilt from branch (instead of 'master') and new aggregated updatesites are created as well.  A site is promoted from nightly to staging for QE, and moves from 'updates/nightly' to 'updates/staging', including a respin suffix if required.
.. If QE finds a blocker issue, a respin is requested
... On Jira, add a 'respin-a' or 'respin-b' or 'respin-x' label to bugs that needs for be fixed for the respin
... Edit CI jobs to the next respin label (eg CR2b)
... Re-run necessary jobs
... Go To 1
.. If QE approves, release is accepted and promoted
... JIRA is checked to ensure all JIRAs for this milestone are resolved
... Zips get published on sourceforge
... Site moves from 'updates/staging' with respin label to 'static/releases' without respin label
... Links to 'updates/mars' are replaced to link to new version
... JBoss Tools website is updated
... Git repositories are tagged
... Eclipse Marketplace entries are created or updated
... JIRA version can be released
... Interested parties are notified


== Copy sites

These steps happens on filemgmt.jboss.org, in the jbosstools download area.

=== Copy content to release directory

We simply copy the content of the latest respin to the release directory (under _jbosstools/static_ which is using Akamai)

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Here is a script that performs the copy from /staging/ to /development/.

PLEASE NOTE! If you're pushing a new /development/ site and the last release was to /stable/, make sure you disconnect the symlinks first or you'll end up putting a milestone into /stable/ instead of /development/.

See section "Copy from development to stable & create symlinks from /stable/ into /development/" for details.


[source,bash]
----
# TODO: add a step to check if versionWithRespin ends with ".Final"; if so, use /stable/ instead of /development/
# copy from staging to development (under /static/ for Akamai performance)

# Do these 5 steps in parallel to save time

# JBT aggregate site
version=4.3.1.Beta1
versionWithRespin=4.3.1.Beta1a # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
for site in core; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/
  # copy update site
  for qual in $quals; do
    echo "mkdir ${site}" | sftp ${TOOLS}/static/mars/${qual}/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/static/mars/${qual}/updates/${site}/${version}/
  done
  rm -fr $tmpdir
done
echo "DONE: JBT aggregate site" | grep "JBT aggregate site"


# JBT tests site
version=4.3.1.Beta1
versionWithRespin=4.3.1.Beta1a # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
for site in coretests; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/
  # copy update site
  for qual in $quals; do
    echo "mkdir ${site}" | sftp ${TOOLS}/static/mars/${qual}/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/static/mars/${qual}/updates/${site}/${version}/
  done
  rm -fr $tmpdir
done
echo "DONE: JBT tests site" | grep "JBT tests site"


# Central and EA sites
version=4.3.1.Beta1
versionWithRespin=4.3.1.Beta1a # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
for site in central earlyaccess; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/
  # copy update site
  for qual in $quals; do
    echo "mkdir ${site}" | sftp ${TOOLS}/static/mars/${qual}/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/static/mars/${qual}/updates/${site}/${version}/
  done
  rm -fr $tmpdir
done
echo "DONE: Central and EA sites" | grep "Central and EA sites"


# JBT discovery sites
# unlike above, don't use /static/ paths here because we're going to have to change the content to point to correct paths below
version=4.3.1.Beta1
versionWithRespin=4.3.1.Beta1a # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
for site in discovery.central discovery.earlyaccess; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}
  for qual in $quals; do
    rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/updates/${site}/${versionWithRespin}/* ${tmpdir}/
    # sed .xml files to point at /development/ instead of /staging/, and ${version} instead of $versionWithRespin}
    if [[ ${site/discovery/} != ${site} ]]; then 
      pushd ${tmpdir}/ >/dev/null
      now=`date +%s000`
      for c in compositeContent.xml compositeArtifacts.xml; do 
        sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
        sed -i -e "s#jbosstools/mars#jbosstools/static/mars#" $c
        sed -i -e "s#staging#${qual}#" $c
        sed -i -e "s#${versionWithRespin}#${version}#" $c
      done
      cat compositeContent.xml | egrep "staging|development|${version}|${versionWithRespin}|static"
      popd >/dev/null
    fi
    # copy update site
    echo "mkdir ${site}" | sftp ${TOOLS}/mars/${qual}/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/mars/${qual}/updates/${site}/${version}/
  done
  rm -fr $tmpdir
done
echo "DONE: JBT discovery sites" | grep "JBT discovery sites"


# JBT zips into http://download.jboss.org/jbosstools/static/mars/development/updates/core/
version=4.3.1.Beta1
versionWithRespin=4.3.1.Beta1a # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
for site in core; do
  tmpdir=/tmp/jbosstools-static-development-updates-${site}_${versionWithRespin}_zips; mkdir -p ${tmpdir}
  # get updatesite-core.zip
  # TODO: the build should just create the correct zip name here, instead of "repository.zip"
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/latest/all/repository.zip ${tmpdir}/jbosstools-${version}-updatesite-core.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/latest/all/repository.zip.sha256 ${tmpdir}/jbosstools-${version}-updatesite-core.zip.sha256
  # get src.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-core/latest/all/jbosstools-${version}-src.zip* ${tmpdir}/
  # get browsersim-standalone.zip
  rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-browsersim-standalone/latest/jbosstools-*-browsersim-standalone.zip* ${tmpdir}/
  for qual in $quals; do
    echo "mkdir ${site}" | sftp ${TOOLS}/static/mars/${qual}/updates/
    rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/*.zip* ${TOOLS}/static/mars/${qual}/updates/${site}/
  done
  rm -fr $tmpdir
done
echo "DONE: JBT zips" | grep "JBT zips"


#  verify sites are correctly populated (run locally, not on dev01):
version=4.3.1.Beta1
tmpfile=/tmp/jbosstools-staging__verify.txt
quals="development"; if [[ ${version##*Final} == "" ]]; then quals="development stable"; fi
for site in site coretests-site central-site earlyaccess-site; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  for qual in $quals; do
    echo "http://download.jboss.org/jbosstools/static/mars/${qual}/updates/${sitename}/${version}/ " >> $tmpfile
  done
done
for site in discovery.central discovery.earlyaccess; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  for qual in $quals; do
    echo "http://download.jboss.org/jbosstools/mars/${qual}/updates/${sitename}/${version}/ " >> $tmpfile
  done
done
# browsersim standalone zip, src zip, update site zip
for qual in $quals; do
  echo "http://download.jboss.org/jbosstools/static/mars/${qual}/updates/core/#_____(3_zips_+_SHAs,_and_${version}_folder) " >> $tmpfile
done
echo "" >> $tmpfile
cat $tmpfile
firefox `cat $tmpfile`
rm -fr $tmpfile


----

=== Update composite site metadata for update

Update files __http://download.jboss.org/jbosstools/mars/development/updates/composite*.xml__ , with SFTP/SCP via command-line or your 
favourite SFTP GUI client (such as Eclipse RSE).

This site needs to contain:
* The latest JBoss Tools core site
* The latest matching target platform site
* The latest matching JBoss Tools Central site

[source,bash]
----

cd ~/tru # or where you have jbosstools-download.jboss.org checked out

pushd jbosstools-download.jboss.org/jbosstools/mars/development/updates

git fetch origin master
git checkout FETCH_HEAD

versionWithRespin_PREV=4.3.0.Final
TARGET_PLATFORM_VERSION_MAX_PREV=4.51.0.Final
TARGET_PLATFORM_CENTRAL_MAX_PREV=4.50.0.Final-SNAPSHOT

version=4.3.1.Beta1
versionWithRespin=4.3.1.Beta1a # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.51.2.Beta1-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX=4.51.0.Beta1-SNAPSHOT

rsync ../../staging/updates/composite*.xml .

# replace static/releases with mars/development/updates, then replace all the versions & fix the update site name
# TODO for .Final, use /static/ paths for target platforms, too!

now=`date +%s000`
for c in compositeContent.xml compositeArtifacts.xml; do 
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
  sed -i -e "s#mars/staging/updates/#static/mars/development/updates/#" $c
  sed -i -e "s#${TARGET_PLATFORM_CENTRAL_MAX_PREV}#${TARGET_PLATFORM_CENTRAL_MAX}#" $c
  sed -i -e "s#${TARGET_PLATFORM_VERSION_MAX_PREV}#${TARGET_PLATFORM_VERSION_MAX}#" $c
  sed -i -e "s#${versionWithRespin_PREV}#${versionWithRespin}#" $c
  sed -i -e "s#${versionWithRespin}#${version}#" $c
  # TODO for Beta2 make sure this next step works!
  sed -i -e "s#static/mars/development/updates/integration-stack'/#mars/development/updates/integration-stack/'" $c
  sed -i -e "s#JBoss Tools - static/mars/development/updates/#JBoss Tools ${version} Development Milestone Update Site#" $c
done
cat $c | egrep "${version}|${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${TARGET_PLATFORM_CENTRAL_MAX}|timestamp"

rsync ./composite*.xml core/

# fix core/index.html
pushd core
  rm -f index.html; wget http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/index.html
  sed -i -e "s#href=\"#href=\"http://download.jboss.org/jbosstools/static/mars/development/updates/core/#g" -e "s#href=\"http://download.jboss.org/jbosstools/static/mars/development/updates/core/http#href=\"http#g" -e "s#http://download.jboss.org/jbosstools/static/mars/development/updates/core/web/site.css#http://download.jboss.org/jbosstools/updates/web/site.css#" index.html
  sed -i -e "s#\-SNAPSHOT (\(.\+\))#.\1#" index.html
  if [[ $isFinal == "true" ]]; then
    sed -i -e "s#Development Milestone Update Site#Stable Release Update Site#" index.html
    sed -i -e "s#<b>Development Milestone</b>#<b>Stable Release</b>#" index.html
  fi
  firefox file://`pwd`/index.html &
  cat index.html | egrep "Latest Build|SNAPSHOT|Stable|Milestone|${version}|${versionWithRespin}"
popd

pushd coretests
  # fix coretests/composite*.xml
  now=`date +%s000`
  for c in compositeContent.xml compositeArtifacts.xml; do 
    sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
    sed -i -e "s#mars/staging/updates/#static/mars/development/updates/#" $c
    sed -i -e "s#${versionWithRespin_PREV}#${versionWithRespin}#" $c
    sed -i -e "s#${versionWithRespin}#${version}#" $c
    sed -i -e "s#JBoss Tools - static/mars/development/updates/#JBoss Tools ${version} Development Milestone Update Site#" $c
  done
  cat $c | egrep "${version}|${versionWithRespin}|timestamp"

  # fix coretests/index.html
  rm -f index.html; wget http://download.jboss.org/jbosstools/static/mars/development/updates/coretests/${version}/index.html
  sed -i -e "s#href=\"#href=\"http://download.jboss.org/jbosstools/static/mars/development/updates/coretests/#g" -e "s#href=\"http://download.jboss.org/jbosstools/static/mars/development/updates/coretests/http#href=\"http#g" -e "s#http://download.jboss.org/jbosstools/static/mars/development/updates/coretests/web/site.css#http://download.jboss.org/jbosstools/updates/web/site.css#" index.html
  sed -i -e "s#\-SNAPSHOT (\(.\+\))#.\1#" index.html
  if [[ $isFinal == "true" ]]; then
    sed -i -e "s#Development Milestone Update Site#Stable Release Update Site#" index.html
    sed -i -e "s#<b>Development Milestone</b>#<b>Stable Release</b>#" index.html
  fi
  firefox file://`pwd`/index.html &
  cat index.html | egrep "Latest Build|SNAPSHOT|Stable|Milestone|${version}|${versionWithRespin}"
popd

# fix EA site
now=`date +%s000`
pushd earlyaccess
for c in compositeContent.xml compositeArtifacts.xml; do 
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
  sed -i -e "s#mars/staging/updates/#static/mars/development/updates/#" $c
  sed -i -e "s#${TARGET_PLATFORM_CENTRAL_MAX_PREV}#${TARGET_PLATFORM_CENTRAL_MAX}#" $c
  sed -i -e "s#${TARGET_PLATFORM_VERSION_MAX_PREV}#${TARGET_PLATFORM_VERSION_MAX}#" $c
  sed -i -e "s#${versionWithRespin_PREV}#${versionWithRespin}#" $c
  sed -i -e "s#${versionWithRespin}#${version}#" $c
  sed -i -e "s#JBoss Tools - static/mars/development/updates/#JBoss Tools ${version} Development Milestone Update Site#" $c
done
cat $c | egrep "${version}|${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${TARGET_PLATFORM_CENTRAL_MAX}|timestamp"
popd

# commit the change and push to master
git add composite*.xml core/composite*.xml core/index.html coretests/composite*.xml coretests/index.html discovery.earlyaccess/composite*.xml
git commit -m "release JBT ${versionWithRespin} to public" composite*.xml core/composite*.xml core/index.html coretests/composite*.xml coretests/index.html discovery.earlyaccess/composite*.xml
git push origin HEAD:master

# push updated files to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
scp composite*.xml ${TOOLS}/mars/development/updates/
scp core/composite*.xml core/index.html ${TOOLS}/mars/development/updates/core/
scp coretests/composite*.xml coretests/index.html ${TOOLS}/mars/development/updates/coretests/
scp discovery.earlyaccess/composite*.xml ${TOOLS}/mars/development/updates/discovery.earlyaccess/

popd

# verify site contents are shown
firefox \
http://download.jboss.org/jbosstools/mars/development/updates/ \
http://download.jboss.org/jbosstools/mars/development/updates/core/ \
http://download.jboss.org/jbosstools/mars/development/updates/coretests/ \
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/ \
http://download.jboss.org/jbosstools/mars/development/updates/earlyaccess/ \
http://download.jboss.org/jbosstools/mars/development/updates/compositeContent.xml \
http://download.jboss.org/jbosstools/mars/development/updates/core/compositeContent.xml \
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/compositeContent.xml \
http://download.jboss.org/jbosstools/mars/development/updates/earlyaccess/compositeContent.xml \

----

If this is a /stable/ release, carefully merge changes from /development into /stable, then commit your changes & push to the server. Verify:

[source,bash]
----

# verify site contents are shown
firefox \
http://download.jboss.org/jbosstools/mars/stable/updates/ \
http://download.jboss.org/jbosstools/mars/stable/updates/core/ \
http://download.jboss.org/jbosstools/mars/stable/updates/coretests/ \
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.earlyaccess/ \
http://download.jboss.org/jbosstools/mars/stable/updates/earlyaccess/ \
http://download.jboss.org/jbosstools/mars/stable/updates/compositeContent.xml \
http://download.jboss.org/jbosstools/mars/stable/updates/core/compositeContent.xml \
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.earlyaccess/compositeContent.xml \
http://download.jboss.org/jbosstools/mars/stable/updates/earlyaccess/compositeContent.xml \

----


=== WebTools

==== Publish Site

Webtools site is expected to be found in +http://download.jboss.org/tools/updates/webtools/mars+. So, with a sftp client, on filemgmt.jboss.org


1. Rename +/updates/webtools/mars+ to +/updates/webtools/mars_${version_PREV}+, with ${version_PREV} being the name of last release before this one
2. Symlink from +/updates/webtools/mars+ to http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/

Here is an example of a script doing that. 

NOTE: if this is a /stable/ .Final release, update the script accordingly.
NOTE: if you're releasing a /development/ milestone after there's an existing /stable/ one, SKIP THIS STEP until the /development/ release is ALSO a stable (eg., 4.3.1.Final, not 4.3.1.Beta)

[source,bash]
----
cd ~/tru # or where you have jbosstools-download.jboss.org checked out

version=4.3.1.Beta1
version_PREV=4.3.0.Final
versionWithRespin=4.3.1.Beta1a # a, b, c...
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools

pushd jbosstools-download.jboss.org/jbosstools/updates/webtools
  git fetch origin master
  git checkout FETCH_HEAD

  # create new symlink
  mv mars mars_${version_PREV}
  ln -s ../../static/mars/development/updates/core/${version} mars
  # move the old symlink out of the way
  echo "rename webtools/mars webtools/mars_${version_PREV}" | sftp ${TOOLS}/updates/ #formatting_glitch_
  # push new symlink to server
  rsync -Pzrlt --rsh=ssh --protocol=28 mars $TOOLS/updates/webtools/
  # commit change to github
  git add mars
  git commit -m "update symlink to point at latest ../../static/mars/development/updates/webtools/${version} (${versionWithRespin}) release folder" mars
  git push origin HEAD:master
popd

# verify site contents are shown
firefox http://download.jboss.org/jbosstools/updates/webtools/ http://download.jboss.org/jbosstools/updates/webtools/mars

----

==== Notify webtools project

If this is the first milestone release (ie if you had to create the 'updates/webtools/mars' directory (next year will be "neon"), ensure that upstream project Web Tools (WTP) knows to include this new URL in their server adapter wizard. New bugzilla required!

* https://issues.jboss.org/browse/JBIDE-18921
* https://bugs.eclipse.org/454810

== Update Target Platforms

If this new release includes a new Target Platform, you need to release the latest target platform. If not, there's nothing to do here.

=== Final/GA releases 

For Final or GA releases, the target platform folders should be moved to /static/ and composited back.

Thus for example, 

http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/4.*.*.Final/
http://download.jboss.org/jbosstools/targetplatforms/jbdevstudiotarget/4.*.*.Final/

should be moved to:

http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/4.*.*.Final/
http://download.jboss.org/jbosstools/static/targetplatforms/jbdevstudiotarget/4.*.*.Final/

Then you can create composites in the old locations pointing to the new one, like this:

https://github.com/jbosstools/jbosstools-download.jboss.org/commit/d5306ce9408144ef681627ad8f5bd1e6c491bcf4

[source,bash]
----

cd ~/tru # or where you have jbosstools-download.jboss.org checked out

TARGET_PLATFORM_VERSION_MAX_PREV=4.50.0.Final
TARGET_PLATFORM_VERSION_MAX=4.51.2.Beta1-SNAPSHOT
now=`date +%s000`
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools

pushd jbosstools-download.jboss.org/jbosstools/targetplatforms/
  git fetch origin master
  git checkout FETCH_HEAD

  for f in jbosstools; do
    pushd ${f}target
      mkdir ${TARGET_PLATFORM_VERSION_MAX}
      for d in mars/composite*.xml; do
        sed -i -e "s#${TARGET_PLATFORM_VERSION_MAX_PREV}#${TARGET_PLATFORM_VERSION_MAX}#g" $d
        sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#g" $d
      done
      mkdir -p ${TARGET_PLATFORM_VERSION_MAX}/REPO/
      cp -f mars/composite* ${TARGET_PLATFORM_VERSION_MAX}/
      cp -f mars/composite* ${TARGET_PLATFORM_VERSION_MAX}/REPO/
    popd
  done

  # check your changes here before changing stuff on the server!

  # for Final TPs only!
  for f in jbosstools; do
    git add ${f}target
    # move actual TP to /static/ folder
    echo "rename targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX} static/targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX}" | sftp ${TOOLS}/
    # change pointer to include /static/
    for d in ${f}target/${TARGET_PLATFORM_VERSION_MAX}/composite*.xml ${f}target/${TARGET_PLATFORM_VERSION_MAX}/REPO/composite*.xml; do
      sed -i -e "s#jbosstools/targetplatforms#jbosstools/static/targetplatforms#g" $d
    done
    # create composite pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${f}target/${TARGET_PLATFORM_VERSION_MAX}/* $TOOLS/targetplatforms/${f}target/${TARGET_PLATFORM_VERSION_MAX}/
    # update mars pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${f}target/mars/* $TOOLS/targetplatforms/${f}target/mars/
  done

  for f in jbosstools; do
    # update mars pointer
    rsync -Pzrlt --rsh=ssh --protocol=28 ${f}target/mars/* $TOOLS/targetplatforms/${f}target/mars/
  done

  # commit changes to github
  git commit -m "move target platforms into /static/ and update composite pointers to latest mars => ${TARGET_PLATFORM_VERSION_MAX}" .
  git push origin HEAD:master
popd

# for Final TPs only!
firefox \
http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/REPO/ \
http://download.jboss.org/jbosstools/static/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/compositeContent.xml \

# verify files are correct
firefox \
http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/REPO/compositeContent.xml \
http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}/compositeContent.xml \
http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/mars/compositeContent.xml

----

=== JBoss Central, Early Access, and Discovery

There's nothing more to do here (it was done above). Just review these URLs:

[source,bash]
----

# verify site are correct:
version=4.3.1.Beta1
firefox \
http://download.jboss.org/jbosstools/static/mars/development/updates/central/${version} \
http://download.jboss.org/jbosstools/static/mars/development/updates/earlyaccess/${version} \
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/${version} \
http://download.jboss.org/jbosstools/mars/development/updates/discovery.central/${version} 

----

If this is a .Final release:

[source,bash]
----
version=4.3.1.Beta1
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
cd ~/tru
for d in central earlyaccess; do
  pushd jbosstools-download.jboss.org/jbosstools/mars/stable/updates/discovery.${d}
    scpr $TOOLS/mars/development/updates/discovery.${d}/${version} ./
    scpr ${version} $TOOLS/mars/stable/updates/discovery.${d}/
  popd
  pushd jbosstools-download.jboss.org/jbosstools/static/mars/stable/updates/${d}
    scpr $TOOLS/static/mars/development/updates/${d}/${version} ./
    scpr ${version} $TOOLS/static/mars/stable/updates/${d}/
    cd ..; ln -s ${d} discovery.${d}
  popd
done

# verify site are correct:
version=4.3.1.Beta1
firefox \
http://download.jboss.org/jbosstools/static/mars/stable/updates/central/${version} \
http://download.jboss.org/jbosstools/static/mars/stable/updates/earlyaccess/${version} \
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.earlyaccess/${version} \
http://download.jboss.org/jbosstools/mars/stable/updates/discovery.central/${version} 

----


== Copy from development to stable & create symlinks from /stable/ into /development/

If this is a .Final release:

First, mount an sshfs drive for $TOOLS, tools@filemgmt.jboss.org:/downloads_htdocs/tools, eg., into /media/TOOLS-ssh/

Then, ensure that the destination dirs exist. Move the contents of /development/ into /stable/, then symlink back from the old place:

[source,bash]
----

# TODO verify this works for 4.3.1.Final

TOOLSmnt=/media/TOOLS-ssh
version=4.3.1.Beta1
mkdir -p ${TOOLSmnt}/static/mars/{development,stable}/updates/{central,core,coretests,earlyaccess}
for d in central core coretests earlyaccess; do
  if [[ ! -d ${TOOLSmnt}/static/mars/stable/updates/${d}/${version} ]]; then mv ${TOOLSmnt}/static/mars/{development,stable}/updates/${d}/${version}; fi
  pushd ${TOOLSmnt}/static/mars/development/updates/${d}/; rm -f $version; ln -s ../../../../../static/mars/stable/updates/${d}/${version}/; popd
  ls -la ${TOOLSmnt}/static/mars/{development,stable}/updates/${d}
  firefox http://download.jboss.org/jbosstools/static/mars/development/updates/${d}/ http://download.jboss.org/jbosstools/static/mars/development/updates/${d}/${version}
done

# verify discovery content is where it should be:
for d in ${TOOLSmnt}/mars/{development,stable}/updates/{discovery.,}{central,earlyaccess}; do 
  echo $d; 
  if [[ -L "${d}" ]]; then #symlinks
    ls -la ${d}/.. | egrep "$(basename ${d})" | grep -- "->"
  else # normal dirs
    ls -la ${d}
  fi
  echo ""
done

# verify discovery content is where it should be:
for d in ${TOOLSmnt}/static/mars/{development,stable}/updates/{central,earlyaccess}; do 
  echo $d; 
  if [[ -L "${d}" ]]; then #symlinks
    ls -la ${d}/.. | egrep "$(basename ${d})" | grep -- "->"
  else # normal dirs
    ls -la ${d}
  fi
  echo ""
done


----

Also, make sure that links in composite*.xml files point at the /stable/ URLs, not the /development/ ones.



== Release the latest milestone to ide-config.properties

Check out http://download.jboss.org/jbosstools/configuration/ide-config.properties

Update it so that the links for the latest milestone point to valid URLs. Comment out staging links as required.

[source,bash]
----

# adjust these steps to fit your own path location & git workflow
cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=4.3.1.Beta1
versionWithRespin=4.3.1.Beta1a # a, b, c...

git fetch origin master
git checkout FETCH_HEAD

# you'll want to use URLs like these
firefox \
http://download.jboss.org/jbosstools/mars/development/updates/discovery.central/${version}/jbosstools-directory.xml \
http://download.jboss.org/jbosstools/mars/development/updates/ \
http://download.jboss.org/jbosstools/mars/development/updates/compositeContent.xml \
http://download.jboss.org/jbosstools/mars/development/updates/earlyaccess/ \
http://download.jboss.org/jbosstools/mars/development/updates/earlyaccess/compositeContent.xml \
http://download.jboss.org/jbosstools/mars/development/updates/discovery.earlyaccess/${version}/jbosstools-earlyaccess.properties \

# then edit ide-config.properties 
# vim ide-config.properties 
st ide-config.properties 

# commit the change and push to master
ci "release JBT ${version} (${versionWithRespin}) to public: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
rsync -Pzrlt --rsh=ssh --protocol=28 ide-config.properties $TOOLS/configuration/ide-config.properties
popd

----

== Update Eclipse Marketplace (add/remove features)

WARNING: Only for Beta, CR and GA! We do not release Alphas to Eclipse Marketplace.
NOTE: for 4.3.1.*, we will skip this step until Final (no Betas)!

=== If node does not yet exist

This is usually the case of first Beta version.

Create a new node on Marketplace, use content of http://download.jboss.org/jbosstools/static/mars/stable/updates/core/4.3.1.Beta1/site.properties

=== If node already exists

Access it via +https://marketplace.eclipse.org/content/jboss-tools/edit+ and update the following things:

* Title to match new version
* Description to match new version & dependencies
* Update list of features, using content of http://download.jboss.org/jbosstools/static/mars/stable/updates/core/4.3.1.Beta1/site.properties

To diff if any new features have been added/removed:

[source,bash]
----
versionWithRespin_PREV=4.3.0.Final
version=4.3.1.Beta1

cd /tmp
wget -O ${versionWithRespin_PREV}.properties http://download.jboss.org/jbosstools/static/mars/development/updates/core/${versionWithRespin_PREV}/site.properties
wget -O ${version}.properties http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/site.properties
diff -u ${versionWithRespin_PREV}.properties ${version}.properties

# then verify the the new feature(s) were added to the CoreTools category
firefox https://marketplace.eclipse.org/content/jboss-tools/edit

rm -f /tmp/${versionWithRespin_PREV}.properties /tmp/${version}.properties

----


== Smoke test the release

Before notifying team of release, must check for obvious problems. Any failure there should be fixed with highest priority. In general, it could be wrong URLs in a composite site.

=== Validate update site install 

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Abridged category from http://download.jboss.org/jbosstools/mars/development/updates/ and/or http://download.jboss.org/jbosstools/mars/stable/updates/
3. Restart. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again

=== Validate Marketplace install

1. Get a compatible Eclipse
2. Install from Marketplace
3. Install everything from Central + Earlyaccess
4. Test a project example


== Git tags

=== Create tags for build-related repositories

Once cloned to disk, this script will create the tags if run from the location with your git clones. If tags exist, no new tag will be created.

[source,bash]
----

# if not already cloned, the do this:
git clone https://github.com/jbosstools/jbosstools-build
git clone https://github.com/jbosstools/jbosstools-build-ci
git clone https://github.com/jbosstools/jbosstools-build-sites
git clone https://github.com/jbosstools/jbosstools-devdoc
git clone https://github.com/jbosstools/jbosstools-discovery
git clone https://github.com/jbosstools/jbosstools-download.jboss.org
git clone https://github.com/jbosstools/jbosstools-maven-plugins
git clone https://github.com/jbosstools/jbosstools-versionwatch

# maven-plugins does not get released/branched the same as other projects, but tag it anyway
# download.jboss.org tag might not be valid as tweaks to ide-config.properties happen frequently

jbt_branch=jbosstools-4.3.x
version=4.3.1.Beta1
for d in build build-ci build-sites devdoc discovery download.jboss.org maven-plugins versionwatch; do 
  echo "====================================================================="
  echo "Tagging jbosstools-${d} from branch ${jbt_branch} as tag ${version}..."
  pushd jbosstools-${d}
  git fetch origin ${jbt_branch}
  git tag jbosstools-${version} FETCH_HEAD
  git push origin jbosstools-${version}
  echo ">>> https://github.com/jbosstools/jbosstools-${d}/tree/jbosstools-${version}"
  popd >/dev/null 
  echo "====================================================================="
  echo ""
done

----

=== Request bulk tag creation

@since 4.3

NEW WAY: bulk-tagging via script. This process is under development. See JBIDE-20152.

*To:* max.andersen@redhat.com, fbricon@redhat.com, alkazako@redhat.com +

[source,bash]
----
version=4.3.1.Beta1
echo "
Subject:

Ready for JBT ${version} tag creation

Body:

cd ~/tru # to your clone of jbosstools-build-ci
pushd jbosstools-build-ci/util >/dev/null

# get CSV file & tag repos
curl http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/buildinfo.json | python buildinfo2tags.py \
-n jbosstools-${version} | python tagrepos.py GITHUBUSER GITHUBPWD
"

----


== Release JIRA

If there are no unresolved issues, release the milestone version in JIRA.

Launch the config pages for JBIDE and JBDS and using the gear icons, release the milestone version in JIRA. 

[source,bash]
----

firefox https://issues.jboss.org/plugins/servlet/project-config/JBIDE/versions \
  https://issues.jboss.org/plugins/servlet/project-config/JBDS/versions

----


== Update jbosstools-website

Provide a PR to add the latest JBT milestones to this listing: https://github.com/jbosstools/jbosstools-website/blob/master/_config/products.yml_

Example:

* https://github.com/jbosstools/jbosstools-website/pull/193 (note that the JBDS part is better done after & seprarately, while releasing JBDS)
* https://github.com/jbosstools/jbosstools-website/pull/211 (only JBT part of the change)
* https://github.com/jbosstools/jbosstools-website/pull/343 (ony JBT)
* https://github.com/jbosstools/jbosstools-website/pull/388 (only JBT)
* https://github.com/jbosstools/jbosstools-website/pull/418 (JBT / JBDS Beta1)
* https://github.com/jbosstools/jbosstools-website/pull/449 (JBT Beta2)
* https://github.com/jbosstools/jbosstools-website/pull/488 (JBT CR2)
* https://github.com/jbosstools/jbosstools-website/pull/513 (JBDS GA)


== Enable jobs

TODO: JBIDE-21407 verify this process is fleshed out for Beta2 staging/release

NOTE: This should have been done after staging, but just in case it was not, here's a reminder.

As you have just released something, the next build will be a CI snapshot for the following milestone.

Thus, you need to:

* re-enable jobs that were disabled during staging
* set correct github branch, eg., switch from 4.3.1.Beta2x to 4.3.x
* upversion dependencies, eg., releng scripts move from version Beta2 to CR1 (if that's been released)
* upversion target platforms / Central version (if those have been released)


== Notify Alexey & Max 

Notifify Alexy & Max that the website is ready to be updated & blog ready to be posted. 

If co-releasing JBT and JBDS, make sure that JBDS is released too!

DO NOT send email notification until the above update to the website is done, and the new blog announcement is live, with image inclusion, spelling, & grammar checks done.

____
*To:* alkazako@redhat.com +
*Cc:* max.andersen@redhat.com, fbricon@redhat.com +

[source,bash]
----

version=4.3.1.Beta1
eclipseVersion="Eclipse 4.5.1 Mars.1"
pullrequestURL=https://github.com/jbosstools/jbosstools-website/pull/540

blogURL=/blog/beta1-for-mars2.html

echo "
Subject: 

Ready for JBT ${version} blog & announcement

Body:

Here's a PR for adding ${version} JBoss Tools download page:

${pullrequestURL}

Suggested blog filename: ${blogURL}

The complete list of projects in JBoss Tools, and the SHAs used to build those projects, can be seen here:

http://download.jboss.org/jbosstools/static/mars/development/updates/core/${version}/buildinfo.json

From that list you can create all the jbosstools-${version} tags in Github, should you so desire.

Below is a sample email you could send to the jbosstools-dev mailing list when the blog is live.

--

Subject: 

JBoss Tools ${version} is now available

Body:

This is a development release aimed at ${eclipseVersion} users.

Announcement Blog: http://tools.jboss.org/blog/

Eclipse Marketplace: https://marketplace.eclipse.org/content/jboss-tools

Update Site: http://download.jboss.org/jbosstools/mars/development/updates/

Zips: http://tools.jboss.org/downloads/jbosstools/mars/${version}.html#zips

Installation instructions: http://tools.jboss.org/downloads/installation.html

New + Noteworthy (subject to change): http://tools.jboss.org/documentation/whatsnew/jbosstools/${version}.html

Schedule / Upcoming Releases: https://issues.jboss.org/browse/JBIDE?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel
"

----
____

