= Publishing JBT update sites for QE

This document describe how to provide a valid JBoss Tools build to QE so they can test us.

TODO: use consistent instructions for fetching sources from git & pushing changes

[NOTE]
====
Note that +sftp://tools@filemgmt.jboss.org/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+ +

If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools . 
A Jenkins job can then be triggered to sync changes to download.jboss.org: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-download.jboss.org-rsync-from-svn/
====

== Verify correct version set in org.jboss.tools.foundation.core

Check o.j.t.foundation.core's currentversion.properties for the correct value of default.version

[sources,bash]
----
# @Since JBT 4.2.1 / JBDS 8.0.1 - JBIDE-18820, JBIDE-18806

version=4.3.0.CR1
versionWithRespin=4.3.0.CR1a # a, b, c...

if [[ ${version:0:1} == "4" ]]; then # JBT
  pluginName=foundation.core
  updatesiteURL=http://download.jboss.org/jbosstools/mars/staging/updates/core/${versionWithRespin}/plugins/
  updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/4.3.mars/plugins/
  #updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/master/plugins/
else
  pluginName=core.central
  updatesiteURL=https://devstudio.redhat.com/9.0/staging/updates/core/${versionWithRespin}/plugins/
  updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/4.3.mars/plugins/
  #updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/master/plugins/
fi
pushd /tmp; wget -q -nc $updatesiteURL
thejars=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort`
echo "Found: $thejars" | egrep ${pluginName}
thejar=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort | tail -1; rm -f index.html`
echo ${updatesiteURL}/${thejar} | egrep ${pluginName}
wget -q -nc ${updatesiteURL}/${thejar}
theversion=`unzip -p ${thejar} */currentversion.properties | grep version= | sed -e "s/version=//" | tail -1`; theversion=${theversion/-SNAPSHOT/} # remove -SNAPSHOT suffix from version
rm -f ${thejar}
popd
echo "In ${pluginName}, want ${version}, got $theversion" | egrep "${pluginName}|${version}"

----

If value found above for `$theversion` != current release version, then you need to rebuild foundation or JBDS w/ a new value inserted.


== Verify all branches have been created & all master branch root poms point to the NEXT parent pom version.

Chances are you opened a JIRA like https://issues.jboss.org/browse/JBIDE-18149 and asked everyone to branch and then upversion the references to the parent pom in their root poms.
Chances are also that someone might have forgotten to do this.

So, to ensure everyone has done what they need to do, you can run two scripts:

* ensure all the branches exist.

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/getProjectSHAs.sh

* ensure the root poms are correct

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/getProjectRootPomParents.sh

If any branches have not yet been created, you can either:
* Ask Denis, Fred, or Max to get them created
* Reconfigure the jobs to build from your fork, and create the branch there

If any of the root poms have not been correctly updated, simply re-open the task JIRAs like https://issues.jboss.org/browse/JBIDE-18167 and ask that the root pom be updated.

Once the above conditions have been met, you can proceed to the next steps.

== Disable jobs

To prevent accidentally rebuilding something while you're copying it away, make sure that all the stable branch jobs (4.3.mars, 9.0.mars) are disabled. These include all product, composite and aggregate jobs:

[source,bash]
----
firefox \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-composite-install_4.3.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-browsersim-standalone_4.3.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-build-sites.aggregate.site_4.3.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-build-sites.aggregate.coretests-site_4.3.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-build-sites.aggregate.child-sites_4.3.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/devstudio.product_9.0.mars/ \

----

You may also want to disable these:

[source,bash]
----
firefox \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-build.parent_4.3.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-buildflow_4.3.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-centraltarget_4.3.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/devstudio.versionwatch_9.0.mars/ \
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstoolstargetplatforms-matrix/ \

----

Do not disable this job (not published as part of the release and continues to be updated during staging):

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-integration-tests.aggregate_4.3.mars/

If you want to disable all jobs from the https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/[9.0.mars view], see https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py[toggleJenkinsJobs.py]. See also https://github.com/jbdevstudio/jbdevstudio-ci/blob/master/bin/toggleJenkinsJobs.py.examples.txt[usage examples].

Should a respin be needed, they can be re-enabled as needed.


== Update Discovery Sites and URLs

[[update-discovery-urls]]
Update the *stable branch* discovery job ( https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-discovery_4.3.mars/configure ) to use the correct source URLs and versions +

VERSION = CR1a (not SNAPSHOT!) # a, b, c...
TARGET_PLATFORM_VERSION_MAX = 4.51.0.Final
JBTCENTRALTARGET_VERSION = 4.50.0.CR1-SNAPSHOT

Then respin the job and verify that sites were correctly populated:

* http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-discovery.central_4.3.mars/
* http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-discovery.earlyaccess_4.3.mars/

When done, disable the job.


== Stage to download.jboss.org

=== Copy & rename builds & update sites from "snapshots" to "staging"

@Since JBT 4.3.0.Beta1 / JBDS 9.0.Beta1

Nightly builds are continuously built in http://download.jboss.org/jbosstools/mars/snapshots/builds/. Aggregate sites are also copied into http://download.jboss.org/jbosstools/mars/snapshots/updates/.

Staging builds are the ones prepped for QE, which are then moved to /development/ if approved.

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Here is a script that performs the copy (& rename) from /snapshots/ to /staging/:

[source,bash]
----

# Do these 5 steps in parallel to save time

# JBT aggregate site
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in site; do
  stream=4.3.mars
  versionWithRespin=4.3.0.CR1a # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp ${TOOLS}/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-staging__${site}_${stream}__${ID}; mkdir -p $tmpdir; pushd $tmpdir >/dev/null
      rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream}/${ID}/* ${tmpdir}/
      # copy build folder
      echo "mkdir jbosstools-${versionWithRespin}-build-${sitename}" | sftp ${TOOLS}/mars/staging/builds/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/${ID}/
      # symlink latest build
      ln -s ${ID} latest; rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/latest ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/
      # copy update site
      echo "mkdir ${sitename}" | sftp ${TOOLS}/mars/staging/updates/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* ${TOOLS}/mars/staging/updates/${sitename}/${versionWithRespin}/
    popd >/dev/null
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done
echo "DONE: JBT aggregate site" | grep "JBT aggregate site"


# JBT tests site
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in coretests-site; do
  stream=4.3.mars
  versionWithRespin=4.3.0.CR1a # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp ${TOOLS}/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-staging__${site}_${stream}__${ID}; mkdir -p $tmpdir; pushd $tmpdir >/dev/null
      rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream}/${ID}/* ${tmpdir}/
      # copy build folder
      echo "mkdir jbosstools-${versionWithRespin}-build-${sitename}" | sftp ${TOOLS}/mars/staging/builds/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/${ID}/
      # symlink latest build
      ln -s ${ID} latest; rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/latest ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/
      # copy update site
      echo "mkdir ${sitename}" | sftp ${TOOLS}/mars/staging/updates/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* ${TOOLS}/mars/staging/updates/${sitename}/${versionWithRespin}/
    popd >/dev/null
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done
echo "DONE: JBT tests site" | grep "JBT tests site"


# Central and EA sites
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in central-site earlyaccess-site; do
  stream=4.3.mars
  versionWithRespin=4.3.0.CR1a # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp ${TOOLS}/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-staging__${site}_${stream}__${ID}; mkdir -p $tmpdir; pushd $tmpdir >/dev/null
      rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/snapshots/builds/jbosstools-build-sites.aggregate.${site}_${stream}/${ID}/* ${tmpdir}/
      # copy build folder
      echo "mkdir jbosstools-${versionWithRespin}-build-${sitename}" | sftp ${TOOLS}/mars/staging/builds/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/${ID}/
      # symlink latest build
      ln -s ${ID} latest; rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/latest ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/
      # copy update site
      echo "mkdir ${sitename}" | sftp ${TOOLS}/mars/staging/updates/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* ${TOOLS}/mars/staging/updates/${sitename}/${versionWithRespin}/
    popd >/dev/null
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done
echo "DONE: Central and EA sites" | grep "Central and EA sites"


# Browsersim Standalone Zip
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in browsersim-standalone; do
  stream=4.3.mars
  versionWithRespin=4.3.0.CR1a # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp ${TOOLS}/mars/snapshots/builds/jbosstools-${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-staging__${site}_${stream}__${ID}; mkdir -p $tmpdir; pushd $tmpdir >/dev/null
      rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/snapshots/builds/jbosstools-${site}_${stream}/${ID}/* ${tmpdir}/
      # copy build folder
      echo "mkdir jbosstools-${versionWithRespin}-build-${sitename}" | sftp ${TOOLS}/mars/staging/builds/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/${ID}/
      # symlink latest build
      ln -s ${ID} latest; rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/latest ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/
    popd >/dev/null
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done
echo "DONE: Browsersim Standalone Zip" | grep "Browsersim Standalone Zip"


# TODO: make sure you've rebuilt the discovery sites and disabled the job first before doing this step!
# JBT discovery sites
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
for site in discovery.central discovery.earlyaccess; do
  stream=4.3.mars
  versionWithRespin=4.3.0.CR1a # a, b, c...
  ID=""
  ID=$(echo "ls 20*" | sftp ${TOOLS}/mars/snapshots/builds/jbosstools-${site}_${stream} 2>&1 | grep "20.\+" | grep -v sftp | sort | tail -1); ID=${ID%%/*}
  if [[ $ID ]]; then
    if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
    echo "Latest build for ${sitename} (${site}): ${ID}"
    tmpdir=/tmp/jbosstools-staging__${site}_${stream}__${ID}; mkdir -p $tmpdir; pushd $tmpdir >/dev/null
      rsync -aPrz --rsh=ssh --protocol=28 ${TOOLS}/mars/snapshots/builds/jbosstools-${site}_${stream}/${ID}/* ${tmpdir}/
      # copy build folder
      echo "mkdir jbosstools-${versionWithRespin}-build-${sitename}" | sftp ${TOOLS}/mars/staging/builds/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/* ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/${ID}/
      # symlink latest build
      ln -s ${ID} latest; rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/latest ${TOOLS}/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/
      # copy update site
      echo "mkdir ${sitename}" | sftp ${TOOLS}/mars/staging/updates/
      rsync -aPrz --rsh=ssh --protocol=28 ${tmpdir}/all/repo/* ${TOOLS}/mars/staging/updates/${sitename}/${versionWithRespin}/
    popd >/dev/null
    rm -fr $tmpdir
  else
    echo "ERROR: no latest build found for ${site}" | grep ERROR
  fi
done
echo "DONE: JBT discovery sites" | grep "JBT discovery sites"


#  verify sites are correctly populated (run locally not on dev01):
versionWithRespin=4.3.0.CR1a # a, b, c...
tmpfile=/tmp/jbosstools-staging__verify.txt
for site in site coretests-site central-site earlyaccess-site discovery.central discovery.earlyaccess; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "http://download.jboss.org/jbosstools/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/ " >> $tmpfile
  echo "http://download.jboss.org/jbosstools/mars/staging/updates/${sitename}/${versionWithRespin}/ " >> $tmpfile
done
for site in browsersim-standalone; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "http://download.jboss.org/jbosstools/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/ " >> $tmpfile
done
echo "" >> $tmpfile
cat $tmpfile
firefox `cat $tmpfile`
rm -fr $tmpfile

----

=== Update composite site metadata for staged updates

Update files __http://download.jboss.org/jbosstools/mars/staging/updates/composite*.xml__ , with SFTP/SCP via command-line or your 
favourite SFTP GUI client (such as Eclipse RSE).

This site needs to contain:
* The latest JBoss Tools core site
* The latest matching target platform site
* The latest matching JBoss Tools Central site

[source,bash]
----
versionWithRespin_PREV=4.3.0.CR1 # a, b, c...
TARGET_PLATFORM_VERSION_MAX_PREV=4.50.0.CR1-SNAPSHOT
TARGET_PLATFORM_CENTRAL_MAX_PREV=4.50.0.CR1-SNAPSHOT

versionWithRespin=4.3.0.CR1a # a, b, c...
TARGET_PLATFORM_VERSION_MAX=4.51.0.Final
TARGET_PLATFORM_CENTRAL_MAX=4.50.0.CR1-SNAPSHOT

cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/mars/staging/updates
git fetch origin master
git checkout FETCH_HEAD

# replace static/releases with mars/staging/updates, then replace all the versions
now=`date +%s000`
for c in compositeContent.xml compositeArtifacts.xml; do 
  sed -i -e "s#<property name='p2.timestamp' value='[0-9]\+'/>#<property name='p2.timestamp' value='${now}'/>#" $c
  sed -i -e "s#/static/releases/#/mars/staging/updates/#" $c
  sed -i -e "s#${versionWithRespin_PREV}#${versionWithRespin}#" $c
  sed -i -e "s#${TARGET_PLATFORM_CENTRAL_MAX_PREV}#${TARGET_PLATFORM_CENTRAL_MAX}#" $c
  sed -i -e "s#${TARGET_PLATFORM_VERSION_MAX_PREV}#${TARGET_PLATFORM_VERSION_MAX}#" $c
done
cat $c | egrep "${versionWithRespin}|${TARGET_PLATFORM_VERSION_MAX}|${TARGET_PLATFORM_CENTRAL_MAX}|timestamp"

# commit the change and push to master
git add composite*.xml
git commit -m "release JBT ${versionWithRespin} to QE" composite*.xml
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
scp composite*.xml ${TOOLS}/mars/staging/updates/
popd

----

=== Merge in Integration Stack content

TODO https://issues.jboss.org/browse/JBIDE-20664: write a new mechanism for 4.3.0.CR1 to pull in integration stack jars, using URLs declared in http://download.jboss.org/jbosstools/configuration/ide-config.properties
jboss.discovery.site.integration-stack.url|jbosstools|4.3.0.CR1=http://download.jboss.org/jbosstools/mars/staging/updates/integration-stack/discovery/4.3.0.Alpha1/
jboss.discovery.site.integration-stack.url|devstudio|9.0.0.CR1=https://devstudio.redhat.com/9.0/staging/updates/integration-stack/discovery/9.0.0.Alpha1/


== Release the latest staging site to ide-config.properties

Check out http://download.jboss.org/jbosstools/configuration/ide-config.properties

Update it so that the links for the latest milestone point to valid URLs. Comment out staging links as required.

[source,bash]
----

# adjust these steps to fit your own path location & git workflow
cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=4.3.0.CR1
versionWithRespin=4.3.0.CR1a # a, b, c...

git fetch origin master
git checkout FETCH_HEAD

# then edit ide-config.properties 
# vim ide-config.properties 
# st ide-config.properties 

# commit the change and push to master
ci "release JBT ${version} (${versionWithRespin}) to staging: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
rsync -Pzrlt --rsh=ssh --protocol=28 ide-config.properties $TOOLS/configuration/ide-config.properties
popd

----

== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Abridged category from http://download.jboss.org/jbosstools/mars/staging/updates/
3. Restart when prompted. Open Central Software/Updates tab, enable Early-Access select and install all connectors; restart
4. Check log, start an example project, check log again


== Notify the team

____
*To* jbosstools-dev@lists.jboss.org +

[source,bash]
----
versionWithRespin=4.3.0.CR1a # a, b, c...
respin="respin-a"
TARGET_PLATFORM_VERSION_MIN=4.50.0.Final
TARGET_PLATFORM_VERSION_MAX=4.51.0.Final
TARGET_PLATFORM_CENTRAL_MAX=4.50.0.CR1-SNAPSHOT
jbdsFixVersion=9.0.0.CR1 # no respin suffix here
jbtFixVersion=4.3.0.CR1 # no respin suffix here
echo "
Subject: 

JBoss Tools Core ${versionWithRespin} bits available for QE testing

Body:

As always, these are not FINAL bits, but preliminary results for QE & community testing. Not for use by customers or end users. 

Update site: http://download.jboss.org/jbosstools/mars/staging/updates/

Target platform: 
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX} 

New + noteworthy (subject to change): 
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule: https://issues.jboss.org/browse/JBIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aversions-panel

--

Additional update sites:
* http://download.jboss.org/jbosstools/mars/staging/updates/core/${versionWithRespin}/
* http://download.jboss.org/jbosstools/mars/staging/updates/coretests/${versionWithRespin}/

Discovery sites:
* http://download.jboss.org/jbosstools/mars/staging/updates/discovery.central/${versionWithRespin}/
* http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/

Build folders (for build logs & update site zips):
* http://download.jboss.org/jbosstools/mars/staging/builds/

"
if [[ $respin != "respin-" ]]; then
echo " 

--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${jbdsFixVersion}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${jbtFixVersion}%22%29%29%29

To compare the upcoming version of Central (${versionWithRespin}) against an older version, add lines similar to these your eclipse.ini file after the -vmargs line for the appropriate version & URLs:
 -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.central/${versionWithRespin}/jbosstools-directory.xml
 -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/mars/staging/updates/
 -Djboss.discovery.earlyaccess.site.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/
 -Djboss.discovery.earlyaccess.list.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/jbosstools-earlyaccess.properties
"
fi

----
____
