= Publishing JBT update sites for QE

This document describe how to provide a valid JBoss Tools build to QE so they can test us.

TODO: use consistent instructions for fetching sources from git & pushing changes
TODO: add step that automatically keeps all staged builds in Jenkins, using /lastBuild/toggleLogKeep

[NOTE]
====
Note that +sftp://tools@filemgmt.jboss.org/downloads_htdocs/tools/+ maps to +http://download.jboss.org/jbosstools/+ +

If you do not need it urgently, you can push files there simply by pushing a change into the following location: https://github.com/jbosstools/jbosstools-download.jboss.org/tree/master/jbosstools .
A Jenkins job can then be triggered to sync changes to download.jboss.org: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-download.jboss.org-rsync-from-svn/
====

== Verify correct version set in org.jboss.tools.foundation.core

Check o.j.t.foundation.core's currentversion.properties for the correct value of default.version

[sources,bash]
----
# @Since JBT 4.2.1 / JBDS 8.0.1 - JBIDE-18820, JBIDE-18806

version=4.3.1.Final # or .Final
versionWithRespin=4.3.1.CR1c # a, b, c...

if [[ ${version:0:1} == "4" ]]; then # JBT
  pluginName=foundation.core
  updatesiteURL=http://download.jboss.org/jbosstools/mars/staging/updates/core/${versionWithRespin}/plugins/
  updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/4.3.mars/plugins/
  #updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/master/plugins/
else
  pluginName=core.central
  updatesiteURL=https://devstudio.redhat.com/9.0/staging/updates/core/${versionWithRespin}/plugins/
  updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/4.3.mars/plugins/
  #updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/master/plugins/
fi
pushd /tmp; wget -q -nc $updatesiteURL
thejars=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort`
echo "Found: $thejars" | egrep ${pluginName}
thejar=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort | tail -1; rm -f index.html`
echo ${updatesiteURL}/${thejar} | egrep ${pluginName}
wget -q -nc ${updatesiteURL}/${thejar}
theversion=`unzip -p ${thejar} */currentversion.properties | grep version= | sed -e "s/version=//" | tail -1`; theversion=${theversion/-SNAPSHOT/} # remove -SNAPSHOT suffix from version
rm -f ${thejar}
popd
echo "In ${pluginName}, want ${version}, got $theversion" | egrep "${pluginName}|${version}"

version=9.1.0.GA # or .GA
versionWithRespin=9.1.0.CR1c # a, b, c...

if [[ ${version:0:1} == "4" ]]; then # JBT
  pluginName=foundation.core
  updatesiteURL=http://download.jboss.org/jbosstools/mars/staging/updates/core/${versionWithRespin}/plugins/
  updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/4.3.mars/plugins/
  #updatesiteURL=http://download.jboss.org/jbosstools/mars/snapshots/updates/core/master/plugins/
else
  pluginName=core.central
  updatesiteURL=https://devstudio.redhat.com/9.0/staging/updates/core/${versionWithRespin}/plugins/
  updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/4.3.mars/plugins/
  #updatesiteURL=https://devstudio.redhat.com/9.0/snapshots/updates/core/master/plugins/
fi
pushd /tmp; wget -q -nc $updatesiteURL
thejars=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort`
echo "Found: $thejars" | egrep ${pluginName}
thejar=`cat index.html | egrep -v "source|pack.gz" | egrep ${pluginName} | sed -e "s#.\+href=\"\([^\"]\+\)\">.\+#\1#" | sort | tail -1; rm -f index.html`
echo ${updatesiteURL}/${thejar} | egrep ${pluginName}
wget -q -nc ${updatesiteURL}/${thejar}
theversion=`unzip -p ${thejar} */currentversion.properties | grep version= | sed -e "s/version=//" | tail -1`; theversion=${theversion/-SNAPSHOT/} # remove -SNAPSHOT suffix from version
rm -f ${thejar}
popd
echo "In ${pluginName}, want ${version}, got $theversion" | egrep "${pluginName}|${version}"

----

If value found above for `$theversion` != current release version, then you need to rebuild foundation or JBDS w/ a new value inserted.


== Verify all branches have been created & all master branch root poms point to the NEXT parent pom version.

Chances are you opened a JIRA like https://issues.jboss.org/browse/JBIDE-18149 and asked everyone to branch and then upversion the references to the parent pom in their root poms.
Chances are also that someone might have forgotten to do this.

So, to ensure everyone has done what they need to do, you can run two scripts:

* ensure all the branches exist.

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/getProjectSHAs.sh

* ensure the root poms are correct

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/getProjectRootPomParents.sh

If any branches have not yet been created, you can either:
* Ask Denis, Fred, or Max to get them created
* Reconfigure the jobs to build from your fork, and create the branch there

If any of the root poms have not been correctly updated, simply re-open the task JIRAs like https://issues.jboss.org/browse/JBIDE-18167 and ask that the root pom be updated.

Once the above conditions have been met, you can proceed to the next steps.

== Disable jobs

To prevent accidentally rebuilding something while you're copying it away, make sure that all the stable branch jobs (4.3.mars, 9.0.mars) are disabled. These include all product, composite and aggregate jobs:

[source,bash]
----
# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD
for j in jbosstools-build.parent_4.3.mars jbosstoolstargetplatforms-matrix jbosstools-buildflow_4.3.mars jbosstools-composite-install_4.3.mars jbosstools-browsersim-standalone_4.3.mars jbosstools-build-sites.aggregate.site_4.3.mars jbosstools-build-sites.aggregate.coretests-site_4.3.mars jbosstools-centraltarget_4.3.mars jbosstools-build-sites.aggregate.child-sites_4.3.mars devstudio.product_9.0.mars devstudio.versionwatch_9.0.mars jbosstools-install-p2director.install-tests.matrix_4.3.mars jbosstools-install-grinder.install-tests.matrix_4.3.mars; do
  curl -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable && echo -n "."
done
echo ""

----

== Update Discovery Sites and URLs

[[update-discovery-urls]]
Update the *stable branch* discovery job ( https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-discovery_4.3.mars/configure ) to use the correct source URLs and versions +


Then respin the job and verify that sites were correctly populated:

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD

versionWithRespin=CR1c # a, b, c... (not SNAPSHOT!)
TARGET_PLATFORM_VERSION_MAX=4.52.0.Final
TARGET_PLATFORM_CENTRAL_MAX=4.52.0.Final-SNAPSHOT
for j in jbosstools-discovery_4.3.mars; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable
  curl -k -u ${userpass} --data "VERSION=${versionWithRespin}&TARGET_PLATFORM_VERSION_MAXIMUM=${TARGET_PLATFORM_VERSION_MAX}&JBTCENTRALTARGET_VERSION=${TARGET_PLATFORM_CENTRAL_MAX}" https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/buildWithParameters
  sleep 15s
  # then disable the job
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/disable
done

----

If you ran the above in Jenkins / on dev01, this next step needs to be run locally to launch a browser for manual verification.

[source,bash]
----

google-chrome \
http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-discovery_4.3.mars/lastBuild/parameters \
http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-discovery_4.3.mars/lastBuild/console \
http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-discovery.central_4.3.mars/latest/all/repo/compositeArtifacts.xml \
http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-discovery.central_4.3.mars/latest/all/repo/jbosstools-directory.xml \
http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-discovery.earlyaccess_4.3.mars/latest/all/repo/compositeArtifacts.xml \
http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-discovery.earlyaccess_4.3.mars/latest/all/repo/jbosstools-directory.xml
google-chrome \
https://devstudio.redhat.com/9.0/snapshots/builds/jbosstools-discovery.central_4.3.mars/latest/all/repo/compositeArtifacts.xml \
https://devstudio.redhat.com/9.0/snapshots/builds/jbosstools-discovery.central_4.3.mars/latest/all/repo/devstudio-directory.xml \
https://devstudio.redhat.com/9.0/snapshots/builds/jbosstools-discovery.earlyaccess_4.3.mars/latest/all/repo/compositeArtifacts.xml \
https://devstudio.redhat.com/9.0/snapshots/builds/jbosstools-discovery.earlyaccess_4.3.mars/latest/all/repo/devstudio-directory.xml

----


== Stage to download.jboss.org

=== Copy & rename builds & update sites from "snapshots" to "staging"

@Since JBT 4.3.0.CR1 / JBDS 9.0.CR1

Nightly builds are continuously built in http://download.jboss.org/jbosstools/mars/snapshots/builds/. Aggregate sites are also copied into http://download.jboss.org/jbosstools/mars/snapshots/updates/.

Staging builds are the ones prepped for QE, which are then moved to /staging/ if approved.

First connect to dev01.mw.lab.eng.bos.redhat.com as +hudson+ user (requires permissions).

[source,bash]
----
me@local$ ssh dev01.mw.lab.eng.bos.redhat.com
me@dev01$ sudo su - hudson
hudson@dev01$ ...
----

Here is a script that performs the copy (& rename) from /snapshots/ to /staging/:

[source,bash]
----
stream=4.3.mars
versionWithRespin=4.3.1.CR1c # a, b, c...
cd /tmp
if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.3.x/publish/stage.sh --no-check-certificate
chmod +x stage.sh
for site in site coretests-site central-site earlyaccess-site; do
  ./stage.sh -sites $site -eclipseReleaseName mars -stream ${stream} -vr ${versionWithRespin} -JOB_NAME jbosstools-build-sites.aggregate.\${site}_\${stream} -q &
done
for site in browsersim-standalone; do
  ./stage.sh -sites $site -eclipseReleaseName mars -stream ${stream} -vr ${versionWithRespin} -q &
done


# TODO: make sure you've rebuilt the discovery sites and disabled the job first before doing this step!
stream=4.3.mars
versionWithRespin=4.3.1.CR1c # a, b, c...
cd /tmp
if [[ -f /tmp/stage.sh ]]; then rm -f /tmp/stage.sh; fi
wget https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/jbosstools-4.3.x/publish/stage.sh --no-check-certificate
chmod +x stage.sh
for site in discovery.central discovery.earlyaccess; do
  ./stage.sh -sites $site -eclipseReleaseName mars -stream ${stream} -vr ${versionWithRespin} -q &
done

----

Verify sites are correctly populated (run locally, not on dev01):

Note that Akamai caching might result in the appearance of missing files (apache directories may look incomplete) but if you ping specific files, they should be there.

[source,bash]
----

versionWithRespin=4.3.1.CR1c # a, b, c...
tmpfile=/tmp/jbosstools-staging__verify.txt
for site in site coretests-site central-site earlyaccess-site discovery.central discovery.earlyaccess; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "http://download.jboss.org/jbosstools/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/ " >> $tmpfile
  echo "http://download.jboss.org/jbosstools/mars/staging/updates/${sitename}/${versionWithRespin}/ " >> $tmpfile
done
for site in browsersim-standalone; do
  if [[ ${site} == "site" ]]; then sitename="core"; else sitename=${site/-site/}; fi
  echo "http://download.jboss.org/jbosstools/mars/staging/builds/jbosstools-${versionWithRespin}-build-${sitename}/ " >> $tmpfile
done
echo "" >> $tmpfile
cat $tmpfile
google-chrome `cat $tmpfile`
rm -fr $tmpfile

----

=== Cleanup OLD builds

Optional step.

First, use sshfs to mount filemgmt file paths.

[source,bash]
----

TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
sshfs $TOOLS /media/TOOLS-ssh

----

Then move old builds into an OLD/ folder to they're less visible and ready for deletion later.

[source,bash]
----
version_PREV=4.3.1.CR1b # a, b, c...
for d in updates/core updates/central updates/earlyaccess updates/discovery.central updates/discovery.earlyaccess builds; do
  if [[ -d /media/TOOLS-ssh/mars/staging/${d}/ ]]; then
    echo "${d}/*${version_PREV}* ..."
    mkdir -p /media/TOOLS-ssh/mars/staging/${d}/OLD/
    mv /media/TOOLS-ssh/mars/staging/${d}/*${version_PREV}* /media/TOOLS-ssh/mars/staging/${d}/OLD/
  fi
done

----

=== Update http://download.jboss.org/jbosstools/mars/staging/updates/

This should point to the latest staging bits. Just copy what's in discovery.central/composite*.xml into this folder.

[source,bash]
----

cd ~/tru
RSYNC="rsync -aPrz --rsh=ssh --protocol=28"

versionWithRespin_PREV=4.3.1.CR1b # a, b, c...
versionWithRespin=4.3.1.CR1c # a, b, c...
DESTINATION=tools@filemgmt.jboss.org:/downloads_htdocs/tools
PROJECT_PATH=jbosstools-download.jboss.org/jbosstools
DEST_URL="http://download.jboss.org/jbosstools"
updatePath=mars/staging/updates

pushd ${PROJECT_PATH}/${updatePath}
git fetch origin master
git checkout FETCH_HEAD

for d in discovery.central discovery.earlyaccess; do
  mkdir -p ${d}/${versionWithRespin}/
  pushd ${d}/${versionWithRespin}/
    ${RSYNC} ${DESTINATION}/${updatePath}/${d}/${versionWithRespin}/composite*xml ./
    cat $c | egrep "${versionWithRespin}|targetplatforms|REPO|updates|timestamp"
  popd
done
rsync discovery.central/${versionWithRespin}/composite*.xml ./

# update index.html
if [[ -f index.html ]]; then
  sed -i "s#${versionWithRespin_PREV}#${versionWithRespin}#" index.html
  cat index.html | egrep "${versionWithRespin_PREV}|${versionWithRespin}"
fi

# push changes to server
${RSYNC} discovery.central/${versionWithRespin}/composite*xml ${DESTINATION}/${updatePath}/discovery.central/${versionWithRespin}/
${RSYNC} discovery.earlyaccess/${versionWithRespin}/composite*xml ${DESTINATION}/${updatePath}/discovery.earlyaccess/${versionWithRespin}/
${RSYNC} ./composite*xml *.html ${DESTINATION}/${updatePath}/

# verify changes
echo "Check 4 URLs:"
google-chrome \
${DEST_URL}/${updatePath}/discovery.central/${versionWithRespin}/compositeContent.xml \
${DEST_URL}/${updatePath}/discovery.earlyaccess/${versionWithRespin}/compositeContent.xml \
${DEST_URL}/${updatePath}/compositeContent.xml \
${DEST_URL}/${updatePath}/

rm -fr discovery.central/${versionWithRespin}/composite*.xml discovery.earlyaccess/${versionWithRespin}/composite*.xml

# commit the change and push to master
git commit -m "release ${versionWithRespin} to QE"
git push origin HEAD:master
popd

----

=== Merge in Integration Stack content

See details in Merge_IS_Discovery.adoc

== Release the latest staging site to ide-config.properties

Check out http://download.jboss.org/jbosstools/configuration/ide-config.properties

Update it so that the links for the latest milestone point to valid URLs. Comment out staging links as required.

[source,bash]
----

# adjust these steps to fit your own path location & git workflow
cd ~/tru
pushd jbosstools-download.jboss.org/jbosstools/configuration
version=4.3.1.CR1
versionWithRespin=4.3.1.CR1c # a, b, c...
jbdsFixVersion=9.1.0.CR1 # no respin suffix here
jbdsFixVersionWithRespin=9.1.0.CR1c # a, b, c...

git fetch origin master
git checkout FETCH_HEAD

# then edit ide-config.properties
# vim ide-config.properties
# st ide-config.properties
# TODO something like this?
# sed -i "s/CR1b/CR1c/g" ide-config.properties

# commit the change and push to master
ci "release JBT ${version} (${versionWithRespin}) to staging: link to latest dev milestone discovery site" ide-config.properties
git push origin HEAD:master

# push updated file to server
TOOLS=tools@filemgmt.jboss.org:/downloads_htdocs/tools
rsync -Pzrlt --rsh=ssh --protocol=28 ide-config.properties $TOOLS/configuration/ide-config.properties

# verify these 6 URLs exist
google-chrome $(egrep "/${version}/|/${versionWithRespin}/|/${jbdsFixVersion}/|/${jbdsFixVersionWithRespin}/" ide-config.properties | sed -e "s#.\+=\(.\+\)#\1#")
popd

----

== Smoke test the release

Before notifying team of staged release, must check for obvious problems.

1. Get a recent Eclipse (compatible with the target version of JBT)
2. Install Abridged category from http://download.jboss.org/jbosstools/mars/staging/updates/
3. Restart when prompted. Open Central Software/Updates tab, enable Early Access select and install all connectors; restart
4. Check log, start an example project, check log again


== Enable jobs

You will need to re-enable the jobs once the bits are staged, so that CI builds can continue.

If the next build WILL be a respin, you need to simply:

* re-enable 15 jobs that were disabled above. If you committed a change to jbdevstudio-ci, you can simply revert that commit to re-enable the jobs!

[source,bash]
----

# kerberos login for the Jenkins server
userpass=nboldt:PASSWORD
for j in jbosstools-build.parent_4.3.mars jbosstoolstargetplatforms-matrix jbosstools-buildflow_4.3.mars jbosstools-composite-install_4.3.mars jbosstools-browsersim-standalone_4.3.mars jbosstools-build-sites.aggregate.site_4.3.mars jbosstools-build-sites.aggregate.coretests-site_4.3.mars jbosstools-centraltarget_4.3.mars jbosstools-build-sites.aggregate.child-sites_4.3.mars devstudio.product_9.0.mars devstudio.versionwatch_9.0.mars jbosstools-install-p2director.install-tests.matrix_4.3.mars jbosstools-install-grinder.install-tests.matrix_4.3.mars jbosstools-discovery_4.3.mars; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable && echo -n "."
done
echo ""
for j in jbosstools-discovery_4.3.mars; do
  curl -k -X POST -u ${userpass} https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/${j}/enable
done

----

If the next build will NOT be a respin, you will also need to ALSO make these changes to jobs, and upversion/release artifacts such as releng scripts or target platforms if you haven't done so already:

* set correct github branch, eg., switch from 4.3.1.CR1x to 4.3.x
* upversion dependencies, eg., releng scripts move from version CR1 to CR1 (if that's been released)
* upversion target platforms / Central version (if those have been released)


== Notify the team

Run this on dev01 so that we can use /bin/mail. Email should be generated automatically rather than requiring copy & paste into your mail client.

____
*To* jbosstools-dev@lists.jboss.org +

[source,bash]
----

versionWithRespin=4.3.1.CR1c # a, b, c...
respin="respin-b"
TARGET_PLATFORM_VERSION_MIN=4.50.2.Final
TARGET_PLATFORM_VERSION_MAX=4.52.0.Final
TARGET_PLATFORM_CENTRAL_MAX=4.52.0.Final-SNAPSHOT
jbdsFixVersion=9.1.0.CR1 # no respin suffix here
jbtFixVersion=4.3.1.CR1 # no respin suffix here
recipients=jbosstools-dev@lists.jboss.org
sender=nboldt@redhat.com
subject="JBoss Tools Core ${versionWithRespin} bits available for QE testing"
echo "
These are not FINAL bits, but preliminary results for QE & community testing. Not for redistribution to customers or end users.

Update site: http://download.jboss.org/jbosstools/mars/staging/updates/

New + noteworthy (subject to change):
* https://github.com/jbosstools/jbosstools-website/tree/master/documentation/whatsnew
* http://tools.jboss.org/documentation/whatsnew/

Schedule: https://issues.jboss.org/projects/JBIDE?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page

--

Additional update sites:
* http://download.jboss.org/jbosstools/mars/staging/updates/core/${versionWithRespin}/
* http://download.jboss.org/jbosstools/mars/staging/updates/coretests/${versionWithRespin}/

Target platforms:
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MIN}
* http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/${TARGET_PLATFORM_VERSION_MAX}

Discovery sites:
* http://download.jboss.org/jbosstools/mars/staging/updates/discovery.central/${versionWithRespin}/
* http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/

Build folders (for build logs & update site zips):
* http://download.jboss.org/jbosstools/mars/staging/builds/
" > /tmp/mailbody.jbt.txt
if [[ $respin != "respin-" ]]; then
echo "
--

Changes prompting this $respin are:

https://issues.jboss.org/issues/?jql=labels%20in%20%28%22${respin}%22%29%20and%20%28%28project%20in%20%28%22JBDS%22%29%20and%20fixversion%20in%20%28%22${jbdsFixVersion}%22%29%29%20or%20%28project%20in%20%28%22JBIDE%22%2C%22TOOLSDOC%22%29%20and%20fixversion%20in%20%28%22${jbtFixVersion}%22%29%29%29

To compare the upcoming version of Central (${versionWithRespin}) against an older version, add lines similar to these your eclipse.ini file after the -vmargs line for the appropriate version & URLs:
 -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.central/${versionWithRespin}/jbosstools-directory.xml
 -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/mars/staging/updates/
 -Djboss.discovery.earlyaccess.site.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/
 -Djboss.discovery.earlyaccess.list.url=http://download.jboss.org/jbosstools/mars/staging/updates/discovery.earlyaccess/${versionWithRespin}/jbosstools-earlyaccess.properties
" >> /tmp/mailbody.jbt.txt
fi

# use mail (with sendmail's -f flag), NOT mailx
/bin/mail -s "$subject" $recipients -- -f"$sender" < /tmp/mailbody.jbt.txt
rm -f /tmp/mailbody.jbt.txt

----
____

